### ISSUE TITLE
Specify and implement dummy spends and outputs

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1005]
There are a few changes required here: changes to the consensus rules, changes to the `TransactionPlan` code, and changes to the transaction builder itself.

### Consensus changes

To support dummy spends, we need to change the checks in the spend proof, so that verification short-circuits to "true", regardless of the other witness data, if the value the spend action releases is 0.  (We still need to include the other witness data in the transparent proof, since when we do the real zk-SNARK proofs, there's no short-circuiting, we'll do both checks and combine them with an OR statement).

### `TransactionPlan` changes

To support dummy spends, we should add a new constructor, `SpendPlan::dummy<R: CryptoRng + RngCore>(rng: &mut R) -> Self`.  This constructor should:

- Generate a random `note` recording `0` `penumbra`.  Probably the easiest way to do this is using `Note::from_parts`, with a random `diversifier`, a random `transmission_key`, and a random `note_blinding`.  (These parts don't need to be valid, they just need to exist).
- Call `Self::new(rng, note, 0u64.into())` to create the spend plan.

To support dummy outputs, we should add a new constructor, `OutputPlan::dummy<R: CryptoRng + RngCore>(rng: &mut R) -> Self`.  This constructor should:

- Generate a random `dest_address`.  This could be done by generating a random spending key and obtaining its default address.
- Call `Self::new(rng, Value { amount: 0, .. }, dest_address, ...)` to create the output plan.

### Transaction builder changes

The dummy spends and outputs are now part of the transaction plan as ordinary spends and outputs, rather than as special "dummy spend plans" etc. This is important because the transaction plan is supposed to _fully determine_ the transaction, so it has to include all of the randomness etc. that will be used.

For outputs this is fine, when inspecting a transaction plan, the custodian can see that the amount of an output is 0 and decide that it's a dummy output.

For spends, this is mostly fine. While the custodian can see that the amount of a spend is 0 and decide that it's a dummy spend, we currently query the view service for authentication paths for all of the notes we want to spend.  But the notes in the dummy spends don't exist, so the view service won't be able to answer them.

To fix this, we need to only request witness data for spend plans that release **nonzero** amounts of value.  However, the current `WitnessData` assumes that every spend plan will have witness data, so it just includes a `Vec<Proof>`.  Trying to get the indexes to line up for some subset is unworkable, so we will want to:

- [x] change this to a `BTreeMap<note::Commitment, Proof>` in the domain type;
- [x] change the transaction builder to only request witness data for spends unlocking **nonzero** amounts of value;
- [x] change the transaction builder to fill in the "holes" in the returned `WitnessData`, so that it has an entry for the dummy spends (this can just copy in one of the real proofs, the value doesn't matter because it won't be checked).

**Comment by plaidfinch** [comment]
> this can just copy in one of the real proofs, the value doesn't matter because it won't be checked

Would it make sense instead to randomly generate a bogus proof here instead? That way we aren't implicitly dependent on having at least one real proof to copy, and we would more easily catch a bug of the form "we are partially checking this proof for validity, but we shouldn't be".

**Comment by hdevalence** [comment]
Yeah sure, sounds fine, whatever's easiest.

**Comment by redshiftzero** [comment]
After https://github.com/penumbra-zone/penumbra/pull/1282, for dummy spends we'll want to generate a full random address since now the `Note` contains a full `Address` and not just the transmission key and diversifier
