### ISSUE TITLE
view service not getting all height updates

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1007]
We had an issue (#932) where we failed to terminate syncing due to never hitting the condition where `sync_height == latest_known_block_height` [here](https://github.com/penumbra-zone/penumbra/blob/018-euanthe.1/view/src/service.rs#L262). A workaround (#1001) was implemented that simply breaks out of the while loop whenever we see a height update where the `sync_height >= latest_known_block_height`.

However, skipping the condition where `sync_height == latest_known_block_height` is happening due to the view service not getting all height updates, i.e. if we log the `height` the worker is processing and `sync_height` in the view service, we can see we're not getting all the updates from the worker:

```
[view/src/service.rs:291] sync_height = 16843
[view/src/service.rs:291] latest_known_block_height = 16846
[view/src/worker.rs:143] height = 16845
[view/src/worker.rs:143] height = 16846
[view/src/service.rs:291] sync_height = 16845
[view/src/service.rs:291] latest_known_block_height = 16846
[view/src/worker.rs:143] height = 16847
[view/src/worker.rs:143] height = 16848
[view/src/service.rs:291] sync_height = 16847
```

**Comment by hdevalence** [comment]
This should be (defined as) expected behavior. What's happening is that the synced-to-height notifications are happening via a Tokio `watch` channel, which only holds a single value.  The sync worker doesn't block on having a watch receiver get the value, so the watcher might miss some.

**Comment by redshiftzero** [comment]
Ah thanks for explaining, I'll close this then as the fix applied already is the right one given that behavior
