### ISSUE TITLE
canonical serialization for transactions

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#102]
Followup from MVP1's stub transaction format #60 #29:

> The Cosmos format is defined in ADR20; it uses protobufs. The main downside of protobufs in this context is the lack of canonical serialization, but the rest of the ecosystem seems to do OK.

> We should decide how we want to encode the container for the transaction's action descriptions, and how much of the ADR20 format it makes sense to adopt.

**Comment by hdevalence** [comment]
We don't need this now that we have `AuthHash`es.
