### ISSUE TITLE
Change `state_key` methods to return keys, not key hashes

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1022]
**Is your feature request related to a problem? Please describe.**

Currently, we have (or are in the process of having, as soon as #997) is done a `mod state_key` pattern, where all of the state keys are computed using `state_key::some_descriptive_name` functions in a standalone module, making it easy to see what all the state keys are.

Unfortunately, these methods all return `KeyHash`es, and the ICS23 proofs require having the full key, not just the key hash.  This messes up the state query interface, because we can't use the same code to query with or without a proof.  The resulting RPC implementation is a mess.

**Describe the solution you'd like**

Change the state key methods to return `String` or `&'static str` (as appropriate), using `.into()` to convert to `KeyHash`es as required.  Then clean up the `KeyValueRequest` to only take a `key`, not a `key_hash`, and to unconditionally do `get_with_proof` on that `key`, with the only difference being whether or not the proof is returned to the user.

**Comment by plaidfinch** [comment]
Is doing `get_with_proof` more expensive than doing a `get` that doesn't return a proof?

**Comment by hdevalence** [comment]
No, not really, they have to access the same data from the database, which is the expensive part (because in order to find the leaf, they have to traverse the tree from the root), so bundling it up into a proof is cheap.
