### ISSUE TITLE
Undelegations don't work after merging quarantine code

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1030]
**Describe the bug**

The initial implementation of quarantining for unbonding periods is now on `testnet-preview.penumbra.zone`.  But undelegations don't currently work.

**To Reproduce**

To get a local replica of the testnet (this would be automated by #939)

1. Run `pd generate-testnet`
2. Run `curl -s http://testnet-preview.penumbra.zone:26657/genesis | jq ".result.genesis" > $HOME/.penumbra/testnet_data/node0/tendermint/config/genesis.json` to replace the genesis file with the one from `testnet-preview`
3. Run `curl -s http://testnet-preview.penumbra.zone:26657/status | jq ".result.node_info.id"` to get the node ID, and use `vim ~/.penumbra/testnet_data/node0/tendermint/config/config.toml` to fill in `NODE_ID@testnet-preview.penumbra.zone:26656` as a `bootstrap-peer` 
4. Run `cargo run --release --bin pd -- start  -r ~/.penumbra/testnet_data/node0/pd/rocksdb` in one terminal and `tendermint --home ~/.penumbra/testnet_data/node0/tendermint/ start` in another

To reproduce:

1. Use `cargo run --release --bin pcli -- -n 127.0.0.1 stake list-validators` to get the list of validators
2. Use `cargo run --release --bin pcli -- -n 127.0.0.1 stake delegate 10000penumbra --to VAL_ID` to delegate
3. Use `cargo run --release --bin pcli -- -n 127.0.0.1 stake undelegate 4000delegation_penumbravalid14tcg3...` to undelegate

**Expected behavior**

Undelegation works correctly

**Comment by hdevalence** [comment]
Currently, I get:
```
pre-checking transaction...
broadcasting transaction...
confirming transaction  ...
Error: timeout waiting to detect outputs of submitted transaction
```

We detect transaction confirmation by detecting its outputs during scanning.  This is usually the behavior we want, because the reason to wait for full confirmation is to have access to change notes. In this case, we won't be able to detect the outputs, because they're quarantined.  But we also don't need to, because we can't spend them anyways.  So we can just wait for the transaction to be submitted.

**Comment by hdevalence** [comment]
The problem is indeed with the JMT accesses, specifically with the quarantined nullifier checks.  The component writes the nullifier as
```
        self.state
            .put_domain(
                state_key::quarantined_spent_nullifier_lookup(&nullifier),
                // We don't use the value for validity checks, but writing the source
                // here lets us find out what transaction spent the nullifier.
                source,
            )
            .await;
```
as a `NoteSource`, but reads it as a Proto `bytes` value, which it isn't:
```
        if let Some(source) = self
            .get_proto::<Vec<u8>>(state_key::quarantined_spent_nullifier_lookup(&nullifier))
            .await?
```
causing a decode failure.

**Comment by plaidfinch** [comment]
Resolved (in several PRs last night).
