### ISSUE TITLE
`pcli` does not work offline following refactoring

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1044]
**Describe the bug**

The refactoring @hawkw did in #1003 made the code much cleaner, splitting the role of the `Opt` struct (now just representing the arguments themselves) and the `App` struct (now representing the configured and constructed application data.

However, as a side effect, it also made `pcli` stop working offline, for subtle reasons.  Previously, the `needs_sync` method on the command controlled both (1) whether `pcli` would try to synchronize before doing the command and (2) whether `pcli` would connect to the network at all.  Now, `needs_sync` controls whether we wait to sync before running the command, but we unconditionally connect to the remote node in `Opt::view_client`.  This means that if the node is offline, we won't run the command at all.

I'm not sure what the best way to fix this is, because we can't easily get rid of the requirement to construct a view service in the `App`.  It's not essential to have `pcli` work solely offline, at least for now, so this isn't urgent, but it would be ideal to be able to run it offline.

**Comment by hawkw** [comment]
Agh, whoops! I can try to fix this.
