### ISSUE TITLE
Uptime tracking is off-by-one

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1050]
When running a standalone testnet, the singular validator is marked as having missed one block. This... isn't exactly possible. We should fix the off-by-one error.

**Comment by zbuc** [comment]
What's happening here is that the `last_commit_info.votes` received from Tendermint ABCI for block height 1 is empty. I think this is actually a mismatch based on this comment:

```rust
        // Note: this probably isn't the correct height for the LastCommitInfo,
        // which is about the *last* commit, but at least it'll be consistent,
        // which is all we need to count signatures.
```

i.e. the last commit info is actually for height _0_ (the genesis block) so it's expected that there's no signer.

**Comment by hdevalence** [comment]
Hmm, that sounds plausible, but I think that I also recall seeing this happen when creating a new validator post-genesis, would that fix also apply to that case?

**Comment by zbuc** [comment]
> Hmm, that sounds plausible, but I think that I also recall seeing this happen when creating a new validator post-genesis, would that fix also apply to that case?

Nope, I wasn't aware of that case. I think that's also related to the mismatch -- i.e. the validator can't vote in the block they were introduced. I'll take a look and see if I can reproduce, and maybe there's a better fix based on special casing the height the validator was introduced rather than the genesis height.

**Comment by zbuc** [comment]
I tested this and new validators seemed to behave as expected, i.e. they are marked as having voted for the block they appear, but required to vote for subsequent votes.
