### ISSUE TITLE
Integrate Galileo deployment with CD

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1066]
- [ ] Create galileo-preview deployment to run against the `main` branch of penumbra and `testnet-preview`. Perhaps send messages to a different private channel or disable Discord messaging entirely.
- [ ] Modify testnet-preview GitHub Action to automatically deploy galileo-preview on main branch
- [ ] Modify testnet deploy GitHub Action to automatically deploy galileo on testnet release tag
- [ ] Update testnet deployment template to incorporate any changes to process

The trickiest thing is that we need to pin the dependency versions of the penumbra repos within the Galileo `Cargo.toml`.

**Comment by hdevalence** [comment]
We've been doing reasonably well with a barebones setup, so I don't think we need to prioritize this.
