### ISSUE TITLE
Publish protobuf documentation

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1068]
There's derived documentation for the Rust autogenerated types from our protobufs available at https://rustdoc.penumbra.zone but it's unwieldy.

It would be nice to have a dedicated protobuf documentation page as the protobufs help with the understanding of protocols.

https://github.com/pseudomuto/protoc-gen-doc looks reasonable, example output: https://rawgit.com/pseudomuto/protoc-gen-doc/master/examples/doc/example.html

**Comment by hdevalence** [comment]
Maybe this could be rendered as protobuf.penumbra.zone/main/... , matching rustdoc.? If we put the /main/ in there like in the rustdoc URLs, we leave open the possibility of doing some per-tag or per-branch renders.
