### ISSUE TITLE
Don't attach chain_id to metrics

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1071]
The `chain_id` label isn't being attached to all metrics. This causes some issues in our grafana, for example the `penumbra_stake_validators_active` metric for the genesis validator has `chain_id`, but subsequent active validators do not have the `chain_id` label, so they appear separately in the dataset.

It would be nice to have the `chain_id` label attached to every metric, so we can differentiate between chains and keep prometheus data from old chains. We can (and are trying to) do this with the span metrics labels crate, but it seems to not be configured 100% correctly.

**Comment by hdevalence** [comment]
I think it'd be cleaner to not attach the chain ID to any metrics at all; updating the issue title.
