### ISSUE TITLE
Compact serialization of TCT frontier for use in `pd`

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1082]
In `pd`, we need to serialize and deserialize the frontier of the tree in a sidecar table in RocksDB. Currently we use the derived serde implementation for this, but that wastes space serializing a variety of lengths and enum variants for internal structure we can infer from smart calculations. This could save some IO operations on the node.

## New serialization format

- position of frontier tip (= position - 1, or max if tree is full): 6 bytes,
- complete sibling hashes for each level in order from tip to root (as little as 0 bytes, as much as 24 levels * 3 hashes per level * 32 bytes per hash = 2304 bytes),
- hash at frontier tip (could be a hash of commitment, block, or epoch, depending on position): 32 bytes,
- if evaluated, internal hashes of frontier nodes in order from tip to root (as little as 0 bytes, as much as 24 levels * 1 internal hash per level * 32 bytes per hash = 768 bytes).

Minimum total (when non-empty): 6 + 32 bytes = 38 bytes.
Maximum total: 6 + 2304 + 32 + 768 = 3110 bytes.

When the tree is empty, we can serialize it as the empty byte sequence.

## Decoding

This schema, and its particular ordering, means that the encoding can be read in sequence without accumulating a buffer. To reconstruct the tree:

1. If the serialization is empty, return the empty tree. Otherwise:
2. Take the first 6 bytes and convert to a `u64` called `frontier_tip`; if that's equal to `0x0000_ffff_ffff_ffff`, then the position is `None`; else, the position is `frontier_tip + 1`.
3. Create an uninitialized tree at the calculated position.
4. For `height` in `1..=24`, pop `(frontier_tip >> ((height - 1) * 2)) & 0b11` number of hashes from the list of hashes, and in sequence set the hashes at that height and the position equal to `(((frontier_tip >> ((height - 1) * 2)) << ((height - 1) * 2)) + n` where `n` is the index of the hash in the sequence for this level.
5. Compute `(frontier_tip.trailing_zeros() / 16) * 8` to get the height of the deepest internal frontier hash (this computation is checking each tier to see whether it has size zero).
6. If there are hashes remaining, starting at that `deepest` height, from `deepest..=24`, pop one hash off the sequence of hashes, and set it as the hash at that height and the position `((frontier_tip >> ((height - 1) * 2)) << ((height - 1) * 2)) + ((frontier_tip >> ((height - 1) * 2)) & 0b11) + 1` (that is to say, fill in the hash to the right of the previous ones). It should be expected that this iteration only concludes after processing height 0 or after processing height 24.
7. There should be no more remaining hashes.

## Encoding

In the reverse direction, we can serialize a `Tree` into its frontier encoding:

1. If the tree is empty, return the empty encoding. Otherwise:
2. Take the position of the tree: if it is `None`, the `frontier_tip` is the maximum position; otherwise, it is one less than the position (note that the position cannot be zero because the tree is non-empty). Write out the 6 bytes of the frontier tip.
3. Traverse the tree's frontier from tip to root, writing out the sibling hashes for each internal frontier node.
4. Traverse the tree's frontier again from tip to root, writing out each node's cached hash, if any, starting at the tip of the frontier and going up to the root, terminating when a node has no cached hash. It should be expected that this iteration only concludes after processing height 0 or after processing height 24.

For this encoding, a canonical encoding of hashes needs to be used. Elsewhere, we use little-endian encoding, so we probably should use that here also.

## Testing

Property tests should check that the composition of frontier-encoding and frontier-decoding is an idempotence on trees, and for all frontier-encodings of trees, the composition of frontier-decoding and frontier-encoding is an identity on byte sequences.

## Remaining work

A separate ticket/PR should integrate this into `pd`.

It's unclear whether with incremental serialization of full trees and compact serialization of frontiers, there is a place for derived `serde` implementations. Should these be removed when this is integrated?

**Comment by plaidfinch** [comment]
The [`byte-slice-cast`](https://crates.io/crates/byte-slice-cast) crate may be useful for implementing decoding, but I'm not sure it's necessary.

**Comment by plaidfinch** [comment]
For a more compact encoding, compatible with this scheme, there could be an option to switch off serializing cached internal node hashes. This would save up to 768 bytes, and would require no changes to the decoding logic.

**Comment by plaidfinch** [comment]
I don't think this is necessary: we can use the _same_ incremental serialization API for RocksDB, and this will save writes compared to what we're currently doing. Closing this ticket for now.

**Comment by plaidfinch** [comment]
This ticket is relevant to #1128 and may yet be needed, reopening.

**Comment by hdevalence** [comment]
@plaidfinch was this done as a side effect of making the TCT an incremental data structure?

**Comment by hdevalence** [comment]
Great, in that case, I'll close this out as not-planned; if we ever need to revisit it, we'll have it recorded in the issue tracker.
