### ISSUE TITLE
DecodeError with key, value example functionality

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#110]
I haven't debugged this much yet and it may be a tower-abci issue, but for awareness [the basic setup](https://github.com/penumbra-zone/penumbra/blob/main/penumbra/README.md) with `pd` (running the node) and `pcli` (running the client) using the existing example key, value functionality on `main` gives a `DecodeError` 

Steps to reproduce are:

1. Follow [the readme](https://github.com/penumbra-zone/penumbra/blob/main/penumbra/README.md), installing Tendermint by compiling from `v0.35.0-rc3`. The node will start generating blocks as expected.
2. Try to send a request e.g. `cargo run --bin pcli -- tx key value`

I get:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: DecodeError { description: "invalid wire type: ThirtyTwoBit (expected LengthDelimited)", stack: [("Request", "value")] }', /Users/redshiftzero/.cargo/git/checkouts/tower-abci-3fc79852fd8d3c75/f911c04/src/server.rs:165:70
```

**Comment by hdevalence** [comment]
Is that panic in `pcli` or `pd`?

Trying to reproduce with current `main` and `tendermint 0.35.0-rc4` works on my machine; I can set a key with `pcli tx` and recover it with `pcli query`.

**Comment by redshiftzero** [comment]
It was in `pd` but... it turns out this is an error I introduced in the `client-state` branch.... `main` is indeed working, apologies for the noise
