### ISSUE TITLE
Pick up low-hanging fruit on the `pviewd` side of `CompactBlock` syncing

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1123]
**Is your feature request related to a problem? Please describe.**

We'd like syncing to be faster.  Following the incremental TCT serialization in #1103, we no longer perform a write amplification attack on our users' disks. This is a great first step, but based on some minimal profiling, it seems like we're now CPU-bound.

**Describe the solution you'd like**

Some low-hanging fruit we could pick up:

- [x] Use an optimized Poseidon (software) implementation: https://github.com/penumbra-zone/poseidon377/issues/18 (cc @redshiftzero; not sure where this came from but I recall a 5x speedup being possible?);
- [x] A one-off optimization @plaidfinch came up with to accelerate hashing by caching power-of-4-aligned internal hashes of empty blocks within epochs #1125.

**Describe alternatives you've considered**

There were many other ideas discussed on discord, maybe @plaidfinch could edit this issue to fill them in.

**Comment by plaidfinch** [comment]
https://github.com/penumbra-zone/penumbra/pull/1125 implements a micro-optimization that precomputes internal node hashes for power-of-4-aligned sequences of empty blocks within an epoch. This means that an empty epoch of duration 40 saves 9 (height 9) + 2 (height 10) = 11 hashes, assuming the epoch-ending block contains reward notes. The total number of hashes required without the optimization would be 10 (height 9) + 3 (height 10) + 1 (height 11) + 1 (height 12) + 1 (height 13) + 1 (height 14) + 1 (height 15) + 1 (height 16) = 19 hashes. This means we get a savings of more than 2x, for the testnet epoch duration, and more the longer the epochs are.
