### ISSUE TITLE
NCT frontier snapshot endpoint for `pd`

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1131]
**Is your feature request related to a problem? Please describe.**

Motivation is the same as #1128, solution desired is simpler.

If you absolutely know that you don't have any transactions before a certain date (say, you generated your spendkey on that date), it would be nice to not have to sync the entirety of the chain, but rather to start processing at that date.

**Describe the solution you'd like**

`pd` could track every epoch-boundary NCT frontier in sidecar non-consensus storage, and provide a gRPC endpoint to let you request the one for a given epoch, alongside a proof of inclusion of that frontier's root in the JMT.

(some details copied from #1128)

Implementing this would require writing a non-incremental (de)serialization function for solely the frontier of the NCT, into a protobuf representation. Some details about this are discussed in https://github.com/penumbra-zone/penumbra/issues/1082, which I previously closed as low-priority and negligible impact. Because this would not be consensus critical information, we could choose to include or not include cached internal node hashes in the frontier; either choice is fine, and can be altered at will.

On the view-client side, when the view service is started in this checkpointed mode, it should request the checkpoint for the most recent epoch prior to the block desired to start at, and proceed synchronizing from there. In order to prevent leaking information about which height is desired, the client could issue an additional number of random chaff requests to the endpoint, distributed so that the desired request is randomly ordered in the chaff, and cannot be reasonably distinguished in the distribution.

To make this process automatic, we can have key generation store in the custody file the block height at which the keys were generated (check the block height, then generate the keys, to ensure that they only existed before that moment). This way, if you reset your view state, this extra data is present in the custody file and can still be used to resume from that moment in time rather than zero.

**Describe alternatives you've considered**

#1128 is an alternative, but it's not necessary to store this in consensus, as pointed out by @hdevalence.

On the point about automating this via custody, we could instead choose to disable this feature by default and require the user to explicitly opt-in when initializing `pviewd` or `pcli` for the first time.

**Comment by hdevalence** [comment]
I don't think we should do this -- by definition, it's only useful after the chain has been running for a long time, and there are many users who know for sure that they're coming on board far after everyone else.  But that's not where we are now, and it's not where we'll be for at least a year. It's also not important to make any supporting changes now, because the NCT roots are authenticated in the chain state.

**Comment by TalDerei** [comment]
prioritizing https://github.com/penumbra-zone/web/issues/1278 over this approach for now since it's more palatable.
