### ISSUE TITLE
gRPC methods for streaming block roots and epoch roots

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1133]
Building on https://github.com/penumbra-zone/penumbra/pull/1132, we can now have `pd` return streams of only block roots or only epoch roots, which can be used to drastically reduce network bandwidth during synchronization once FMD is implemented.

Proposed protos for these:

```protobuf
rpc BlockRootRange(BlockRootRangeRequest) returns (stream crypto.MerkleRoot);
rpc EpochRootRange(EpochRootRangeRequest) returns (stream crypto.MerkleRoot);

// Requests a range of block roots.
message BlockRootRangeRequest {
  // The expected chain id (empty string if no expectation).
  string chain_id = 1;
  // The start height of the range.
  uint64 start_height = 2;
  // The end height of the range.
  //
  // If unset, defaults to the latest block height.
  uint64 end_height = 3;
  // If set, keep the connection alive past end_height,
  // streaming new block roots as they are created.
  bool keep_alive = 4;
}

// Requests a range of epoch roots.
message EpochRootRangeRequest {
  // The expected chain id (empty string if no expectation).
  string chain_id = 1;
  // The start index of the range.
  uint64 start_index = 2;
  // The end index of the range.
  //
  // If unset, defaults to the latest finished epoch.
  uint64 end_index = 3;
  // If set, keep the connection alive past end_height,
  // streaming new epoch roots as they are created.
  bool keep_alive = 4;
}
```

These are identical in shape to `CompactBlockRangeRequest`, but should be different types because we might change options non-identically between them.

Regarding the above, which is written to be compatible with the protos as they are written, this might be a good time as any to differentiate in the protos the different kinds of `MerkleRoot`, rather than serializing all of them to the same type. We should instead have `NctRoot`, `NctEpochRoot`, and `NctBlockRoot`.

## Unknowns

I don't personally know how the keep-alive functionality is implemented for compact block ranges, but I imagine that could be replicated for this set of queries also.

**Comment by hdevalence** [comment]
I think we should not do this (now), because it won't be useful until we build FMD infrastructure, and we don't know what that will look like -- for instance, we may not want the client to be talking to `pd` at all, but only to an FMD server, in which case we wouldn't be using an RPC like this.
