### ISSUE TITLE
Flow-encrypted vote counting

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1140]
A delegator vote is flow-encrypted, and delegator votes must be tallied via flow-decryption at epoch boundaries (just like delegations/undelegations). This running tally should be checked into the chain for each open proposal at each epoch boundary, until voting ends.

When voting ends, if the proposal has passed, any automated actions associated with it should be enacted (DAO spend, schedule parameter change, etc.)

**Comment by hdevalence** [comment]
Closing this out since we won't ship flow encryption in V1.
