### ISSUE TITLE
Chain parameter change proposals

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1144]
A chain parameter change proposal should have a freeform text field to describe the motivation for the change, as well as:

- a non-empty mapping from chain parameter name to new value, and
- a block height (in the future) at which the parameters should be changed.

**Comment by zbuc** [comment]
Probably don't want every parameter to start with -- maybe just a few to start.

Need to define which parameters can change by governance. Some can't (for example epoch duration)
