### ISSUE TITLE
Proposal deposit period

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1155]
How long should the proposal deposit period be? Should we have one at all, or should the single proposer be required to put in all the deposit at time of proposal?

**Comment by hdevalence** [comment]
Having a deposit period at all is only useful if we do joint deposits.  But this is much more complicated, and means that we have many more possible states.  Instead, we decided to have a single proposer put in the entire deposit, and have voting begin immediately.
