### ISSUE TITLE
Proposal voting period

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1156]
How long should the voting period be? This may depend on the type of proposal, so see #1158 for a list of types that may have different voting period lengths.

**Comment by hdevalence** [comment]
We should make sure this is a governance parameter so it can be changed over time as the chain evolves.

**Comment by hdevalence** [comment]
@conorsch Can you check that this is a governance parameter and is adjustable?

**Comment by cratelyn** [comment]
https://github.com/penumbra-zone/penumbra/blob/main/crates/core/component/governance/src/params.rs#L14-L16

it looks like this is already covered by `proposal_voting_blocks`, does that sound correct?
