### ISSUE TITLE
Proposal deposit required amount

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1157]
How should the deposit required amount be chosen?

Especially the early days of the chain, while there's a lot of price discovery happening, the value of the staking token may change rather rapidly, which could produce quick fluctuations in the difficulty of making a proposal. In one direction, it could go up quickly, making proposals (including those to lower the deposit amount) harder, or go down, allowing for more spam proposals. Should we have some kind of control mechanism here, or is this not a problem in practice?

**Comment by hdevalence** [comment]
I don't think we need to do anything here, we can just have a chain parameter, and then adjust it by governance if need be.  The deposit amount serves no purpose other than to deter spam, so it's not particularly important to dial it in really precisely.

**Comment by hdevalence** [comment]
Let's set it to `100penumbra` by default.
