### ISSUE TITLE
Document existing protobufs

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1178]
We now publish protobuf documentation to https://buf.build/penumbra-zone/penumbra/ however only some of our protobufs have good descriptions.

The documentation would be much better if the fields and messages were properly described, so we should make a pass through all our protobuf files and update documentation.

**Comment by conorsch** [comment]
We've done a pretty good job of documenting the protobufs as we write them. Sure, there are gaps, but in general we'll continue to expand the docstrings opportunistically as we work on those parts of the code.
