### ISSUE TITLE
Wallet: Separate spending and viewing authority

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#118]
Currently `pcli` is assuming that the user has spend authority, generating a spend key for them if they don't have one. But as @hdevalence pointed out on Discord, we will need to also support the case where one only has viewing keys and no spend authority.

This would mean at least:
* What we save in the wallet file needs to change, we won't have a `SpendSeed` to save, and instead will have one or more viewing keys, which could be incoming, outgoing, or full
* The `ClientState` needs to change, currently the keys field on that struct simply stores a `SpendKey`
* more TK

This issue is for deciding what the best way to support both situations is in `pcli`.

**Comment by hdevalence** [comment]
I think we can punt on this for a while, since the only case that this will be useful is when we have some external signing mechanism like a hardware wallet.

**Comment by hdevalence** [comment]
This was done as part of the wallet rewrite.
