### ISSUE TITLE
021-eurydome release

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1180]
# Testnet Release

Testnet name: 021-eurydome
Release date: 7/18/2022
Milestone link: [X](https://github.com/penumbra-zone/penumbra/milestone/14)
Testnet release manager: @aubrika 

# Testnet Release Manager Checklist

Monday (week before release):
- [x] Create GitHub milestone, work with team to populate the milestone with tickets targeted for the release.
- [x] Create new testnet directory with initial genesis allocations for this testnet (make sure all current team members and the Galileo bot have some assets!)
- [x] Update `discord-addresses` file using the Galileo bot (`cargo run --release history --channel <channel>`)
- [x] Update `testnet/<moon>/allocations.csv` file with the above Discord faucet addresses

Thursday:
- [x] Check in with team again in a release meeting and update the GitHub milestone to ensure it represents what will make it into the testnet.

Monday (release day):
- [x] Check for any [tendermint updates](https://github.com/tendermint/tendermint/releases) and update the Dockerfiles, documentation, and relay deployments with the latest desired version
- [x] Update the User Guide to mention the git tag
- [x] Create new git tag e.g. `006-orthosie`, push to shared remote: `git tag -a <tag_name>` - must be annotated tag for Vergen build. This will create a `Waiting` GitHub Action for deployment.
- [x] You must [manually review](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) the `Waiting` deployment in the GitHub UI before the deployment will begin. Monitor the GitHub action to ensure it completes.
- [x] Update Galileo to run against the correct tag: change [the dependencies in the Cargo.toml](https://github.com/penumbra-zone/galileo/blob/main/Cargo.toml#L11) to reference the new git tag and commit to `main`.
- [x] Bounce galileo: git checkout latest tag in `~/penumbra`, stop galileo, git pull main in `~/galileo`, `pcli wallet reset`, start Galileo.
- [x] Make GitHub release object.
- [x] Make an announcement to Discord 🎉

**Comment by hdevalence** [comment]
Due to a tag snafu, we're redoing this with a new tag, and took the opportunity to slip a few more performance improvements in.

This means we'll have a `021-eurydome.1` tag.  I unchecked the Galileo points there because they'll need to be redone with the new tag.
