### ISSUE TITLE
Deposit fees in the DAO Treasury account instead of burning them

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1224]
After implementing multi-asset fees, it doesn't make sense to just burn fees any more.  The purpose of the fee mechanism is just to price block space, so we should pick the next simplest thing, which is to deposit them in the DAO Treasury account.

**Comment by hdevalence** [comment]
(This is blocked on governance implementation).

**Comment by plaidfinch** [comment]
We're going to put fees into validator funding streams instead.
