### ISSUE TITLE
Remove block proof module from TCT

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1235]
This is no longer necessary for implementing swap claims. @zbuc can you confirm that we're no longer depending on this? I don't want to go and remove this out from under you, but I don't want it to sit around longer than it needs to.

**Comment by zbuc** [comment]
@plaidfinch we are not, I have already done this in the (unmerged) #1216

**Comment by plaidfinch** [comment]
Looks like this has already been done.
