### ISSUE TITLE
Wallet: Rename `--addr` to `--node`

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#127]
Currently on `main` we have two `pcli` options which are too similar:
* `pcli addr` which is a subcommand that manages the diversified addresses
* `pcli --addr` which passes in the address of the tendermint node

Proposed fix is to rename `--addr` to `--node`

**Comment by hdevalence** [comment]
What about `--node`? Unlike `pd start`, `pcli` isn't going to be hosting anything.
