### ISSUE TITLE
Refactor `pcli` CLI design

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1276]
The `pcli` design has gotten a little unwieldy and there's been some discussion about refactoring it for better usability. Initial thoughts based on conversation with @hdevalence:

We might consider separating subcommands not by functional area, but rather by capability, i.e.:

- `pcli q` queries public state (no key needed)
- `pcli view` queries private state (full viewing key needed)
- `pcli tx` executes transactions (spend key needed)

This should ideally cover most of the functionality we'd like, but there's some functionality we might want to be separate:

- `pcli validator` does validator-related things (validator key needed)
- `pcli wallet` manages keys (should this be renamed? "wallet" isn't great)

This work interacts with @zbuc's work on swap subcommands, so we should coordinate on a design here, implement it in a separate PR, and then rebase our respective work on top of that new structure.

**Comment by hdevalence** [comment]
Edited the comment to split out the "main three" from the other commands. Some other thoughts on commands:

- We could rename `pcli wallet` to `pcli keys` and have it focus only on key management. There's only one subcommand (`reset`) that's not about key management, and it could be promoted to top level (`pcli reset`).
- `pcli addr` and `pcli balance` could move into `view`, as `pcli view addr` and `pcli view balance`. `addr` isn't stateful, it's really more of a key management function technically speaking, but I think putting it in `keys` would be more confusing.

**Comment by plaidfinch** [comment]
Currently, here's the map of subcommands:

- addr
    - ephemeral
    - show
- balance
- chain
    - info
    - params
- q
    - key
    - shielded-pool
    - tx
- stake
    - delegate
    - list-validators
    - redelegate
    - show
    - undelegate
- sync
- tx
    - send
    - sweep
- validator
    - fetch-definition
    - identity
    - template-definition
    - upload-definition
- wallet
    - delete
    - export-fvk
    - generate
    - import-from-phrase
    - reset

**Comment by plaidfinch** [comment]
Proposed new hierarchy:

- `refresh` (formerly `wallet reset`)
- `sync`
- `key` (formerly `wallet`)
    - `generate`
    - `import`
        - `phrase`
    - `export`
        - `full-viewing-key`
    - `delete`
- `info`, `i` for short
    - `tx`
    - `validators`
    - `chain`
        - `status` (formerly `chain info`)
        - `parameters` (formerly `chain params`)
    - `shielded-pool`
        - `root`
            - `global`
            - `epoch`
            - `block`
        - `commitment`
        - `nullifier`
        - `quarantined-nullifier`
        - `scheduled`
    - `query`, `q` for short (formerly `q key`)
- `view`, `v` for short
    - `balance`
    - `staked` (formerly `stake show`)
- `tx`
    - `send`
    - `sweep`
    - `delegate`
    - `redelegate`
    - `undelegate`
- `validator`
    - `identity`
    - `definition`
        - `template`
        - `fetch`
        - `upload`

**Comment by hdevalence** [comment]
I had:

- query
    - key
    - shielded-pool
        - anchor
        - block-anchor
        - commitment
        - epoch-anchor
        - nullifier
        - quarantined-nullifier
        - scheduled
    - tx
    - chain
        - subcommands tbd, replacing `chain info`, `chain params`
    - stake
        - subcommands tbd, replacing `stake list-validators`, `validator fetch-definition`
- view
    - addr
        - ephemeral
        - show
    - balance
    - stake (formerly `stake show`)
- tx
    - send
    - sweep
    - delegate
    - undelegate
    - redelegate
- keys
    - generate  
    - import-from-phrase
    - delete
    - export-fvk
- sync
- reset
- validator
    - identity
    - template-definition
    - upload-definition

**Comment by hdevalence** [comment]
Some differences:

- I think `query` is better than `info`, because it conveys that the command will be querying the chain, and I think we should keep the existing structure of the `query` command as being a fairly lightweight wrapper around K/V queries.
- `reset` seems better than `refresh` to me, because "refresh" implies that it reloads data, but the command only does deletions
- We could arguably have `validator upload-definition` be in `tx`, but I think it's better to segment validator-specific commands from the main transaction commands.

**Comment by plaidfinch** [comment]
The reason I picked "refresh" was that there was some confusion from several users about whether `pcli wallet reset` would delete their keys, understandable given that `pcli wallet generate` creates the keys. Is there another name we could use besides `reset`? Is it less salient now that it's moved out of the `wallet` subcommand, so we shouldn't care?

**Comment by plaidfinch** [comment]
It could even be `pcli view reset`, to emphasize that it is resetting your local view of the chain, but not any keys or state on chain?

**Comment by hdevalence** [comment]
We could call it `reset-state`, or, alternatively, we could move it into the `view` subcommand as `pcli view reset`?

**Comment by hdevalence** [comment]
Sounds like `view reset` is a winner
