### ISSUE TITLE
Terraform module for GCS bucket for remote state

### ISSUE THREAD

**Issue by agouin** [penumbra-zone/penumbra#1285]
**Is your feature request related to a problem? Please describe.**
Terraform state files should be managed remotely to remove the need for state files in the repo and allow multiple operators to work on a module simultaneously.

**Describe the solution you'd like**
We can use GCS buckets to store terraform state remotely.

[Use a Gcloud storage bucket to store remote state](https://cloud.google.com/docs/terraform/resource-management/store-state)

**Describe alternatives you've considered**
Storing state in github has been a pain point for us in the past due to large PRs and state drift due to tfstate files being out of sync between branches.

**Additional context**
Strangelove uses this strategy for our own terraform deployments.

**Comment by danbryan** [comment]
#1281
