### ISSUE TITLE
Kubernetes Deployment for penumbra fullnode

### ISSUE THREAD

**Issue by agouin** [penumbra-zone/penumbra#1288]
**Is your feature request related to a problem? Please describe.**
As a follow on to #1286, and in addition to #1287, once we have the GKE cluster and node pools, we will need to spin up the kubernetes resources to compose the testnet. A core part of this will be the penumbra fullnode(s). This node will participate in the p2p network with the validators but will not participate in consensus. It will additionally expose the interfaces to a public domain such as tendermint RPC and penumbra GRPC.

**Describe the solution you'd like**
- Use a kubernetes `Deployment` or `ReplicationController` that will have a daemon container for `pd` and a second container for `tendermint`. 
- Use `initContainers` to handle startup tasks such as disk ownership and config population.
- Two PVCs, one for the pd persistence (rocksdb) and one for tendermint persistence.
- Kubernetes ingress for the exposed services (RPC and GRPC), using google managed certificates and reserved IPs on the load balancers. This will make the fullnode, or cluster of fullnodes, accessible behind a load balancer on a domain such as `https://rpc.testnet.penumbra.zone`.

**Describe alternatives you've considered**
N/A

**Additional context**
This is the strategy Strangelove uses to host fullnode infrastructure.

**Comment by boojamya** [comment]
Test gRPC before closing.

**Comment by conorsch** [comment]
This is done. See #1659 & #1818 for additional detail.
