### ISSUE TITLE
CI/CD ibctest  integration tests

### ISSUE THREAD

**Issue by agouin** [penumbra-zone/penumbra#1291]
**Is your feature request related to a problem? Please describe.**
Integrate https://github.com/strangelove-ventures/ibctest into penumbra's CI/CD pipeline

**Describe the solution you'd like**
- Integrate `ibctest` conformance test suite into CI/CD pipeline, so that every PR will be tested to ensure it does not break IBC.
- Determine any test cases that might need to be written outside of the conformance suite for specific test needs.

**Describe alternatives you've considered**
Using the terraform/kube automated testnet deployments for the PR lifecycle. This would require complex overhead such as linking IBC paths between the PR testnets and the weekly testnet, and would be an anti-pattern for a short lived integration test.

**Additional context**
This will allow testing IBC from the client creation, connection handshakes, channel handshakes, packet flows, and other useful cases in the future e.g. interchain accounts, interchain queries, etc.

**Comment by hdevalence** [comment]
Closing this out as stale -- we're now working on hooking `pclientd` into InterchainTest, but this issue isn't the best place to track that.
