### ISSUE TITLE
CI/CD rust documentation generation

### ISSUE THREAD

**Issue by agouin** [penumbra-zone/penumbra#1293]
**Is your feature request related to a problem? Please describe.**
CI/CD pipeline that will produce rendered output for the following documentation:
- Protocol specification (mdbook) to protocol.penumbra.zone
- User documentation (mdbook) to guide.penumbra.zone
- Rust API docs (cargo doc) to rustdoc.penumbra.zone
- Protobuf docs to protobuf.penumbra.zone

**Describe the solution you'd like**
Add github actions that will create artifacts (either direct artifacts or a URL to the rendered content) for the documentation.

**Describe alternatives you've considered**
Checkout the specific branch locally and build the rendered documentation.

**Additional context**
N/A

**Comment by conorsch** [comment]
Looks like all of these are done:

* https://protocol.penumbra.zone/main/index.html
* https://guide.penumbra.zone/main/index.html
* https://rustdoc.penumbra.zone/main/index.html (:warning: broken styles on homepage)
* https://buf.build/penumbra-zone/penumbra

The rustdoc styles need to be fixed. We're now hosting the protobuf docs on `buf.build`, and `protobuf.penumbra.zone` is now a dead URL. Would be nice to redirect that or at least shut it off.

**Comment by conorsch** [comment]
> The rustdoc styles need to be fixed. 

First attempt in https://github.com/penumbra-zone/penumbra/pull/1765, but alas, I still see the issue on https://rustdoc.penumbra.zone. Will take a closer look.
