### ISSUE TITLE
Guide has incorrect instructions

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1307]
**Describe the bug**

As reported on Discord, we didn't completely update the guide for the new `pcli` commands, e.g., it still points people to `pcli addr show`.

We should do a pass over the guide and ensure all the commands are up-to-date.

**Comment by plaidfinch** [comment]
Thought I already did this in the closed PR. I'll take another look through.

**Comment by pygmygoats** [comment]
We should add a section for upgrades ?

Probably include:
`cargo run --release --bin pcli view reset`

**Comment by pygmygoats** [comment]
Messaging from Polkachu: 
On https://guide.penumbra.zone/main/pd/join-testnet.html, cargo run --release --bin pcli -- stake delegate 1penumbra --to penumbravalid1g2huds8klwypzczfgx67j7zp6ntq2m5fxmctkf7ja96zn49d6s9qz72hu3 is wrong. should be "transaction delegate"
cargo run --release --bin pcli -- balance is wrong too. Should be view balance

Also noticed from messages and brief skim: 
`cargo run --quiet --release --bin pcli wallet generate`
should be `cargo run --quiet --release --bin pcli keys generate`

`cargo run --release --bin pcli wallet reset` should be 
`cargo run --release --bin pcli view reset`

`cargo run --quiet --release --bin pcli addr show 0` should be
`cargo run --quiet --release --bin pcli view address 0`

**Comment by pygmygoats** [comment]
Addressed in #1334
