### ISSUE TITLE
Have pcli error on too-large transactions and suggest pcli tx sweep

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1316]
**Is your feature request related to a problem? Please describe.**

The current testnet setup causes problems with dust notes, for two reasons: (1) our epochs are very short, causing lots of reward notes (2) our proofs are transparent and not succinct, so all the actions are much bigger than they will be in the future.

This manifests as an error submitting transactions, where the transaction is too large to be URL-encoded.

**Describe the solution you'd like**

To fix this, we should:

- [ ] determine a bound on the max size we can submit. This doesn't have to be exact, it can be found by just one-off patching pcli to submit longer and longer runs of zeros until an error occurs;
- [ ] once we have a bound (we can be conservative), check the transaction bytes are shorter than the bound, and if not, error out with a suggestion to run pcli tx sweep.

**Describe alternatives you've considered**

We don't need to do a Great job at this, because this is a problem that's specifically exacerbated by our current testnet setup. Instead, we just need to do a minimal simple thing to point people at the sweep command.

**Comment by zbuc** [comment]
@hdevalence would it be reasonable to detect the "transaction size too large" error and recommend sweep at that point instead? otherwise I've found that it's somewhere between 2^18 and 2^19 bytes where the transaction fails to send. Currently bisecting the range to figure out the exact boundary.

**Comment by hdevalence** [comment]
What about picking 2^18 as a conservative lower bound?

**Comment by zbuc** [comment]
499975 is the exact first byte size that's "too large", FWIW
