### ISSUE TITLE
add the clue key to the note commitment

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1317]
Currently the note commitments commit to the amount and asset of the value, plus two of the three components of the address (diversified base, transmission key). 

I'm not aware of any negative security implications to _not_ including the clue key, but would it be better to also commit to the clue key such that we are committing to all components of the address?

**Comment by hdevalence** [comment]
We should definitely include the clue key in the note commitment — we want to ensure that two notes are equal iff their note commitments are equal.
