### ISSUE TITLE
should we verify the construction of the clues somewhere?

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1318]
Starting with #1312 we'll be adding clues into transactions. There is not a 1:1 mapping between clues and outputs however. I'm wondering if we should verify the clue generation somewhere (in ZK) to check that the clues were constructed for the right clue keys. Rephrased, we would verify (perhaps in each output proof) that there exists a valid clue in a list of clues for the diversified clue key of the destination address. Does this make sense to do?

**Comment by hdevalence** [comment]
The clue construction isn't snark-friendly, so this would be very expensive to do in a circuit. In addition, it's not clear what the privacy benefit would be -- if the transaction constructor is malicious, they can already compromise privacy (by tweeting out the transaction contents, for instance), so it seems better to leave them unverified, similar to the in-band note encryption.
