### ISSUE TITLE
Decide which data should be saved in view service vs being queried from fullnodes

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1340]
Currently there's some non-private data being cached to the view service, alongside private data.

It should be possible to query most of the non-private data from the fullnodes. We should probably make a principled design decision on which data should live in the view service database.

**Comment by hdevalence** [comment]
So far we've ended up dividing this along the line of whether the data is scoped to a particular user (in which case it goes in the view service) vs whether the data is part of the public state (in which case it doesn't), and this has worked reasonably well so far.
