### ISSUE TITLE
Make `BatchSwapOutputData` record a complete picture of a batch swap

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1341]
**Is your feature request related to a problem? Please describe.**

Currently, the `BatchSwapOutputData` only records $(\Delta_1, \Delta_2)$, $(\Lambda_1, \Lambda_2)$, and a success bit, but doesn't contain the trading pair or height. Originally, this decision was made on the basis that since the `BatchSwapOutputData` would probably be queried by the trading pair and height, those were extra data, and we could save space by not including them.

But this means that the `BatchSwapOutputData`, as a standalone structure, doesn't give a complete picture of what the swap was.

**Describe the solution you'd like**

Change the `BatchSwapOutputData` domain and proto types to include:

* a trading pair
* a height

**Additional context**

This will allow simplifying the `SwapClaimProof` verification function, which can now take a single `BatchSwapOutputData` as a parameter, rather than also requiring a height and trading pair. It also ensures that the `SwapClaimProof` can be verified statelessly.

**Comment by zbuc** [comment]
This happened as part of the wider Swap implementation.
