### ISSUE TITLE
State Model V3

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1353]
RocksDB can (probably) provide an exact set of live keys per version, so... let's redo the state model, again.

A lot of things we'd want to do on the DEX, for example, are difficult to accomplish without data indexing.

Some of the staking and governance implementation could be simplified with this as well.

- [ ] Fill in design writeup (@hdevalence)
- [ ] Refactor (someone else? @zbuc @aubrika)

**Comment by hdevalence** [comment]
Replaced by https://github.com/penumbra-zone/penumbra/issues/1454
