### ISSUE TITLE
Better handle liquidity status in swap front-end

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1366]
Currently the swaps in `pcli` don't report on whether there was enough liquidity available to perform the swap or not.

It should be able to implement messaging to the end-user on whether their swap had sufficient liquidity to execute or not by ~~checking the output notes received (since two output notes will always be minted regardless) and seeing if the positively-valued output note is associated with the input asset or output asset.~~

A better way to handle this would be by checking the BatchSwapOutputData after the swap transaction is confirmed.

**Comment by hdevalence** [comment]
Regardless of what the `pcli tx swap` behavior is, it'd be useful to have a query command of the form
```
pcli q dex SUBCOMMANDS
```
that allows querying for info about the `BatchSwapOutputData`.

**Comment by zbuc** [comment]
Fixed in #1410
