### ISSUE TITLE
Create an asset registry

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#140]
Our asset IDs are hashes of denomination traces, so we need to have a registry that inverts the map and allows looking up the denomination by the asset id.  This can be part of the public chain state, since conservation of value means that every denomination is either (a) one that was created as part of the geneses state or (b) one that was created as part of a (transparent) IBC transfer.

We could do this by (proposal sketch):

- [x] keeping a `BTreeMap<asset::Id, String>` in the node application;
- [x] initially populating it with the assets from genesis;
- [x] providing an ABCI query that returns a list of `(asset_id, denom)` pairs;
- [ ] ~having `pcli` pull the registry while syncing and cache it as part of its local state.~

**Comment by hdevalence** [comment]
> keeping a `BTreeMap<asset::Id, String>` in the node application;

Once #146 lands, this should probably be a database table rather than an in-memory map.

**Comment by zbuc** [comment]
>  having pcli pull the registry while syncing and cache it as part of its local state.

The cacheing part is being punted as there's no actual `pcli` sync implementation yet.
