### ISSUE TITLE
Store nullifier set and note commitment tree in database

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#144]
We need to store the following information in the database:

- the nullifier set (idea: table with one column, nullifier, acting as the index, use for set membership)
- the note commitment tree (idea: table with one row, height column and a binary blob with a serde-bincode encoding of the `BridgeTree`)

Currently, we create a new empty NCT and nullifier set whenever we initialize the `App`, regardless of what the actual database state is. Instead, we should load things from the database.

**Comment by redshiftzero** [comment]
Will be resolved by #146
