### ISSUE TITLE
AMM calculation seems off

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1441]
**Describe the bug**
i'm pretty sure the stub logic i implemented for the batch netting is totally wrong

i think it's netting the flow in only one direction, and burning the return direction

**To Reproduce**

@hdevalence can you fill more details in here on what's going on?

**Comment by zbuc** [comment]
I think it's somewhere in the logic introduced in this commit: https://github.com/penumbra-zone/penumbra/commit/e4c0bdc3da8eb6a045fb42eed049812af62ae01c but I'm not seeing what the issue is after a cursory glance

**Comment by hdevalence** [comment]
The issue is that, when netting out the cross flow, we only credit one side, and don't handle the flow in the other direction.
