### ISSUE TITLE
Add info on newly-added asset types to the CompactBlock

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1462]
This is a thing we will need to know about, and `record_block` should have a good way of adding new asset types, which ideally would exist as data in the `CompactBlock`. Currently this is only done on storage initialization, but that can't continue indefinitely.

**Comment by hdevalence** [comment]
We'll potentially have many asset types, so we can't rely on every client to save every asset ever created. Instead we should use #1600 to do per-asset lookups.
