### ISSUE TITLE
staking: refactor and clean up staking rate calculations

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1480]
**Is your feature request related to a problem? Please describe.**

Currently, the staking code is in one giant `Component` implementation.  In particular, the staking rate calculations are all done in one big loop in the body of the `end_block` implementation. It would be easier to reason about them if they were broken out into functions that could compute the staking rates for each validator as a pure function with declared inputs and outputs, and if the code was generally a bit cleaner and better organized.

**Additional context**

This structural refactoring (changing the structure without changing the contents) will unlock the ability to make semantic changes to the functionality of the code.

TODO:

- #1481 
- #3453

**Comment by erwanor** [comment]
This was done in #3453.
