### ISSUE TITLE
Unable to `pcli query governance list-proposals`

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1484]
**Describe the bug**
Running on tag `030-isonoe`, I am unable to `pcli query governance list-proposals` against `testnet.penumbra.zone`.

**To Reproduce**
1. `git checkout 030-isonoe`
2. `cargo run --release --bin pcli -- view reset`
3. `cargo run --release --bin pcli -- view sync`
4. `cargo run --release --bin pcli -- query governance list-proposals`

```
Error: status: Internal, message: "Requested proof of inclusion for non-existent key [103, 111, 118, 101, 114, 110, 97, 110, 99, 101, 47, 117, 110, 102, 105, 110, 105, 115, 104, 101, 100, 95, 112, 114, 111, 112, 111, 115, 97, 108, 115]", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 26 Sep 2022 18:11:57 GMT", "content-length": "0"} }
```

The error message should also turn the key into plaintext rather than an array of ints

**Comment by hdevalence** [comment]
The error message is a bit weird -- the `KeyHash` should have a `Debug` impl... ?

**Comment by zbuc** [comment]
I can't replicate this any more 🙃

**Comment by zbuc** [comment]
Happening again today against `testnet-preview`:

```
Error: status: Internal, message: "Requested proof of inclusion for non-existent key [103, 111, 118, 101, 114, 110, 97, 110, 99, 101, 47, 117, 110, 102, 105, 110, 105, 115, 104, 101, 100, 95, 112, 114, 111, 112, 111, 115, 97, 108, 115]", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 30 Sep 2022 17:44:00 GMT", "content-length": "0"} }
```

**Comment by zbuc** [comment]
The ASCII encodes the key: `governance/unfinished_proposals` FYI @plaidfinch

**Comment by zbuc** [comment]
So what's happening is that this key is used for indexing unfinished proposals. After a proposal has been created, the problem goes away.

As a short-term fix, we can initialize the field in `init_chain`, and long-term this key will be deprecated by the Storage V3.0 changes.
