### ISSUE TITLE
implement SpendN, OutputN actions

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1503]
Suggestion from @hdevalence:
> it would be useful to work out how much space saving we could get by having Spend2 and Output2 actions

Similarly for Spend2, Spend4, etc.

Edit: Based on the results below, it makes sense to implement SpendN, OutputN actions where the smallest N is 2. These actions will replace Spend and Output. This makes sense to begin once the Groth16 proofs are implemented.

**Comment by redshiftzero** [comment]
# SpendN

Costs in size per Spend:
* 1 proof (iirc Groth16 proofs are constant size, and I believe are 3 group elements so let’s say 96 bytes) 
* 1 auth signature = 64 bytes
* 1 balance commitment = 32 bytes
* 1 nullifier = 32 bytes
* 1 rk = 32 bytes
*Total cost*: 256 bytes for a single Spend

For what follows I assume we share the rk, auth sig, and proof between the N spends.

Cost for a Spend2:
* Shared proof, auth signature, and rk: 192 bytes total
* 2 nullifiers = 64 bytes
* 2 balance commitments = 64 bytes
*Total cost:* 320 bytes

So there is a 2(256) - 320 = 192 byte saving using `Spend2`.

Generalizing, the cost in bytes for a SpendN = 192 + N * (64). 

# OutputN

Costs per Output:
* 1 proof, 96 bytes
* Note commitment = 32 bytes
* Ephemeral public key = 32 bytes
* Encrypted note = 168 bytes
* Balance commitment =  32 bytes
* ovk_wrapped_key = 48 bytes
* wrapped_memo_key = 48 bytes
*Total cost:* 456 bytes

Cost per Output2:
* Shared proof, 96 bytes
* Rest of stuff is the same, basically a 96 bytes save
*Total cost:* 816 bytes

So there is a 2(456) - 816 = 96 byte savings using `Output2`.

General cost in bytes for an OutputN = 96 + 360 * N.

**Comment by hdevalence** [comment]
> 2 balance commitments

Do we need multiple balance commitments? Since the balance commitments can commit to arbitrary value vectors, I think we could have just one per action, committing to the sum of all of the spends and outputs.

**Comment by redshiftzero** [comment]
ah true! I've updated the calculations above to only use a single balance commitment per ActionN and corrected the size of a Groth16 proof (each proof is two G1 elements (48 bytes compressed), one G2 element (96 bytes compressed), which are 192 bytes in total). Here's a plot showing the savings of ActionN over N actions in bytes:

![savings](https://user-images.githubusercontent.com/7832803/194107461-119ec940-58c7-4823-b6b5-a8224f9c6d0a.png)

Savings are better for the spends, for N=16 we get a savings of 4800 bytes for spends, 3360 bytes for outputs.

**Comment by hdevalence** [comment]
We should backburner this until after we have fee mechanics, which would inform our choices about what's worth implementing. But it seems likely that we'll get more upside out of `SpendN` than `OutputN`, because high-arity spend statements allow more economically sweeping dust value.

**Comment by hdevalence** [comment]
We won't be doing this because we're already partway through our proof ceremony.
