### ISSUE TITLE
Duplicate note commitment causing failure when syncing view service

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1507]
**Describe the bug**

When running `pcli view balance`, I get an error:

```
~/c/p/penumbra ((031-autonoe)|✔) $ cargo run --release --bin pcli -- view balance
Scanning blocks from last sync height 13544 to latest height 27114
[0s] ██████████████████████████████████████████████████   13570/13570   14873/s ETA: 0s
Error: status: Internal, message: "Worker failed: error returned from database: UNIQUE constraint failed: notes.note_commitment", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

There are two separate problems here:

1. Something is creating duplicate notes, which indicates a bug -- the blinding factor in a note is intended to ensure that note commitments are globally unique, and that's not happening here.
2. The view service should not fail on duplicate note commitments.  Although note commitments are verified, in the sense that they must be created from the actual note contents, they're still attacker-controlled (an attacker could deliberately craft two identical notes with identical blinding factors, to obtain duplicate note commitments), so the view service cannot assume that notes are constructed with unique blinding factors.

**This is actually a security bug**, because it violates infallibility of scanning -- an attacker could use this to take a targeted address's view service offline, and thus learn about that user's network location (by watching which client goes offline).

**To Reproduce**

My testnet FVK is

```
penumbrafullviewingkey10meak7pngg580r57fpvclrrzvaf8da56nayejxssv50w85anngfy2sct8myyjy8fgxxs7whrrpew5ncyzma76ern06ueevump8ae7zqd2wd7w
```

and this can probably be used to reproduce the problem.

**Comment by hdevalence** [comment]
To fix this, it seems like we'll either have to decide to:

1. Relax the `UNIQUE` constraint on the notes table, sacrificing uniqueness of note-by-commitment lookups. This relaxation would have to propagate through the whole API, because now a note commitment corresponds to a set of `NoteRecord`s.
2. Reject duplicate notes during scanning, so that duplicated notes are not accepted by the user (and thus become unspendable without a special software implementation). This acts as a forcing function to ensure that client software doesn't create duplicate notes (because the recipients won't accept them).

**Comment by hdevalence** [comment]
My sense is that (2) is probably a better option, since duplicate note commitments "shouldn't" happen, and that way we avoid contorting our API to accomodate malformed data.

**Comment by aubrika** [comment]
Currently, `pviewd` reports this error at `INFO` level instead of `ERROR` level, but doesn't crash on this instance, unlike `pcli` which is stopped by this.

**Comment by aubrika** [comment]
The problem block is 15098, where pcli crashes, and running `cargo run --release --bin pcli q shielded-pool compact-block 15098` provides a list of potentially duplicate note_commitments which @plaidfinch helped me pull out, though we haven't yet been able to identify which in particular is already present in storage.

`"89538d12e30cbccc5a647a79307376b417a471d981b0b42e4866397e1ac8a608"
"858b29518234c445f021b89374bdfdbeeaaf8ab71222a4a4c9c716683c53330c"
"3b9240300f59dbbfe44cf4308c491619cf7589cc34224a5ccaa7834d691c540e"
"3c42bd6134534fd84b1846558835b8cee37708c68f8b04c50791741ac754080a"
"5a2f9072f551809e87b205680c43c274cb7f693f6befe762bb7dea7e5197d10a"
"99adcd65858aadfb6f59dcd2eb6eb8568cfcac27c44038891499658e88a39d06"
"7907141044c754c8935bf577e1d39e71105f251f1b86b66fecba848b2b487209"
"d9db537f53b99b2ae9f77ceb6c69cd13da8e37bd0ced5a390692344d0f07950d"
"b2ac0a8e7003f28b7614509c3ad0a37f8de6ceb6ed1f57b60c7dc29f4e73300c"
"5ab1ff6d69c85aa83d04f04985bcc2e96153214fcc0556c05d9ebc4747e96501"
"4b2939ae54c54ad3df4dfade25fe35ef325a8ce98e14c3b27c4826048354770f"
"9ddbbc4b81eb629d62ae5d0b1a9f703dad29536886bd62efe3afeece3e0e8612"
"9e9aa6e92fb501123cb75a81c417ccd1060baa431ab1b4d27e2f9b40ed41190f"
"ee8dddde3ff3b21893aafea64a143721dcd08961a49f46bd905fded3566e6808"
"8b1ea865bbba0b55a607a151a8a3742019b8cd90190fc2e2868db91e37434508"
"926a3daa4429e0c1be7e0475f42524bfa82a56c78bb98d88df2dedd7030ff409"
"a853fc6e8acde7105f636da047a3a8daf153020594d1d3bdcd1edfcd9db5870e"
"cd827f8725291f6093d958236d414520a28dc6c52a440ed2eac4e0b21a160812"
"7f47256b0567b90db120edbf191047100b16b29696bf3beada3ecc7c65dfa006"
"b67c211a2d7b993a1fe44cd26740ad4c8f1845e25d5514eb5230ac186ffba005"
"92392845ba6a960a3df195fd6b3dd062deb6def04b8dd23dd25cc0ae04267910"
"65c860e3e80ddaf8a93256ef67a0ed88618bf69526b203271d8508f2e82c340d"
"b84e0106a83e894c6b42c3cb66c42071f9ac9bdd7128ca3f6be1944e72cde407"
"b484722bf6410ad916cb6a89aeaf1b13413a3296ce3de20ee2119d13be790e0e"
"66f50bcc8ae3631e4793a89e901e3b21a2b9634fe6160a9031a106d75dbf7d11"
"770f78db0dda4dbd29df3212c214131c07dfab40192053288fd40c7a664e8a08"
"a26b34c1afc757890be028be8c02da0c4c171fc2dfd95250cbda60a62727d104"
"929d27c5a13fd88a22279b082b084892084fcecd6d5d0ef09f4f3bc3cf535a04"
"540cebfb4286c0139ccfb2b5d956785d877776889d7efbec112631e671c1a00f"
"ca1fedc09846ee1b45f1604433cf275e4780a1ed2d28468fea8752053b1f2f05"
"f3021c0542c0ed5fd0e2155342a1e73f9ed6f848ae83fe630230a65cd39f2a04"`

**Comment by aubrika** [comment]
Based on similar duplicates being found by @redshiftzero it appears this issue arises from the refactor to using a `notes` table alongside the `spendable_notes` and `quarantined_notes` table - so when a note is removed from `quarantined_notes`, the associated entry in the `notes` table is not removed, which is causing an error when it is attempted to add the note_commitment to the `notes` table.

@redshiftzero from discord:

```1. The note commitment in question first is added to the notes table at height 13170.
2. At height 13170, it is also added to the quarantined_notes table. (I think at some point it is un-quarantined, and removed from the quarantined_notes table since there are no entries in that table for height 13170 after syncing, but haven't verified this or tracked this down further).
3. Later, we add the same note commitment to the notes table at height 15098. But it was already added in height 13170, so we hit the unique constraint. 
The denom for this note is upenumbra. 
a while ago I also hit a duplicate note commitment when I was doing the recent changes to the integration tests, and my best guess at that time was it was something related to quarantine```
