### ISSUE TITLE
update dev guide to explain proto build process

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1530]
We should add a section to the dev guide about generating protos explaining:

1. The instructions in https://github.com/penumbra-zone/penumbra/tree/main/tools/proto-compiler about how to compile the protos
2. That the version of protoc in apt is pretty old and to follow these instructions if you're not on mac: https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os 

See PR #1475 which has helpful text for the guide

**Comment by conorsch** [comment]
There's a draft PR at https://github.com/penumbra-zone/penumbra/pull/1559. I'm happy with the docs changes, but hope to tack on a CI check that'll nag devs if they forget to rebuild the protobuf specs when necessary.
