### ISSUE TITLE
Deal with sidecar data in Storage

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1531]
As part of the new `Storage` design we'd like to be able to handle sidecar data stored outside of consensus. The use case for this is for storing indices of existing JMT keys.

In #1491 we added the following sidecar methods:

```rust
fn get_sidecar(&self, key: &[u8]) -> Result<Option<Vec<u8>>>;
fn put_sidecar(&mut self, key: Vec<u8>, value: Vec<u8>);
```

Since these use byte keys instead of string keys, we can now build indexed binary data (e.g., sorting by an integer by encoding its big-endian bytes into the key). This should be implemented ad-hoc in individual components when we decide we need it.

For this issue, we aim to support range queries in the sidecar. We'll need to build some range-querying functions that interleave data from the overlay and the underlying state.

* In `State`: `fn range_sidecar(&self, range_start: &[u8], range_end: &[u8]) ->  Pin<Box<dyn Stream<Item = Result<(Vec<u8>), Self::Error>> + Send + '_>>`
* This will return a `futures::Stream` of `Vec<u8>` items representing every value retrieved from the sidecar storage for keys ranging between `range_start` and `range_end`
* The unsaved snapshot data should be queried first, falling back to the stored `Snapshot` data

**Comment by hdevalence** [comment]
We currently don't have any components that need to do out-of-consensus (private) indexing, so I think we could punt on filling in the range support for sidecar data until after doing #1532 and replacing the current `storage` implementation. 

Then, we can adapt the API we come up with for the JMT range queries to this use case.

> The unsaved snapshot data should be queried first, falling back to the stored Snapshot data

Similar to #1532, we'll need to do interleaving here, I think.

**Comment by plaidfinch** [comment]
I agree with discussion on Discord that `nonconsensus` is the most clear name here.

**Comment by plaidfinch** [comment]
Can we use the RocksDB `prefix` operations here as in #1532?

**Comment by plaidfinch** [comment]
As in #1532 [see here for more details](https://github.com/penumbra-zone/penumbra/issues/1532#issuecomment-1282978537), I think we should be using (synchronous) `Iterator`s for this interface, not `Stream`'s. We should wrap things in a `tokio::spawn_blocking` at a layer up beyond this, because using `Iterator`s here allows for sync-to-sync composition with the JMT interface.
