### ISSUE TITLE
Integrate new Storage code

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1534]
* Store NCT in sidecar
* Pass a single `StateTransaction` to each component per transaction

In a block with `N` transactions, the state modification lifecycle will have one `State` and `N+2` `StateTransaction`s applied to it before committing:

- `BeginBlock` processing creates a `StateTransaction` at the start and unconditionally commit it to the `State` at the end
- `DeliverTx` processing creates a `StateTransaction` at the start, and commits it to the `State` only if the transaction executed successfully
- `EndBlock` processing creates a `StateTransaction` at the start and unconditionally commits it to the `State` at the end

The reason all components need to be working with a common `StateTransaction` during the processing of a transaction is that their joint changes should be committed transactionally -- if the tx succeeds, we want all of them, if it fails, none of them

**Comment by hdevalence** [comment]
We'll need to change the `Component` trait to pass around a `StateTransaction`. We currently already have a `Context` struct, I'm wondering if it makes sense to try to put the `StateTransaction` into the `Context`, or ?

**Comment by plaidfinch** [comment]
> The reason all components need to be working with a common `StateTransaction` during the processing of a transaction is that their joint changes should be committed transactionally -- if the tx succeeds, we want all of them, if it fails, none of them

What does it mean for a `StateTransaction` to fail? Do you mean for a `StateTransaction` to fail to be committed to the underlying storage? Or do you mean a Penumbra `Transaction` here when you say "if the tx succeeds, we want all of them, if it fails, none of them"?

**Comment by zbuc** [comment]
> What does it mean for a `StateTransaction` to fail? Do you mean for a `StateTransaction` to fail to be committed to the underlying storage? Or do you mean a Penumbra `Transaction` here when you say "if the tx succeeds, we want all of them, if it fails, none of them"?

The latter. In the case of IBC, there might be failures in processing the transaction that should roll everything back (and in turn fail the `StateTransaction`).

**Comment by hdevalence** [comment]
Closing this as completed by #1558
