### ISSUE TITLE
Tracking issue: `storage2` integration cleanup

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1537]
In #1534 / #1558, we ported the existing `pd` code to use the `storage2` API and execution model.  We'd hoped to have a drop-in replacement, but this turned out not to be possible because the change in execution model forced changes to the component implementation.

Most notably, because all phases of execution are now fallible, components cannot maintain any in-memory state: if a transaction fails, all changes have to be rolled back consistently, so components can only use the `StateTransaction` to write state. This means that components become stateless placeholders for a `Component` implementation, and all of the logic is contained in extension traits that compose component-specific behavior into a `StateRead` or `StateWrite` implementation.

Now that #1558 has landed, we're out of the giant, stop-the-world stage, but we have a number of follow-up tasks:

- [x] #1584
- [x] #1585
- [x] #1587 
- [x] #1586 
- [x] #1588
- [x] #1589
- [x] #1590 
- [x] #1591
- [x] #1592
- [x] #1594
- [x] #1595

Once this is done, we can do #1593 over a longer period of time.

**Comment by hdevalence** [comment]
This will be a good opportunity to drop a bunch of the protos we have right now that just serve as containers.

**Comment by hdevalence** [comment]
Turning this into a tracking issue for remaining TODO items following #1558

**Comment by hdevalence** [comment]
Closing this as completed, since the remaining work of #1593 is an improvement to our existing structure rather than being integration cleanup properly.
