### ISSUE TITLE
Remove `NotePayload`s from `SwapClaim`

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1544]
In the `SwapClaim`, we construct the proof statement to prove that the output notes both (1) have the correct amount but also (2) are controlled by the address that was specified in the original, signed, `Swap` action with the goal that the `SwapClaim` shouldn't need a spend auth signature, because it can only direct the funds into the correct place.

But: we're only proving that there exist two note plaintexts that output funds to the correct address, we're not proving that the constructor of the `SwapClaim` action actually correctly symmetrically encrypted those plaintexts to that address!

So there's a griefing attack where an attacker can take someone else's `SwapClaim`, overwrite the symmetrically encrypted output `NotePayload`s' `encrypted_note` fields, pay a higher fee, and then effectively burn their outputs -- because while the output notes are technically spendable, the user who could spend them never learns what the plaintext is.

The core problem is that we're reliant on data (the note payloads) that's not authenticated by anything.

We could eliminate the `SwapClaim`'s `NotePayload`s entirely, by making it so that the output notes can be fully deterministically derived from the original `SwapPlaintext`.

At the level of the `SwapClaim`, the only thing we'd need to do is to deterministically generate the blinding factors for the output notes inside the circuit -- e.g., by poseidon hashing the blinding factor from the swap plaintext with different domain separators. Then we'd get the property that knowledge of the `SwapPlaintext` is sufficient to have knowledge of its eventual outputs, which seems "right".

Then we wouldn't be dependent on the `NotePayload`s at all, because the client could always derive the contents of the output notes from the `SwapPlaintext` it already knows.

But, in order to actually eliminate the `NotePayload`s, we'd need to change the way the client protocol works, because currently we assume that every new note commitment has a `NotePayload`, and we have the client use the set of `NotePayload`s to build up the note commitments that will be inserted into the NCT.  We might want to do that later, too, for other reasons, like the "out of band" note management idea.

**Comment by hdevalence** [comment]
To do this, we need #1549

**Comment by hdevalence** [comment]
Yes, we still haven't done either #1549 or #1679 (on the agenda for today)

**Comment by hdevalence** [comment]
Closed in #1736
