### ISSUE TITLE
Native support for out-of-band note distribution.

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1549]
Currently, the `CompactBlock` contains a list of annotated note payloads, each of which contains a note commitment, an encryption of the note plaintext, and the source of the note (usually a transaction hash).

This data allows a client to trial decrypt each note to discover which notes are addressed to it.  The client then has to insert *every* note commitment into the commitment tree, marking the ones it cares about for retention and marking the others for forgession. (The TCT accelerates this process by allowing a client to insert a precomputed block root when all note commitments in the block are irrelevant, but this decision can only be made after trial decryption).  

This is **in-band** note distribution: the note contents are distributed via the blockchain.  However, the chain only actually needs to see the note *commitments* to verify proofs.  The chain does not check the note ciphertexts and does not need to. Notes can also be distributed **out-of-band**, without using the chain state.

We'd like to change the semantics of the `CompactBlock` to have native support for out-of-band note distribution. There are two motivations for this:

1. Scalability: if a note is distributed out-of-band, every *other* user of Penumbra can skip scanning it.
2. Security: when performing asynchronous computation like a swap, we'd like later phases of execution to be fully deterministically derived from data signed in the original transaction (as in #1544), and at that point there's no need to be creating encrypted notes at all.

In effect, this allows any Penumbra user to create their own personal rollup, maintaining their own state off-chain and only posting state commitments, nullifiers, and proofs to the L1.  This seems particularly useful for active market makers, who can cheaply perform frequent updates to their own state (e.g., updating their liquidity positions potentially every block), while saving on gas and saving other users from scanning irrelevant state updates. 

There are other important problems to solve to enable this use case, notably, maintaining a fault-tolerant record of the state that has been moved off-chain, but those are out-of-scope of the core Penumbra protocol.

### Redefining `NotePayload` for out-of-band distribution

EDIT: **we decided not to do the below design, and instead to make a first-class `StatePayload` enum, defined as follows:**.
```rust
pub enum StatePayload {
    RolledUp(note::Commitment),
    Note {
        source: NoteSource,
        note: EncryptedNote,
    },
    Swap {
        source: NoteSource,
        swap: SwapPayload,
    },
}
```

Original:

The `NotePayload` domain and proto types are currently defined as follows:
```rust
pub struct NotePayload {
    pub note_commitment: note::Commitment,
    pub ephemeral_key: ka::Public,
    pub encrypted_note: [u8; note::NOTE_CIPHERTEXT_BYTES],
}
```
```proto
// The body of an output description, including only the minimal
// data required to scan and process the output.
message NotePayload {
  // The note commitment for the output note.
  NoteCommitment note_commitment = 1;
  // The encoding of an ephemeral public key.
  bytes ephemeral_key = 2;
  // An encryption of the newly created note.
  bytes encrypted_note = 3;
}
```

Since proto fields are optional, we'd leave the proto unchanged, but modify the domain type to be
```rust
pub struct EncryptedNote {
    pub note_commitment: note::Commitment,
    pub ephemeral_key: ka::Public,
    pub encrypted_note: [u8; note::NOTE_CIPHERTEXT_BYTES],
}

pub enum NotePayload {
    InBand(EncryptedNote),
    OutOfBand(note::Commitment),
}
```
The existing `NotePayload::trial_decrypt()` becomes `EncryptedNote::trial_decrypt`.  We also need to update the `auth_hash` implementation to encode the enum.

For the `AnnotatedNotePayload`, we don't care about the source if the note was sent out-of-band (the reason it's in the compact block in the first place is to allow querying for full transaction data), so we can again leave the proto unchanged, but change the domain type to
```rust
pub enum AnnotatedNotePayload {
    InBand {
        payload: EncryptedNote,
        source: NoteSource,
    },
    OutOfBand(note::Commitment),
}
```

### Nullifiers

**EDIT: we decided not to do this design, and instead to have distinct actions for rolled-up spends and outputs.**

Out-of-band note commitments skip most of the data currently an `Output` contributes to the `CompactBlock`, dropping from `32+32+168+32=264` to `32` bytes (not counting protobuf padding).  To complete the spend-output cycle, however, it would be useful to also support out-of-band nullifiers, dropping the contribution of a `Spend` from `32` to `0` bytes.

Unlike note commitments, which must be broadcast to every user to allow them to synchronize their local instance of the note commitment tree, nullifiers can be freely dropped from the `CompactBlock`, without affecting any user other than the one whose nullifier it was.

To support this, we should add a `bool out_of_band = 5;` to the `SpendBody` proto (and corresponding changes to the domain type).  If `out_of_band` is `true`, the shielded pool component records the nullifier as spent in the chain state as normal, but does *not* add it to the current `CompactBlock`.

### Required Changes

After

- [ ] redefining the `NotePayload` and `AnnotatedNotePayload` types
- [ ] adding `out_of_band` to `SpendBody`

we'll need to propagate those semantics through the rest of the node:

- [ ] update components to handle in-band and out-of-band note payloads;
- [ ] change the memo presence consensus rule so that the "number of outputs" only includes outputs with *in-band* notes, to allow OOB outputs to skip a memo field;
- [ ] update shielded pool component to skip adding `out_of_band` spends;

and then update the data types for the full lifecycle of pre- and post- construction transaction handling:

- [ ] update `TransactionPlan` structures to reflect out-of-band intent while planning;
- [ ] propagate those changes into the `Planner`, but without yet giving the possibility to create OOB spends or outputs;
- [ ] update `TransactionPerspective` to allow the possibility of including the openings of "rolled-up" `Output`s, similar to the way we already handle `Spend`s;
- [ ] update `TransactionView` structures to record both whether outputs were out-of-band and whether we have visibility into the OOB data;

and then update the view server to handle OOB data:

- [x] move the `height_created`, `address_index`, `source` columns of the `notes` table into the `spendable_notes` table, so that the `notes` table is purely a preimage lookup from note commitments to notes;
- [x] add `async fn Storage::record_note(&self, note: Note)` that computes the note commitment, then records the `Note` in the `notes` table (without making any assumptions that it's spendable, just allowing lookup by note commitment), so that we have a way to feed "advice" to the view server about known notes;
- [x] add `async fn Storage::match_notes(&self, commitments: impl Iterator<Item=&note::Commitment>) -> BTreeMap<note::Commitment, Note>` that matches a list of note commitments against the `notes` table and returns the known ones;
- [x] change the scanning logic to call `match_notes` against the note commitments in the `CompactBlock` to learn which ones were known out-of-band, and feeds them in as if they were decryption results;

and then finally prevent users from creating OOB transactions using the default signing mechanism, which doesn't maintain a fault tolerant log and therefore isn't safe to use with out-of-band data (what happens if you drop your database?):

- [ ] Add a policy check to `custody::SoftKms::sign` that rejects any `TransactionPlan`s with OOB spends or outputs.

**Comment by hdevalence** [comment]
Currently the `output::Body` is defined as

```rust
#[derive(Clone, Debug)]
pub struct Body {
    pub note_payload: NotePayload,
    pub balance_commitment: balance::Commitment,
    pub ovk_wrapped_key: OvkWrappedKey,
    pub wrapped_memo_key: WrappedMemoKey,
}
```

but if the `note_payload` is `OutOfBand`, it doesn't really make sense to include the `ovk_wrapped_key` and `wrapped_memo_key`.

I'm wondering what the best way for us to handle this (in domain types and in protos) is. On the proto side, the strategy above would mean that when interpreting a `NotePayload` proto message, we'd use the presence or absence of fields to determine whether it should be a `NotePayload::InBand` or `NotePayload::OutOfBand`. This has the upside that existing uses can be switched over and tweaked so that they handle both cases.

One possibility would be to similarly make the `output::Body` an enum on the Rust side without changing the protos, to make the interpretation of present/absent fields clear:
```rust
pub enum Body {
    InBand {
        encrypted_note: EncryptedNote,
        balance_commitment: BalanceCommitment,
        ovk_wrapped_key: OvkWrappedKey,
        wrapped_memo_key: WrappedMemoKey,
    },
    OutOfBand {
        note_commitment: note::Commitment,
        balance_commitment: BalanceCommitment,
    }
}

impl Body {
    pub fn balance_commitment(&self) -> BalanceCommitment {
        match self {
            Body::InBand { balance_commitment, .. } => &balance_commitment,
            Body::OutOfBand { balance_commitment, .. } => &balance_commitment,
        }
     }
     
     pub fn note_payload(&self) -> NotePayload {
        match self {
            Body::InBand { encrypted_note, .. } => NotePayload::InBand(encrypted_note),
            Body::OutOfBand { note_commitment, .. } => NotePayload::OutOfBand(note_commitment),
        }
     }
 }
```
The downside is that now we have a fairly wide divergence between the domain and proto types, and we have to be constantly matching and rebuilding enums. The divergence between domain and proto types is patched over in our Rust code, but that doesn't help any other tooling in the ecosystem understand it.

This suggests we might want to change the protos so that they more faithfully represent the in-band/out-of-band distinction.  Perhaps we should have distinct `OutputOob` and `SpendOob` actions that can be defined differently, rather than overloading our interpretations of our existing actions with missing fields.

**Comment by hdevalence** [comment]
> This suggests we might want to change the protos so that they more faithfully represent the in-band/out-of-band distinction. Perhaps we should have distinct OutputOob and SpendOob actions that can be defined differently, rather than overloading our interpretations of our existing actions with missing fields.

A further thought on this is that it could allow us to drop the `NotePayload`/`AnnotatedNotePayload` distinction, using `EncryptedNote` (consisting of `note_commitment`, `epk`, `note_ciphertext`) in `Output` actions, and defining
```rust
pub enum NotePayload {
    InBand {
        encrypted_note: EncryptedNote,
        source: NoteSource,
    }
    OutOfBand(note::Commitment),
}

impl NotePayload {
    pub fn note_commitment(&self) -> &note::Commitment {
        match self {
            NotePayload::InBand { encrypted_note, .. } => &encrypted_note.note_commitment,
            NotePayload::OutOfBand(note_commitment) => &note_commitment,
        }
    }
    
    pub fn encrypted_note(&self) -> Option<&EncryptedNote> {
        match self {
            NotePayload::InBand { encrypted_note, .. } => Some(&encrypted_note),
            NotePayload::OutOfBand(_) => None,
        }
    }

    pub fn source(&self) -> Option<&NoteSource> {
        match self {
            NotePayload::InBand { source, .. } => Some(&source),
            NotePayload::OutOfBand(_) => None,
        }
    }
```

**Comment by hdevalence** [comment]
After talking with @aubrika, we decided to aim for a minimal version of this first: https://github.com/penumbra-zone/penumbra/issues/1711

**Comment by hdevalence** [comment]
Closing as completed-ish for now; we will probably want to add a version of `Spend` and `Output` that don't include payload data later, once we ship Narsil.
