### ISSUE TITLE
Give information about an address

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1551]
It would be useful to be able to look up information about an address. At minimum:

- Is it mine?
- If so, what is its index (or is it ephemeral)? An explicit non-goal here is displaying the ephemeral address index; this should never be displayed. (Perhaps a lightweight way to enforce this is to change the `Display` impl for `AddressIndex`?)

Other things this command could do:

- What transactions were sent to this address?
- What transactions were sent from this address (if it's mine)?
- What is the current balance in all denominations spendable from this address (if it's mine)?

Perhaps other things too?

Tentatively, `pcli view address info`? This would require breaking `pcli view address <INDEX>` and instead putting that behind a subcommand like `pcli view address index 1`...

**Comment by hdevalence** [comment]
I think only the first set makes sense to have as part of pcli view address. The others already exist (pcli view balance --by-address) or should be part of the transaction viewing functionality.

**Comment by hdevalence** [comment]
Closing in favor of #2007
