### ISSUE TITLE
Add a custom Serde serializer for the `Amount` proto type

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1562]
**Is your feature request related to a problem? Please describe.**

We now record amounts with an `Amount` type.  The proto-generated type currently serializes like this:
```
              "amount": {
                "lo": 100000000,
                "hi": 0
              },
```
It would be better if it serialized as a decimal string, like this:
``` 
             "amount": "100000000",
```
(Why a decimal string? Because we want amounts to be 128 bits, and don't expect every Serde backend to be able to handle that.) 

**Describe the solution you'd like**

Add a custom serializer implementation for `Amount`s to proto/src/serializers, then add annotations to the proto compiler to use it for the generated `Amount` type.

**Comment by erwanor** [comment]
I wrote out the encoding/decoding part in #1571

**Comment by conorsch** [comment]
We don't want to do this anymore. We recently decided custom serializers are more trouble than they're worth; see #1896 for context.
