### ISSUE TITLE
Create a `PayloadKey` proto type and use it instead of `bytes`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1563]
**Is your feature request related to a problem? Please describe.**

Currently payload keys are represented in protos as `bytes`, so every struct using them has to manually serialize from the byte slice, and it's impossible to apply common formatting rules to the Serde data.

**Describe the solution you'd like**

Add a `PayloadKey` proto type and use it instead of `bytes`. Then add a Serde rule to the proto compiler that shapes the `PayloadKey` serialization to be a base64 string (using `transparent` to hide the `inner` byte slice, and the base64 serializer to encode it as base64).

**Comment by aubrika** [comment]
> Then add a Serde rule to the proto compiler that shapes the PayloadKey serialization to be a base64 string (using transparent to hide the inner byte slice, and the base64 serializer to encode it as base64).

Unsure about this part, are we currently doing this/applying such a rule anywhere else?

**Comment by hdevalence** [comment]
Good catch, we indeed got rid of every custom serde rule and don't do any custom shaping any more.
