### ISSUE TITLE
Provide a `pcli debug` command to streamline supporting users

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1564]
**Is your feature request related to a problem? Please describe.**
Users do not have the necessary context to debug their issues. As a result, helping a user out can require an onerous back and forth to access all the information needed to solve the issue. We can provide tooling to streamline the support process.

**Describe the solution you'd like**
A `pcli debug` command that outputs structured debug information, such as:
- tendermint version
- pd version
- chain id
- other metadata (i.e `pcli chain info`) etc. 
- `uname`
- data directory path

**Describe alternatives you've considered**
There is an existing `pcli query chain info` which embeds some of the data we would want to capture. Maybe, it's enough.

**Additional context**
Feel free to suggest useful data that we should grab

**Comment by pierwill** [comment]
This doesn't look too difficult. Might give it a go 😇

**Comment by erwanor** [comment]
@pierwill awesome, thanks! let me know if you have all the information you need, very happy to connect on discord (https://discord.gg/PkR7EuSt) and chat about this

**Comment by conorsch** [comment]
> data directory path

Also the location of `custody.json`, as that's separate from data dir.

**Comment by conorsch** [comment]
Picked this up, since it'll come in handy when fielding questions from testnet participants. So far it's a pretty barebones approach:

```
$ pcli debug
DebugInfo {
    tendermint_version: Some(
        "v0.34.23",
    ),
    pd_version: Some(
        "pd 042-adraste-22-g4619247",
    ),
    pcli_version: "042-adraste-22-g4619247",
    chain_id: None,
    uname: Some(
        "Linux Antigonus 6.1.7-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 18 17:11:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux",
    ),
    data_directory: None,
}
```

The output is ugly, as it's just a derived debug representation, but I'm inclined to say it's still useful enough to merge, warts and all. Still need to add some logic for looking up the data directories (view, custody, and archive); I don't see value in including `chain_id` since we can mostly infer that from the version output.

**Comment by hdevalence** [comment]
> The output is ugly, as it's just a derived debug representation, but I'm inclined to say it's still useful enough to merge, warts and all.

Hmm, what about deriving `Serialize` and then using `serde_json::to_string_pretty`? I think it'd be about as ugly and about as much effort, but we could parse it if we wanted.

**Comment by hdevalence** [comment]
Rather than `pcli debug`, let's have the command be `pcli debug info`; that way, we can add other debug/devtool commands and have them be bundled away from the main functionality.
