### ISSUE TITLE
Add notification system for state updates in storage2

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1574]
We should get rid of the block height notification system, and replace it with something in the storage system.

(find in files for height_rx to see)
i think it would be cleaner to have a method like Storage::subscribe(&self) -> watch::Receiver<State>
the Storage would create both tx, rx ends of the watch channel and hold on to them, then have subscribe hand out a clone of the receiver and have commit push the latest state into the sender end

1. we could have the channel just notify of a jmt::Version and then have the notified entities use a Storage instance that they have somehow to get a new State
2. we could have the channel notify of a State and then have some kind of fork_again method that makes a new State without sharing the data (not sure how to name this?)
3. we could have the channel notify of a Storage (even though the receivers might have a reference already) and then have the receivers call .state()
4. we could have the channel notify of a new NewState struct that would have a Storage internally and a single .state() -> State method
(1) is kind of weird because the thing you're notified of isn't actually useful on its own
(2) is kind of weird because, like, the fork_again method could be used on any State at any time, and what does that mean?
(3) is kind of weird because it's saying "a new Storage has arrived", which also doesn't feel right

the only tricky thing is that we would want to make sure that all of the recievers get independent snapshots
ah, hmm. i think that a watch::Receiver<State> doesn't work
because the State is already an individual snapshot/fork of the chain state with some (possibly empty) set of in flight changes

**Comment by hdevalence** [comment]
This is done in #1569
