### ISSUE TITLE
Dev scripts to initialize, run, and reset `pd`

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#158]
Currently the sequence of actions to set up a new node, run it (alongside tendermint), and reset it back to pre-genesis, are several complex commands each. It would be good to have scripts (or makefiles, or justfiles...?) to accomplish these actions. This has the side-effect of making our README much less likely to get out of date, and simpler to use to boot.

**Comment by hdevalence** [comment]
We already have some tooling that controls the sequence of actions needed to run `pd`, Postgres, Tendermint, grafana, prometheus, etc, together with `docker-compose`, so ideally we could extend it to handle creating a genesis file rather than adding a second set of scripts.

**Comment by redshiftzero** [comment]
Having a small script for generating the full Penumbra genesis file for dev purposes could be really handy. It would need to take a [template](https://github.com/penumbra-zone/penumbra/blob/main/testnets/genesis_tn001.json) and fill in:
* Info about validator state (to populate the `validators` field) from Tendermint, so it could run `tendermint init validator` if we haven't already, 
* Info about genesis notes (to populate the `app_state` field), by default doing something like sending 100 PEN to an valid address (perhaps optionally taking an address that the dev specifies if they want to spend) could be good.

**Comment by hdevalence** [comment]
We have the `freshstart` script to do this now.
