### ISSUE TITLE
Clean up handling of Merkle proof queries

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1591]
**Is your feature request related to a problem? Please describe.**

Currently, our Merkle proof queries are a mess. We currently have at least two different ways of returning Merkle proofs, with two different root hashes. The situation is as follows.  

First, ideally our app hash would be the root hash of the JMT.  Unfortunately this is not possible, because our IBC counterparty chains, who use the Cosmos SDK, require that IBC proofs have two nontrivial ICS23 proofs, an artefact of the SDK's use of an IBC-specific IAVL subtree (specifically, ibc-go requires that the tree has a [stable prefix](https://github.com/cosmos/ibc-go/blob/c9b806485e1d28f5fed46f323cf6236ccfbd45bd/modules/core/03-connection/keeper/verify.go#L39), something that isn't achievable in a sparsed prehashed tree like the JMT).  To achieve interoperability, we introduce a stable prefix by making our app hash be a hash of the JMT root hash, so we can treat it as a depth-1 Merkle tree, and supply a chain of two proofs.  There are thus two different Merkle roots at play: the "real" JMT root, and the "workaround" apphash.  This was introduced in https://github.com/penumbra-zone/penumbra/pull/1189

Second, there are two kinds of Merkle proofs in use, Tendermint Merkle proofs and ICS23 Merkle proofs. These formats are similar but not identical.  ABCI queries from Tendermint need to be responded to with Tendermint Merkle proofs.  This way, a relayer which queries Tendermint's RPC can have their request forwarded to the ABCI app, and get a Tendermint Merkle proof back, which they then immediately convert to an ICS23 Merkle proof (🫡).

**Describe the solution you'd like**

As in #1586 #1588, ideally the `storage2` crate is general-purpose, and independent of Penumbra.  So the `get_with_proof` method in `storage2::State` should return an ICS23 proof up to the JMT root.

We can handle the Penumbra-specific interop workaround with a new extension trait in the `chain` crate, providing methods like `get_with_proof_to_apphash` or `get_with_proof_to_apphash_tendermint` returning ICS23 or Tendermint proofs. In the case of ICS23, it should return an `ibc::core::ics23_commitment::merkle::MerkleProof`. In the case of tendermint, it should return a `tendermint::merkle::proof::Proof`.

**Comment by conorsch** [comment]
Confirmed during weekly wrap-up today that this work is indeed complete.
