### ISSUE TITLE
Convert lists in the chain state that could be ranges of keys.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1593]
**Is your feature request related to a problem? Please describe.**

Following #1558, we can make range queries on our state now.  This was one of the big goals of #1454, because it avoids a quadratic-cost update process where we have to save lists of keys as values to be able to do indexing.

**Describe the solution you'd like**

Look through the proto files for wrapper structs that just hold lists of items, which may be artefacts of our previous state design's limitations.  If the proto type is only used as a list, replace it with a range of keys.

Don't touch quarantining logic because it will be improved by #1581 

### Dex Component:

- ~~Swap flows~~ (this was eliminated as part of the state rework)

### Governance Component:

- [x] #1633
- [x] #1634
- ~~Proposal Refunds~~ (we'd like to replace this with an NFT mechanism instead in #1635

### IBC Component

- [x] #1636

### Shielded Pool

- [x] #1637

### Staking Component

- [x] #1638
- [ ] Slashed Validators
- [ ] Current Consensus Keys
- [ ] Delegation Changes
- [ ] Tendermint Validator Updates

**Comment by zbuc** [comment]
# Dex Component:

* Swap flows

# Governance Component:

* Unfinished Proposals
* Voting Validators
* Proposal Refunds

**Comment by hdevalence** [comment]
I think we could pause forward progress on this until we wrap up some other work, for instance we're planning to rework the governance code with #1635, and we could wait to change the code until then.
