### ISSUE TITLE
Migrate to ABCI++

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#161]
This is for post MVP1, but once we're a bit further along as a followup to #145 we should migrate to ABCI++. This will let us reject invalid blocks during ABCI++'s Process Proposal phase.

ABCI++ RFC: https://github.com/tendermint/spec/blob/master/rfc/004-abci%2B%2B.md

**Comment by hdevalence** [comment]
We should look into doing this once we finish the `Component` refactoring, especially now that ABCI++ is further along.

**Comment by hdevalence** [comment]
ABCI++ didn't ship, so we won't be doing this.
