### ISSUE TITLE
Replace proposal authorization keys with an NFT mechanism

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1635]
**Is your feature request related to a problem? Please describe.**

Currently, we record the capability to adjust / withdraw / etc proposals using a special kind of randomization of the spend authorization signature. But it would be much cleaner not to have that kind of deep entanglement with the authorization mechanism, and instead use an NFT-based mechanism along the lines of the one used for LP NFTs.

**Describe the solution you'd like**

Eliminate the use of signatures in proposal authorizations. (TODO: fill in)

**Comment by hdevalence** [comment]
I disabled some withdrawal checks in #1676 that didn't fit the new shape of the `ActionHandler` trait and that seemed like they'd be rewritten anyways as part of this issue.

**Comment by plaidfinch** [comment]
This issue is superseded by #1793.
