### ISSUE TITLE
pcli commands write diagnostic info to stdout, rather than stderr

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1642]
**Describe the bug**
The `pcli` command emits progress data, such as syncing block height, to stdout. This means that commands with structured json output cannot have their output safely redirected, or used in a shell pipeline. If we instead print progress data to stderr, then users can still benefit from the informative info being displayed, while permitting pcli to be used like a standard *nix cli tool.

**To Reproduce**
1. Run `pcli query validator definition penumbravalid1lfz3pmtetvmpk3davwe9srqrmtyghfd7uaq644v9gdpk438xa5zqyckd8r | jq .consensus_key`

2. Observe failure to parse output as JSON:

```
parse error: Invalid numeric literal at line 1, column 9
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1018:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
I expect that the output from the command is valid JSON, as it is with the `validator definition template` command:

```
$ cargo run --bin pcli --release -- validator definition template | jq .consensus_key
    Finished release [optimized] target(s) in 0.69s
     Running `target/release/pcli validator definition template`
"w2hluJjw7uMfMcvywSjNue7XvAzoUecFxvrLs8nXMDk="
```

**Screenshots**
N/A

**Additional context**
Similar to https://github.com/penumbra-zone/penumbra/issues/1542 ; recently discussed during review in https://github.com/penumbra-zone/penumbra/pull/1631#discussion_r1026004280 . Changing `println` -> `eprintln` on https://github.com/penumbra-zone/penumbra/blob/7cca81ba5126dc29eb33d6bc3be6636297e6706f/pcli/src/main.rs#L61 would resolve nicely. There are also `--file` arguments that enable writing directly to files as a workaround.

**Comment by hdevalence** [comment]
We also write output via tracing-subscriber, so we should ensure that if we direct progress output to stderr, we also put tracing output on stderr as well.

**Comment by conorsch** [comment]
Closed via https://github.com/penumbra-zone/penumbra/pull/1893
