### ISSUE TITLE
Add an additional RocksDB column family to look up keys by key hash

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1647]
**Is your feature request related to a problem? Please describe.**

To make ICS23 nonexistence proofs, we need to be able to create existence proofs for the left and right splits from the nonexistent key.  This isn't currently possible, because we'll look up those leaf nodes by key hash, but the existence proof requires a full key.

**Describe the solution you'd like**

Add an additional RocksDB column family that allows looking up keys by key hashes. The (RocksDB) keys would be (JMT) key hashes and the (RocksDB) values would be (JMT) keys.  Like the existing JMT keys column family, this column family should be inserted into when a key is added and removed when a key is deleted.

**Comment by redshiftzero** [comment]
Status update? Is this done @plaidfinch?

**Comment by conorsch** [comment]
We think not; but there's WIP in https://github.com/penumbra-zone/penumbra/pull/1681

**Comment by conorsch** [comment]
Update: we still need functionality to support non-existence proofs. The work in #1681 should be revisited; however, this work won't make 042 testnet (#1877) given other priorities.

**Comment by conorsch** [comment]
This will ship as part of #2032, which is slated for 51, so we're on track. Won't land until the associated IBC changes are in, also for 51.
