### ISSUE TITLE
Push TransactionPlan into WitnessRequest RPC

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1669]
**Is your feature request related to a problem? Please describe.**

See https://github.com/penumbra-zone/penumbra/issues/1555

In #1568, the Rust wrapper around the protobuf RPC was changed to take a TransactionPlan, but this change wasn't pushed out into the actual RPC. So the problem that #1555 describes is still present for any user of the view protocol who doesn't use the Rust wrapper. (In general, we should aim to have that wrapper trait just do conversions between domain and proto types, and not more complicated logic).

**Describe the solution you'd like**

Push the TransactionPlan into the WitnessRequest proto, and move the logic currently in the wrapper trait into the view service itself.

**Comment by conorsch** [comment]
From planning meeting today: @aubrika can you prioritize this over the ongoing work in https://github.com/penumbra-zone/penumbra/pull/1663 ? The changes requested here are (hopefully) rather mechanical and can be ground out in an afternoon. (Famous last words. <3)

**Comment by hdevalence** [comment]
> To perform the dummy proof generation in the service itself, do you think it is better to add an `Rng` field to the service or as a parameter to the witness function specifically, or is it alright to have non-deterministic generation for the dummy proofs as so:

Yeah, having non-deterministic dummy proofs seems fine, they're fake padding data anyways so I'm not sure what benefit there is to having them be deterministic.
