### ISSUE TITLE
Swap NFT claim is not bound to height properly

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1679]
**Describe the bug**

Original discussion in Discord:

> We prove that the swap claim uses the clearing price from the block that created the note recording the swap nft
.... but ... you can send the swap nft to yourself (thus including it in a different block height).
>
> So it seems like if there's a price later that you like better, you can send the swap nft to yourself and then get the new price.
> 
> The tricky thing is that we can't easily bind the height when creating the swap nft, because we don't know what block it will end up in.
> 
> instead of having the swap action produce an output note, it publishes the swap nft asset id -- which will be random, because it will have a blinding factor -- and then the chain creates a new "executed swap nft" (unit 1 of asset id hash(height, swap_nft)) and puts it into the note commitment tree.
> 
> then in swap claim, you could open the "executed swap nft" inside the proof to get an authenticated height?
> idk
> we should wait to fix this until after doing the swap blinding stuff
> the problem / lesson to learn is that when we resume execution, we can only resume execution of data actually committed to by the state nft

After further discussion, we realized that the best fix isn't the one above. Instead, a better fix has an overlap with #1549, which changes the semantics of the `CompactBlock` to allow us to add commitments into the TCT without having to have an encrypted note to go with the commitment.

Currently, we record the user's participation in a batch swap roughly as follows:

1. Create a `SwapPlaintext` recording the user's contribution to the swap (including their final claim address).
2. Poseidon-hash the `SwapPlaintext` to an `Fq` element, which we use as the "swap NFT" asset ID.
3. Create a note recording unit 1 of the swap NFT asset ID, controlled by the same address as the claim address.
4. Later, in the `SwapClaim`, do a special kind of spend action that skips spend authorization but proves that the spend is of 1 unit of an asset whose ID is the Poseidon hash of some `SwapPlaintext`, and proves that the output notes have the correct amounts for the batch, that they're controlled by the claim address, etc.

The first key point here is that the swap NFT asset ID acts as a commitment to the `SwapPlaintext`, and that opening that commitment inside the `SwapClaim` proof allows resuming the computation. But there's a bunch of extra steps that aren't actually necessary, and in this case, led to a bug. In particular, what is a note? A note is a typed quantity of value, plus a capability to spend that value. But here we're disregarding that capability, and saying that we have a different notion of what it means to consume the "value" -- namely, resuming the computation.

The second key point is that the swap commitment is also an `Fq` element, just like a note commitment. From the point of view of the TCT, all the leaves are just `Fq` elements; the fact that they're formed as note commitments is irrelevant.

### Solution

Once we have #1622 and #1549, all the ingredients for a much simpler solution are in place: we recast the note commitment tree as a _state commitment_ tree, define both note commitments and swap commitments as different kinds of state commitments, and insert the swap commitments directly into the state commitment tree rather than creating "swap NFTs". Then, to perform a swap claim, we simply witness a TCT inclusion path from the swap commitment up to the anchor, and prove that the path's block height matches the supplied `BatchSwapOutputData`. There's no need to make a fake, special-case spend proof, and the swap commitment is inserted in the TCT by the chain, so there's no more malleability issue.

Moreover, on the client side, we also have an opportunity to clean up the `CompactBlock` a bit, and prevent the current situation, where clients are forced to download additional data from a fullnode to understand their own notes. We'd do this by including the `SwapCiphertext`s and the `BatchSwapOutputData` in the `CompactBlock`.

- [x] #1713
- [x] #1714
- [x] #1715
- [ ] Rename the new `NotePayload` enum introduced in #1549 to `StatePayload`, with variants `RolledUp`, `Note` (containing an `EncryptedNote`), `Swap` (containing a `SwapCiphertext`).
- [ ] Change the `Swap` action to contain only the `SwapCommitment` and `SwapCiphertext`, rather than a general purpose note that happens to contain a swap NFT.
- [ ] Change the DEX component to record the `SwapCommitment`s in the TCT and to record the `StatePayload::Swap` in the `CompactBlock`.
- [ ] Update the `SwapProof` to reflect the simplification.
- [x] #1712
- [ ] Change the `SwapClaim` so that it:
  - [ ] reveals the swap nullifier
  - [ ] produces two note commitments for output notes
  - [ ] contains an amended `SwapClaimProof`, which proves:
    - [ ] knowledge of the swap plaintext corresponding to a swap commitment
    - [ ] knowledge of an inclusion proof for that swap commitment in the state commitment tree
    - [ ] consistency between the block height implied by the commitment position and the `BatchSwapOutputData`
    - [ ] that the swap nullifier was well-formed for the positioned swap commitment
    - [ ] that the output notes are of the correct amounts, and controlled by the address in the swap plaintext.

**Comment by plaidfinch** [comment]
There would need to be a way to detect the "executed swap nft" in order to determine what height to use. Or maybe if you know you're awaiting a swap NFT you can compute the hash and see if it matches for each successive height...?

**Comment by hdevalence** [comment]
> There would need to be a way to detect the "executed swap nft" in order to determine what height to use. Or maybe if you know you're awaiting a swap NFT you can compute the hash and see if it matches for each successive height...?

In #1736 I added a new `swaps` table to the view server that records the swap commitment -> swap lookup.  It also changes the `CompactBlock` format to bundle in the `BatchSwapOutputData`, so the `SwapRecord` the view server stores can save the client from having to download prices.
