### ISSUE TITLE
Add client authorization to view protocol requests.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1682]
**Is your feature request related to a problem? Please describe.**

See #1556.

**Describe the solution you'd like**

Add bearer tokens to the view protocol RPC, as described in that issue:

```
package penumbra.view.v1alpha1;

message ViewAuthToken {
  bytes inner = 1;
}

message ViewAuthRequest {
 core.crypto.v1alpha1.FullViewingKey fvk = 1;
}

message ViewAuthResponse {
 ViewAuthToken token = 1;
}

service ViewAuthService {
  rpc ViewAuth(ViewAuthRequest) returns (ViewAuthResponse);
}
```
Then replace the existing fvk hash / account id with the bearer tokens:
```
// ... in messages for the main view protocol ...

message NotesRequest {
  // Authorizes the request.
  ViewAuthToken token = 1;
  // If set, return spent notes as well as unspent notes.
  bool include_spent = 2;
  // ...
}
```

The existing `pviewd` code has logic to check the existing account ID.  We'll want to delete that logic entirely, but in this issue it's not necessary to replace -- it's more important to get the protos we use for data interchange correct, and we can add an implementation in a later PR.

**Comment by conorsch** [comment]
I'll try to take this one on today, might ping @aubrika for support if I get lost.

**Comment by conorsch** [comment]
> might ping @aubrika for support if I get lost.

Reporting self as lost. Is the goal here to _add_ bearer token handling to the viewservice protocol? This statement in the OP confuses me:

> The existing pviewd code has logic to check the existing account ID. We'll want to delete that logic entirely, but in this issue it's not necessary to replace

How is it possible that we don't need to replace the account id logic? If the protos change, defining a `token` field, then that field must be provided in the rust code when handling the objects. Similarly, if we snip out the `account_id` field from the protos, then we must excise it everywhere. Shall I fudge it for now, passing in `Option(None)` for the value of `token` everywhere?

**Comment by conorsch** [comment]
After discussing this briefly on a call, we decided that making an additive change, inserting the "token" field into the proto specs, was good enough for now. The account_id logic is best cleaned up when we write the replacement impl.

**Comment by hdevalence** [comment]
We shouldn't do this additively, because the goal is to frontload changes to the protocol that external systems have to interface with, reducing churn for external systems. Adding more fields now and planning to remove others later increases the amount of churn, which is the opposite of what we want.

The account ID fields can be deleted immediately. Any Rust code that uses them can also be deleted; that's what I meant by "not necessary to replace".

**Comment by conorsch** [comment]
Discussed this issue with @hdevalence synchronously. We decided to 1) preserve account_id throughout, for now, but make it an option; and 2) add the bearer-token field, also as an option, and update the Rust code to match.

Removing the account-id from the view service was rather straightforward; but other components, like custody, made heavy use of account_id in a way that was not trivial to remove. So, it appears that account_id is useful in some places in the codebase, and may remain useful even after we implement auth tokens. 

Perhaps we should revisit as a group during weekly design meeting to dig in a bit more.
