### ISSUE TITLE
Use rseed mechanism

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1688]
Placeholder issue to use the rseed mechanism as described as https://zips.z.cash/zip-0212, essentially:

We choose a random rseed.
We derive using a PRF the esk from this rseed.
We derive using a PRF the note commitment randomness from this rseed.
The note plaintext includes the rseed instead of the note blinding factor. 

During note decryption the recipient will check epk = [esk] g_d and discard the note if this check fails. 

This will obviate the ephemeral pubkey integrity check (epk = [esk] g_d) check in our proofs

**Comment by hdevalence** [comment]
We should also check whether we should use an `rseed`-style mechanism for swap plaintexts (which we encrypt similarly to the way note plaintexts are constructed), or, whether we should switch to an OVK-based swap encryption mechanism
