### ISSUE TITLE
Remove `ed25519-dalek` stub code

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1693]
We want to remove the `ed25519-dalek` stub code (in pcli and pd) once tendermint-rs transitions to `ed25519-consensus`. The latter has been tracked and resolved in https://github.com/informalsystems/tendermint-rs/issues/355, but was ultimately part of a yanked release.

Desired changes:
- [x] replace `ed25519-dalek` with `ed25519-consensus` in https://github.com/informalsystems/tendermint-rs
- [ ] port penumbra-zone/penumbra to using the corresponding new release of `tendermint-rs`
- [ ] remove stub dalek code from the codebase (pcli / pd)

**Comment by hdevalence** [comment]
Point #1 is addressed by https://github.com/informalsystems/tendermint-rs/pull/1245

**Comment by hdevalence** [comment]
The first point is done now that https://github.com/informalsystems/tendermint-rs/pull/1245 has been merged; we just have to wait for it to propagate through our dep tree.

**Comment by conorsch** [comment]
As with #1932, we're waiting on upstream to release.

**Comment by erwanor** [comment]
`tendermint-rs@v0.29.0` is now out, we're just waiting for `ibc-rs@v0.29.0` and `ibc-proto-rs@v0.26.0` to be published and we should be good to go to close this.
