### ISSUE TITLE
Allow different light clients to be used in the IBC component

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1694]
With #1650, the IBC component has regressed to only supporting a specific implementation of a light client ([ics07_tendermint](https://docs.rs/ibc/latest/ibc/clients/ics07_tendermint/index.html)). Among other things, we had issues making our own `penumbra_proto::Protobuf` marker work wellwith the object-safe marker supplied by `ibc_proto::protobuf`.

Instead of supporting a specific light client implementation, we want to abstract away the implementation and turn on support for any light client implementing ICS02.

- [ ] Reconcile our protobuf marker with the `ibc_proto` one, without changing the semantics of `StateReadProto`, etc. 
- [ ] Make the IBC component work with boxed ICS02 trait objects (such as `ClientState`, `ConsensusState` etc.)
- [ ] Propagate changes through out the codebase, avoiding dynamic dispatch when possible.

**Comment by erwanor** [comment]
We're going to wait needing to support another light client before we implement this. This is so that we don't overfit on the current ibc-rs `Client*` traits, which might change to enable supporting light clients with different semantics. But abstracting away a specific light client implementation is still a priority and something we want to do in the future.

**Comment by conorsch** [comment]
This ticket is outdated. We've decided to support only Tendermint clients for mainnet, and that much we've achieved already. It's possible we'll want to to support specific alternative light clients in the future, but that work should be tracked separately.
