### ISSUE TITLE
Follow-up polishing work for the tendermint/IBC unforking

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1696]
This is an issue tracking small scale improvements and miscellaneous polishing that we should do as follow-ups to the unforking (#1650)

- [ ] Remove obsolete comments (`rg TODO(erwan)`)
- [x] Make clippy happy
- [x] Remove stub verification methods in the IBC module (`penumbra_component::ibc::connection`)
- [x] stop pinning `ics23` versions
- [ ] TBD

**Comment by conorsch** [comment]
Discussed this at IBC sync. Most of the work tracked in this ticket was achieved in 2022Q4. There are still a few lingering TODOs, but those are best handled as part of dedicated assurance work, shortly to come. This ticket wasn't tracked as part of #454, so we're closing it out, and will continue to use #454 as the One IBC Ticket to Rule Them All.
