### ISSUE TITLE
Create `docker-compose` configs for building testnets

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#17]
From #14:

> Tendermint has a nifty [docker-compose config](https://docs.tendermint.com/master/tools/docker-compose.html) for running a local
testnet of several nodes in Docker, we might want something like that
as well for dev purposes?

- [ ] Fix Prometheus configs to read from each server
- [ ] Create DB + pd + tendermint instance for each node
- [ ] Modify `setup_validator.py` script to enable ` --populate-persistent-peers` flag for `tendermint/localnode` invocation

**Comment by zbuc** [comment]
They're using a `Makefile` to manage all of this, and a special `tendermint/localnode` Docker image for local multi-node testnet deployments (https://hub.docker.com/r/tendermint/localnode) source: https://github.com/tendermint/tendermint/tree/05bc2f344a20bd25beb4b6f9e6f41d2295d99492/networks/local/localnode

It looks like they followed a similar approach for managing genesis configs, but have more resiliency as they use a special command within the `localnode` image to generate: `docker run --rm -v $(CURDIR)/build:/tendermint:Z tendermint/localnode testnet --config /etc/tendermint/config-template.toml --o . --starting-ip-address 192.167.10.2`

**Comment by hdevalence** [comment]
Already done
