### ISSUE TITLE
Smoketests should error out if we have a chain-halting bug

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1706]
**Describe the bug**
During release of `037-megaclite` (https://github.com/penumbra-zone/penumbra/issues/1699) we shipped a bug that halted the chain, requiring a hotfix and re-deploy to recover.

**Expected behavior**
The smoketest (network integration test) suite should have caught this error, and failed, prompting developers to scrutinize the relevant code more closely. 

**Actual behavior**
The smoketests blithely reported green marks, so devs thought everything was working just fine. 

**Notes**
Both @hdevalence and @redshiftzero suggest that the smoke tests aren't running for long enough. That is, if the entire test run doesn't execute long enough for an epoch boundary to be encountered, we can miss bugs like might halt the chain.

Rather than simply raise the duration (thus requiring more wall time on every PR), perhaps we can adjust the tests carefully enough that we get stronger guarantees about stability, without waiting a terribly long time. Or, we could crank up the duration for smoketests on a schedule run against main, but not necessarily against every PR.

**Comment by hdevalence** [comment]
In recent changes I made to the smoke test script, we now run a much shorter block interval, letting us get more blocks in the same amount of time.  We've also been moving to longer-running public testnets, which has helped us identify stability issues.
