### ISSUE TITLE
Docker Enhancement: fix build process so changes to crypto/protobuf/wallet don't require full rebuild

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#171]
Right now in the Dockerfile crypto/protobuf/wallet/decaf crates are all built as part of the build cache layer, meaning that if there are any changes to them a full rebuild is necessary. This means that the dev feedback cycle for those crates is slow for Docker development.

Not super high priority but this would be a nice productivity enhancement at some point.

**Comment by hdevalence** [comment]
Obviated by Strangelove deployment improvement work.
