### ISSUE TITLE
Clean up `penumbra_crypto` API for note encryption following #1711

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1716]
**Is your feature request related to a problem? Please describe.**

In #1711 we'll add an `EncryptedNote` type that bundles the note commitment, epk, and note ciphertext. This structure is disconnected from the existing `Note::encrypt` API, and this disconnect should be smoothed over after we land those changes.

**Comment by hdevalence** [comment]
Another thought, xref https://github.com/penumbra-zone/penumbra/pull/1736#discussion_r1045171474 , is that perhaps we should rename `EncryptedNote` back to `NotePayload`, and then have a streamlined API that produces the note payload, or turns a note payload into an `Option<Note>`.

This also connects with #1688 ; we should probably fix the note encryption mechanism to use `rseed` prior to doing the API cleanup, in case it changes some data flow requirements.

**Comment by conorsch** [comment]
This won't make 44; let's carry over to 45.
