### ISSUE TITLE
Make `tonic` an optional dependency of `penumbra-proto`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1717]
**Is your feature request related to a problem? Please describe.**

The Zpoken team mentioned that the use of `tonic` in `penumbra-proto` is a problem, because Tonic depends on Tokio, and Tokio doesn't compile in wasm, but because `penumbra-proto` is a common dependency of many of our crates, this blocks using them from `wasm` contexts.

**Describe the solution you'd like**

Make the tonic-specific parts of `penumbra-proto` behind an `rpc` feature flag (off by default), and make the crates that use RPC definitions enable the `rpc` flag.

**Describe alternatives you've considered**
We could make the `rpc` feature on by default, but making it off by default makes it more likely we'll notice if something breaks when not using that feature flag.

**Comment by zpoken** [comment]
Crates that we use for wasm:
```
penumbra-crypto
penumbra-tct
penumbra-transaction
penumbra-proto 
```

Note that `ibc-proto` also has a dependency on tonic 
```
tonic v0.8.2
└── ibc-proto v0.17.1 (https://github.com/penumbra-zone/ibc-rs?branch=penumbra-034#27639da9)
    ├── ibc v0.14.0 (https://github.com/penumbra-zone/ibc-rs?branch=penumbra-034#27639da9)
       ├── penumbra-proto v0.1.0 (/Users/valentincernusevic/penumbra/proto)
```
And jmt is dependent on tokio 
```
tokio v1.21.1
└── jmt v0.1.0 (https://github.com/penumbra-zone/jellyfish-merkle.git?branch=penumbra-034#94bc1cfe)
    └── penumbra-crypto v0.1.0 (/Users/valentincernusevic/penumbra/crypto)
```

**Comment by hdevalence** [comment]
Out of those four crates, I see only `penumbra-proto` depending directly on `tonic`. There's also an indirect dependency of `penumbra-transaction` on `ibc` and hence `ibc-proto`.

On main, we're using
```
tonic v0.8.3
├── ibc-proto v0.22.0
│   ├── ibc v0.23.0
```
and we've eliminated the `jmt` dependence on `tokio` (and also eliminated most direct use of the `jmt` crate, using `penumbra_storage` instead).

**Comment by hdevalence** [comment]
Looking at https://crates.io/crates/ibc-proto/0.23.0/dependencies , it looks like `tonic` is an optional dependency of `ibc-proto`, so I think we may be able to avoid pulling it in.
