### ISSUE TITLE
Implement Dex Routing

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1722]
- [x] Use data from liquidity indices (#1778) with the `Path` (#1257  #1776  to construct `Path`s based on `TradingPair`s and available `LiquidityPosition`s.
- [ ] #1948
- [ ] #1949

Based on details here: https://hackmd.io/jtoiMn0pQnSTZlOi2ig5Wg

**Comment by conorsch** [comment]
#1725 has taken precedence over this, and will likely ship in #1877. This work we'll track on the subsequent sprint.

**Comment by conorsch** [comment]
https://github.com/penumbra-zone/penumbra/pull/1894 is WIP, good candidate to ship in testnet 43 next week.

**Comment by zbuc** [comment]
@erwanor @hdevalence should this be combined with #1724 ?

**Comment by hdevalence** [comment]
Yes, now that we're doing routing via simulated execution, we can merge them and close this as not planned.
