### ISSUE TITLE
Implement Liquidity Management APIs

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1725]
* [x] #1904
* [x] #1905
    - `PositionOpen`
    - `PositionClose`
    - `PositionWithdraw`
    - `PositionRewardClaim`
* [ ] #1906
* [x] #1907
* [x] #1991
* [ ] #1908
    - Should estimate the payoff curve of a CPMM using linear positions
    - Propose a desired payoff curve, then generate test positions that approximate that payoff curve
* [ ] #1909

Based on details in https://hackmd.io/rsgSwz3BQKuL0GrSF0LWXA# and https://hackmd.io/jtoiMn0pQnSTZlOi2ig5Wg

**Comment by conorsch** [comment]
Discussed in sync today: we'll get a portion of this week in for 041-adraste (#1877), but the rest of the work will require follow-up tickets.

**Comment by conorsch** [comment]
Moving to "Future" column in work-planning because this is an epic. For individual subtasks, we'll drag those onto sprint columns going forward.

**Comment by hdevalence** [comment]
Folding into #1724
