### ISSUE TITLE
rename `NoteCommitmentProof` to `StateCommitmentProof`, `note commitment tree` to `state commitment tree`

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1732]
Now that the TCT will store not just note commitments but swaps also, and in the future other bits of state, we should rename the `NoteCommitmentProof` to `StateCommitmentProof` everywhere (including docs and comments) and `note commitment tree` to `state commitment tree` to avoid confusion.

**Comment by hdevalence** [comment]
Should we also rename "note commitment tree" to "state commitment tree"?
