### ISSUE TITLE
Refactor transaction builder to build up delayed computation

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#174]
Instead of taking the `rng` parameter for each step in the transaction builder, we can take it once, in the `finalize` step. Internally, this would look like building up a "script" of actions to perform using the `rng`, and executing that script upon finalization.

**Comment by hdevalence** [comment]
We could also take an owned RNG at the beginning of the transaction builder and save it internally. This way, we could evaluate the actions eagerly rather than lazily, and avoid having to build an internal script.

**Comment by hdevalence** [comment]
Closing this for now since the design has shifted (and will shift further), we could re-evaluate after finishing wallet refactoring.
