### ISSUE TITLE
Expand `Amount` API to cover existing use cases.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1745]
Here and elsewhere there are a lot of issues where we do internal math on `u64` values, and bridging that with an `Amount` type is difficult. I think this speaks to some limitations of the existing `Amount` type we should address, in particular the lack of an analogue of a "widening multiply + divide" (which we can do for `u64` by means of `u128`).

We should fix those limitations and use `Amount` everywhere before trying to push forward on 128-bit `Amount`s.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/1736#discussion_r1045171833_

**Comment by conorsch** [comment]
From sprint planning today: we'll want to keep our eyes open for opportunities to implement this. For now, moving to "Future" pile.

**Comment by hdevalence** [comment]
Closing this out as not planned -- we now plan to replace those uses with `U128x128` fixed-point arithmetic.
