### ISSUE TITLE
Followup: review signs for fee commitment in Swap actions

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1746]
Followup: review signs for fee commitment in Swap actions

I don't think either this code or the original code was correctly handling signs for the fee commitment. I suspect there are bugs lurking that we only miss because we set 0 fees by default.

We should do a followup pass and:
- [ ] review the signs of fees as they're used in `Swap`s
- [ ] write a state machine integration test that creates and executes complete, fully-valid `Transaction`s (using the test account's note state) that sets distinct nonzero fees for both `Swap` and `SwapClaim` transactions.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/1736#discussion_r1045172362_

**Comment by conorsch** [comment]
Just needs one test, so feasible for testnet 43 still.
