### ISSUE TITLE
release testnet 39: Praxidike

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1757]
# Testnet Release

Testnet name: Praxidike
Release date: January 3, 2023
Testnet release manager: @conorsch 

# Testnet Release Manager Checklist

Preceding Friday (sprint planning day):

- [x] Create GitHub project column, work with team to populate the milestone with tickets targeted for the release.

Tuesday (this will be done on Jan 5 or 6, 2023):

- [x] Construct the genesis data for the release:
  - [x] Create new testnet directory with initial genesis allocations for this testnet by running `cd testnets && ./new-testnet.sh`
    - This genesis data will be used for `testnet-preview` with a randomized version of the future testnet's chain ID.

Thursday:

- [x] Check in with team again in a release meeting and update the GitHub milestone to ensure it represents what will make it into the testnet.
- [x] Draft an announcement for peer review to ensure major changes included are comprehensive.

Following Monday (release day):

- [x] Verify that `testnet-preview.penumbra.zone` is operational; it is redeployed on every push to main, and is an exact preview of what is about to be deployed.
- [x] Create new git tag e.g. `006-orthosie` on `main` (tags created on any other branches will not transfer when merged in) and push to shared remote: `git tag -a <tag_name>` - **must be annotated tag, i.e. `git tag -a`** for Vergen build. This will create a `Waiting` GitHub Action for deployment.
- [x] You must [manually review](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) the `Waiting` deployment in the GitHub Action UI before the deployment will begin. Monitor the GitHub action to ensure it completes after it is approved.
- [x] Update the User Guide to mention the newly created git tag.
- [x] Delegate to the Penumbra Labs CI validator
- [x] Make GitHub release object and include the announcement
- [x] Make the announcement to Discord! 🎉🎉🎉

**Comment by conorsch** [comment]
We experienced a chain halt on the long-running 038-kalyke testnet, so I'm going to proceed with releasing 039 today, rather than waiting till next Monday.

**Comment by conorsch** [comment]
New testnet is live. The early birds in Discord are reporting trouble connecting to peers, though. It looks like some local IPv4 addresses made it into the config, which shouldn't happen because of https://github.com/penumbra-zone/penumbra/pull/1672. Still, it is happening. Leaving this ticket open to follow up on tomorrow and report results.

**Comment by conorsch** [comment]
>  For the fix to Praxidike, I'm going to re-deploy on the old infra to keep things moving.

After some discussion in Discord, we decided to keep the testnet offline, rather than reuse the legacy infra. I'll focus on resolving the remaining blockers and post updates regularly.
