### ISSUE TITLE
`pcli`: add `--by-address` flag to balance command

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#177]
Add a `--by-address` `bool` flag for the `balance` command that builds a table like this:

```
Address            Asset        Balance
Default             pen            100
                    cubes         12
Dogs                shib            24
                    doge          9
```

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/176#issuecomment-976015952_

**Comment by hdevalence** [comment]
One way to do this would be to change the current
```rust
    pub fn notes_by_asset_denomination(&self) -> HashMap<String, Vec<Note>> {
```
to
```rust
    pub fn notes_by_denom_and_address(&self) -> HashMap<String, BTreeMap<DiversifierIndex, Vec<Note>>> {
```
where the `BTreeMap` categorizes the notes by diversifier index.  Users who don't care about the diversifier index can call `.values().flat_map()` to get an iterator over the notes for whatever denomination they want.

To actually do this, we'd have to implement decryption for diversifiers -> diversifier indices, afaik we only do the other direction to derive them currently.
