### ISSUE TITLE
Implement AMM Composition

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1776]
Composition of AMMs (for routing): if we have one AMM trading between asset 1 and 2, and one trading between 2 and 3, we should be able to compose the two to trade between 1 and 3

- [x] Add type information to trading struct (done in #1764)
- [x] Implement formulas in [DEX engine design doc](https://hackmd.io/jtoiMn0pQnSTZlOi2ig5Wg). 
- [x] #1960
- [x] #1933
- [ ] #1951

**Comment by conorsch** [comment]
We merged #1854 this week; @erwanor can you provide a status update on this ticket?

**Comment by conorsch** [comment]
^ as above, @erwanor. Unlikely to make testnet 43, but we'll see how much work is still outstanding.

**Comment by erwanor** [comment]
I'm going to move composition onto `BareTradingFunction` and push the coefficient scaling code. Last, I will write some tests.
