### ISSUE TITLE
Implement `Path` type for routing

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1777]
* Maintains a list of asset IDs and an end-to-end trading function
* For `Path` of length 1, list of asset IDs: `[asset1, asset2]` and trading function is the original trading function
* We’ll want a `Path.extend(&self, trading_function: TradingFunction) -> Path` method that puts the next asset ID into the list and composes the trading functions together
* Stub struct
```rust
struct Path {
    asset_ids: Vec<asset::Id>,
    trading_function: TradingFunction,
}

impl Path {
    pub fn start(&self) -> asset::Id {
        // return first element
    }
    
    pub fn end(&self) -> asset::Id {
        // return last element
    }
}

impl PartialOrd for Path {
    // comparison should return `None` if start and end asset IDs don't match
    // otherwise compare by price
}
```

**Comment by conorsch** [comment]
Closed via https://github.com/penumbra-zone/penumbra/pull/1854 !
