### ISSUE TITLE
crypto: add asset `Denom` type

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#179]
One odd part of the crypto crate's asset module is that we have an `impl From<&[u8]> for Id` intended for hashing denomination strings (e.g. `b'pen'`) to their asset IDs, and also an `impl TryFrom<Vec<u8>> for Id` for creating an asset ID from the inner Fq's bytes. 

The suggestion [here](https://github.com/penumbra-zone/penumbra/pull/176/files/aadf860318c9129f74719c0231f35922811729ce#r754720628) to resolve this is to add a `Denom` type in the asset module. This would mean that `impl From<&[u8]> for Id` would become `impl From<Denom> for Id`.

**Comment by kwf** [comment]
While doing this, it would be good to change the error message for `impl TryFrom<Vec<u8>> for Denom`, which the current code doesn't quite represent accurately in text: the message "vec not long enough to construct Asset ID" would be thrown when the vec in question is _too long_ also, not just too short.
