### ISSUE TITLE
Eliminate `NoWithVeto` and replace with a percentage cutoff for deposit burning

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1794]
Instead of `NoWithVeto` there should be another governance chain parameter that controls the threshold ratio of no votes to total votes below which a proposal should be considered vetoed (and its accompanying deposit burned).

**Comment by conorsch** [comment]
Encountered some complexity; this issue will be closed by #1881, which won't ship in 44. Moving to 45.
