### ISSUE TITLE
Add semantic version of domain types / protos

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1811]

**Comment by hdevalence** [comment]
We already do this in the protos, by means of the "v1alpha1" tag. For the domain types, we'll always be able to do this in the future, by moving Rust structures around (similar to the way tendermint-rs will have support for 0.34 and 0.37 side by side in submodules).

So I think we can actually close this out as completed, at least to the extent we'll need to go to mainnet.
