### ISSUE TITLE
upgrades: create a template guide 

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1812]
We should create a template that specifies the different steps that one has to take in order to upgrade their full node. This document should recommend best practices such as creating multiple backups, checking the hash of migrated state, handling common setups (e.g. systemd etc.)

**Comment by erwanor** [comment]
This is not immediately actionable since we have yet to begin work on #1804, but this could be a good first issue once the `on-hold` tag is removed, maybe worth bookmarking if that's interesting for you!

**Comment by erwanor** [comment]
@conorsch has been leading/driving the work on this front with the [wiki](https://github.com/penumbra-zone/penumbra/wiki/Performing-upgrades) entry

**Comment by conorsch** [comment]
Was tracking this work as part of #3841, see details there. This will be resolved as soon as #4097 lands.

**Comment by conorsch** [comment]
This is done, BUT we have changes to make as a result of feedback. Will close when those additions lands.

**Comment by conorsch** [comment]
> This is done, BUT we have changes to make as a result of feedback. Will close when those additions lands.

Picking this up, will have a revised version of the docs up by tomorrow.
