### ISSUE TITLE
Ensure that we correctly update the token supply when tokens are converted from one type to another

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1823]
Following work in #1819 , there is work to be done around token supply tracking utilizing `Amounts`.

@hdevalence:
> We should check that whenever we convert tokens from one type to another, we correctly update the supply. This will be tricky for cases like swaps, unbonding, etc., where the chain might not be able to perfectly track that information, and we need to do some design thinking about what the implications of that are.

To-do:

- [ ] Find everywhere that we create or destroy tokens as a starting point for thinking through related issues.

**Comment by zbuc** [comment]
There should be a ledger invariant where transactions don't create/destroy value except under certain conditions. We don't have a statement about what those conditions are, so it's hard to formalize this.

**Comment by hdevalence** [comment]
Closing as not planned; we realised that the shielded pool component's supply tracking was being used in multiple places with contradictory interpretations. To fix this, we removed it entirely, and each place that needs supply tracking is responsible for doing that itself (ics20, staking).
