### ISSUE TITLE
Move `pd testnet` code out of `main.rs` and clean it up

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1826]
**Is your feature request related to a problem? Please describe.**

The current `pd testnet` code is large and unwieldy, and it's difficult to maintain because it's all in the body of `pd`'s `main.rs`. See comments in #1821, for instance.

**Describe the solution you'd like**

Extract the code out of `main.rs` and do minimal cleanup (breaking stuff into functions, for instance)

**Comment by conorsch** [comment]
Closed via https://github.com/penumbra-zone/penumbra/pull/1897
