### ISSUE TITLE
Unauthenticated Buf queries in GH Actions cause failures

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1828]
**Describe the bug**

See logs in https://github.com/penumbra-zone/penumbra/actions/runs/3878969437/jobs/6615673549

Sounds like we should be authenticating to the endpoint to avoid rate limiting.

**Comment by conorsch** [comment]
https://github.com/penumbra-zone/penumbra/commit/80bb552fbdff93990ab831bc0d389b591218a634 resolved on main, but as that commit msg indicates, we still see the same problem on PRs; e.g. https://github.com/penumbra-zone/penumbra/actions/runs/3943526057/jobs/6748446868 from https://github.com/penumbra-zone/penumbra/pull/1845 . Fixing.

**Comment by hdevalence** [comment]
Seeing this again, on, e.g., https://github.com/penumbra-zone/penumbra/actions/runs/4034376532/jobs/6935541824
