### ISSUE TITLE
k8s: default validator config should use PL definition

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1832]
The new k8s deployments use ad-hoc validator identities for the deployment. We've long had a blessed validator config that we reuse on every testnet; let's use that for k8s, too. It's not strictly necessary, but for continuity's sake and legibility on other projects like the block explorer, it will be good to see the familiar human-readable fields for the genesis validator.

In terms of implementation, we'll need to lower the number of validators in the k8s deployment from 2 -> 1, but that's worthwhile. We can customize the validator generation logic to contain metadata later if when we want to grow the deployment.

**Comment by hdevalence** [comment]
Why do we need to lower the number of validators? It seems more desirable to have a multi-validator setup than to have perfect metadata, if we had to pick, but I'm not sure what the conflict is.

**Comment by conorsch** [comment]
Discussed at sprint planning today: we definitely _don't_ want to lower the validators back to 1, but it'd be nice to have human-readable strings for the PL validators in the output of `pcli q validator list` again. Will need to unpick the `testnet generate` logic and how the `deployments/ci.sh` script munges that output.

**Comment by conorsch** [comment]
New logic is live on preview:

```
 Voting Power  Share   Commission  State   Bonding State  Validator Info                                                                    
 25000.000     50.00%  300bps      Active  Bonded         penumbravalid12rxgvvu88fwh0x25qeptka8tt7g460dp3g4uz99gscvysrj7p5gq68de7l 
                                                            Penumbra Labs CI 2                                                     
 25000.000     50.00%  300bps      Active  Bonded         penumbravalid14eq4ua3luketug3f5ddz77dxkyppmgn70wsypy422ddpwy3cnqfq3zvz42 
                                                            Penumbra Labs CI 1                                                     


```

so closing.
