### ISSUE TITLE
Add testnet join flag for setting external_address

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1848]
**Is your feature request related to a problem? Please describe.**
Right now, public testnet participants peer directly with the PL-run infra when running `testnet join`. By default, the nodes run by testnet partipicants won't peer with each other, because our tendermint config template sets `external_address` to any-address:

https://github.com/penumbra-zone/penumbra/blob/40f9de041c2c5cddaedebc05cd3696271f9c8cc7/testnets/tm_config_template.toml#L207-L215

Our `pd testnet join` logic carefully excises special addresses like "0.0.0.0" (#1821), so only the PL-run instances will have their addresses set in a new node's `p2p.seeds` section of the tm config.

**Describe the solution you'd like**
Allow public testnet participants to opt-in to setting an `external_address` when joining, e.g.:

```
pd testnet join --external-address 1.2.3.4
```

Doing so will enable folks to declare their nodes as external accessible, and cause their external addresses to land in tm configs of subsequently joining nodes.

**Describe alternatives you've considered**
We've considered leveraging the `remote_ip` attribute, but decided against it (#1815). It makes more sense to permit testnet participants to opt in to serving as an externally accessible peer.

**Additional context**
While it's not a hard requirement, let's perform some housekeeping on the testnet code before tackling this change: #1826, #1827. Also, make sure to update the documentation with an explanation of how the `--external-address` flag functions.

**Comment by hdevalence** [comment]
I think we can do this now that #1827 is closed.

**Comment by conorsch** [comment]
Testing in combination with the seed_mode=true setting described in #1847 works just peachy: 

![npeers-with-seed-and-external-addr](https://user-images.githubusercontent.com/657862/213804276-a0a2b651-5757-473b-946b-1ab77224e07d.png)

Look at all those peers!
