### ISSUE TITLE
Unify buf and prost protobuf build systems

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#1867]
Currently, we have two independent systems for building the penumbra protobufs:

- [buf](buf.build/)- Buf provides a standalone protobuf build system and registry, and can autogenerate code (such as for the relayer).
- prost- Rust protobuf implementation, which is what links all of our protobufs to our crates internally and generates the rust code we use internally.

Until #1860, these two systems functioned identically. However, we now want `buf` to include upstream libraries instead of vendoring them, to avoid causing namespace conflicts in our consumers (such as the relayer). #1860 accomplishes that. However, now the `prost` side of the build system is building from different dependencies than the `buf` side. This happens to be okay now, but in the future this will likely cause issues.

To fix this, we should:

- [ ] Change our prost build tooling to look in the `buf` module cache for dependencies (see https://docs.buf.build/bsr/overview#module-cache)

**Comment by conorsch** [comment]
@avahowell Optimistically adding this to testnet 43, given the priority of the relayer work you've been doing. If you disagree, please update the milestone!

**Comment by conorsch** [comment]
Work is ongoing, untangling the protobuf build story. @avahowell reports she's going strong on this front, but it'll slip to next testnet; unlikely to be merged by EOW.

**Comment by conorsch** [comment]
For sanity's sake, let's deprioritize this ticket, and get @avahowell back into Rustlang for a bit. =)

**Comment by conorsch** [comment]
Cross-linking related work for visibility:

* https://github.com/penumbra-zone/penumbra/pull/2020
* https://github.com/penumbra-zone/penumbra/pull/2035

**Comment by hdevalence** [comment]
Closing in favor of #2184
