### ISSUE TITLE
Change memo plaintexts to include a structured sender address.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1880]
**Is your feature request related to a problem? Please describe.**

For payment transactions, it's important that the receiver of a payment can view information about who sent them funds. To address this use case, we have a memo field, similar to Zcash.  Our memo field is 512 bytes of UTF-8 text.  While this is enough space to encode a good amount of information about the sender and the purpose of the payment, that information is unstructured.

Having unstructured data at the protocol level is good, because it leaves flexibility for evolving use-cases in the future. But it also imposes costs, because clients have to agree on how to encode data in the memo.  Currently, the entirety of the memo field is unstructured, but we could do better by defining a sender address field.  This would give client software a standard way to display the sender of a payment.

**Describe the solution you'd like**

Instead of 512 bytes of freeform UTF-8 text, memo plaintexts should be encoded as `80-byte address || 432-byte text`, i.e., exactly the same encoding as now, but with a fixed 80-byte prefix.

This should be represented in the client code by a `Memo` domain/proto type defined as
```rust
struct Memo {
    pub sender: Address,
    pub text: String,
}
```
This change should propagate through the `TransactionView` code.  Along the way, we should tweak the memo handling in the `TransactionView` so that the memo ciphertext is included even when the memo plaintext is not visible, in support of #1788.

When constructing a transaction, the `Planner` should fill in the `sender` field with the default address if it is unset. In `pcli`, we should set the address based on the source-index parameter if it is set.

**Comment by plaidfinch** [comment]
How should we handle decoding if we receive a memo with an invalid `Address`? I think instead we might consider:

```rust
enum Memo {
    WithSender {
        sender: Address,
        text: String,
    },
    Unstructured {
        text: String,
    }
}
```

This allows you to send a payment without a sender address, and for the receiver to receive it on the other end without an error: if the first 80 bytes are not a valid `Address`, then the entire memo is interpreted as an unstructured UTF-8 `String`.

Should we leave future room in this design for more extensibility of these two variants?

**Comment by plaidfinch** [comment]
> they could create an ephemeral address and use that in the memo field.

Ah, of course, didn't think of that option!
