### ISSUE TITLE
TransactionBuild RPC

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1883]
Following #1782, we need another RPC on the view service to receive a TransactionPlan and build the Transaction

**Comment by hdevalence** [comment]
To build a transaction, we need a `TransactionPlan`, a `WitnessData`, and an `AuthorizationData`.  The `AuthorizationData` comes from the custody service, and the `WitnessData` comes from the view service.  We already have a `WitnessRequest` on the view service that takes a `TransactionPlan` and returns the witness data, so I think it would make sense to structure this as a
```proto3
service ViewProtocolService {
  // ...
  rpc WitnessAndBuild(WitnessAndBuildRequest) returns (WitnessAndBuildResponse);
  // ...
}

message WitnessAndBuildRequest {
  penumbra.core.transaction.v1alpha1.TransactionPlan transaction_plan = 1;
  penumbra.core.transaction.v1alpha1.AuthorizationData authorization_data = 2;
}

message WitnessAndBuildResponse {
  penumbra.core.transaction.v1alpha1.Transaction transaction = 1;
}
```

Internally, the implementation of `WitnessAndBuild` should call the internal method used to implement `witness` to get the witness data, and then build the transaction to construct the response.  This is an opportunity to clean up some mess we have left over -- currently, we don't cleanly isolate handling of the witness request into the view service, and instead spread the logic over the convenience rust wrapper trait for the view client and the view service implementation.  To fix *that* problem, we should remove the `note_commitments` field from the `WitnessRequest` and ensure that the view service is processing the supplied `TransactionPlan` to determine what notes need to be witnessed.
