### ISSUE TITLE
Add support for HTTPS calls via pcli

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1887]
The `pcli` binary should be able to talk to HTTPS endpoints. Right now, it assumes all connections are HTTP, but we should update the option handling to infer the proper scheme based on a [`url::Url`](https://docs.rs/url/latest/url/struct.Url.html) or similar and make the relevant requests. 

We already have a long-running HTTPS endpoints for the testnet deployments: `https://{,g}rpc.testnet{,-preview}.penumbra.zone ` Traffic on 443/TCP to those FQDNs will talk to pd or tm as necessary. Let's use those to build the new option handling, and default client requests to an HTTPS endpoint in future releases.

**Comment by conorsch** [comment]
Took a first look at this, documenting some progress below. The test command is `pcli view sync`.

### Naive approach
After updating the relevant args to default to an HTTPS URL for `https://grpc.testnet.penumbra.zone`:
```
Error: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

Caused by:
    0: transport error
    1: http2 error: connection error detected: frame with invalid size
    2: connection error detected: frame with invalid size

```
The error messages are less descriptive than I'd like, but they make sense: we haven't even clicked on TLS support in tonic yet.

### Features: tls
Updating URLs to be HTTPS, and enabling the ["tls" feature for tonic](https://docs.rs/tonic/latest/tonic/#feature-flags):


```
Error: transport error

Caused by:
    0: error trying to connect: Connecting to HTTPS without TLS enabled
    1: Connecting to HTTPS without TLS enabled
```

Progress. Docs indicate that we may need to pass in a [ClientTlsConfig](https://docs.rs/tonic/latest/tonic/transport/struct.ClientTlsConfig.html) struct; or, we can try more features

### Features: tls & tls-roots
Also enabling feature `tls-roots` for tonic:

```
Error: status: Internal, message: "grpc-status header missing, mapped from HTTP status code 400", details: [], metadata: MetadataMap { headers: {"content-length": "0", "date": "Tue, 31 Jan 2023 23:14:33 GMT", "via": "1.1 google", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"} }
```

OK, that's much better: we're now establishing a valid connection over HTTPS and receiving a response. The headers match what we'd see via curl, leaving grpc aside:

```
curl -I https://grpc.testnet.penumbra.zone
HTTP/2 200 
grpc-status: 12
content-type: application/grpc
content-length: 0
date: Tue, 31 Jan 2023 23:33:42 GMT
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

Notably the `grpc-status` header is present in that response, matching what we explicitly set in a few places in the protos. The route, however, doesn't match the request that pcli makes. 

### Next steps
I'll do some interactive testing of the specific proto endpoints that pcli uses, via [grpcurl](https://github.com/fullstorydev/grpcurl). I suspect we'll need to add some headers to our proto schemes to get things working well. We may also need to tweak the ingress proxy settings; testing with a node behind e.g. Caddy (#1766) might be useful to check whether headers are being dropped.

**Comment by hdevalence** [comment]
The code in https://github.com/penumbra-zone/penumbra/tree/pcli-tls-grpc might also be helpful as a reference; I didn't get it working at the time because there wasn't an endpoint for it to talk to, so no guarantees that it works.

**Comment by conorsch** [comment]
OK, got it sorted. Testing with grpcurl against preview didn't work:

```
grpcurl -import-path proto/proto/ -import-path proto/ibc-go-vendor/ -proto proto/proto/penumbra/client/v1alpha1/client.proto  grpc.testnet-preview.penumbra.zone:443 penumbra.client.v1alpha1.ObliviousQueryService/ChainParameters
ERROR:
  Code: Internal
  Message: unexpected HTTP status code received from server: 400 (Bad Request); malformed header: missing HTTP content-type
```

However, if we modify a single line in the `pd` code, disabling the http1 support, then we can use `grpcurl` just fine against that pd instance over HTTPS:

```
grpcurl -import-path proto/proto/ -import-path proto/ibc-go-vendor/ -proto proto/proto/penumbra/client/v1alpha1/client.proto  pd-tls.penumbra.zone:443 penumbra.client.v1alpha1.ObliviousQueryService/ChainParameters
{
  "chainParameters": {
    "chainId": "penumbra-testnet-leda-26a8ec7f",
    "epochDuration": "719",
    "unbondingEpochs": "2",
    "activeValidatorLimit": "80",
    "slashingPenaltyMisbehavior": {
      "inner": "10000000"
    },
    "ibcEnabled": true,
    "baseRewardRate": "30000",
    "slashingPenaltyDowntime": {
      "inner": "10000"
    },
    "signedBlocksWindowLen": "10000",
    "missedBlocksMaximum": "9500",
    "proposalVotingBlocks": "720",
    "proposalDepositAmount": {
      "lo": "10000000"
    },
    "proposalValidQuorum": {
      "numerator": "2",
      "denominator": "5"
    },
    "proposalPassThreshold": {
      "numerator": "1",
      "denominator": "2"
    },
    "proposalVetoThreshold": {
      "numerator": "1",
      "denominator": "3"
    }
  }
}
```

This makes sense, as the tonic docs state [about accept_http1](https://docs.rs/tonic/0.5.0/tonic/transport/server/struct.Server.html#method.accept_http1):

> Accepting http1 requests is only useful when developing grpc-web enabled services. If this setting is set to true but services are not correctly configured to handle grpc-web requests, your server may return confusing (but correct) protocol errors.

Is there still a reason we want that setting on? It's not clear to me what benefit we get from it. I made sure to test Buf Studio against the patched pd instance, as done in #1766, and it worked just fine. Sticking with HTTP/2, now that we have HTTPS, seems best, given that's what gRPC expects. We've also set accept_http1 for pviewd in #1872, but I'm not going to change that now, since we're tracking transport hardening for pviewd in #1556. I suspect that simply enabling tonic-web, but not accept_http1, would be sufficient for our needs, but haven't tested. 

I'll open a PR implementing the approach described above.

**Comment by hdevalence** [comment]
> If this setting is set to true but services are not correctly configured to handle grpc-web requests, your server may return confusing (but correct) protocol errors.

Do we have an understanding of what "correctly configured to handle grpc-web requests" means, and what we're missing that causes the errors to occur?

Intuitively, it doesn't seem right (to me) that HTTP/1 support should make TLS-based HTTP/2 requests break.

**Comment by erwanor** [comment]
Done!

**Comment by conorsch** [comment]
> Do we have an understanding of what "correctly configured to handle grpc-web requests" means, and what we're missing that causes the errors to occur?

No, I don't have a clear picture of this definition. Thanks for starting some upstream discussion (https://discord.com/channels/500028886025895936/628706823104626710/1070712461180805180). The suggestion in that thread was:

> Would be using the cors middleware from tower-http + tonic-web's middleware https://docs.rs/tonic-web/latest/tonic_web/

There's a lot more work toward HTTPS covered in #1886, so I'll keep pressing forward, and make sure to document any breakage discovered.

**Comment by conorsch** [comment]
Post merge of #1926, `pcli` can't sync against preview:

```
pcli -n https://grpc.testnet-preview.penumbra.zone view sync
Error: status: Internal, message: "protocol error: received message with invalid compression flag: 10 (valid flags are 0 and 1) while receiving response with status: 502 Bad Gateway", details: [], metadata: MetadataMap { headers: {"content-type": "text/html; charset=UTF-8", "referrer-policy": "no-referrer", "content-length": "332", "date": "Fri, 03 Feb 2023 20:34:59 GMT", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"} }
```

We're using a different proxy setup on the testnet deployment from what I tested against above. Reopening. Will work on updating the proxy config to match, otherwise back out the breaking change for 43.

**Comment by hdevalence** [comment]
I'd lean towards backing it out pre-emptively, since we know that there are issues we don't yet understand.

**Comment by conorsch** [comment]
Reverted, and therefore removed from the upcoming testnet 43 release. Will prototype on a separate cluster deployment and work on updating the proxy headers. As we saw in #1766, Caddy makes it quite simple to configure h2c (HTTP2 over cleartext); for GKE ingress, we'll need to set http2 in the ingress annotations, and may need to configure another set of TLS certs, which would require #1405. I hope to avoid an intermediary set of TLS certs, deferring handling that logic to `pd` as a built-in.

**Comment by hdevalence** [comment]
Blocked on #2196

**Comment by hdevalence** [comment]
#2326 experimentally disables http/1.  If our web clients don't break (because they support HTTP/2) we could move forward that way, at least for now.

> Intuitively, it doesn't seem right (to me) that HTTP/1 support should make TLS-based HTTP/2 requests break.

I asked @hawkw about how HTTP/2 negotiation works, and she pointed to https://www.rfc-editor.org/rfc/rfc7540#section-3.3 and mentioned that there's a way it can be negotiated as part of the TLS handshake, skipping an initial HTTP/1 request, and speculated that this means that `accept_http1` probably influences the TLS protocol negotiation in some way.
