### ISSUE TITLE
Fill in `Position`-related `ActionHandler` implementations

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1905]
Related to the `ActionHandler` for `component::dex`.

This ticket tracks the consensus-side execution of the action handlers for position actions.  The implementation of the DEX engine itself is tracked in #1724. Client-side logic like `Planner` support is tracked in #1991.

- [x] #2137
- [x] #2138
- [x] #2139
- [ ] #2140 (Blocked on #2167)

**Comment by conorsch** [comment]
@zbuc Is this ticket still useful? Can you expand in the OP what the goal here is?

**Comment by hdevalence** [comment]
Folding into #1724
