### ISSUE TITLE
Derive trading function approximation

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1908]
## Trading function approximation

Our goal is to approximate any trading function with a consistent[^1] payoff function using constant-price pools (i.e. $\phi(R) = p\cdot R_1 + q\cdot R_2$).

The RMM[^2] paper  provides a method to construct CFMMs that match a given consistent payoff function. We can use it here to find a match trading function $\phi_j$ for the portfolio value function $V_j(p,q)$.

The strategy to get there is to find the discrete approximation of the given payoff using portfolio value functions for each segment of the approximation, and then find their corresponding trading function.

$V_j(p,q) = \inf_{\substack{R_1, R_2 \geq0 \\ \phi_j(R) = k_j}} p\cdot R_1 + q \cdot R_2$

in closed form, we have $V_j(p,q) = k_j \cdot \min (\frac {q} {q_j}, \frac {p} {p_j}))$ which is approximate $V$ between $\alpha_j$ and $\alpha_{j+1}$ such that $V(\alpha_j) = $

and $\bar V(p,q) = \sum_j V_j(p,q)$

$\phi_j(R) = p_j \cdot R_1 + q_j \cdot R_2 = k_j$

##### Approximating the constant-product CFMM

- [x] #2318
   - [x] Parametrize the approximation of the portfolio value ($\alpha_i$s)
   - [x] Find the $k_i$ invariant for each constant-price pool
- [x] #2477
- [x] #2319

##### API

```rust
/// Approximate the payoff of an `x*y=k` market-maker using `position::Position`s 
fn approximate_xyk(invariant_k: Amount, current_price: U128xU128, precision: u32) -> Vec<Position>;
```

[^1]: A payoff is _consistent_ if it is 1-homogeneous, non-negative, and non-decreasing in its arguments.

[^2]: Replicated market makers

**Comment by conorsch** [comment]
Hasn't been worked on this sprint; moving to Future. We'll reclass this subticket as part of work planning for #1725.

**Comment by erwanor** [comment]
This is currently being worked on. I updated the issue with details about the next steps.
