### ISSUE TITLE
Refactor `CheckTx` and `DeliverTx` response code handling

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#191]
Currently, the `CheckTx` and `DeliverTx` implementations have a lot of code that builds responses inline on every failure case, like so:
```rust
            let pending_transaction = match transaction.verify_stateless() {
                Ok(pending_transaction) => pending_transaction,
                Err(_) => {
                    let _ = finished_signal.send(());
                    return Ok(Response::DeliverTx(response::DeliverTx {
                        code: 1,
                        ..Default::default()
                    }));
                }
            };
```
Instead, it would be cleaner for the `check_tx` and `deliver_tx` methods to return `Result`s (so that the results can be bubbled up with `?`), and for those to be wrapped (in the body of `call`, where they're invoked) with a single stub that matches on the `Result` and constructs the response code.

Also, it would be helpful to include the error code on failure in the `log` field of the response message with `log: err.to_string()` or similar, so that when a transaction fails the reason is given.

**Comment by redshiftzero** [comment]
This was done in #222
