### ISSUE TITLE
Replace transaction expiry height with a time-based mechanism

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1915]
**Is your feature request related to a problem? Please describe.**

The current `TransactionBody` has an `expiry_height` field, which I originally added because it was present in Zcash (which, in turn, inherited it from Bitcoin).  In that context, using a height makes sense because it's the only notion of temporality in the system. With Tendermint, however, validators come to consensus on a latest time (and we use that notion of time elsewhere, e.g., in IBC).  From an end-user perspective, specifying transaction validity periods in terms of time is much more useful than specifying them in terms of block heights. In addition, we'd like to have the chain logic be relatively independent of the block height -- if the chain produces blocks faster than normal, the rest of the logic should be as unaffected as possible.

**Describe the solution you'd like**

- [ ] Remove the current `expiry_height` field from the transaction body;
- [ ] Add new fields, `valid_before` and `valid_after`. These messages should have the following semantics, where `latest_time()` is the most recent block header timestamp:
  - If `valid_before` is set, the transaction is valid iff `latest_time() < valid_before`;
  - If `valid_after` is set, the transaction is valid iff `latest_time() > valid_after`;
 - [ ] Add state machine unit tests that
   1. Initialize a genesis state
   2. Set a test timestamp (see the IBC state machine test for an example of how to do this)
   3. Create transactions with all four combinations of `valid_before` and `valid_after` present and not present, and check that validation rules behave as expected.

**Comment by mikayla-maki** [comment]
Note on Checkbox 3.ii: This seems to refer to the test in `component/src/app/ibc/component/client.rs` file

**Comment by hdevalence** [comment]
> This seems like it removes the ability for someone to specify "I want this transaction to execute if and only if it is included in this specific block". That seems useful. Is it less useful than I think it is?

To the extent that the desired behavior can't be specified by an equivalent time interval, I don't think we should support it. Ideally, I think we want the block interval to be an implementation detail, and keep the primary mechanism time-based.

I think there are two use cases:

- I want to bound when the transaction can execute — in which case, a time bound is better than a block height bound, because it names the actually desired range
- I want to bound when this transaction can execute relative to something else — in which case I think the solution is to combine transactions coinjoin-style (eg I want my swap to execute in the same block as yours, so we'll aggregate them into one transaction).

So I think we should get rid of height-based mechanics entirely, so that we're prepared for a setting where block intervals float and vary over time.

**Comment by conorsch** [comment]
Blocked on https://github.com/penumbra-zone/penumbra/issues/2070, which must land before associated PR can be updated.

**Comment by hdevalence** [comment]
We stabilized the protos already.
