### ISSUE TITLE
Compose files should use prebuilt containers for testnet

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1927]
We have several docker-compose files in the repository, all of which require building `pd` code from source into to run them. Now that we have container images built fresh per testnet tag, that's not strictly necessary: after updating the git repo, folks can pull the latest images and get up and running quickly. 

We should be mindful of pre-existing state: typically we recommend running `pd testnet unsafe-reset-all`, which requires a version of pd locally. A custom entrypoint script should bootstrap a join to the testnet if-and-only-if no previous testnet exists. 

In the process, we can reorganize the specs as described in #621. A quick straw poll of the dev team didn't show that the compose files were regularly used, although the smoketest CI job uses it. As long as we preserve that functionality, we can simplify the setup considerably: consolidating `Dockerfile.{dev,old}`, for instance, and moving the override compose specs to a subdir.

**Comment by hdevalence** [comment]
The smoke test no longer uses Docker at all, so I think we could drop everything not needed for the release containers we build and publish.

**Comment by conorsch** [comment]
Someone dropped by the Discord today to report that our still-documented compose workflow wasn't working for them. I'll take a stab at this and try to clean it up for 52.
