### ISSUE TITLE
Creating a component that tracks all distributions

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1934]
Related to #2070

**Comment by hdevalence** [comment]
I have some rough notes on this, let's wait to start working on it until we close out some of our other WIP projects (like delegator voting).

**Comment by erwanor** [comment]
Currently paused to focus on making the relayer work, and push for the IBC migration #2379

**Comment by hdevalence** [comment]
We have a `distributions` component now, but it doesn't do much AFAICT. How would we know what the status of this issue is and whether it's done? Could we edit the description to have some concrete goals?

**Comment by hdevalence** [comment]
Closing as superceded by #3452
