### ISSUE TITLE
Clean up validator update building

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1935]
The [`build_tendermint_validator_updates` method](https://github.com/penumbra-zone/penumbra/blob/main/component/src/stake/component.rs#L538) currently is inefficient and runs during every block. Specifically, parsing _all_ validator data (including funding streams) that is unneeded for tendermint updates slows things down.

Maybe this can be optimized so that only the relevant validator data, for validators whose voting power has changed, is accessed.

**Comment by hdevalence** [comment]
Closed by #1940
