### ISSUE TITLE
Implement test vectors for the AMM compositions

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#1951]

**Comment by conorsch** [comment]
During sprint planning: @erwanor optimistic about inclusion in 44. Keeping in 44.

**Comment by erwanor** [comment]
This won't make it to 44, we're rethinking how we plan to do routing + execution, in a way that would possibly make AMM composition not needed.

**Comment by hdevalence** [comment]
This was dropped as part of route-and-execute.
