### ISSUE TITLE
Check chain id prior to pcli sync to provide more informative error messages

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1955]
Currently when a user submits a transaction or attempts to synchronize when their chain id doesn't match (such as because they have specified a prior chain id), they don't get a very helpful message.

Instead we could have `pcli` itself throw an error when chain id mismatches, which will suggest that they run pcli view reset in case they are attempting to connect to the current deployed chain, otherwise suggest that they use the --node argument to specify the chain they want to connect to.

**Comment by hdevalence** [comment]
This is a good idea. I'm surprised we don't already see an error, though -- we start `pcli` by syncing to the chain tip. Why doesn't syncing to the tip on the wrong chain cause an error? Shouldn't the `CompactBlockRangeRequest` include the chain ID, and error if incorrect?

**Comment by hdevalence** [comment]
Closing as not planned, if we do this at all it should be with a header-based approach that can be grpc middleware.
