### ISSUE TITLE
Zpoken Wallet Extension Documentation

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1975]
**Is your feature request related to a problem? Please describe.**

As of 2023-02-09, we have seen a live demonstration of transaction send via the Zpoken web wallet, but we don't have a step-by-step guide for letting testnet users do this themselves with the least amount of setup work.

**Describe the solution you'd like**

We would like a brief summary of the (current, as of the most recent testnet) steps needed to start a local node, install the web wallet extension to Chrome, and interact with the testnet to the fullest extent possible without using `pcli`.

**Additional context**

This is related to ongoing interface support work tracked in #1775 - producing these docs and ensuring that they work for new users will be critical to ensuring ease of access to the wallet user interface and that Penumbra team has provided the necessary protocol and other support. This work should follow any in-flight updates to the existing testnet join guide, such as those in #1976, so we can provide up-to-date instructions across the board.

**Comment by redshiftzero** [comment]
This is paused while we wait for the state of the extension to settle

**Comment by conorsch** [comment]
As part of #2216, I made very small changes to the readme docs in that repo: https://github.com/penumbra-zone/penumbra_dapp/commit/ee87b0fb238c180291074c2e147f0d6465fd55e5 My understanding is that to complete this ticket, we'll want to add setup steps to guide.penumbra.zone. If that's so, do we still consider this blocked? We might do well to document what we have and let folks on the next testnet take it for a spin.

**Comment by conorsch** [comment]
Discussed at sprint planning today. We plan to ask for community testing of the web extension shortly after the release of Testnet 52. Given the typical several-day delay to get new versions of the webext verified and available in the Chrome store, we expect the following:

1. Monday 2023-05-08 we release Testnet 52.
2. Zpoken updates the web extension and uploads it to Chrome store.
3. Wait a few days, during which we can write these docs.
4. Receive confirmation of new version published, double-check docs are accurate.
5. Make a second announcement, calling for community testing of the webext.

**Comment by redshiftzero** [comment]
@conorsch is going to take a first pass at writing these docs and @aubrika will review

**Comment by conorsch** [comment]
Fixed by:

* https://github.com/penumbra-zone/penumbra/pull/2651
* https://github.com/penumbra-zone/penumbra/pull/2810
* https://github.com/penumbra-zone/penumbra/pull/2811
