### ISSUE TITLE
metrics: create latency histogram of storage queries

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1996]
We recently added some metrics for the storage lookups in #1995. Now that we have histogram-aware metrics tracked, let's cobble together a dashboard in grafana so we can view that info. A succinct definition of what we want to display is "p95 of latencies over the last 10 seconds". See related [discussion in Discord](https://discord.com/channels/824484045370818580/982088858348970064/1075512600223301643).

**Comment by conorsch** [comment]
I've had some trouble getting the bucketing logic to work as expected. Here are the new metrics exposed:

<details>
<summary>
output from `curl`ing the pd metrics endpoint
</summary>

```
# HELP penumbra_storage_get_raw_duration_seconds The duration of a get_raw request
# TYPE penumbra_storage_get_raw_duration_seconds summary
penumbra_storage_get_raw_duration_seconds{quantile="0"} 0.000008289
penumbra_storage_get_raw_duration_seconds{quantile="0.5"} 0.0000339813049393384
penumbra_storage_get_raw_duration_seconds{quantile="0.9"} 0.00006164613411384577
penumbra_storage_get_raw_duration_seconds{quantile="0.95"} 0.00007681581330626366
penumbra_storage_get_raw_duration_seconds{quantile="0.99"} 0.00013314124047711232
penumbra_storage_get_raw_duration_seconds{quantile="0.999"} 0.0005380817648410731
penumbra_storage_get_raw_duration_seconds{quantile="1"} 0.005187919
penumbra_storage_get_raw_duration_seconds_sum 1.7578365779999938
penumbra_storage_get_raw_duration_seconds_count 43344
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0"} 0.0000066
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.5"} 0.000010880916933679308
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.9"} 0.0000324211347912189
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.95"} 0.00009425
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.99"} 0.00009425
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.999"} 0.00009425
penumbra_storage_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="1"} 0.00009425
penumbra_storage_get_raw_duration_seconds_sum{chain_id="\"penumbra-testnet-meti-05ce3518\""} 0.00030323
penumbra_storage_get_raw_duration_seconds_count{chain_id="\"penumbra-testnet-meti-05ce3518\""} 17
# HELP penumbra_storage_nonconsensus_get_raw_duration_seconds The duration of a nonconsensus_get_raw request
# TYPE penumbra_storage_nonconsensus_get_raw_duration_seconds summary
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="0"} 0.00000403
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="0.5"} 0.000009159673320006035
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="0.9"} 0.000012129136281051658
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="0.95"} 0.00001496045693600691
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="0.99"} 0.000033623005447962665
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="0.999"} 0.00008398267450537698
penumbra_storage_nonconsensus_get_raw_duration_seconds{quantile="1"} 0.00069944
penumbra_storage_nonconsensus_get_raw_duration_seconds_sum 0.026387014999999955
penumbra_storage_nonconsensus_get_raw_duration_seconds_count 2574
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0"} 0.00000549
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.5"} 0.000005490451609876202
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.9"} 0.0000106996444807023
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.95"} 0.0000106996444807023
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.99"} 0.0000106996444807023
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="0.999"} 0.0000106996444807023
penumbra_storage_nonconsensus_get_raw_duration_seconds{chain_id="\"penumbra-testnet-meti-05ce3518\"",quantile="1"} 0.0000107
penumbra_storage_nonconsensus_get_raw_duration_seconds_sum{chain_id="\"penumbra-testnet-meti-05ce3518\""} 0.00001619
penumbra_storage_nonconsensus_get_raw_duration_seconds_count{chain_id="\"penumbra-testnet-meti-05ce3518\""} 2
```
</details>

Based on that I'd expect a query like this to work: `histogram_quantile(0.90, sum(rate(penumbra_storage_get_raw_duration_seconds[10s])))`. However, running that shows "no data." The docs on the `histogram_quantile` function state:

> Calculates the φ-quantile (0 ≤ φ ≤ 1) from the buckets `b` of a histogram. The samples in `b` are the counts of observations in each bucket. Each sample must have a label `le` where the label value denotes the inclusive upper bound of the bucket. (Samples without such a label are silently ignored.) The histogram metric type automatically provides time series with the `_bucket` suffix and the appropriate labels.

Notably we don't have any `le` labels. I suspect we'll need to use [metrics_exporter_prometheus::PrometheusBuilder::set_buckets](https://docs.rs/metrics-exporter-prometheus/0.10.0/metrics_exporter_prometheus/struct.PrometheusBuilder.html#method.set_buckets); from the docs:

> If buckets are set, then any histograms that match will be rendered as true Prometheus histograms, instead of summaries.

Which appears to match the behavior I'm seeing.

**Comment by conorsch** [comment]
This doc proved helpful: [Histograms and summaries](https://prometheus.io/docs/practices/histograms/). Based on that, we can cobble together a rolling 5m average of storage request latency:

![storage-lookup-progress](https://user-images.githubusercontent.com/657862/220766202-1f04e0b9-5e69-4375-9820-aa03190dd159.png)

There's no filtering based on quantile, but it's still informative. Will spend some more time aiming for better bucketing logic, so we can filter by quantile.

**Comment by conorsch** [comment]
Storage lookup charts have been [deployed to preview](https://grafana.testnet-preview.penumbra.zone/d/YT0tG3X7z/penumbra?orgId=1):

![grafan-storage-first-pass](https://user-images.githubusercontent.com/657862/221014203-e72a920a-2f28-487a-b78b-2942837fcd11.png)

In order to filter by quantile, we'll need to update the instrumentation to set buckets explicitly. That's not a hard blocker, but I'm inclined to ship the above for the next testnet, and follow up on custom buckets once we see the spread of data on the next public testnet. For now, I'm going to prioritize #1997, trying to get those changes in near-term.

**Comment by hdevalence** [comment]
This looks great! I think this is enough to get a basic ballpark of how fast storage accesses are.

**Comment by conorsch** [comment]
Closing. When revisiting this, we should re-instrument the code to use explicit buckets, as described in https://github.com/penumbra-zone/penumbra/issues/1996#issuecomment-1432280626
