### ISSUE TITLE
metrics: expose rocksdb storage info

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1997]
Since #1995, we have a start on metrics for storage lookup latency. Let's also aim to track storage info over time, such as:

* memory footprint of rocksdb (https://docs.rs/rocksdb/latest/rocksdb/perf/fn.get_memory_usage_stats.html)
* total on-disk storage size (likely via an OS call to sum up the dir contents;; cf. https://docs.rs/fs_extra/1.3.0/fs_extra/dir/fn.get_size.html)

Once we resolve #1996, we can then evaluate the correlation between increasing storage size and lookup latency.

**Comment by hdevalence** [comment]
I think that we could not plan to do this, and just revisit it if/when it comes up again in the future.
