### ISSUE TITLE
Change `SwapBody` to use a `BalanceCommitment` proto message

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2001]
**Is your feature request related to a problem? Please describe.**

The `SwapBody` has a `bytes fee_commitment`: https://buf.build/penumbra-zone/penumbra/docs/3f1a941c1acd4abdbe10a580f8b0f3c7:penumbra.core.dex.v1alpha1#penumbra.core.dex.v1alpha1.SwapBody

This is a legacy holdover and represents the byte-encoding of a `BalanceCommitment`. But we have a proto type for that, so we should use the `BalanceCommitment` type instead of raw bytes.

**Comment by mikayla-maki** [comment]
This seems to have been resolved.
