### ISSUE TITLE
make it easier to detect divergence between `TransactionPlan::build` and `TransactionPlan::build_concurrent`

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2024]
**Is your feature request related to a problem? Please describe.**
Right now we have both `TransactionPlan::build` (for wasm) and `TransactionPlan::build_concurrent` (async for pcli). They have very similar functionality and it is easy during development to accidentally update one without updating the other. Right now this can be caught by the `plan_effect_hash_matches_transaction_effect_hash` test which checks that the effect hash from both `TransactionPlan::build` and `TransactionPlan::build_concurrent` is the same. However, that test only includes the spend, output, swap, memo and clue plans. 

**Describe the solution you'd like**
Some ideas to resolve:
1. Ensure the `plan_effect_hash_matches_transaction_effect_hash` test to cover all actions, this way the divergence will always be quickly caught. 
2. Factor out the common functionality of `TransactionPlan::build` and `TransactionPlan::build_concurrent`  into helper functions. This could get a bit messy. 
3. Something else?

**Comment by hdevalence** [comment]
An alternate strategy could be to reduce the complexity of the build methods. Currently they're responsible for carefully aligning the order of the actions, but instead, we could define an ordering on transaction actions and then sort them.

**Comment by hdevalence** [comment]
Less relevant after build refactoring.
