### ISSUE TITLE
Universalize `pcli` output format selection

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2065]
It's sensible for many commands in `pcli` to have multiple output formats. Instead of specifying this ad-hoc, we should have a single, global option to select the format, and a system to ensure that each command supports every format, to provide a consistent set of user expectations.

Formats should include, at least:
- JSON
- TOML
- base64 encoded proto
- hex encoded proto
- base64 of raw binary data*
- hex of raw binary data*
- bech32 of raw binary data**

*When applicable: these are only reasonable for single-element things like keys, addresses, amounts, etc.
**When there is a canonical bech32 prefix for the given data type only.

Additionally, it would be worth revisiting how `pcli` handles stdin/stdout, to allow any command that needs input from a file to instead read from stdin if file not specified. We might also consider getting rid of the flags to write to a particular file, because this can be accomplished by shell redirection, unless multiple files need be specified?

**Comment by hdevalence** [comment]
We can avoid doing this for now, and possibly ever -- we want to avoid making contracts about output formats for `pcli`, and encourage machine readers to use RPC calls instead.
