### ISSUE TITLE
Enforce length limit on validator info fields

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2066]
User `@what's_next?#1511` discovered that there is no length limit imposed on validator names, and uploaded the following validator definition to testnet 047-lysithea:

https://gist.github.com/plaidfinch/67b043b9569dbefcdc4db26adb80f070

As you can see, both the `name` and `website` fields contain a 29kB base64-encoded GIF, specifically this one:

![barcode](https://user-images.githubusercontent.com/597089/221955952-73811e19-276e-4b17-81d1-f095a8db6a6e.gif)

We should enforce a reasonable maximum length limit for all fields in validator definitions, in consensus. We should also take this opportunity to check that any other freeform `String` fields that are user-controlled also have length maximums imposed.

**Comment by hdevalence** [comment]
Length limits are a good idea. In addition, once we implement fees, we should also have a per-byte fee for blockspace usage.

**Comment by hdevalence** [comment]
Let's bound the name, website, etc fields at 140 characters and the description at 280 characters.

Let's also scope this issue just to fixing the validator definitions to have bounds. We can do a general survey of other messages at a later point.
