### ISSUE TITLE
Provide TOML format for chain parameters

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2067]
This is necessary for parameter change proposals. Once we have this, we can template those and submit them.

**Comment by hdevalence** [comment]
Question: instead of having a separate ChainParametersToml, what if we just made the original ChainParameters proto message be stringly-typed, so that the standard domain type was natively Toml'able?

**Comment by hdevalence** [comment]
How is that different from binary protobuf data, though? They already have to validate the domain types contained in the message, what difference does it make whether they're parsing those domain types from a bytes/Vec<u8> vs a string/String?
