### ISSUE TITLE
Provide a command line interface for producing `TransactionPlan`s for the DAO

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2074]
This relies on #2069 so that we can have a human-readable input format describing the intention of the transaction: both the ability to produce a `TransactionPlan` from an intent, and the ability to synthesize a `TransactionPlan` back to an intent so that users can understand proposals.

**Comment by hdevalence** [comment]
I don't think we should do this; creating a transaction plan manually is fine for now, and in any future where we have active engagement with on-chain governance, people will be primarily interacting with it through means other than the command-line interface.
