### ISSUE TITLE
Choose a data store for Penumbra's application state

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#21]
Some candidates:

- RocksDB: Pros: fast, mature, fairly simple KVstore interface. Cons: big C++ dependency, platform issues, need to decide on queries upfront
- SQLite: Pros: lightweight, simple, embeddable. Cons: possible scaling issues (?)
- Postgres: Pros: very powerful "real database", flexible queries. Cons: cannot be embedded in the application.

One point to consider is that the setup of having `tendermint` drive `pd` using ABCI already requires bundling two programs and running them together. If this is done with docker, the marginal cost of having another program (postgres) is smaller, and instead of having to build the database, it can just be pulled as a docker image.  On the other hand, leaning into docker in this way probably increases the pain of deployment for any non-Docker users.

**Comment by hawkw** [comment]
A nice thing about using a SQL database for this is that (if we're careful about designing queries that don't rely on database-specific features) we can pretty easily make the database modular, so that it's possible to run a Penumbra node that's either configured to embed Postgres _or_ configured talk to a Postgres DB.

**Comment by hawkw** [comment]
I'll add that an additional con of SQLite is that it's _also_ a big wad of C you have to compile and link as a build-time dependency of Penumbra, just like RocksDB. Whereas a non-embedded Postgres db is a docker image you can just download and it works.

**Comment by arturomf94** [comment]
It seems like a good compromise would be to facilitate PostgreSQL via Docker and to keep the modularity @hawkw mentioned so as to compensate for _"leaning into docker"_? That would leave the door open for a more flexible set-up, surely?

**Comment by hdevalence** [comment]
Okay, it sounds like using Postgres is a good idea, especially if we don't try to use any Postgres-specific stuff. (I'm not sure how careful it's important to be, weighing the guaranteed near-term cost of checking all the queries against the potential future cost of rewriting a few of them that accidentally used a Postgres-specific feature).  

@zmanian mentioned that a future release of Tendermint is supposed to have support for indexing the consensus data with Postgres, which could be a nice overlap.

Closing this as decided on the Postgres option; we can always revisit it later.

**Comment by hdevalence** [comment]
Some info on the timing of Postgres support from @marbar3778 https://twitter.com/mark0baricevic/status/1436004495427788808?s=21

**Comment by hdevalence** [comment]
Some info on the timing of Postgres support, from @marbar3778 https://twitter.com/mark0baricevic/status/1436004495427788808?s=21
