### ISSUE TITLE
Add `pcli view tx` step to transaction submission in smoke tests.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2101]
Currently we don't check that the transaction view code works, leading to the possibility that #2092 was a real issue instead of just a parsing problem. 

Instead, we should change the smoke test so that the transaction send test grabs the hash from the output of `tx send` (it can use a regex to match a 32-byte hex string, there will only be one in the output), and then run `pcli view tx HASH --raw` to get the JSON-encoded transaction view, then deserialize it to a `TransactionView`.  (I don't think we need to check specific aspects of the view, as long as we get valid JSON I think we'll be checking what we care about in the context of an integration test, which is "does the command work").

**Comment by conorsch** [comment]
Closed via https://github.com/penumbra-zone/penumbra/pull/2759
