### ISSUE TITLE
Make transaction plan JSON more human-readable by making protos stringly typed

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2110]
Right now, it is extremely difficult to hand-craft a transaction plan, or even to understand one when you are looking at it. This impedes DAO spend usability, as well as makes debugging more painful. If we changed the transaction plan proto format to use string values where currently it uses well-typed sub-messages, this would make it much easier to understand what is happening in a transaction plan, and in the case of plans that don't require randomizers and such, make it possible to reasonably easily human-author one (i.e. for a DAO spend proposal).

Non-goals of this change: transaction plan JSON should not be the canonical human view of a transaction plan, because it is still too low-level. I posit that humans care about the net flow of typed value between addresses and accounts, not individual actions, and this latter concept is meant to be reified in possible future work on #2076.

**Comment by hdevalence** [comment]
This would also be useful to do for transaction views, but that runs into the problem identified in https://github.com/penumbra-zone/penumbra/pull/2150 , which I assume would also be a problem for `TransactionPlan`s.

**Comment by hdevalence** [comment]
xref #1788, they're different issues but the same concerns as in this issue may be relevant while revising the TxV structures.

**Comment by conorsch** [comment]
Blocked while waiting for clarification on the above.

**Comment by redshiftzero** [comment]
Upon discussion with @plaidfinch, closing as not needed
