### ISSUE TITLE
bug: spend proofs do not verify for 0 valued spends

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2135]
The idea with dummy spends was that spending notes of 0 value should always verify. This is not happening, as found by @zbuc. 

Reproducer here: https://github.com/penumbra-zone/penumbra/compare/dummy-spends-fail-merkle?expand=1

Two issues:
1. The proofs don't verify when the anchor of the dummy spend used at proving time is that from the dummy spend commitment proof. 
2. This bug was found because a note has 0 value but was not intended to be a dummy spend, meaning that indicating dummy spends only by their 0 value may not be the right path.

**Comment by hdevalence** [comment]
> The proofs don't verify when the anchor of the dummy spend used at proving time is that from the dummy spend commitment proof.

Can we gate the "publicly supplied anchor == anchor in proof" consistency check based on whether or not the spent value is nonzero?
