### ISSUE TITLE
Bug: fix client scanning to not record 0-value swap outputs

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2136]
**Describe the bug**
The view client scanning is supposed to ignore 0-value notes, but this is not happening.

**Comment by hdevalence** [comment]
Did we ever get more information about why it's not happening? I checked the code and the check is there.

Maybe the 0-value check is only applying to _scanned_ notes, and not ones we derive deterministically as swap outputs?

**Comment by hdevalence** [comment]
I'm pretty sure that's exactly the problem. To fix this, we'll want to change the view server not to record the 0-valued outputs of a swapclaim.

**Comment by hdevalence** [comment]
In the meantime, a client state can be fixed by opening the database in `sqlite3` and running
```sql
DELETE FROM spendable_notes WHERE ROWID IN (SELECT spendable_notes.ROWID FROM spendable_notes JOIN notes ON spendable_notes.note_commitment = notes.note_commitment WHERE notes.amount = 0);
```

**Comment by hdevalence** [comment]
Looks like this is affecting testnet users: https://discord.com/channels/824484045370818580/915710988312002610/1087793758935978045

**Comment by aubrika** [comment]
> not to record the 0-valued outputs of a swapclaim

Unsure how exactly to calculate this for swaps because I'm unfamiliar with that implementation - looking at the `BatchSwapOutputData`

`pub struct BatchSwapOutputData {
    pub delta_1: Amount,
    pub delta_2: Amount,
    pub lambda_1_1: Amount,
    pub lambda_2_1: Amount,
    pub lambda_1_2: Amount,
    pub lambda_2_2: Amount,
    pub height: u64,
    pub trading_pair: TradingPair,
}
`
Do we just want to exclude `SwapClaimPlan`s where delta_1 and delta_2 are both zero, or should a more complex calculation be done here?

**Comment by hdevalence** [comment]
I think it won't be necessary to interpret the BSOD at all, at some point in the code the view service already computes the swap claim output notes in order for them to be recorded. We just need to trace through how that happens, and filter out the notes before we record them.

**Comment by hdevalence** [comment]
On mobile but I think this is how they're getting in:

![image](https://user-images.githubusercontent.com/44879/227385177-769e5621-9585-48a5-b050-db18e9ce9270.jpeg)

![image](https://user-images.githubusercontent.com/44879/227385118-d64e5d8c-dade-4a13-b460-1538a9f1e409.jpeg)

Somewhere (probably easier to find not on mobile) the thing that processes swaps is calling give_advice to record the output notes that _would_ be recorded by a future SwapClaim, and we just need to filter zero value notes out of the advice mechanism. This could either be making give_advice be internally a no-op on a zero value note (probably the cleanest) or it could be externally filtering calls to it wherever it's called.

**Comment by aubrika** [comment]
oh! thank you, that is helpful, will investigate advice fn
