### ISSUE TITLE
denote dummy notes with another method

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2142]
The spend proofs are written to allow 0 valued spends to always pass (see #2135) assuming that they are always dummy spends. But this is not correct: a 0 valued note can happen for other reasons: if someone sends you a note with 0 value, or from outputs of a swap. 

Should we denote the dummy values by another method? i.e. using a special sentinel asset ID?

**Comment by hdevalence** [comment]
Wait, why is it not correct to allow this?

**Comment by redshiftzero** [comment]
It's OK to allow proofs to autopass for completely dummy/fake notes that only exist for metadata resistance. Is it correct to allow proofs to autopass for 0-valued notes in general? I was wondering this since dummy notes are not "real" notes (e.g. not inserted into the SCT, etc) but my understanding is in the other 0-valued note cases they are "real" notes so they could be spent normally. Or does this not matter because they carry no value?

**Comment by hdevalence** [comment]
To keep things simple, I think we shouldn't intend to support non-dummy spends of zero-value notes. There's no reason to do so anyways — clients should not be planning transactions with zero-value spends other than for metadata resistance.
