### ISSUE TITLE
docker-compose build fails on 048-carme

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2155]
A Discord user reported the `docker-compose` build fails:

```
 => ERROR [build-env 32/40] RUN cargo fetch --target $(uname -m)-unknown-linux-gnu 
------
 > [build-env 32/40] RUN cargo fetch --target $(uname -m)-unknown-linux-gnu:
#45 0.384 error: failed to load manifest for workspace member `/usr/src/pclientd`
#45 0.384
#45 0.384 Caused by:
#45 0.384   failed to read `/usr/src/pclientd/Cargo.toml`
#45 0.384
#45 0.384 Caused by:
#45 0.384   No such file or directory (os error 2)
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c cargo fetch --target $(uname -m)-unknown-linux-gnu" did not complete successfully: exit code: 101
```

I can reproduce that on my machine, too. We recently vastly simplified the smoke tests (e.g. #2094), and as a result, we aren't running docker-compose logic in CI anymore. Let's re-add a simple check to confirm it can build cleanly, to minimize breakage of that deployment option.

**Comment by hdevalence** [comment]
Could we alternatively delete it entirely, and do #1927 instead?

**Comment by conorsch** [comment]
> Could we alternatively delete it entirely, and do https://github.com/penumbra-zone/penumbra/issues/1927 instead?

I like this idea a lot. Won't make 49, but happy to revisit thereafter.

**Comment by conorsch** [comment]
As discussed above, #1927 is the real path forward here, so closing this ticket.
