### ISSUE TITLE
Update semantics of `BatchSwapOutputData` to support partial fills

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2157]
Currently, `BatchSwapOutputData` presumes that the entirety of the batch swap will succeed or fail. However as we progressed on implementation of execution, it became clear that we actually need to represent two directional trades for every batch, and so `BatchSwapOutputData` will need to be updated.

We have a trade (1=>2) which we execute in a batch and a trade (2=>1) which we execute in a batch. Our current data structures assume that both of those trades execute at a common clearing price, but in our execution implementation we are going to be doing them as two separate trades.

Concretely, this means:

- [x] Remove the `success` boolean property from `BatchSwapOutputData`
- [x] Update the fields of `BatchSwapOutputData` to contain `lambda_1_1`, `lambda_1_2`, `lambda_2_1`, `lambda_2_2` where:
```
lambda_1_1 <- amount of asset 1 output from (1=>2) trade
lambda_2_1 <- amount of asset 2 output from (1=>2) trade
lambda_1_2 <- amount of asset 1 output from (2=>1) trade
lambda_2_2 <- amount of asset 2 output from (2=>1) trade
```
- [x] Update the `pro_rata_outputs` method to sum the outputs from both directions of the trade (i.e. the pro-rata share of `lambda_1_1` plus the pro-rata share of `lambda_1_2` and the pro-rata share of `lambda_2_1` plus the pro-rata share of `lambda_2_2`)

**Comment by hdevalence** [comment]
This is relatively high priority, since it will change the ZKPs and also the client-side logic.
