### ISSUE TITLE
Support querying for liquidity positions in pcli

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2165]
There should be a `pcli query dex liquidity-positions` command that by default displays all open liquidity positions  (along with reserves and IDs).

Additional flags should support displaying only positions created by the active wallet, as well as a flag for including closed/withdrawn positions.

**Comment by hdevalence** [comment]
To do this we'll need to add new streaming RPCs to `pd` -- IMO we should focus the design on the design of those RPCs, and think of the `pcli` command just as a wrapper for them.

**Comment by erwanor** [comment]
@hdevalence will rollback the view service fix, that blocks the current PR #1408

**Comment by hdevalence** [comment]
Sorry, I meant we should just change it here, by flipping the needs sync boolean
