### ISSUE TITLE
dex: design details of LP reward claim mechanism

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2167]
Currently, we just have a stub design for how the LPNFT design can support retroactive rewards to liquidity positions.  However, we don't have either:

- [ ] Mechanism design for LP rewards
- [ ] System design for LP reward claims

**Comment by hdevalence** [comment]
Blocked on #1934.

**Comment by conorsch** [comment]
> Blocked on https://github.com/penumbra-zone/penumbra/issues/1934.

Implementation is blocked, but we'd still like to discuss the design goals. In fact, we're discussing it today. We'll report back and capture takeaways in this ticket.

**Comment by zbuc** [comment]
07/07/23 meeting notes:
https://hackmd.io/@U47bTB1sSym1rzNSov3h6Q/Syh0HCrK2
