### ISSUE TITLE
IBC-related governance proposals

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2173]
We don't want to forget to have governance proposals for modifying / mutating IBC state:

- [ ] Performing unplanned upgrades of an IBC connection
- [ ] Freezing IBC clients
- [ ] Unfreezing IBC clients

**Comment by erwanor** [comment]
We're going to go ahead with having governance handles to freeze/thaw clients. However, we are not going to allow arbitrarily amending client state
