### ISSUE TITLE
Align command-line interfaces around endpoint URIs (outbound) and socket addresses (inbound)

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2196]
**Is your feature request related to a problem? Please describe.**

Currently, the command-line interfaces for pd, pclientd, and pcli have a disjointed mix of addresses and ports. This is a problem, both because all the tools have a slightly different interface, but also and more importantly because it means it's not easy to handle different protocols (http vs https).

**Describe the solution you'd like**

We should go through the command-line arguments for
- [ ] pd
- [ ] pclientd
- [ ] pcli
and modify them so that
- all _inbound_ addresses (eg a service hosted by that program) are specified as SocketAddr, which includes both the address and port in one item
- all _outbound_ addresses are specified as a [Uri](https://docs.rs/tonic/latest/tonic/transport/struct.Uri.html), allowing specification of the protocol, address, and port all in one item

Then, we'll need to propagate those changes through the smoke test script until it passes CI.

**Comment by agouin** [comment]
This will be very helpful for us in [interchaintest](https://github.com/strangelove-ventures/interchaintest) as we have separate hostnames for `pd`, `tendermint`, and `pclientd` binaries with containerization. This will also be helpful when we reach the production deployment stage since we run with kube.

The current blocker for us is due to this behavior in `pclientd`.

**Comment by hdevalence** [comment]
I'd put this as `good-first-issue` but now that we know this is blocking, I think it'd be good to prioritize it.

**Comment by conorsch** [comment]
I'll pick this one up this week, after next round of testing of the relayer PR (https://github.com/cosmos/relayer/pull/1124).

**Comment by conorsch** [comment]
We have a deploy error in https://github.com/penumbra-zone/penumbra/actions/runs/4529140413/jobs/7976706608 , related to testnet generate logic. First we need to resolve #2218, though.

**Comment by conorsch** [comment]
Resolved via https://github.com/penumbra-zone/penumbra/commit/3a30b4df5747b3986724b16186129dfde1aad703

**Comment by conorsch** [comment]
@erwanor I drafted some language for the release notes: 

> We've changed how URLs and addresses are declared when configuring a Penumbra node. If you use custom scripts to set up your node, you will likely need to update them. Remote end points must now be specified with a full URL, and local bind addresses should be specified as a socket (e.g. `127.0.0.1:8080`). We've updated the documentation to match the new args. See the `--help` option on the various commands for a full list of examples, including associated environment variables.
