### ISSUE TITLE
Define initial ABCI query interface

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#22]
ABCI offers a `Query` method to [request data from the ABCI application](https://docs.tendermint.com/master/spec/abci/abci.html#query).  This will be the main point of access to the Penumbra chain state, and will probably be called via the Tendermint `/abci_query` [RPC endpoint](https://docs.tendermint.com/master/rpc/#/ABCI/abci_query).

The ABCI query method takes `data` as `bytes` and `path` as `string`, but the RPC method takes `data` and `path` as `string`, because the RPC speaks JSON.  So if `data` has binary data, there may be some encoding/decoding involved (?), or maybe the encoded data gets passed through to ABCI.

For the actual protocol, Protobufs seem like a good choice, because they involve an actual specification of the data interchange format.

- [ ] Declare a `.proto` file with at least one ABCI query
- [ ] Use `prost` to generate Rust protobuf types (with Serde support)
- [ ] Implement the ABCI query in `pd`
- [ ] Implement the ABCI query in `pcli`

**Comment by redshiftzero** [comment]
After discussion out of band, this is not quite ready for implementation, so we're moving this to MVP2. The open questions are:
* Should parts of the wallet gRPC service be instead done via ABCI query? Should the wallet service be replaced entirely?  
* What information should the ABCI query return from the application? Note that there is quite a lot of data that users can get through [tendermint-RPC](https://docs.tendermint.com/master/rpc/).

**Comment by hdevalence** [comment]
This may be easier once we are using the JMT and can answer key/value pairs; it may also connect to the work required to support IBC relayers #465 .

One thing that @jackzampolin mentioned recently is that the Cosmos SDK is moving towards having queries just be gRPC methods, and have a way to map gRPC methods into ABCI queries.  This seems like a good direction to go in.

**Comment by hdevalence** [comment]
Closing as completed — we have a basic version of this as part of @avahowell's IBC work.
