### ISSUE TITLE
Fill an order against multiple positions

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2202]
After implementing filling a trade against a single position, the next thing to implement is filling a trade against multiple positions, walking up the order book in price order.

We should make sure to have state machine tests that exercise really simple cases, so we can make sure that, e.g., we're walking through positions from least to greatest price, rather than the opposite, or something else.

- [x] Implement as a method on the `PositionManager`
- [x] Add basic state machine tests.
- [x] After #1908, add more complex state machine tests that create many positions using different passive strategies (tracked in #2237)

**Comment by erwanor** [comment]
I have created #2237 to track writing tests that cover more surface.
