### ISSUE TITLE
Write a bot that maintains active liquidity by quoting prices with some spread

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2204]
To exercise DEX functionality, it would be useful to have a bot that can market-make on the testnet. A simple implementation of a trading strategy is to fetch prices on some centralized, or decentralized, exchanges (off-chain), and submit on-chain quotes for that pair around the mid-price, plus a spread (using the `fee` parameter). The bot should update its bids and asks every block to reflect the changing price of the assets.

Once an MVP is completed, it is possible to extend bot functionality to reach feature parity with the `StubDex` component, for example by adding skew to the orders so that the prices quoted reflect the scarcity of the available inventory (i.e. quote higher prices when we run out of one side of the pair). That's not needed for this ticket.

### Simulating convertibility 

There are no external reference markets and the paper assets are not redeemable for anything. This means that it's impossible to arbitrage the posted quotes or rebalance inventory. We should make sure that the bot is allocated a large fraction of the total float of paper assets so that it never runs out and can always quote the correct prices. (#2229)

**Comment by zbuc** [comment]
We would need a testnet allocation with multiple paper assets to complete this. May want the trading function approximation (#1908) as well.

**Comment by hdevalence** [comment]
What data feed do we want to use for the bot?

**Comment by zbuc** [comment]
Will start w/ Binance free tier streaming websocket API: https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md

**Comment by zbuc** [comment]
This is done in https://github.com/penumbra-zone/osiris
