### ISSUE TITLE
CI check to run build on all features

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2210]
It could be good now that we have feature flags to enable: https://crates.io/crates/cargo-all-features

For example the `penumbra-wallet` crate doesn't compile on `main` without the `parallel` feature (I first noticed when testing on 3a5aa9464ab5c1db85b3fd9b83204698029f6a50, but it was not introduced in that commit).

If this check is slow, could be fine to just do on `main` as a guard against releasing breaking changes to downstream users.

**Comment by conorsch** [comment]
Interesting! Tried a quick `cargo check-all-features` on `main` and it failed. Looks like there might be some small cleanup we can do on the edge cases; otherwise, we can ignore certain conflicting feature flags in the package metadata. I'll take a closer look next sprint and document results here.
