### ISSUE TITLE
Ensure that swaps from a denomination into itself are not submitted

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2228]
Currently, swapping e.g. `pcli tx swap 100gn --into gn` reduces the account `gn` balance by 100, instead of by 0. This should be fixed with appropriate checks to ignore such swaps or via values guarantees.

**Comment by hdevalence** [comment]
Should we just add a consensus rule to `<Swap as ActionHandler>::check_stateless` method that rejects swaps with an identity `TradingPair`?

**Comment by aubrika** [comment]
Oh, that seems like a good solution, yes
