### ISSUE TITLE
Add complex state-machine tests for execution and order-book traversal

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2237]
Once #1908 is completed, we will have the opportunity to generate realistic order-book scenarios to test execution / order-book traversal.

Here are some properties that we would like the state-machine tests to assert:

- orders are always executed in correct order
- asset conservation is respected
- duplicate orders are executed against randomly

under different configurations (dust fills, partial fills, full executions)

**Comment by hdevalence** [comment]
Closing now that we have more tests; we can create more tests for specific behaviors if desired.
