### ISSUE TITLE
Ensure that bigger-than-64-bit-amounts work throughout the stack.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2251]
**Is your feature request related to a problem? Please describe.**

Following the Testnet 49 release, we should pick up #2192, starting over and generating new allocations for testnet 50.

**Describe the solution you'd like**

- [ ] Copy in the `pusd` definition from `crypto/src/asset/registry.rs`
- [ ] Replicate the changes to the base allocations, adding `pusd` allocations to the team testnet addresses and the test address
- [ ] Replicate the changes to `pcli/tests/network_integration.rs`, making the network integration tests use it
- [ ] Generate a new set of allocations for testnet 50
- [ ] EXPAND AND FILL IN: do the needful for the tests to pass

**Comment by aubrika** [comment]
Note: when swapping SQLite column types to BLOB for u128s, first convert via `to_be_bytes()` to preserve ordering
