### ISSUE TITLE
Determine the cause of ICS23 verification failures in `ConnectionOpenAck` handling

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2252]
**Describe the bug**

Running @conorsch's WIP relayer configs, using the WIP relayer code, gave this output on a local devnet: https://gist.github.com/hdevalence/b9c7a8621ec9e5fbd07cf6f444c0f464

**To Reproduce**

1. Create a local Penumbra devnet, using the "devnet quickstart": `pd testnet generate` followed by `tendermint start` and `pd start`. Before launching, it's probably useful to change the testnet name in 2 places in `genesis.json` so that it's `penumbra-local-HEX`; this way, it'll be easy to distinguish from the preview chain. Keep the randomizer, though, so things don't get confused by duplicate chain IDs during resets. When launching `pd`, set `RUST_LOG="info,[CheckTx]=debug"` to get debug level output for all `CheckTx` spans.
2. Check out the WIP relayer code from the PR: https://github.com/cosmos/relayer/pull/1144 and build it locally with `make install`, installing the `rly` binary. **NOTE**: the last commit in that branch may be bad; examining what happens with- and without it should be part of debugging.
3. Use the WIP scripts @conorsch added in #2166 to generate configs for `preview` and `local` networks.  Follow the steps in `deployments/relayer/README.md`.  Note that the IBC handshake is directional, so depending on which of `preview` and `local` comes first, one or the other will get different handshake messages.  You can use this to your advantage by choosing the ordering so that the messages you care to inspect are on the chain you have local debug output for.

It may be helpful, as part of this process, to use a patch directive to replace crates along the verification stack with local forks that can have extra `tracing` statements added to them.

**Comment by hdevalence** [comment]
Fixed

**Comment by avahowell** [comment]
This turned out not to be a problem with the proofs but rather that we were verifying the wrong data in the ibc implementation- there were a few cases where we mixed up which chain's state we were verifying

**Comment by conorsch** [comment]
Resolved via:

* https://github.com/penumbra-zone/penumbra/pull/2271
* https://github.com/penumbra-zone/penumbra/pull/2274
