### ISSUE TITLE
Extract the tendermint proxy code in `pd` into a standalone workspace crate, so it can be reused by `narsild`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2253]
Maybe `tm-grpc-proxy`?

**Comment by conorsch** [comment]
@zbuc This was achieved by #2297, right?

**Comment by zbuc** [comment]
> @zbuc This was achieved by #2297, right?

Yep! There's a new `tendermint-proxy` crate within the workspace.
