### ISSUE TITLE
Explore enhanced privacy for delegations

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#226]
In the current design, we reveal the validator to whom a delegation transaction is sent, though the amount itself is shielded (and only revealed in aggregate per validator for each epoch). When a validator is small (or just getting started), this could lead to privacy compromises for delegators, because if only a few delegations occur to a validator in a particular epoch, those transactions could be traced to that validator.

If instead the validator for every delegation was encrypted using threshold cryptography just like the amount, this would significantly increase the anonymity set for delegations, mitigating this compromise. This requires some design work, and it seems that any implementation would be blocked on us finishing implementation of the threshold value cryptography.

**Comment by hdevalence** [comment]
We won't be doing this before mainnet, especially because ABCI++ schedule slippage meant we don't actually do flow encryption anyways.
