### ISSUE TITLE
Add a stub `narsil` crate to the workspace

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2260]
This should be structured as a library, with

- [x] A stub ledger implementation in the library that uses `penumbra_storage` as a backing store and can process ABCI messages using `tower_actor`
- [x] A `narsild` binary (for the server) that spins up the stub ledger implementation
- [x] A `narsilcli` binary to poke at it during development; this can be empty to start.

**Comment by zbuc** [comment]
@hdevalence I'm not seeing a stub ledger implementation right now; I see `ledger.proto` with some messages defined but no service proto. Should `narsild` do anything when this issue is completed?

**Comment by hdevalence** [comment]
> @hdevalence I'm not seeing a stub ledger implementation right now; I see `ledger.proto` with some messages defined but no service proto. Should `narsild` do anything when this issue is completed?

Yeah, the idea was for it to have a stub implementation that pulls in `penumbra-storage` and `tower-abci`/`tower-actor` and has a run-loop that can process ABCI messages well enough for Tendermint to produce blocks, even if they're empty. (I don't think we need to have multiple actors, we could have one and use the `split` middleware).
