### ISSUE TITLE
Migrate to CometBFT 0.37

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2263]
The Tendermint project has been forked as CometBFT. We should plan to migrate our use Tendermint accordingly. At first, let's aim 

## Required changes
- [x] Spike on compatibility by swapping cometbft for tendermint binary, joining the testnet-preview deployment. For now, let's keep the version the on the `0.34.x` series.
- [x] Update testnet generate logic to use new config dir paths.
- [x] Update container references to use cometbft, rather than tendermint, container images
- [x] (Later) Update cometbft to latest release series, e.g. `0.37.x`. Check whether LTS channel exists.

## Relevant docs
* [CometBFT announcement post](https://medium.com/the-interchain-foundation/cosmos-meet-cometbft-d89f5dce60dd)
* [CometBFT: Upgrading from Tendermint Core](https://docs.cometbft.com/v0.34/guides/upgrading-from-tm)

**Comment by hdevalence** [comment]
There's currently no LTS channel for CometBFT releases.  We can't easily switch to 0.37.x because it changes the ABCI version, so we'll need to update `tendermint-rs` and `tower-abci` and also change our `Consensus` and `Mempool` implementations to match the new ABCI semantics.

**Comment by conorsch** [comment]
@erwanor has some work in flight that's related to this https://github.com/penumbra-zone/tower-abci/pull/25. To be clear, we're not blocked here: we can still proceed with testing compat on the _current version_. Before we reach for upgrading versions, let's make sure to check compat in e.g. tower-abci.

**Comment by hdevalence** [comment]
Updated issue title to reference a goal of switching to 0.37; the ABCI support should have landed in `tower-abci` by now.

**Comment by conorsch** [comment]
As of https://github.com/penumbra-zone/penumbra/pull/3033, we are running cometbft `v0.34.27` in the preview environment. So far, so good. Updated the checklist. Final remaining task is to increment minor versions, which we'll need to do carefully, making changes to `pd` and/or `tower-abci` where necessary.

**Comment by erwanor** [comment]
The only changes that we will need to do are to `pd`, specifically:

- [ ] use the `v037` module of `tower-abci` and `tower-trace`
- [ ] handle `v037` new messages like `PrepareProposal`, `ProcessProposal`

We can start with naive implementations for the new messages and refine later, [see here](https://github.com/tendermint/tendermint/blob/v0.37.x/spec/abci/abci%2B%2B_tmint_expected_behavior.md#adapting-existing-applications-that-use-abci)

**Comment by conorsch** [comment]
This is done. Docs are updated and preview is now running with `v0.37`. We'll make sure to call out the version change in the release notes for 62 (#3123).
