### ISSUE TITLE
Decide how new validators will be added

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#227]
On the cosmos hub, there's a transaction called [`create-validator`](https://hub.cosmos.network/main/validators/validator-faq.html#how-to-become-a-validator) which is how one expresses the intent to become a validator, as well as specify parameters like commission rate.

We should determine how we'll do this, i.e. should we have something similar in the form of a `CreateValidator`description (and maybe add another description type later to update parameters for existing validators).

**Comment by hdevalence** [comment]
Since validators are supposed to be identified by their public keys, we could potentially reuse `CreateValidator` to edit validator parameters (if a second one appears with the same identity key, it overwrites the fields from the first one).

**Comment by hdevalence** [comment]
This is done in #321 with the `ValidatorDefinition` action, although it hasn't been implemented yet.
