### ISSUE TITLE
Refactor IBC event handling to make use of `TypedEvent`s

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2285]
**Is your feature request related to a problem? Please describe.**

One of the issues we ran into while debugging compatibility between `pd` and `rly` was inconsistent encoding of event data that was intended to be picked up by the relayer.  Currently, we handle events with `events::named_event(...) -> Event` constructors that take typed values and create events from them.  However, this is still somewhat error-prone.

**Describe the solution you'd like**

After https://github.com/informalsystems/tendermint-rs/pull/1288 lands upstream, we can define our own domain types representing the data in `abci::Event`s.  This will give us a more maintainable, single source of truth on how our event serialization should be defined.

**Comment by conorsch** [comment]
ibc-types refactoring is complete. Unclear to me whether this is related to #2385.

**Comment by conorsch** [comment]
Resolved in https://github.com/penumbra-zone/penumbra/pull/2829
