### ISSUE TITLE
Figure out how to execute integration tests against the ABCI App

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#230]
Currently, the ABCI app contains `State` that defines its behavior. As the entrypoint for the application, it would be useful to be able to write integration tests against `App` to verify that behavior functions as expected. This could be accomplished by abstracting the `State` type and writing a mock or facade, for example one which uses an in-memory database instead of a postgres instance.

**Comment by avahowell** [comment]
After discussions in discord, it's probably fine to just test against a postgres instance. So, we would need some scripting that can spin up a testing postgres instance (using docker?), then write e2e tests using a state initialized from that testing postgres instance, and integrate this with our CI system.

**Comment by zbuc** [comment]
Instructions on using postgres in GitHub CI here: https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

**Comment by hdevalence** [comment]
We should revisit this once we finish the `Component` rewrite and discard the Postgres state, since we'll then be able to make ephemeral state instances in the test suite.

**Comment by hdevalence** [comment]
xref #1622
