### ISSUE TITLE
Add support for TxP/TxV generation to the `penumbra-wasm` crate

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2302]
**Is your feature request related to a problem? Please describe.**

We'd like to have support for transaction viewing in the browser extension. To do this, we need to be able to generate `TransactionPerspective`s and `TransactionView`s from the `penumbra-wasm` crate.

**Describe the solution you'd like**

Add functionality to the `penumbra-wasm` crate that takes a transaction and outputs a pair of `TransactionPerspective` + `TransactionView`.  (Returning both is useful, because it means we can support either a caller who wants just the perspective -- to verify on their own later -- or the more common case of a caller who wants the full view without having to do further processing).

**Comment by zbuc** [comment]
Currently blocked on view implementation

**Comment by conorsch** [comment]
We didn't get to this for 51; shoving into next for sprint planning session tomorrow.

**Comment by hdevalence** [comment]
We want to copy-paste the implementation in the Rust view server and adapt it to the wasm view server.  In order to do this, we need to make a list of all of the information that the Rust view server's TxP generation queries from its state, and then ensure that the wasm view server also records that information.

**Comment by aubrika** [comment]
For generating the TxP, we query the following from view storage:

- [ ] the full viewing key
- [ ] the transaction
- [ ] note records for some transaction actions
- [ ] known assets by id

**Comment by hdevalence** [comment]
OK, this actually seems like good news, we should be able to support TxP/TxV generation relatively easily with the data we have:

>     * [ ]  the full viewing key

This is already in the wasm state

>     * [ ]  the transaction

This can be passed in as part of the method call
 
>     * [ ]  note records for some transaction actions

The note and swap records are already in the wasm state

>     * [ ]  known assets by id

This is not currently in the wasm state, but in a first-pass implementation, we can ignore it, and always return an `Unknown` denom view.
