### ISSUE TITLE
Change the `IdentityKey` domain type to store bytes rather than a decoded group element.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2304]
> One sub-case of this that could be worth doing sooner is the `IdentityKey`, which is currently a significant fraction of the total sync time.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/issues/1957#issuecomment-1497989146_

**Comment by conorsch** [comment]
In sprint planning today, we decided this is still worthwhile: when profiling `pd`, a significant amount of time is spent converting this type and then throwing away. Let's make it more efficient.

@cratelyn offered to pick this one up.

**Comment by cratelyn** [comment]
that's right! i'll be picking this up sometime later this week. :rocket:

**Comment by cratelyn** [comment]
reintroducing this to the current sprint milestone, i suspect that it was mistakenly removed!

**Comment by cratelyn** [comment]
i'll be picking this up on monday, by the way :slightly_smiling_face:

**Comment by cratelyn** [comment]
https://github.com/penumbra-zone/penumbra/blob/main/crates/core/component/stake/src/identity_key.rs#L25-L34

is changing this so that we postpone the decoding step going to be a consensus- or state-breaking change? in particular, if we save the decoding for later, `<IdentityKey as FromStr>::from_str()` will not return errors in the same cases as before.

**Comment by cratelyn** [comment]
> https://github.com/penumbra-zone/penumbra/blob/main/crates/core/component/stake/src/identity_key.rs#L25-L34
> 
> is changing this so that we postpone the decoding step going to be a consensus- or state-breaking change? in particular, if we save the decoding for later, `<IdentityKey as FromStr>::from_str()` will not return errors in the same cases as before.

other things that change if identity keys are parsed differently:
* `TryFrom<asset::Metadata> for DelegationToken` https://github.com/penumbra-zone/penumbra/blob/ca16ab138a907f5de021861a2c99a641c904e5b4/crates/core/component/stake/src/delegation_token.rs#L61
* `TryFrom<asset::Metadata> for UnbondingToken` https://github.com/penumbra-zone/penumbra/blob/ca16ab138a907f5de021861a2c99a641c904e5b4/crates/core/component/stake/src/unbonding_token.rs#L61
* `ConsensusIndexRead::consensus_set_stream()` https://github.com/penumbra-zone/penumbra/blob/ca16ab138a907f5de021861a2c99a641c904e5b4/crates/core/component/stake/src/component/stake.rs#L507-L524

the last of which seems particularly noteworthy.
