### ISSUE TITLE
Track "pending" notes in `pcli`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#231]
`pcli` currently only tracks notes as being "spent" or "unspent", and synchronizes that state from the chain.

This causes problems while submitting multiple transactions in succession, since the client state forgets that it's already tried to spend a note, and then tries to spend it again, resulting in an attempted double-spend.  (This interacts particularly badly with the current bug in #229, but would be an issue regardless).

To fix this, we should track pending changes to the client state that have been submitted to the chain, but not yet included. 

There are two relevant additional states: `pending_spent` and `pending_change`. Notes that are consumed by a submitted transaction should be marked as `pending_spent`, and the change notes (outputs we send to ourself) should be marked as `pending_change`. We should track both spends and outputs, because otherwise the UI would report to the user that they've spent much more than they probably intended.

Pending notes should have a timestamp recording when the transaction was created.  Notes are removed from the "pending" state as follows:

- During sync, observing a nullifier from a `pending_spent` note causes it to be moved from the `pending_spent` set to the `spent` set;
- During sync, observing a note in the `pending_change` set causes it to be moved into the `unspent` set;
- After some timeout, `pending_spent` notes are moved back to the `unspent` set;
- After some timeout, `pending_change` notes are deleted.

The timeout should be long enough to mostly cover transaction submission; we don't want to keep stuff in the "pending" state forever, and if a long time has passed without getting any confirmation, we should probably revert to the known chain state.  (Possibly 60 seconds is a good timeout; it's definitely short-lived but still much longer than a block time).

Removing the notes we consume from the `unspent` set will prevent them from being used for transactions, so that logic can be unchanged.  However, we should report to the user on the state of their pending balance.  One idea is to add an extra column to our existing table:
```
 Asset          Balance  Pending          
 tungsten_cube  197                       
 gm             0        -366 +356        
 gn             396                       
 penumbra       44782                     
 pizza          1863 
```
Here, I sent 10 `gm` tokens using a single note that recorded 366 of them; the UI shows me that I have none available to spend but 356 will become available soon.

(This touches on a more general problem of note management, and whether we should try to optimize outputs with respect to the current wallet state to make concurrent transactions possible; this is worthwhile but a bit of a rabbithole and I don't think we should try to optimize this any more than we currently do at this time.)

**Comment by plaidfinch** [comment]
This was closed by #268.
