### ISSUE TITLE
Represent denom metadata compatibly with Cosmos SDK

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2310]
Right now we use a custom `REGISTRY` to keep track of denomination metadata. This only works in the closed-world assumption where we know about all the families of assets that could possibly exist, and does not work in the open-world context of IBC. Instead, we should transition to a uniform representation of denominations, ideally one compatible with the Cosmos SDK so that we can have easy interoperability with external asset registries.

The Cosmos SDK [represents denomination metadata like this](https://buf.build/cosmos/cosmos-sdk/docs/main:cosmos.bank.v1beta1#cosmos.bank.v1beta1.Metadata):

```proto
// Metadata represents a struct that describes a basic token.
message Metadata {
    string description = 1;
    // denom_units represents the list of DenomUnit's for a given coin
    repeated DenomUnit denom_units = 2;
    // base represents the base denom (should be the DenomUnit with exponent = 0).
    string base = 3;
    // display indicates the suggested denom that should be
    // displayed in clients.
    string display = 4;
    // name defines the name of the token (eg: Cosmos Atom)
    //
    // Since: cosmos-sdk 0.43
    string name = 5;
    // symbol is the token symbol usually shown on exchanges (eg: ATOM). This can
    // be the same as the display.
    //
    // Since: cosmos-sdk 0.43
    string symbol = 6;
    // URI to a document (on or off-chain) that contains additional information. Optional.
    //
    // Since: cosmos-sdk 0.46
    string uri = 7;
    // URIHash is a sha256 hash of a document pointed by URI. It's used to verify that
    // the document didn't change. Optional.
    //
    // Since: cosmos-sdk 0.46
    string uri_hash = 8;
}

// DenomUnit represents a struct that describes a given denomination unit of the basic token.
message DenomUnit {
    // denom represents the string name of the given denom unit (e.g uatom).
    string denom = 1;
    // exponent represents power of 10 exponent that one must
    // raise the base_denom to in order to equal the given DenomUnit's denom
    // 1 denom = 10^exponent base_denom
    // (e.g. with a base_denom of uatom, one can create a DenomUnit of 'atom' with
    // exponent = 6, thus: 1 atom = 10^6 uatom).
    uint32 exponent = 2;
    // aliases is a list of string aliases for the given denom
    repeated string aliases = 3;
}
```

This is entirely compatible with our representation of denoms, except that it does not represent the Penumbra asset ID, which is computed like:

```rust
let id = asset::Id(Fq::from_le_bytes_mod_order(
    blake2b_simd::Params::default()
        .personal(b"Penumbra_AssetID")
        .hash(base_denom.as_bytes())
        .as_bytes(),
));
```

Clients should not have to know about the internal implementation of the denom-to-asset-ID computation, so this should also be exposed as a field in our own metadata, even if it is in principle computable from the denom string. Therefore, let's add a field to the metadata proto, picking a high index for the field number to avoid the chance of collisions with future versions of the Cosmos SDK (unknown fields are avoided by compliant proto parsers, and we can file a PR asking to set our field number as `reserved` in the Cosmos SDK). This would mean we'd have a `DenomMetadata` proto like this:

```proto
// DenomMetadata represents a struct that describes a basic token.
message DenomMetadata {
    string description = 1;
    // denom_units represents the list of DenomUnit's for a given coin
    repeated DenomUnit denom_units = 2;
    // base represents the base denom (should be the DenomUnit with exponent = 0).
    string base = 3;
    // display indicates the suggested denom that should be
    // displayed in clients.
    string display = 4;
    // name defines the name of the token (eg: Cosmos Atom)
    string name = 5;
    // symbol is the token symbol usually shown on exchanges (eg: ATOM). This can
    // be the same as the display.
    string symbol = 6;
    // URI to a document (on or off-chain) that contains additional information. Optional.
    string uri = 7;
    // URIHash is a sha256 hash of a document pointed by URI. It's used to verify that
    // the document didn't change. Optional.
    string uri_hash = 8;

    // the asset ID on Penumbra for this denomination.
    crypto.AssetId penumbra_asset_id = 1984;
}
```

Clients should not expect to be able to locally convert between denoms (base or otherwise) and asset IDs, without either having cached the information or looking it up by asking the server for metadata. In order to permit this, we'll want to introduce a new specific query method:

```proto
service SpecificQueryService {
   /* ... */
   rpc DenomMetadata(DenomMetadataRequest) returns (stream DenomMetadataResponse);
}

// A query for metadata about a denom, by 
message DenomMetadataRequest {
  // The expected chain id (empty string if no expectation).
  string chain_id = 1;
  // If set, only return denoms which have some denom unit (base or otherwise) with a name exactly equal to this string.
  optional string unit = 2;
  // If set, only return denoms which have the base denom exactly equal to this string.
  optional string base_denom = 3;
  // If set, only return denoms which have a name exactly matching the given name.
  optional string name = 5;
  // If set, only return denoms which have a symbol exactly matching the given symbol.
  optional string symbol = 6;
  // If set, only return denoms which have an asset ID exactly matching the given asset ID.
  //
  // This guarantees that the number of results will be at most 1, because asset IDs are unique.
  crypto.AssetId penumbra_asset_id = 1984;
}

message DenomMetadataResponse {
  // The denom metadata requested.
  DenomMetadata denom_metadata = 1;
}
```

All assets ingested into Penumbra will need to be associated with `DenomMetadata`, which will need to be stored in the JMT, indexed by denom, name, symbol, and asset ID.

(to be continued)

**Comment by hdevalence** [comment]
Rather than `bytes`, I think it'd be better to have `crypto.AssetId penumbra_asset_id = 1984;`, so that we're using consistent message types.

I also think we should preserve our existing "denom" vs "unit" terminology, which is better and more precise than the Cosmos SDK's: a "denom" is always a base denom, and a "unit" is a unit of that denomination.  Otherwise, I worry we'll end up with issues where we accidentally hash a unit to an asset ID rather than its denomination.

**Comment by hdevalence** [comment]
I'm also not sure we need to index metadata other than by asset ID.  The lookup problem we care about is going from the asset ID to the denom, and its metadata.  I don't think we'll have a situation where we know a denom but not its metadata, and to the extent we do, I think it's a client-side problem. (We can always go from denom to asset ID, and thereby looking up its metadata).

**Comment by hdevalence** [comment]
The thought is that if the client has 100penumbra to swap, their view server has to know about the notes they'd be spending, and therefore has already seen a note with asset ID `PENUMBRA_ASSET_ID`, at which point it would have queried for the metadata related to the assets it has.  Alternatively, a client might have builtin knowledge of common assets, or common assets on other chains.

**Comment by hdevalence** [comment]
I don't think we do need to do that, if a client has never seen an asset I think it's fine for it to be unknown.

Just having an asset ID based lookup means we don't need to edit our existing code much -- we already have code in the `ShieldedPool` component that looks up denom strings by asset ID, and we just need to change that to be looking up complete `DenomMetadata` structures, rather than putting that responsibility entirely on the client.

**Comment by hdevalence** [comment]
All we need to do here is (1) add the compatible protos (2) change the existing on-chain denom-lookup-by-id to look up a DenomMetadata instead of a string.

**Comment by hdevalence** [comment]
I was wrong: the minimal change ends up being problematic, because we'd like to have a domain type for the `DenomMetadata`. The domain type that it *should* be is the `Denom` type we already have, which is constructed via the asset registry and does internal sharing with an `Arc<Inner>` to have related `Unit` types; the `Denom` has access to all the data needed to populate the `base`, `display`, `denom_units`, and `penumbra_asset_id` fields.

But the `Denom` domain type is already the domain type for the `Denom` proto message, which just has the denom string, and the way it passes from the denom string to the metadata is by using the hardcoded registry. So even the minimal change is already entangled with changing how we model denom metadata.

**Comment by hdevalence** [comment]
New plan:

- [ ] Rename the existing `Denom` Rust structure to `DenomMetadata`, without changing which proto type it corresponds to
- [ ] Change the existing `asset::Cache` from being a transparent wrapper over a `BTreeMap` to have multiple internal BTreeMap indexes: `get_by_id(&self, id: asset::Id) -> Option<DenomMetadata>` `get_unit(&self, unit: &str) -> Option<Unit>`
- [ ] Add the new `DenomMetadata` proto message
- [ ] Change the `DenomMetadata` Rust type (fka `Denom`) to be a domain type for the `DenomMetadata` proto message, adding additional fields as necessary, and add a new `Denom` Rust type as the domain type for the `Denom` proto message.
- [ ] Change the shielded pool register denom functionality to take a `DenomMetadata` and store a `DenomMetadata`

**Comment by aubrika** [comment]
```Change the shielded pool register denom functionality to take a DenomMetadata and store a DenomMetadata```

Clarification on this: will we want to add functionality analogous to `Registry::parse_denom` here to turn raw metadata strings into `DenomMetadata`? There is a lot of `Denom`-specific logic in here already (type conversions, parsing, etc) and I don't want to get into the refactoring weeds and accidentally break more than is necessary, as this is already looking to be a pretty extensive change set. @hdevalence

**Comment by hdevalence** [comment]
Not sure what you mean by metadata strings exactly, but I think we could try to pass on touching the existing registry code.  Let's chat about it tomorrow?
