### ISSUE TITLE
Refactor `pcli` transaction viewing to be an extension trait on `TransactionView`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2312]
**Is your feature request related to a problem? Please describe.**

`pcli` has existing code to render transactions, which uses `comfy_table` to render data in a terminal.  This code was written before we even had transaction views, so it assumes that the full viewing key is present.  But the design we're aiming at is that the `TransactionView` is supposed to be a self-contained, pre-computed view of the transaction.

**Describe the solution you'd like**

To reflect this, we could refactor the transaction viewing code in `pcli` into a method on `TransactionView` in an extension trait:

```rust
// in pcli/src/transaction_view_ext.rs
pub trait TransactionViewExt {
    /// Render this transaction view on stdout.
    fn render_terminal(&self);
}

impl TransactionViewExt for TransactionView {
    fn render_terminal(&self) {
        // use comfy_table to render transaction contents
    }
}
```

This would be similar, in spirit, to the `TransactionView => HTML` pipeline we're planning for the web extension.  We could adapt the existing code, but it's not necessary to stick to it, we can do whatever format we want.

**Comment by jackmcasey** [comment]
I recently came across a post on Bluesky from @aubrika , one of your team members, mentioning that you're hiring Rust engineers. I wanted to take a look at Penumbra and get familiar with what it is and how it works. This seemed like as good a jumping off point as any.

Will be pushing the code to a GitHub repo later today, but wanted to post this to get some feedback. It's more or less "playing with the fonts and margins", but I've added a visualization for encrypted ActionViews that is a bit more human friendly. Might be a bit loud though.

![image](https://github.com/penumbra-zone/penumbra/assets/23410235/ffeaa66c-97fe-466a-a1f9-1f9e8482a788)

Anyway, let me know what you think!

**Comment by hdevalence** [comment]
That looks really cool! I think the colors are a bit loud, but maybe in black and white it would convey the "this data is encrypted" part really well...

**Comment by cronokirby** [comment]
Another cool idea for the aesthetics would be to use a random string of braille characters, which kind of has this look to it:
`⠨⡳⠡⡳⡸⢠⠌⢊⠋⣢⣶⣑⣕⠃⢻⠜⢮⡬⢌⠎⣴⣓⣿⡮⣈⣽⠓⣹⡷⡜⡤⢘`

**Comment by jackmcasey** [comment]
I agree. It also dodges the case where the foreground_color and background_color happen to be the same color.

Also like the idea of using braille characters to make it feel like a paper receipt.

Another question I have, is if this method could ever be called with less than a FullViewingKey? If so, it could be made generic over different key types.

**Comment by hdevalence** [comment]
There shouldn't need to be any key in use at all -- the purpose of the `TransactionView` is to have a pre-decrypted, pre-interpreted view of the transaction contents from a particular perspective, so that no keys or other data are necessary to interpret it. (See our [blog post](https://penumbra.zone/blog/how-to-see-in-the-dark) for details).

However, the current transaction code in `pcli` was written before we created the `TransactionView`, so it still makes use of viewing keys. Once this change is made, however, the viewing process would look like:

1. Get a `TransactionView` from the view service (which will use the FVK and other data internally)
2. Render the pre-computed view using the new `TransactionViewExt` code.

**Comment by jackmcasey** [comment]
Ah, I see. I didn't realise the TransactionView was "always decrypted" in that sense. That simplifies things.

**Comment by hdevalence** [comment]
To put it another way: if there's data in the `TransactionView` that can only be understood with extra key material, we'd consider that a bug, for instance https://github.com/penumbra-zone/penumbra/issues/2780

**Comment by jackmcasey** [comment]
Pushed here: https://github.com/jackmcasey/penumbra/tree/2312

Will open a PR when I have the rest of the ActionViews implemented.

**Comment by jackmcasey** [comment]
I believe this is now ready for review: [#3240](https://github.com/penumbra-zone/penumbra/pull/3240)
