### ISSUE TITLE
pd logs are always colored, even with no tty

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2314]
**Describe the bug**
The logs emitted by `pd` are _always_ colored, which makes them hard to read in plaintext contexts, such as log aggregation, or grepping/searching through logs.

**To Reproduce**
Here's what the logs look like in a terminal—colored and pretty:

![pd-logs-colored](https://user-images.githubusercontent.com/657862/230479856-154fc712-92e3-4075-8720-d797583dbbc7.png)

Pipe that same command to `less`, however, and it's difficult to make sense of:

![pd-logs-unescaped](https://user-images.githubusercontent.com/657862/230479933-18b5c52a-4625-4f15-bc0c-2c52c6de7e86.png)

**Expected behavior**
Logs should be colored if-and-only-if pd is run inside a tty, such as an interactive terminal window. In other contexts, when there's no tty, such as run under systemd or as an orchestrated container, the logs should be plaintext. 

**Additional context**
We'll need to tweak the settings on the tracing config to alter the behavior. Ideally we can do that by detecting whether there's a tty, but failing that, let's prefer plaintext logs for readability.

**Comment by hdevalence** [comment]
We should check the `tracing-subscriber` docs to find out if there's an easy auto-color option, I'm sure this isn't a unique problem to us.

**Comment by hdevalence** [comment]
Another, more general, question, in a separate comment since I don't want to derail this issue: in the bigger picture view, the reason we care about having non-colored logs is that the color codes make it difficult to consume them through machine tools.  But from that perspective, is the issue really about the color codes? Should we instead aim to have log output that's machine-readable, like JSON-formatted tracing output?

**Comment by conorsch** [comment]
> We should check the tracing-subscriber docs to find out if there's an easy auto-color option, I'm sure this isn't a unique problem to us.

Collecting from links from chat:

* https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.Layer.html#method.set_ansi
* https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html

A succinct statement of the functionality I'm asking for is already filed upstream: https://github.com/tokio-rs/tracing/issues/1160 but consensus seems to be we'll have to do tty detection ourselves.

> Should we instead aim to have log output that's machine-readable, like [JSON-formatted tracing output](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html)?

Great suggestion. My preference would be near-term to eliminate the escape codes in standard logging messages, as a quality of life improvement. Further changes to logging format ideally would be customizable at runtime. Targeting json support for that opt-in sounds great to me.

**Comment by hdevalence** [comment]
Looking at https://github.com/engula/engula/pull/909/files , it seems like `.with_ansi(atty::is(atty::Stream::Stderr))` would be an easy fix to have auto-coloring.
