### ISSUE TITLE
Provide a `pcli` interface to post `xyk` approximations

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2319]
As part of #1908, we would like to have a `pcli` command that generates a collection of `Position`s approximating a specified payoff. This should be broken into two commands:

- Approximating a CPMM without posting the `Posititon`s:

`pcli view dex approximate constant-product <PAIR> <QUANTITY>`

- Approximating and posting the orders:

`pcli tx position approximate constant-product <PAIR> <QUANTITY>`

In the future, it would be nice to be able to segment approximated positions from the rest of the open orders so that one can perform group actions on these positions e.g. "cancel all", "display" etc.

**Comment by conorsch** [comment]
Unlikely to ship for 51, given higher priority on IBC & DEX.
