### ISSUE TITLE
Include epoch and intra-epoch block height in `BatchSwapOutputData`

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2351]
Currently, the `BatchSwapOutputData` uses the global block height of inclusion, and the associated proofs used math on the epoch to calculate the global block height (since the commitment only has the intra-epoch block height available).

Now that we are using non-fixed block length epochs, the swap claim proof can no longer assume the epochs are fixed-length. An easy fix would be to include the epoch height and an intra-epoch block height in the `BatchSwapOutputData` in place of (or alongside) the global block height.

**Comment by redshiftzero** [comment]
Reported [today](https://discord.com/channels/824484045370818580/915710988312002610/1103017394022121613) in Discord:

```
Error: status: Internal, message: "could not broadcast transaction: transaction pre-submission checks failed: a swap claim proof did not verify: note commitment was not for clearing price height", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

This is probably happening because the transparent swap claim is still using the fixed epoch duration to compute the swap commitment block height, so if any epochs have ended early, this equality assertion will fail: 

```Rust
        // Validate the swap commitment's height matches the output data's height.
        let position = self.swap_commitment_proof.position();
        let block = position.block();
        let epoch = position.epoch();
        let note_commitment_block_height: u64 =
            epoch_duration * u64::from(epoch) + u64::from(block);
        ensure!(
            note_commitment_block_height == output_data.height,
            "note commitment was not for clearing price height"
        );
```
