### ISSUE TITLE
Lack of git-lfs causes non-working pd build

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2354]
Since introduction of #2300, we again require `git-lfs` for build. If git-lfs is absent, however, _the build will still complete_, but result in a non-working binary, which fails with the message:

>  could not configure grpc reflection service

We should fail at build time. We don't need port all the auto-git-lfs logic from the proof-params crate (or should we?) but we can at least error out if the proto descriptor file is sufficiently small. 

Might be worth jotting down some notes on recovery into the guide, for when folks inevitably try to build without git-lfs, then need to fix their setup.

**Comment by hdevalence** [comment]
I don't think we need to port all the auto-git-lfs logic as yet, because longer-term, I expect that this shouldn't be a problem for publishing crates (the file size is not so large that it can't be included in a crate, the reason to use LFS is just to minimize churn in the git repo). But erroring out in the `build.rs` would be useful.

**Comment by conorsch** [comment]
Something like this would help:

```
❯ cargo build --release
   Compiling penumbra-proto v0.1.0 (/home/conor/src/penumbra-no-lfs/proto)
   Compiling penumbra-tct-visualize v0.1.0 (/home/conor/src/penumbra-no-lfs/tct-visualize)
   Compiling pd v0.1.0 (/home/conor/src/penumbra-no-lfs/pd)
error: failed to run custom build command for `penumbra-proto v0.1.0 (/home/conor/src/penumbra-no-lfs/proto)`

Caused by:
  process didn't exit successfully: `/home/conor/src/penumbra-no-lfs/target/release/build/penumbra-proto-b7c34a3cdfec399d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error: the protobuf descriptor file is too small.
  Check that you have git-lfs installed, and retry the build.', proto/build.rs:8:38
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
