### ISSUE TITLE
Experiment with Tor support in `pcli` 

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2358]
**Is your feature request related to a problem? Please describe.**

Now that we have support for HTTPS in `pcli`, as well as automatic HTTPS in `pd`, we can make requests from `pcli` over untrusted networks.

**Describe the solution you'd like**

In a time-boxed way (say, not more than ~90mins for a first attempt), let's try adding Tor support to `pcli`, using [`arti-hyper`](https://docs.rs/arti-hyper/latest/arti_hyper/) and [`arti-client`](https://docs.rs/arti-client/latest/arti_client/).

To do this, we'll probably want to:

- [x] Add a top-level `--use-tor` option to `pcli`, alongside the RPC endpoint.
- [ ] Require that if `--use-tor` is present, the RPC endpoint is an HTTPS URL.
- [ ] Create a new `PCLI_HOME/arti-state` subdirectory for Arti data, and [configure Arti to only store data there](https://docs.rs/arti-client/latest/arti_client/config/struct.TorClientConfigBuilder.html#method.from_directories), ensuring that `pcli` doesn't read or write state outside of its home directory.
  - Arti, due to its Tor heritage, is apparently [fussy](https://docs.rs/fs-mistrust/0.6.3/fs_mistrust/index.html) about filesystem permissions. I personally don't believe this is a particularly useful threat model, since most systems are effectively single-user anyways. If we run into problems, let's take the path of least resistance for now (which might be [`dangerously_trust_everyone`](https://docs.rs/fs-mistrust/0.6.3/fs_mistrust/struct.MistrustBuilder.html#method.dangerously_trust_everyone)).
- [ ] Hook the `arti-hyper` connector up to the places in `pcli` where we connect to `pd`: https://github.com/penumbra-zone/penumbra/blob/main/pcli/src/network.rs#L82-L94
- [ ] Connect to a `pd` instance over Tor!

Note: depending on timing, it might be helpful to do this work branching directly off of the `050-thebe` tag, so that the client can be aimed at https://pd-tls.penumbra.zone, which is currently serving HTTPS gRPC for Testnet 50 in a way we know to be compatible with `pcli` (thus avoiding a dependency on #2341 if it's not finished yet).

**Comment by hdevalence** [comment]
I think that would make sense, but for an initial experiment we could stick with just having a flag for pcli.

**Comment by mikayla-maki** [comment]
Could this be solved by adding the static feature to [arti-hyper](https://gitlab.torproject.org/tpo/core/arti/-/blob/main/crates/arti-hyper/Cargo.toml#L18)? It seems to configure rustqlite to use a bundled sqlite ([here](https://gitlab.torproject.org/tpo/core/arti/-/blob/main/crates/arti-client/Cargo.toml#L43) then [here](https://gitlab.torproject.org/tpo/core/arti/-/blob/main/crates/tor-dirmgr/Cargo.toml#L21)

**Comment by mikayla-maki** [comment]
That will not help, see discord: https://discord.com/channels/824484045370818580/981304070444814367/1096209913694400562

**Comment by hdevalence** [comment]
Yeah, unfortunately the ultimate problem is that the sqlx version of libsqlite3 is outdated and there's no clear plan to update/maintain it. One possibility I discussed with @plaidfinch was to explore swapping out sqlx for rusqlite.

**Comment by mikayla-maki** [comment]
Yikes 😬😬😬. I guess a Tor support exploration is pretty important for Penumbra tho…

**Comment by erwanor** [comment]
This is momentarily deprioritized in favor of implementing the distributions module, but this is next.

**Comment by erwanor** [comment]
We did an experiment (#2361), we weren't able to get it completely working. To make further progress, we should add a test command to `pcli` that makes a single gRPC request through Tor.
