### ISSUE TITLE
Update `ibc` crate version

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2373]
**Is your feature request related to a problem? Please describe.**

We need to update the `ibc` crate version to be able to pull in `ics23` `0.10.0`.  There isn't yet a version with `ics23` `0.10.0`, but we're already several versions behind so it'd be good to start upgrading. 

**Describe the solution you'd like**

Upgrade to `ibc` `0.37.0`.

**Comment by erwanor** [comment]
we will also need it to complete the jmt integration, unfortunately. I'm planning to get to it once routing execution is completed, or shortly after anyway.

**Comment by redshiftzero** [comment]
No longer using the ibc crate
