### ISSUE TITLE
Design: ABCI event storage

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2385]
While working on https://github.com/penumbra-zone/penumbra/issues/1947 we identified an eventual need for storing and indexing emitted ABCI events.

This should ideally be as turnkey as possible, keeping with the current design of Penumbra/`pd`. This might mean including an optional indexing server that runs by default.

Options for storage might include:

* Storing in the current RocksDB DB
* Storing in a new RocksDB DB
* Using a Rust k/v store

**Comment by conorsch** [comment]
We should have a design discussion to capture spec here.

**Comment by zbuc** [comment]
Is this related to/solved by https://github.com/penumbra-zone/penumbra/pull/2828 ? /cc @avahowell

**Comment by hdevalence** [comment]
We'll use a standard Postgres indexer rather than rolling our own solution here.
