### ISSUE TITLE
pcli fails when detecting large transactions

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2388]
A long-time user in discord reported that the tx detection time in pcli isn't long enough to wait for large transactions:

```
building transaction...
finished proving in 37.337 seconds [24 actions, 23 proofs, 9708 bytes]
broadcasting transaction and awaiting confirmation...
Error: status: Internal, message: "could not broadcast transaction: error while waiting for detection of submitted transaction: Change subscriber failed: channel lagged by 5", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

Discussion determined that we've two differently configured capacities in storage, due to an incomplete refactor:

```
# Storage::initialize
        Ok(Storage {
            pool,
            uncommitted_height: Arc::new(Mutex::new(None)),
            scanned_notes_tx: broadcast::channel(128).0,
            scanned_nullifiers_tx: broadcast::channel(512).0,
            scanned_swaps_tx: broadcast::channel(128).0,
        })
        
# Storage::load
  Ok(Self {
            pool: Self::connect(path.as_ref().as_str()).await?,
            uncommitted_height: Arc::new(Mutex::new(None)),
            scanned_notes_tx: broadcast::channel(10).0,
            scanned_nullifiers_tx: broadcast::channel(10).0,
            scanned_swaps_tx: broadcast::channel(10).0,
        })
```

There shouldn't be two codepaths duplicating the construction of the Storage object. Let's refactor that. 

Holding off for now so that we can land the in-flight refactor in #2372.

**Comment by hdevalence** [comment]
Edited the title, the issue isn't about the time, it's a capacity issue: a large transaction overfills the detection buffer before the notifier can read out of it, causing the notifier to error out because it missed the data needed for notifications.

**Comment by conorsch** [comment]
#2372 landed, so no longer blocked

**Comment by conorsch** [comment]
Confirmed this still needs to be done. Let's aim for 52, since 51 is going out today, and we don't want to postpone.
