### ISSUE TITLE
Use updated ICS23 proof spec supporting noninclusion proofs

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2391]
**Is your feature request related to a problem? Please describe.**

Now that we've been able to merge our extensions to ICS23 upstream, we should ensure that we ship a version of Penumbra that uses the correct ICS23 proof spec.  This is important to do as part of the next testnet release, because otherwise, we'll have `testnet` and `testnet-preview` using different proof specs, and the relayer doesn't know how to support that (and shouldn't need to, because there should just be one correct proof spec).

**Describe the solution you'd like**

Getting this done has a somewhat deep dependency chain, so we should focus to make sure we get all of the steps done in time:

- [x] Ensure that the published `jmt` crate uses `ics23 = "0.10"` and has the correct proof spec
- [ ] Use the updated `jmt` crate, partially done in #2032 ...
  - but blocked on #2374, which is impossible ...
  - so we need the first part of #2379 instead:
    - [x] Finish and merge  https://github.com/penumbra-zone/penumbra/pull/2392
    - [x] #2380
    - [x] https://github.com/penumbra-zone/ibc-types/issues/2
    - [x] #2381
    - [x] https://github.com/penumbra-zone/ibc-types/issues/3

**Comment by hdevalence** [comment]
For some reason I thought that `ibc-proto` `0.30.0` included the ICS23 changes already, but that's not the case: https://github.com/penumbra-zone/ibc-types/issues/3#issuecomment-1518591455

So this is blocked on those two crate releases. Let's see how things go on Monday; one possibility is that we can consume them, possibly delaying the release a day or two; another is that we stick to the schedule and let the ICS23 changes slip.

**Comment by erwanor** [comment]
@hdevalence a third, more sinister, option is to fork ibc-proto-rs with the right vendored ics23 protogen'd: https://github.com/penumbra-zone/ibc-proto-rs/tree/vendor_ics23 and plug back into upstream for testnet 52.

**Comment by hdevalence** [comment]
Sure, that's a good thing to consider as a temporary measure -- we should definitely avoid a long-term fork of those crates, though.

**Comment by hdevalence** [comment]
I copied the branch that is supposed to be merged and fix our problem into our repo: https://github.com/penumbra-zone/ibc-proto-rs/tree/penumbra

**Comment by erwanor** [comment]
@hdevalence thanks, i'll use it to get ahead of the monday release.

**Comment by hdevalence** [comment]
I'm working on an update to `ibc-types` at the moment.

**Comment by erwanor** [comment]
Moved to testnet 53, as a result of #2032 getting delayed.

**Comment by redshiftzero** [comment]
Will be closed by https://github.com/penumbra-zone/penumbra/pull/2628
