### ISSUE TITLE
Add memo handling to `pcli`

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#240]
Currently we send every transaction with an empty memo. Fixing this would entail adding a way to specify memos on the command line in `pcli tx send`, and a way to view memos for transactions one has received. This seems interrelated with any effort to display transaction histories, which currently we don't do in `pcli`; perhaps the latter part (display received memos) should be folded into a future issue on that subject?

**Comment by redshiftzero** [comment]
@avahowell implemented #216 for memo handling, although there's the change note which we don't let the user specify the memo for, not sure if we want to do that though

**Comment by plaidfinch** [comment]
ah! missed that somehow, thanks @avahowell!

**Comment by plaidfinch** [comment]
@redshiftzero @avahowell what do you think about automatically setting the memo for change notes to be "change" or something more specific like "change for <succinct description of transaction>"?

**Comment by redshiftzero** [comment]
I think that would be nice

**Comment by hdevalence** [comment]
Prior to going further on use of the memo field, we should probably decide how it should be structured (e.g., is there a way to signal information about what the contents are?). I'd vote to defer this for later, since we currently don't even have a way to fetch transactions.

**Comment by hdevalence** [comment]
We should defer this until after refactoring into a wallet server.

**Comment by hdevalence** [comment]
We won't be doing this as part of `pcli` any more, but as part of the view service.
