### ISSUE TITLE
Testnet 52: Amalthe

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2415]
# Testnet Release

Testnet name: Amalthe
Release date: 2023-05-15
Testnet release manager: @erwanor 

# Testnet Release Manager Checklist

Preceding Friday (sprint planning day):

- [x] Create GitHub project column, work with team to populate the milestone with tickets targeted for the release.

Tuesday (or after release of previous testnet):

- [x] Construct the genesis data for the release: - https://github.com/penumbra-zone/penumbra/pull/2491
  - [x] Create new testnet directory with initial genesis allocations for this testnet by running `cd testnets && ./new-testnet.sh`
    - This genesis data will be used for `testnet-preview` with a randomized version of the future testnet's chain ID.

Thursday:

- [x] Check in with team again in a release meeting and update the GitHub milestone to ensure it represents what will make it into the testnet.
- [x] Draft an announcement for peer review to ensure major changes included are comprehensive.

Following Monday (release day):

- [x] Verify that `testnet-preview.penumbra.zone` is operational; it is redeployed on every push to main, and is an exact preview of what is about to be deployed.
- [x] Bump the version number and push its tag, via [cargo-release](https://crates.io/crates/cargo-release).
    - [x] Run `cargo release minor` for a new testnet, or `cargo release patch` for a bugfix. For the latter, make sure you're on a dedicated release branch.
    - [x] Push the commit and newly generated tag, e.g. `v0.51.0`, to the remote.
- [x] Wait for the "Release" workflow to complete: it'll take ~90m, most of which is the macOS builds.
- [x] Edit the newly created (and published) release object, then click "Generate release notes." Cut and paste the generated text from the bottom to the top of the post, then save it.
- [x] You must [manually review](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) the `Waiting` deployment in the GitHub Action UI before the deployment will begin. Monitor the GitHub action to ensure it completes after it is approved.
- [x] Delegate to the Penumbra Labs CI validators; use amounts of ~200k `penumbra` per validator.
- [x] Update the User Guide to mention the newly created git tag.
- [x] Update Galileo deployment, [following docs](https://github.com/penumbra-zone/galileo).
- [x] Make GitHub release object and include the announcement
- [x] Make the announcement to Discord! 🎉🎉🎉

**Comment by conorsch** [comment]
Pushed target release date 2023-05-08 -> 2023-05-10, to tackle some changes to the DEX engine.

**Comment by conorsch** [comment]
New schedule for release of 52 is 2023-05-15, now that the DEX functionality is stabilizing.

**Comment by hdevalence** [comment]
Identifying https://github.com/penumbra-zone/penumbra/issues/2560 as a release blocker.

**Comment by hdevalence** [comment]
Looking at the project board, looks like the outstanding issues/PRs are:

- [ ] #2557 
- [ ] #2550 
- [ ] #2545 
- [ ] #2544 
- [ ] #2539 / #1779

**Comment by conorsch** [comment]
Announced this morning!
