### ISSUE TITLE
Change `penumbra_proto::DomainType` to add a `TypeUrl` bound

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2419]
**Is your feature request related to a problem? Please describe.**

It's useful to be able to convert proto types to and from `Any` types (the proto `Any`, which requires a type URL).

To allow this to happen programmatically, we need to record the protobuf type url somehow.

**Describe the solution you'd like**

Add a `TypeUrl` trait to the proto crate:
```rust
pub trait TypeUrl {
    const TYPE_URL: &'static str;
}
```
Then, change the `DomainType` trait bounds to add `Self: TypeUrl`, and go through every domain type to fill in the missing type URLs.

**Comment by phasewalk1** [comment]
I'd like to take this up if no one else is. Just for clarification, by "fill in the missing type URLs" we are implementing the `TypeUrl` trait for each `DomainType`? i.e., `impl TypeUrl for decaf377_rdsa::Signature<SpendAuth>` where the `TYPE_URL` attribute is hard-coded?
```Rust
impl TypeUrl for decaf377_rdsa::Signature<SpendAuth> {
    const TYPE_URL: &'static str = "gen/penumbra.core.crypto.v1alpha1.SpendAuthSignature";
}
impl TypeUrl for decaf377_rdsa::Signature<Binding> {
    const TYPE_URL: &'static str = "gen/penumbra.core.crypto.v1alpha1.BindingSignature";
}
...
```
If these assumptions hold, is `gen` an appropriate prefix here?

**Comment by hdevalence** [comment]
Sure! One thing to note is that although it's a fairly mechanical change, there are a lot of implementations to update, and because it's a wide-ranging change, it would conflict with any big refactors. So if you start on it, it'd be helpful to create a draft PR and keep it up to date as you go.  That way, if we need to rearrange code while the PR is still outstanding, it'd be possible for us to pick up the draft state and carry it over the finish line.

The type URL is rooted in the protobuf package, rather than `gen`; you can see an example here: https://github.com/penumbra-zone/ibc-types/blob/main/crates/ibc-types-core-client/src/msgs/create_client.rs#LL21C46-L21C46

**Comment by phasewalk1** [comment]
Cool, I'll try and open a working draft PR in the next couple of hours. I'm thinking to place the implementations alongside the corresponding foreign `DomainType` impl's here https://github.com/penumbra-zone/penumbra/blob/main/proto/src/protobuf.rs.

**Comment by hdevalence** [comment]
Sounds good, the `impl TypeUrl` should probably go next to the `impl DomainType`.  That way if/when we move the `DomainType` impl around, we can carry the `impl TypeUrl` with them.

**Comment by phasewalk1** [comment]
Was thinking the same, will do!

**Comment by phasewalk1** [comment]
my apologies, accidentally dirtied the first one with a bad rebase >.<

**Comment by phasewalk1** [comment]
should be good to go here

**Comment by redshiftzero** [comment]
Completed
