### ISSUE TITLE
asset metadata: use base denom for calculations, display denom for UI

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#244]
In  #178 we decided how to track the base denomination, implemented in #283. 

We should decide how we want to use the asset metadata on the client-side. Suggestion:
* `BaseDenom`  is used for calculations, e.g. value balance
* any `DisplayDenom`  is used for displaying assets in the UI

**Comment by hdevalence** [comment]
I think a good pathway to doing this would be:

- [ ] #292
- [ ] #293 
- [ ] #294 (really about how to specify values using display denoms, sending multiple values is a happy enhancement)
- [ ] #295
