### ISSUE TITLE
protocol docs links are wrong in sidebar

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2514]
The links in the left hand sidebar on https://protocol.penumbra.zone/main/index.html seem to be incorrect in the rendered documentation. However, when I build the docs locally, the links in the sidebar are correct. Something is going wrong in the build CI process possibly?

The [SUMMARY.md file](https://raw.githubusercontent.com/penumbra-zone/penumbra/main/docs/protocol/src/SUMMARY.md) is what the left hand sidebar is generated from. As one example, it links the section "Cryptographic Protocol" to a file called "protocol.md", but instead in the rendered documentation it links to an unrelated page of docs, about "Undelegate claims": https://protocol.penumbra.zone/main/protocol.html

**Comment by conorsch** [comment]
For the record, I was able to reproduce the buggy behavior locally, using mdbook `v0.4.28`. After fixing an empty URL in the navbar, the docs rendered locally, and now that they're live on line, I can't find a single broken link. Please reopen if you notice any strange behavior!
