### ISSUE TITLE
add ZK proof of correct nullifier derivation

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2517]
Suggested by @hdevalence intended for the `TransactionView`: The transaction view will have nullifiers indexed by spends.  We should add a ZKP that has:
* the note, nullifier, and position as public inputs,
* the nullifier derivation key as a private witness,
* and it demonstrates that the nullifier was derived correctly given those values

**Comment by hdevalence** [comment]
It'd be great to know how expensive proving is. Ideally it could be cheap enough that we could bundle these into every TxP every time we generate one. Otherwise, we'd want the relevant RPCs to have a "prove: bool" option and make the spend view proofs optional in the TxP (cc @aubrika)

**Comment by redshiftzero** [comment]
Per my comment [here](https://github.com/penumbra-zone/penumbra/pull/2526#issue-1704276658), this proof currently takes about 0.1s to generate on my M1 Macbook pro
