### ISSUE TITLE
Implement `Serialize`, `Deserialize` for `Address`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#255]
We should implement `Serialize`, `Deserialize` for `Address`, so that we don't need annotations on any struct using them that wants to use Serde.  The `Serialize` and `Deserialize` impls should convert to/from strings using `Display`/`FromStr`.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/248#discussion_r766153933_

**Comment by redshiftzero** [comment]
Closed by #258
