### ISSUE TITLE
Deprecate `Asset` now that we have `DenomMetadata`

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2577]
What's the point of the `Asset` proto message, now that we have `DenomMetadata` ?

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/2520#discussion_r1194573570_

Ticket for tracking consolidation of these protos/structs following merging in the `DenomMetadata` changes in #2520.

**Comment by hdevalence** [comment]
The `Asset` proto is used in the `AssetInfo` RPC: https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.client.v1alpha1#penumbra.client.v1alpha1.SpecificQueryService.AssetInfo

This method only returns the bare `Denom`. Instead, it should be renamed to `DenomMetadataById` and return a `DenomMetadata`.
