### ISSUE TITLE
Document format for entering pairs for dex operations in `pcli`

### ISSUE THREAD

**Issue by voteblake** [penumbra-zone/penumbra#2640]
**Is your feature request related to a problem? Please describe.**
When querying my opened RMM positions for the first time using `pcli` I was prompted for `TRADING_PAIR` with no additional context on how to express the pair for the command. I found in the source code that the `FromStr` implementation splits using a colon and was able to run the command successfully. A review of the Discord found I was not the first person to [run into this](https://discord.com/channels/824484045370818580/1082420866438156418/1108192776010600529).

```bash
$ cargo run --bin pcli -- q dex positions --help

pcli-query-dex-positions 
Display open liquidity for a given pair, sorted by effective price

USAGE:
    pcli query dex positions [OPTIONS] <TRADING_PAIR>

ARGS:
    <TRADING_PAIR>    The trading pair to query, with ordering determining direction of trade
                      (1=>2)

OPTIONS:
    -h, --help             Print help information
        --limit <LIMIT>    A limit on the number of positions to display
```

**Describe the solution you'd like**
For operations involving `TradingPair`, `DirectedTradingPair`, or `DirectedUnitPair`'s in `pcli` the help output generated on the command line should indicate the format. 

**Describe alternatives you've considered**
There are two implementation alternatives I've considered, and am happy to submit a pull request for either (or another option entirely) based on the project's preference:

1. Set `clap` `value_name` for the subcommand argument, altering the name of the argument shown in the help output to show the input format expected:

Code change:
```rust
#[derive(Debug, clap::Subcommand)]
pub enum DexCmd {
...
    /// Display open liquidity for a given pair, sorted by effective price.
    Positions {
        /// The trading pair to query, with ordering determining direction of trade (1=>2).
        #[clap(value_name = "asset_1:asset_2")]
        trading_pair: DirectedTradingPair,
        /// A limit on the number of positions to display.
        #[clap(long)]
        limit: Option<u64>,
    },
}
```

Ex. Output:

```bash
$ cargo run --bin pcli -- q dex positions --help

pcli-query-dex-positions 
Display open liquidity for a given pair, sorted by effective price

USAGE:
    pcli query dex positions [OPTIONS] <asset_1:asset_2>

ARGS:
    <asset_1:asset_2>    The trading pair to query, with ordering determining direction of trade
                         (1=>2)

OPTIONS:
    -h, --help             Print help information
        --limit <LIMIT>    A limit on the number of positions to display
```

2. Add some explanation to the argument doc comment, which will also be included in the `pcli` help output. The main downside to this is that the help text is only shown with the `--help` flag, not on output with an error entering the pair, which is when a user may most need this guidance.

Ex. Help Output:

```bash
$ cargo run --bin pcli -- q dex positions --help

pcli-query-dex-positions 
Display open liquidity for a given pair, sorted by effective price

USAGE:
    pcli query dex positions [OPTIONS] <TRADING_PAIR>

ARGS:
    <TRADING_PAIR>    The trading pair to query, with ordering determining direction of trade
                      (1=>2). Pairs are entered as two comma separated asset IDs, for example
                      penumbra:test_usd.

OPTIONS:
    -h, --help             Print help information
        --limit <LIMIT>    A limit on the number of positions to display
```

Ex. Error Output:
```bash
$ cargo run --bin pcli -- q dex positions penumbra test_usd

error: Found argument 'test_usd' which wasn't expected, or isn't valid in this context

USAGE:
    pcli query dex positions [OPTIONS] <TRADING_PAIR>

For more information try --help
```
**Additional context**

**Comment by conorsch** [comment]
Great idea. Thanks for the super clear description and examples!
