### ISSUE TITLE
Release testnet 54: Europa

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2642]
# Testnet Release

Testnet name: Europa
Release date: June 12, 2023
Testnet release manager: @redshiftzero 

# Testnet Release Manager Checklist

Preceding Friday (sprint planning day):

- [x] Create GitHub project column, work with team to populate the milestone with tickets targeted for the release.

Tuesday (or after release of previous testnet):

- [x] Construct the genesis data for the release:
  - [x] Create new testnet directory with initial genesis allocations for this testnet by running `cd testnets && ./new-testnet.sh`
    - This genesis data will be used for `testnet-preview` with a randomized version of the future testnet's chain ID.

Thursday:

- [x] Check in with team again in a release meeting and update the GitHub milestone to ensure it represents what will make it into the testnet.
- [x] Draft an announcement for peer review to ensure major changes included are comprehensive.

Following Monday (release day):

- [x] Verify that `testnet-preview.penumbra.zone` is operational; it is redeployed on every push to main, and is an exact preview of what is about to be deployed.
- [x] Bump the version number and push its tag, via [cargo-release](https://crates.io/crates/cargo-release).
    - [x] Run `cargo release minor` for a new testnet, or `cargo release patch` for a bugfix. For the latter, make sure you're on a dedicated release branch.
    - [x] Push the commit and newly generated tag, e.g. `v0.51.0`, to the remote.
- [x] Wait for the "Release" workflow to complete: it'll take ~90m, most of which is the macOS builds.
- [x] Edit the newly created (and published) release object, then click "Generate release notes." Cut and paste the generated text from the bottom to the top of the post, then save it.
- [x] You must [manually review](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) the `Waiting` deployment in the GitHub Action UI before the deployment will begin. Monitor the GitHub action to ensure it completes after it is approved.
- [x] Delegate to the Penumbra Labs CI validators; use amounts of ~200k `penumbra` per validator.
- [x] Update the User Guide to mention the newly created git tag.
- [x] Update Galileo deployment, [following docs](https://github.com/penumbra-zone/galileo).
- [x] Make GitHub release object and include the announcement
- [x] Make the announcement to Discord! 🎉🎉🎉

**Comment by conorsch** [comment]
See comment in https://github.com/penumbra-zone/penumbra/issues/2586#issuecomment-1582858590. We decided today to move up the release of Testnet 54, so we have a working chain for folks to interact with. Rather than releasing on Monday, we'll ship what we have on main today, 2023-06-08.

**Comment by conorsch** [comment]
Update: postponing announcement until we pull in https://github.com/penumbra-zone/penumbra/pull/2698 and tag as v0.54.1.

**Comment by redshiftzero** [comment]
Since Europa was released early by @conorsch, opened #2700 to track the next regular release (55).
