### ISSUE TITLE
Avoid generating a merkle proof if a `KeyValue` request doesn't ask for it

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2647]
**Is your feature request related to a problem? Please describe.**
Once #2628 lands, we will be able to retrieve JMT values directly from storage, circumventing the need to traverse the tree entirely. However, whenever a `KeyValue` request is received, we default to generating a (non-)inclusion proof and dropping it after the fact if it wasn't needed.

**Describe the solution you'd like**
To fully take advantage of segmenting values from the tree structure, we should make sure that we do not generate a (non-)inclusion proof when a `KeyValueRequest` specify that it doesn't need it. The solution should take advantage of `TreeReader::get_value_option`.

**Comment by hdevalence** [comment]
Since we don't use the KeyValueRequest much — AFAIK, the only current use is in the relayer, which does generate proofs — this feels like it could be something we backburner and get to at some point in the future.

**Comment by zbuc** [comment]
@hdevalence is this still true:

> Since we don't use the KeyValueRequest much — AFAIK, the only current use is in the relayer, which does generate proofs — this feels like it could be something we backburner and get to at some point in the future.

I don't see any references to either `KeyValueRequest` or `cnidarium` in the Hermes code

**Comment by zbuc** [comment]
> I'm not sure, but seems like it, then? How does Hermes fetch inclusion proofs for packets or client updates?

It seems to be handled via the IBC RPCs rather than cnidarium RPCs. The IBC RPC implementations call `Snapshot::get_with_proof` directly and `KeyValueRequest` never enters the picture AFAICT
