### ISSUE TITLE
Change Docker setup to support `genesis.json` and/or `priv_validator_key.json`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#267]
Despite the instructions in the README, it's not currently possible to use the Docker setup to run a Penumbra node, since the workflow doesn't provide a way to specify the `genesis.json` & `priv_validator_key.json` that the node should use.

I think the cleanest way to fix this would be to specify a directory on the host machine that would be used as the `$TMHOME/config` directory for the Tendermint container. Then, the `genesis.json` and `priv_validator_key.json` files for a local testnet can be placed in that directory and be picked up by Docker.

**Comment by hdevalence** [comment]
One remaining question is how to handle initialization. Our `create-genesis-template` produces something that's supposed to be edited into the `app_state` key of an existing `genesis.json` file, and for making a single-node testnet, the easiest thing is to use the auto-generated validator key. If we connect a host directory to `$TMHOME/config`, can we run something that will just start the Tendermint docker image and run `tendermint init validator`, so that those files are generated and written back to the host directory, without starting all of the services before they've been validly configured?

**Comment by zbuc** [comment]
> can we run something that will just start the Tendermint docker image and run tendermint init validator, so that those files are generated and written back to the host directory, without starting all of the services before they've been validly configured?

 This is similar to what the Tendermint Makefile does for multi-node testnet setup -- though they use a special `tendermint/localnode` Docker image's `testnet` command to generate everything: https://github.com/tendermint/tendermint/blob/master/Makefile#L249

**Comment by zbuc** [comment]
Here's the implementation of the `testnet` command in Tendermint, I think we can probably make use of it: https://github.com/tendermint/tendermint/blob/93eb940dcdc37e959f054479e9741c190bd4ca6c/cmd/tendermint/commands/testnet.go#L44

It looks like it will handle generating the keys and base config files. I'll dig in and see how to integrate it in our process.

**Comment by zbuc** [comment]
Running the default `testnet` command results in the following directory structure (from an empty directory structure):

```
build
├── config
│   ├── config.toml
│   ├── genesis.json
│   ├── node_key.json
│   └── priv_validator_key.json
├── config-template.toml
├── data
│   └── priv_validator_state.json
├── node0
│   ├── config
│   │   ├── config.toml
│   │   ├── genesis.json
│   │   ├── node_key.json
│   │   └── priv_validator_key.json
│   └── data
│       └── priv_validator_state.json
├── node1
│   ├── config
│   │   ├── config.toml
│   │   ├── genesis.json
│   │   ├── node_key.json
│   │   └── priv_validator_key.json
│   └── data
│       └── priv_validator_state.json
├── node2
│   ├── config
│   │   ├── config.toml
│   │   ├── genesis.json
│   │   ├── node_key.json
│   │   └── priv_validator_key.json
│   └── data
│       └── priv_validator_state.json
├── node3
│   ├── config
│   │   ├── config.toml
│   │   ├── genesis.json
│   │   ├── node_key.json
│   │   └── priv_validator_key.json
│   └── data
│       └── priv_validator_state.json
└── tendermint
```

Their design is that you run the `testnet` command to generate the above files, and then the `node[0-3]` configs from https://github.com/tendermint/tendermint/blob/master/docker-compose.yml will point at the generated files. I think our setup just needs to integrate the `create-genesis-template` step post-`testnet` and modify the docker-compose to point to the persistent files stored on the host.
