### ISSUE TITLE
`GetBlockByHeight` request does not work in GRPCUI

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2673]
**Describe the bug**

The `TendermintProxyService.GetBlockByHeight` request does not work or return an error. The network console reports something about a wrong timestamp.

<img width="563" alt="Screen Shot 2023-06-04 at 1 48 10 PM" src="https://github.com/penumbra-zone/penumbra/assets/44879/d0cb2d2f-493a-4928-a72c-5f85aed0a7c5">

**Comment by conorsch** [comment]
I'll take a look at this one. Not sure if it's a proto/RPC problem, or a grpcui problem. FYI, we're using an old version of grpcui. We'd have to build our own container to get a newer version. Will test locally.

**Comment by conorsch** [comment]
Took a look at this today. Even with a locally-built extremely recent version of grpcui, the problem persists. The browser console emits an error about an undefined JS error that is the result of a legitimate bug in the grpcui JS. That's beside the point for our needs, though. Will try to make sense of the actual method call and its parameters next.

**Comment by conorsch** [comment]
Progress: looks like it's the `nanoseconds` field in the constructed Block that's causing the error. What's puzzling is that we cast the nanos as an `i32`, which the type constraints like, but there's an artificial limit imposed on the nano seconds field that's lower than i32:

```
>>> 1033892547 / 1000000000 
1.033892547
>>> 1033892547 / 2**32
0.24072186718694866
>>> 
```

The `1033892547` value above was taken from ad-hoc debug logs during the Block construction in the `get_block_by_height` method. Next I'll try to isolate where that max value 1000000000 is coming from.

**Comment by conorsch** [comment]
> Next I'll try to isolate where that max value 1000000000 is coming from.

That value limit is 1 billion, or the maximum number of nanoseconds _within one second_. The error message is coming from `golang/protobuf`: https://github.com/golang/protobuf/blob/5d5e8c018a13017f9d5b8bf4fad64aaa42a87308/jsonpb/encode.go#L177-L179. In that part of the rust code, we're calling [`DateTime::timestamp_nanos`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timestamp_nanos), but I think we actually want [`DateTime::timestamp_subsec_nanos`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timestamp_subsec_nanos).
