### ISSUE TITLE
Re-allow consecutively routing over the same route twice

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2676]
**Is your feature request related to a problem? Please describe.**
As part of our quickfix (#2667) for the arbitrage loop bug (#2675) , we started discard macro-routes that had been just previously used. This was an acceptable tradeoff to unstuck testnet 53, but is generally a speaking an undesirable regression.

**Describe the solution you'd like**
A stable solution to the arbitrage loop bug that doesn't discard the best route if it had just previously been routed over.

**Describe alternatives you've considered**
Instead of fixing it, we could leave it as it is, even if it makes routing worse. We shouldn't do that.

**Comment by hdevalence** [comment]
> This was an acceptable tradeoff to unstuck testnet 53, but is generally a speaking an undesirable regression.

I'm not sure this is true -- we don't ever want to use the same macro-route twice, because once we fill along a macro-route, we expect that we've consumed up to its spill price, so if the estimation was good, it should no longer be the best route.
