### ISSUE TITLE
Restore support for ETH assets

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2677]
**Is your feature request related to a problem? Please describe.**
We uncovered a fixpoint bug (#2559) which we temporarily routed around by temporarily limiting DEX values to be at most $2^{60}$ bits wide. So that $k = p R_1 + q R_2$ is at most $\log_2(2*(2^{60} -1)^2) = 121$ bits fitting in a $128$ bits with some headroom.

**Describe the solution you'd like**
The above solution works as a temporary bandaid, but limits our ability to support assets with larger denom units such as ETH and ERC-20s, which we definitely want to be supporting. Instead of limiting values, we should incorporate finding a working solution as part of #2589.

**Comment by conorsch** [comment]
@erwanor Thoughts on inclusion in 55? I see there's some other high-priority DEX work still in flight. Please provide an update async when you can.

**Comment by erwanor** [comment]
Moving this to 57, because although this is a small change in terms of LoC, it will require more thorough quality assurance work than time allows for now. In particular, we want to test that error recovery implemented in #2740 works well in the case of complex multi-hop routes. This requires somewhat involved assurance work which I hadn't fully realized during planning.

**Comment by zbuc** [comment]
After this is complete we should also (in a separate issue) re-enable ETH in Osiris and allocate some ETH to the Osiris wallet.
