### ISSUE TITLE
Replace the asset registry with the asset cache

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2682]
The current asset registry code does not presently fit our purposes, so a new design is proposed to extend the asset cache code to encompass its existing functionality and break out the logic for parsing and categorization of candidate denom strings into the respective target refinement types such as `DelegationToken`.

As it stands, the registry dynamically builds metadata for various assets, while the cache is a list of a specific number of enumerated assets. In replacing the asset registry, we want to fill the capability gap in the cache by adding something like a `try_populate` function to the cache, which can try to interpret a denom string as representing one of various asset families.

The asset cache should ultimately include a default list of known individual assets alongside this `try_populate` functionality, which will dynamically add in a specific instance of one of these families of assets (e.g. `DelegationToken` which names a family of many potential individual delegation tokens).

This will require:

- [ ] Adding `try_parse` methods for each relevant token family to check if a provided denom string is of that type.
- [ ] Adding a `try_populate` method to the asset cache to utilize the above parsing methods to identify denom strings when encountered.
- [ ] Pre-populating a list of known assets for the cache for the view service.
- [ ] Once this functionality is added to the relevant types and the asset cache, refactoring accordingly to replace the existing registry wherever it is being used.

Previous research into registry replacement revealed calls to `registry::parse_denom` throughout the codebase, with high variable ease of replacement. The existing `default_for` functionality will drop in nicely in some cases, but other cases will require the more detailed functionality described above to avoid breaking any existing functionality.

**Comment by hdevalence** [comment]
I think we won't be able to have the `try_populate` method on the asset cache call the `try_parse` methods for each token family, because the token families are (or should be) defined in other, higher-level crates (e.g., delegation tokens are defined in the staking crate) that depend on the asset cache.  Solving this would either require building a dependency injection system, or just duplicating the metadata construction functions, which seems simpler and cleaner.

Relatedly, we could consider splitting out a `penumbra-asset` crate in `crates/core/asset` that would have asset-related functionality, and which the shielded pool and other crates could depend on.

**Comment by aubrika** [comment]
Duplicating the metadata construction functions sounds like the path of least resistance here, but I have a few questions along these lines:

1. What is the alternative to having a `penumbra-asset` crate in terms of dependency management here? `DenomMetadata` currently lives in `core/crypto`, but could just as well live in `core/asset` as you describe.
2. Regarding token families, should we try to canonize these inside of an enum somewhere, so we have a nice list of available categories to try to parse into? What should this enum certainly vs. potentially contain?

**Comment by aubrika** [comment]
Rescoping: rather than tackling the entire replacement at once, implement a `with_known_assets` function on the asset::cache to replace only those instances of using the registry to parse _known_ assets/raw denoms with cache lookups. Refactor the initial `REGISTRY` population using `Inner::new` to utilize the `DenomMetadata` struct that didn't exist when the registry was built. Spin off second issue to address the case of unknown assets/raw denom strings with a better sense of scope and context, by separating the known asset behavior from the novel asset behavior.
