### ISSUE TITLE
Add AuthorizeAndBuild rpc to the view service

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2726]
This is meant to allow the view server to perform proving concurrently with authorization. It will require the view server to be connected to an auth mechanism, so the rust view server can respond with `unimplemented`.

**Comment by conorsch** [comment]
Some context on motivation from sprint planning today: Right now we have a four-step process for building a transaction. That's needlessly complicated for e.g. the web extension. What we want instead is a one-shot method for those four steps, exposed as an RPC service. This'll allow for the web extension to begin proving while the UI is still displaying a confirmation dialog, prior to submission of the transaction. More concurrency, more responsive UI.

**Comment by aubrika** [comment]
Note: the purpose of this is to make it possible for an implementation to perform these steps concurrently without actually requiring that it currently do anything. If client code uses this method, the implementation can be upgraded to perform concurrent proving and authorization without changing the interface.
