### ISSUE TITLE
Newer versions of protoc don't regenerate proto descriptor

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2736]
As part of the proto codegen process, we use `protoc` via `tools/proto-compiler`. Our dev docs currently say:

>  After installing, run protoc --version and confirm you’re running at least 3.21.8 (or newer). Don’t install protoc from package managers such as apt, as those versions are often outdated, and will not work with Penumbra.

Current version of `protoc` is [v23.3](https://github.com/protocolbuffers/protobuf/releases/tag/v23.3). If that sounds astonishingly newer than v3.21, you are correct. Looks like the project jumped from v3 to v20 last year:

```
❯ curl -s https://api.github.com/repos/protocolbuffers/protobuf/releases | jq '.[] | .tag_name + " " + .published_at' -r
v23.3 2023-06-14T19:22:45Z
v23.2 2023-05-26T16:43:43Z
v23.1 2023-05-17T17:28:25Z
v22.5 2023-05-10T03:56:57Z
v23.0 2023-05-08T18:31:51Z
v23.0-rc3 2023-05-05T17:20:25Z
v22.4 2023-05-04T20:35:56Z
v23.0-rc2 2023-04-28T18:59:14Z
v23.0-rc1 2023-04-26T23:16:56Z
v22.3 2023-04-12T23:47:13Z
v22.2 2023-03-10T18:35:01Z
v22.1 2023-03-07T22:31:27Z
v22.0 2023-02-16T18:17:29Z
v22.0-rc3 2023-02-10T20:17:58Z
v22.0-rc2 2023-02-02T21:18:01Z
v22.0-rc1 2023-01-31T18:24:35Z
v21.12 2022-12-14T14:45:50Z
v21.11 2022-12-08T06:34:59Z
v21.10 2022-11-30T19:15:02Z
v21.9 2022-10-26T20:28:55Z
v21.8 2022-10-18T18:18:56Z
v21.7 2022-09-29T22:22:53Z
v3.20.3 2022-09-29T21:22:59Z
v3.19.6 2022-09-29T20:46:59Z
v3.16.3 2022-09-29T22:17:28Z
v21.6 2022-09-14T21:37:03Z
v3.20.2 2022-09-14T18:05:45Z
v3.19.5 2022-09-14T21:36:20Z
v3.18.3 2022-09-14T21:02:42Z
v21.5 2022-08-09T19:53:44Z
```

Some more info here https://protobuf.dev/support/version-support/ . For our purposes, we need to document an explicit version for protoc, and check for that in the proto compiler tool, otherwise we get very strange and hard to debug errors.

For our docs, we're linking to https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os , which appears badly out of date, given that it still recommends `v3.15.8` in its example. Better would be to link out to https://protobuf.dev/downloads/ .

**Comment by conorsch** [comment]
Ah, this isn't so bad: the problem isn't that the descriptor file isn't been regenerated, it's just that different major versions of `protoc` emit slightly different binary blobs. I'll update the tooling and docs to use the current latest version (`23.3`) and add a reminder message to the proto-compiler tool.

**Comment by hdevalence** [comment]
I think the problem isn't just about different major versions, but that the descriptor output isn't stable even within the same version. In a previous iteration of the CI tooling we ignored changes that only affected the descriptor, with the assumption that if there were "real" changes, they'd be caught by changes to the generated files (and that any generation would update the descriptor).

**Comment by conorsch** [comment]
> that the descriptor output isn't stable even within the same version

The descriptor output _is_ stable within the same version! That's the point of the changes in #2739: if the same version is used, then we can expect the output to be fully deterministic.

> In a previous iteration of the CI tooling we ignored changes that only affected the descriptor

My current understanding is that we did this because we couldn't explain why we were seeing flapping: now I'm certain it's because different version of `protoc` were used locally and in CI. We can still ignore the flapping on that particular file, of course, but if we're using different tooling versions then we're likely going to experience flapping elsewhere in the generated artifacts, e.g. https://github.com/penumbra-zone/penumbra/pull/2739/files#diff-4c7f8084527df765ac0133b6828891e9b82fb03557bacf323960235942b56c3aR3 So my preference would be to ride out this latest set of changes, but very open to different opinions!

**Comment by conorsch** [comment]
After some [discussion in Discord](https://discord.com/channels/824484045370818580/883455571003576320/1123119972646916128), we decided that it's fine to let the protos flap a bit, if it prevents us from requiring specific versions of tooling locally. To reduce developer friction, we'll disable the persnickety CI check that ensures the codegen is byte-for-byte identical, and lean on visual review to ensure the protos have been updated accordingly.
