### ISSUE TITLE
docs: explain how to reset the web wallet

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2747]
We have starter docs on using the web wallet here: https://guide.penumbra.zone/main/extension.html Let's also add an explanation about what to do if one forgets one's passphrase. Basically, the only option is to uninstall and reinstall. That's fine as long as you have your seed phrase. Let's spell that out clearly, so that the extension/dapp can link out to our docs as an explainer for the "Forgot your passphrase?" use case.

**Comment by conorsch** [comment]
This should be fairly quick :crossed_fingers: , I'll pick it up for 61.

**Comment by conorsch** [comment]
Still undone. Holding for now, since the web wallet is undergoing a rewrite and UX overhaul. That work should ship in 63 Rhea (#3182), or else 64 at the latest. We should return to this ticket as part of that push.

**Comment by hdevalence** [comment]
Unclear that the need for this has persisted through the rewrite.
