### ISSUE TITLE
Implement integration tests for staking and slashing mechanics

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2754]
Currently no integration tests exist for the staking and slashing mechanics, resulting in a low degree of assurance when we are making changes and requiring more manual testing.

While implementing https://github.com/penumbra-zone/penumbra/issues/2630 this shortcoming was noted, since the slashing mechanics are somewhat complicated it would be great to get some tests in place for the expected behavior.

The tests should use the existing `MockClient`-style integration testing.

**Comment by conorsch** [comment]
Turns out this is pretty complicated in terms of implementation. Let's step back and focus on writing a mock client for tendermint, which will make writing adequate tests much easier. That's tracked in #2771. Reprioritizing accordingly.

**Comment by hdevalence** [comment]
These tests will be easy to write following https://github.com/penumbra-zone/penumbra/issues/3588#issuecomment-1930965418

**Comment by aubrika** [comment]
Closed as duplicate
