### ISSUE TITLE
Rename "nonconsensus" store to "nonverifiable" store

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2772]
**Is your feature request related to a problem? Please describe.**

Penumbra's storage system gives the application access to one K/V store recorded by the JMT and verifiable from the consensus-chosen state root, and another K/V store recorded in an ordinary RocksDB table that is not verifiable.

Currently, we call the latter store the "nonconsensus" store, but this is a misnomer, as the data may actually be consensus-critical. Instead it should be called "nonverifiable" to better reflect its role.

cc @noot (this would be a trivial but breaking API change)

**Comment by noot** [comment]
@hdevalence this sounds fine to me - we haven't started using the "nonconsensus" store much yet, so should be fine to change from our side :)
