### ISSUE TITLE
Change `ValueView` to have a `DenomMetadata` rather than just a bare denom string.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2783]
**Is your feature request related to a problem? Please describe.**

The point of the `ValueView`, and the view structures generally, is to provide a pre-parsed structure that doesn't require additional information to interpret.  But currently the `ValueView` shows at most a denom string, not the full denom metadata, making it not at all useful for that purpose, e.g.,

https://github.com/penumbra-zone/penumbra_dapp/blob/main/src/components/penumbra/view/SpendView.tsx#L18-L27

**Describe the solution you'd like**
Change the protos to have the full `DenomMetadata` when the denom is known.

**Comment by aubrika** [comment]
So, this may have been true at the time of the linked comment in the `penumbra_dapp` code, but this has since been fixed by the comprehensive `DenomMetadata` refactor & can be taken into account in `SpendView.tsx`
