### ISSUE TITLE
Stateless TxP/TxV generation for wasm code

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2785]
**Is your feature request related to a problem? Please describe.**

The browser extension needs to generate TxPs and TxVs in wasm'd Rust code, but that code doesn't have direct access to the state.  This is the cause of some visibility bugs in the current implementation. Transactions, even those created by the user, are being marked as "opaque", indicating that the extension is not be properly populating the TxP/TxVs.

Upon examining the Typescript and penumbra-wasm code, we have identified potential root causes related to how the extension fetches transactions and the data it passes to the Rust view server. Specifically, the problem seems to lie with the `ViewServer` object not being initialized with every single note and nullifier ever seen, and hence it fails to find the necessary notes for TxP population.

The method in question can be found at: [transaction_info](https://github.com/penumbra-zone/wallet/blob/main/src/utils/WasmViewConnector.ts#L350) in WasmViewConnector.ts, which is defined in [view_server.rs](https://github.com/penumbra-zone/penumbra/blob/main/crates/wasm/src/view_server.rs#L385) and calls into [transaction_info_inner](https://github.com/penumbra-zone/penumbra/blob/main/crates/wasm/src/view_server.rs#L416), which in turn ports the logic for the Rust view server.

To fix this, we need to restructure the TxP/TxV generation so that it is stateless -- or rather, is an explicit state machine, where explicit context structures feed necessary data in at each step.

**Comment by Valentine1898** [comment]
I don't seem to have been able to properly associate this issue to PR https://github.com/penumbra-zone/penumbra/pull/2787
