### ISSUE TITLE
Remove "next rates" APIs

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2802]
In https://github.com/penumbra-zone/penumbra/issues/2630 we added and began using the current epoch's staking rates in the node and client, however the APIs for fetching the next epoch rates remained in place. This is an issue because they can no longer be predicted accurately; the API should be removed entirely.

**Comment by conorsch** [comment]
WIP exists in #2909. We're deprioritizing from Testnet 62, but we'll need this work to be rebased and then land for distributions work.
