### ISSUE TITLE
Staking protocol docs are stale

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2807]
Needs to be updated:

- [ ] There is no unbonding queue
- [ ] The delegation rate is computed based on the start of the current epoch, as is the undelegation rate
- [ ] The docs state that flow encryption is used, when it is not going to be used until after mainnet

**Comment by hdevalence** [comment]
@erwanor you recently talked about wanting to work on this, can this be closed as a dup of another issue you've filed more recently?

**Comment by hdevalence** [comment]
dupe of https://github.com/penumbra-zone/penumbra/issues/3637
