### ISSUE TITLE
Denom metadata changes must land in wasm crate

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2825]
We recently added DenomMetadata to Transactions #2310, but recently the Zpoken team mentioned they don't have access to that info. We suspect we forgot to update the `wasm` crate to use the new setup. Common mistake: we've been depending on Zpoken to update the WASM ad-hoc, but we should aim to update that crate in tandem with other changes.

**Comment by conorsch** [comment]
Aiming to land this in Testnet 57.

**Comment by aubrika** [comment]
Closed by #2787
