### ISSUE TITLE
Support Raspberry Pi 4 architecture 

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2857]
**Is your feature request related to a problem? Please describe.**
It'd be nice to support folks running nodes on Raspberry Pis, given how few resources are needed to run a node. Currently, our docker containers don't work on Raspberry Pis:

```
❯ sudo lshw -class system | grep -v serial
hattusa                     
    description: Computer
    product: Raspberry Pi 4 Model B Rev 1.5
    width: 64 bits
    capabilities: smp cp15_barrier setend swp tagged_addr_disabled
❯ uname -m
aarch64
❯ docker run -it --entrypoint sh ghcr.io/penumbra-zone/penumbra:v0.56.0 echo hello
exec /bin/sh: exec format error
```

**Describe the solution you'd like**
We could adjust the container build, or add a new target to the precompiled release binaries. At the very least, we should builds from source on RPi4s and confirm that works OK.

**Describe alternatives you've considered**
Our options for RPi support seem to be:

1. container images
2. precompiled release binaries
3. from-source target compilation

At least 3 _should_ work out of the box, but I don't believe anyone has tested it. Once that's in place, then one of either 1 or 2 would be nice-to-have.

**Additional context**
This isn't high-priority work. The existing container build logic is rather verbose, and could be trimmed down substantially to make it easier to work with.

**Comment by hdevalence** [comment]
I don't think we should plan to do this; if someone is interested they're free to submit a PR, though.
