### ISSUE TITLE
New Balances RPC request returns empty results

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2894]
**Describe the bug**
The new (as of https://github.com/penumbra-zone/penumbra/pull/2799) RPC method [`penumbra.view.v1alpha1.BalancesRequest`](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.BalancesRequest) returns empty responses, regardless of request params. 

**To Reproduce**

1. Configure and run `pclientd` locally. 
2. Run [grpcui](https://github.com/fullstorydev/grpcui) locally: `grpcui -plaintext localhost:8081`
3. Navigate to grpcui web ui, and make a request for `penumbra.view.v1alpha1.BalancesRequest`. 
4. Observe empty results.

**Expected behavior**
I expected to see balance info, meaning denoms and amounts, returned from the query. Instead, I saw nothing at all, which was disappointing. 

**Additional context**
You must run pclientd locally so there's an FVK available to parse response. If you try to use e.g. https://grpcui.testnet.penumbra.zone, the method will return empty, which is expected. (Maybe a custom response error code would be nice for that case.)

**Comment by conorsch** [comment]
This is blocking ongoing IBC integration work in interchaintest, so I'm pulling into Testnet 58.

**Comment by aubrika** [comment]
This is related to (caused by) the query construction issues mentioned in #2879
