### ISSUE TITLE
Update proto documentation around tx_hash encodings

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2905]
> The issue here seems to have been a documentation/API issue, where a mismatch in encodings in pcli (using hex) vs the serde json encodings (using base64) was not documented in the protos, as suggested in comments above - the base64 encoding has since been confirmed to work as designed with the client endpoint, and the proto documentation will be updated accordingly.

_Originally posted by @aubrika in https://github.com/penumbra-zone/penumbra/issues/2844#issuecomment-1668592248_

The protos themselves should be updated to specify the required encoding (base64) for transaction hashes, for ergonomics when using e.g. web interfaces.

It may be helpful for end users to have pcli display base64 transaction hashes by default.

**Comment by hdevalence** [comment]
The rest of the blockchain ecosystem uses hex encoding for transaction hashes, and we should keep to that convention in the UI we create. (We should not change the data encoding in the protos, which should remain a `bytes` field).

**Comment by aubrika** [comment]
Agreed re: keeping encoding the same in the protos, but I think in this case we should do something like note that the existing field is expected by the client as base64 & add an `alt_hex` field as previously suggested, now that we've ruled out any actual encoding issue (other than API documentation clarity) in the pipeline.
