### ISSUE TITLE
Register chain in cosmos registry, osmosis chain registry, etc.

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2914]
https://docs.osmosis.zone/overview/integrate/registration/#how-to-register-an-asset-onto-the-osmosis-assetlists-registry

**Comment by conorsch** [comment]
I'm not aware of any in-flight work on this front, so I'm moving this ticket back to the Next pile. @erwanor please add more detail if I overlooked something!

**Comment by erwanor** [comment]
This was accidentally moved columns due to a silly mobile browser bug.

**Comment by hdevalence** [comment]
Closing as not planned to be subsumed by more recent IBC integration planning.
