### ISSUE TITLE
upgrades: testnet rollover between 60 and a private fork

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2917]
Part of #1804, stub.

**Comment by erwanor** [comment]
This is currently blocked on #2967

**Comment by conorsch** [comment]
We are optimistic about merging https://github.com/penumbra-zone/penumbra/pull/2981 for Testnet 60. Our plan for 60 is not to engage the community validators and require them to participate, but rather to fork the network into a private devnet, and run the upgrade logic there. That will enable us to exercise the upgrade logic for the first time, identify and issues, and target a future testnet (61?) for a community-run upgrade process.

**Comment by erwanor** [comment]
Another item we will want to test during the rollover is whether we confirmation that we can get a tendermint light client to verify across the upgrade boundary. This is an important goal of the upgrade story because it would mean that we do not need to patch penumbra light clients on counterparty chains, unless we deliberately change their client state (e.g. client id).

**Comment by erwanor** [comment]
@conorsch and I were able to test this successfully, here are the ([notes from the test](https://hackmd.io/@U47bTB1sSym1rzNSov3h6Q/SyEz6b5ya)).

During next testnet we want to exercise the updated upgrade flow that completely resets the consensus state and takes advantage of new checkpointed genesis format.
