### ISSUE TITLE
staking: ignore byzantine violations from unregistered validators

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2919]
The function `process_evidence` is called in the staking component's `begin_block` whenever a validator commits a byzantine violation. It attempts to look up the validator in the chain's mapping from tendermint consensus key to validator identity key, and then if this is successful, it tombstones the validator in the penumbra chain state.

https://github.com/penumbra-zone/penumbra/blob/43768e74c1e4a6bd8280dd3faeb487b791b49fc0/crates/core/component/stake/src/component.rs#L859-L867

However, notice above that this method is fallible: if the validator's consensus key cannot be found in the lookup table from consensus key to validator identity, it returns `Err`. This function is called in `begin_block` like so:

https://github.com/penumbra-zone/penumbra/blob/43768e74c1e4a6bd8280dd3faeb487b791b49fc0/crates/core/component/stake/src/component.rs#L941-L945

This `unwrap` means that if a validator commits a byzantine fault while they are not known to the penumbra state, they will trigger a panic on every node, halting the chain. This is possible to do, because being a validator _according to tendermint_ and being a validator _according to penumbra_ are not the same thing: if you configure tendermint to run in validator mode, it will begin to sign blocks before you ever upload a validator definition. If you double-sign a block without ever having uploaded a definition, this will trigger a chain halt.

The solution here is straightforward: ignore byzantine violations from unknown validators in `process_evidence` — it should be infallible. This is sound because a validator that is unknown to the chain cannot have more than zero stake delegated to it, and so cannot be slashed.

**Comment by aubrika** [comment]
@zbuc did your unwrap-related changes already fix this by chance?

**Comment by zbuc** [comment]
> @zbuc did your unwrap-related changes already fix this by chance?

No, the issue still exists
