### ISSUE TITLE
dex: write a general IBC-arbitrage bot

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2930]
**Is your feature request related to a problem? Please describe.**
As part of exercising the DEX + IBC functionalities, it would be good to write an arbitrage bot that interacts with a set of other IBC-enabled testnets and performs mechanical arbs between them. Either through deferred settlement (maintain inventory on all of those chains), or by immediately clearing on Penumbra. The latter would mean being able to confidently estimate latency and transaction costs as part of the arbitrage calculations. 

**Describe the solution you'd like**
Stub for now.

**Comment by hdevalence** [comment]
We should probably backburner this until we figure out how this interacts with IBC packet-forwarding middleware.

**Comment by hdevalence** [comment]
I think we could leave this to the community.
