### ISSUE TITLE
BIP44 support

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2946]
In #419 (corresponding PR #443) we modified the `SpendSeed` generation to be derived deterministically from a `SeedPhrase`, instead of randomly generated. When we did this, we followed [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) which is a standard for generating a seed from a mnemonic phrase. However, for hardware wallet support, we need BIP44 support, which is the default derivation mode [used by Ledger Live](https://developers.ledger.com/docs/coin/address-derivation/). BIP44 is a standard that defines an organizational hierarchy allowing the user to remember a single seed phrase for multiple cryptocurrencies. To support this we need to:

# Add experimental BIP44 support

- [x] Add BIP44 support in `penumbra-keys`, using the [BIP44 path](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) (`m / purpose' / coin_type' / account' / change / address_index`).
- [x] Add it in `pcli` with an optional flag e.g. `--bip44-derivation` to allow for testing
- [x] Add a Penumbra `coin_type` to the list of registered coins: https://github.com/satoshilabs/slips/blob/master/slip-0044.md - in https://github.com/satoshilabs/slips/pull/1592

# Make BIP44 derivation default

- [x] Update documentation in protocol spec
- [x] Determine if changes are needed on the web extension side (one change needed: https://github.com/penumbra-zone/penumbra/blob/f482b485ad265511e2040fa2d9090c5bc04273c7/crates/wasm/src/keys.rs#L16C17-L16C17)
- [x] Make above change to web extension
- [x] Make this BIP44 derivation the default in `pcli` and `pclientd`, and reserve the old BIP39 derivation in `pcli` with an optional flag `--legacy-raw-bip39-derivation`
- [x] Replace test account (and its allocations) with one that uses BIP44 derivation using the seed phrase in `bip44_test_ledger` which has addresses as below:

```rust
pub const ADDRESS_0_STR: &str = "penumbrav2t147mfall0zr6am5r45qkwht7xqqrdsp50czde7empv7yq2nk3z8yyfh9k9520ddgswkmzar22vhz9dwtuem7uxw0qytfpv7lk3q9dp8ccaw2fn5c838rfackazmgf3ahhvhypxd";
pub const ADDRESS_1_STR: &str = "penumbrav2t1vmmz304hjlkjq6xv4al5dqumvgk3ek82rneagj07vdqkudjvl6y7zxzr5k6qq24yc7yyyekpu9qm7ef3acg2u8p950hs6hu3e73guq5pfmmvm63qudfx4qmg8h7fdweydr93ku";
```

- [x] Migrate Galileo to use an account derived using BIP44
- [x] Migrate Osiris to use an account derived using BIP44

**Comment by hdevalence** [comment]
Because Penumbra has our own "internal" derivation scheme, we'll need to determine the appropriate place to join the BIP44 derivation heirarchy and the Penumbra derivation heirarchy.  For instance, we probably don't want to be using change indices, because that's already encompassed by the Penumbra derivation mechanisms.

I think it might make sense to treat the BIP44 `account` index as an index of Penumbra **account groups**, and jump from the BIP44 derivation to the Penumbra derivation at that point. This means that users can BIP44-derive as many distinct spending / viewing authorities as they want, and have that be segmented to a Penumbra coin type, but most users can just use a single account group, so their derivation path looks like
```
m / 44' / PENUMBRA_TYPE' / account' => spend seed => ask => fvk => ivk => address index => address
```

**Comment by hdevalence** [comment]
Also, I noticed that the docs in the chart on https://protocol.penumbra.zone/main/protocol/addresses_keys.html are out-of-date, it should annotate the `seed` as `spend seed` and have an edge showing the derivation from a seed phrase.

**Comment by cronokirby** [comment]
One conceptual thing: the coin type would presumably be "penumbra", but also, the key you're deriving could in theory be used to spend any asset on Penumbra, so I wonder if we're not stretching the definition a bit; oh well.

**Comment by hdevalence** [comment]
With the SLIP44 coin type selected, the derivation path for an address will look like:
```
m / 44' / 6532' / ACCOUNT_GROUP' => spend_key_bytes => ask => fvk / ACCOUNT / RANDOMIZER
`------------------------------'    `--------------------------------------------------'
  bip44 derivation                              penumbra derivation
```
