### ISSUE TITLE
Support build.rs git-lfs fetching for proto_descriptor 

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3038]
**Is your feature request related to a problem? Please describe.**
When trying to build a Rust project that uses the Penumbra crates as dependencies, `cargo build` fails with an error on the `penumbra-proto` crate, because the proto_descriptor.bin file isn't found. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
A workaround is to set a `path` dependency in the `Cargo.toml` file, rather than e.g. a `git` dependency. Provided you have the git-lfs assets checked out locally, that'll work. 

**Additional context**
We've encountered this problem before, e.g. in Galileo https://github.com/penumbra-zone/galileo/issues/29 , and our "fix" was to use path dependencies as a workaround. However there's also the dope https://github.com/penumbra-zone/penumbra/pull/2201 which resolves the lfs problem specifically for the proof params. 

Let's port that `build.rs` logic to the proto crate so that external projects can use `git` dependencies. 

Unsure what the implications of the `build.rs` strategy are for future hosting on `crates.io`; I suggest we figure that out later.

**Comment by hdevalence** [comment]
In the meantime, we can disable LFS for the proto descriptor. (We're already checking in hex-formatted proto descriptors into the repo in the form of the generated Go code).

**Comment by hdevalence** [comment]
Closing with #3044 as "good enough" for now.
