### ISSUE TITLE
dex(path_search): test liquidity heuristic with ibc assets

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3039]
**Is your feature request related to a problem? Please describe.**
To decide what part of the liquidity graph to explore, the DEX uses a combination of fixed candidates that act as safe defaults, as well as dynamically elected candidates based on a liquidity heuristic (#2843).

Now that the IBC implementation is coming together, it would be good to actually test the liquidity indexing by depositing a large number of assets and asserting that the subset of the graph that is explored matches the pairs with most counterparty liquidity.

**Comment by hdevalence** [comment]
I think we could backburner this for a while, until we have multiple IBC paths.

**Comment by erwanor** [comment]
To clarify, this issue is not about testing IBC-equivalency. Instead, this is about testing that the liquidity indices that the path search algo. The connection with IBC is that we can test that non-default assets are used by making IBC deposits, posting positions for those assets, and making sure that these assets are routable.

**Comment by hdevalence** [comment]
I think we should mark this as not planned, and subsume it into the more general task of exercising the DEX logic.
