### ISSUE TITLE
ibc: update packet data encoding to use json-protobuf encoding

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#3042]
Currently, IBC packets are serialized using raw protobuf. This is in-sync with the IBC [spec](https://github.com/cosmos/ibc/tree/main/spec/app/ics-020-fungible-token-transfer):

```

    // create FungibleTokenPacket data
    data = FungibleTokenPacketData{denomination, amount, sender, receiver}

    // send packet using the interface defined in ICS4
    sequence = handler.sendPacket(
      getCapability("port"),
      sourcePort,
      sourceChannel,
      timeoutHeight,
      timeoutTimestamp,
      protobuf.marshal(data) // protobuf-marshalled bytes of packet data
    )
```

but unfortunately this is out of sync with `ibc-go`, which uses a json encoding of the protobuf data:

https://github.com/cosmos/ibc-go/blob/242cb9f630269ae53c92345d0b98ae5fcb6be6b7/modules/apps/transfer/types/packet.go#L72C2-L72C2
https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/codec.go#L56

In order to correctly send and receive packets, we must replicate this json encoding in encoding packets on the penumbra chain. I think we can use `pbjson` for this

**Comment by hdevalence** [comment]
Where do we encode the packet?

**Comment by avahowell** [comment]
Here:

https://github.com/penumbra-zone/penumbra/blob/61c4e901a1717ed62a9bfd588fff43afeecb7e3a/crates/core/component/ibc/src/ics20_withdrawal.rs#L49

**Comment by hdevalence** [comment]
Will be done in #3043

**Comment by avahowell** [comment]
This is done now
