### ISSUE TITLE
docs: add IBC testing steps to dev guide

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3062]
Condense the testing steps described in #3043 & add these to the developer section of the Penumbra guide under a new subsection

**Comment by conorsch** [comment]
Post release of 61, we manually created a new channel from the Penumbra testnet to the Osmosis testnet. We'll need to publish the channel info emitted by Hermes in our docs for people to make use of it:

```
# Chain: penumbra-testnet-dione
 - Client: 07-tendermint-2
   * Connection: connection-18
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-0
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-1759
# Chain: osmo-test-5
  - Client: 07-tendermint-1066
    * Connection: connection-975
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-1759
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-0
```

Having #2937 in place would be nice, but not a blocker.

**Comment by conorsch** [comment]
Discussed with @aubrika: since I recently ran through these steps, setting up Hermes on 61, I'm going to grab this docs ticket. Will tag @aubrika for review, to make sure the steps are legible.
