### ISSUE TITLE
Storage Method for Recipient Tallying

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3068]
**Is your feature request related to a problem? Please describe.**
As part of our ongoing work on summoning ceremony coordination, we ultimately need a way to easily figure out how much of a given asset has been sent to us by specific addresses, as declared in the recipient part of the transaction memo.

**Describe the solution you'd like**
One simple way to add this feature would be to add extra functionality to the storage struct in the view crate. One way of dividing up the feature would be to add a method which streams out pairs of `(Address, Amount)` by joining the transaction table and the note table, giving us the total amount sent to the owner of a viewing key by various addresses.

This would potentially be useful for other situations as well, and would be enough for using in the coordinator.

**Comment by hdevalence** [comment]
The return address isn't an attribute of the note, it's an attribute of the transaction. So I think the right move is to add a `return_address` field to the `tx` table, changing it from
```
CREATE TABLE tx (
    tx_hash                 BLOB PRIMARY KEY NOT NULL,
    tx_bytes                BLOB NOT NULL,
    block_height            BIGINT NOT NULL
);
```
to
```
CREATE TABLE tx (
    tx_hash                 BLOB PRIMARY KEY NOT NULL,
    tx_bytes                BLOB NOT NULL,
    block_height            BIGINT NOT NULL,
    return_address  BLOB
);
```
When we fetch the transaction to add it into the table, we can also view the transaction and look to see if the memo has a return address. While transactions MUST include a return address (in the RFC2119 sense), nothing actually enforces this, so the return address might be missing (hence it can't be `NOT NULL`).

Once we have this, we can query for notes that were sent from a particular return address by doing a join on `spendable_notes.source == tx.tx_hash` and selecting by `return_address`.
