### ISSUE TITLE
Update to `prost` `0.12`, `tonic` `0.10`.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3078]
This is useful for two reasons:

> It looks like `prost` `0.12` has a `Name` trait: https://docs.rs/prost/latest/prost/trait.Name.html so we could skip updating all the `TYPE_URL`s, switch to `prost` `0.12`, and delete all the impls instead of updating them.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/issues/3077#issuecomment-1730866734_

and also, because Tonic `0.10.0` has an `add_routes` feature that will let us composably build up RPC services defined in each component: https://docs.rs/tonic/latest/tonic/transport/server/struct.Server.html#method.add_routes

This will require pulling all our dependencies over.

**Comment by hdevalence** [comment]
https://github.com/cosmos/ibc-proto-rs/issues/145

**Comment by conorsch** [comment]
Resolved via https://github.com/penumbra-zone/penumbra/pull/3192. Notably we've not yet implemented: 

> and also, because Tonic 0.10.0 has an add_routes feature that will let us composably build up RPC services defined in each component: https://docs.rs/tonic/latest/tonic/transport/server/struct.Server.html#method.add_routes

but we're now unblocked from doing so.
