### ISSUE TITLE
jmt: tree traversal fails when fetching an unknown key

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3082]
**Is your feature request related to a problem? Please describe.**
When the JMT is queried for an unknown key, it should return a `None` with an exclusion proof for the supplied key. However, doing this on the current testnet fails:

```
RUST_LOG=debug,h2=off cargo run --bin pcli --release -- query key this_key_does_not_exist

Error: status: Internal, message: "Missing node at NodeKey { version: 151176, nibble_path: 7ea02f }.", details: [], metadata: MetadataMap { headers: {"access-control-allow-credentials": "true", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "content-type": "application/grpc", "date": "Fri, 22 Sep 2023 04:04:07 GMT", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers", "content-length": "0"} }
```

The error is caused by an `InternalNode` holding a dangling pointer to a child node in the tree. ~~When a traversal occurs during `JellyfishMerkleTree:: get_with_proof`, the implementation tries to fetch the child node from storage but fails, because the node doesn't exist.~~

Another method, `get_node_option` exists and it is fallible. However, this is beside the point because the fetch should never fail in the first place. It is indicative of a bug. There are two competing hypothesis:
- least likely: there is a bug in the jmt implementation that makes `InternalNode` hold incorrect references to their subtree in certain circumstances
- ~~most likely: there is a bug in the backing store handling logic in pd~~

The reason why the first hypothesis is less likely is that this bug seems to never when using the in-memory mock storage, and has only been spotted on the penumbra-side of things.

**Comment by conorsch** [comment]
We consider this release-blocking for #3046, given our goal of IBC with Hermes.

**Comment by erwanor** [comment]
Unlike what I previously reported, it seems that the bug is located in the jmt, specifically in the bounding path logic of the ics23 nonexistence proof generation. I am working on a local reproduction using the mock backing store.

**Comment by erwanor** [comment]
I have a minimal reproduction, this fails when we insert >= 4 keys. Something that I have noticed is that during the bounding path phase of the ICS23 nonexistence proof calculation, we do a path search that returns a nibble path to the left or right adjacent neighbor. Then, at a later step we actually seek either or both of those extremal nodes and use them to form the nonexistence proof. However, it seems that the path search result is assumed to have the latest version number. I am not sure this is actually the case. That would explain why when we seek a `NodeKey` with matching nibble path and version, the backing store comes back empty handed.

```rust
    #[test]
    /// Write four keys into the JMT, and query an ICS23 proof for a nonexistent
    /// key.
    fn test_jmt_ics23_nonexistence_simple() {
        let db = MockTreeStore::default();
        let tree = Sha256Jmt::new(&db);

        const MAX_VERSION: u64 = 3;

        for version in 0..=MAX_VERSION {
            let key_str = format!("key-{}", version);
            let key = key_str.clone().into_bytes();
            let value_str = format!("value-{}", version);
            let value = value_str.clone().into_bytes();
            let keys = vec![key.clone()];
            let values = vec![value];
            let value_set = keys
                .into_iter()
                .zip(values.into_iter())
                .map(|(k, v)| (KeyHash::with::<Sha256>(&k), Some(v)))
                .collect::<Vec<_>>();

            db.put_key_preimage(&key);
            let (_root, batch) = tree.put_value_set(value_set, version).unwrap();
            db.write_tree_update_batch(batch)
                .expect("can insert node batch");
        }
        let (_value_retrieved, _commitment_proof) = tree
            .get_with_ics23_proof(format!("does_not_exist").into_bytes(), MAX_VERSION)
            .unwrap();
    }
```
