### ISSUE TITLE
pclientd: latest synced height endpoint & better debug console output for sync status

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3087]
In the current implementation, it's not immediately clear how far a pclientd instance has progressed in its sync progress - we should fix this by adding an endpoint to confirm the latest sync height & also add some sync-related progress data to the debug level console output.

**Comment by hdevalence** [comment]
We have this already.  The endpoints are

- https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.StatusStream (streams until synced, useful for progress bars etc)
- https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.Status (point-in-time request)

The view server will also output debug info with `RUST_LOG=debug` or lower.
