### ISSUE TITLE
Define RPC methods for the governance component to restore access to its functionality.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3093]
**Is your feature request related to a problem? Please describe.**

In refactoring #3091, I discovered that the client-side governance functionality used raw state read queries coordinated by Rust code, rather than making use of GRPC methods like other functionality. This makes it practically impossible for any software not part of our Rust monorepo to interact with the system, since it won't know what raw state reads to construct or how to parse their data.

The Rust code that coordinated the raw reads was removed as part of the refactoring, so the functionality is disabled for now. To restore it, we'll need to define and implement relevant RPC methods as part of the governance component's `QueryService`. This isn't a consensus-affecting change, so the timing isn't critical with respect to any release, but until we do it, we won't be able to interact with any governance functionality.

**Comment by conorsch** [comment]
@zbuc will pick this up for second half of 63 sprint. This ticket is blocking further governance work, so we definitely want it in. For now, operations like voting via pcli are not working. We'd like to restore that functionality pronto.
