### ISSUE TITLE
Re-enable governance param change proposals

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3107]
In the refactoring efforts for #3084/#3085 it was simpler to disable the ability to submit param change proposals for now, since splitting apart the configurable parameters per-component introduces more complexity.

These should be re-enabled after the refactoring work is complete. This will require redesigning the proposal storage and proposal RPCs in the governance component.

- [ ] grep the codebase for references to `3107` and ensure all functionality is re-added
- [ ] split the param change validation per-component [crates/core/app/src/params/change.rs](https://github.com/penumbra-zone/penumbra/pull/3086/files/26314039d08bb61d1fbe98447c053817abdc4b1b#diff-1a67e737348dc179b290adb5e1a05057a0d10deec233c67dc23ecd171e6167ef)

**Comment by conorsch** [comment]
Optimistic about completion for Testnet 63.

**Comment by conorsch** [comment]
We have a CI regression since merge of #3212: https://github.com/penumbra-zone/penumbra/actions/runs/6566057359/job/17835924660 it's flagging allegedly unused protos.
