### ISSUE TITLE
protos: support ICS20 withdrawals via TransactionPlanner

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3108]
**Is your feature request related to a problem? Please describe.**
When using the `TransactionPlanner` interface for Penumbra from non-Rust code, it's not currently possible to make an IBC withdrawal. It's possible to withdraw funds via pcli, as [described in the docs](https://guide.penumbra.zone/main/pcli/transaction.html#ibc-withdrawals), but not via the protos. In fact, the pcli implementation appears to use Rust logic directly, rather than also leveraging the proto planner interface.

**Describe the solution you'd like**
I want to use the Penumbra protos to trigger IBC withdrawals, specifically via the TransactionPlanner interface. 

**Describe alternatives you've considered**
One can shell out to `pcli tx withdraw` on the CLI as a workaround. 

**Additional context**
Captured this feedback during IBC meeting with @aubrika, @avahowell, and @jtieri.

**Comment by conorsch** [comment]
For context, here's the TxP:

![txp](https://github.com/penumbra-zone/penumbra/assets/657862/ef387df2-3ccf-4f5a-a58b-8fa005930e1d)

There's a field called `ibc_actions` but that type cannot accept a withdrawal plan:

![ibc-actions](https://github.com/penumbra-zone/penumbra/assets/657862/e132aa8e-cb33-4b99-93ee-fe5e29a9d456)

These fields should be commented to reduce developer confusion. (I myself had mistakenly thought that `ibc_actions` could take an [`Ics20Withdrawal`](https://buf.build/penumbra-zone/penumbra/docs/57fdc610ee234343bff22185e039ae51:penumbra.core.component.ibc.v1alpha1#penumbra.core.component.ibc.v1alpha1.Ics20Withdrawal)).

**Comment by hdevalence** [comment]
Yep, we should clarify that in the docs -- the `IbcAction` (could be called `IbcRelay`? cc @avahowell ) is for relaying messages from counterparty chains; the `Ics20Withdrawal` action is for causing the Penumbra chain to initiate those messages.

**Comment by conorsch** [comment]
We need this for 62 to support interchaintest integration.

**Comment by conorsch** [comment]
> We need this for 62 to support interchaintest integration.

As a temporary workaround, it's possible to use raw `pcli tx withdraw` syntax. Not ideal, but at least it means we have more time to get this interface right. Soon the rewritten web extension will be downstream of these interfaces, too, when it comes to implement ibc withdrawals over there.

**Comment by hdevalence** [comment]
Moving this back to Testnet 62 so that the interface is in place to develop ICS20 support in the web interface during the next cycle.
