### ISSUE TITLE
[wasm] separate block scanning and receiving updates for wasm ViewServer

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/penumbra#3109]
Related: https://github.com/penumbra-zone/web/issues/34 

**Problem:** Now we save notes and swaps after each block, returning it as the result of scan_block(), while we get SCT updates every 1000 blocks, and save them separately. At the same time it is necessary to save all changes transactionally. 

**Solution:** 
1. `scan_block() `function should only scan the block, modify the in-memory data and return no results 
2. `get_updates()` function should return all changes: new notes, new swaps, SCT updates, new nullifiers  
3.  We must clear the in-memory data after calling the `get_updates()` function
4.  We should handle nullifiers in `scan_block()`, mark notes as spent in-memory, and mark swaps as claimed

**Comment by Valentine1898** [comment]
#3146

**Comment by conorsch** [comment]
After Testnet 62 is released, then the second half of this work becomes unblocked.

**Comment by aubrika** [comment]
This should be handled by the extension
