### ISSUE TITLE
Exercise ICS20 timeouts end-to-end against a Cosmos-SDK chain.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3116]
**Is your feature request related to a problem? Please describe.**

In advance of getting automatic testing as part of ongoing InterchainTest integration, we should manually exercise the end-to-end flow of timeouts against a Cosmos-SDK chain.

This will require a counterparty chain with ICS23 non-inclusion proof support (#3045) and using our Hermes fork with the config option added in https://github.com/penumbra-zone/hermes/pull/3  to create a client with the correct proof spec.

Currently, this is blocked by:

- [x] #3082

**Comment by conorsch** [comment]
To test this, we can make a packet with near-immediate timeouts. This test should be manual, so we can observe behavior and document results.

**Comment by conorsch** [comment]
Achieved! @avahowell managed to get a local testing setup together to validate the behavior. She's going to write up those testing steps in this ticket, then close out.

**Comment by avahowell** [comment]
I was able to successfully perform a timeout of a packet from a local osmosis testnet (built using the osmosis `make localnet-*` tooling) to a penumbra testnet.

The steps were as follows,

1. perform an ibc handshake using hermes 
2. perform a transfer using `rly`, with a timeout height of +5 blocks
3. wait 5 blocks, then run `hermes start`
4. observe that hermes constructs a timeout, using the nonexistence proof from the penumbra chain, commits it to the osmosis chain,
5. try another transfer and verify that it still succeeds after timeout

A small change to our query api was required. When that's merged, I'll close this issue

https://github.com/penumbra-zone/penumbra/pull/3163

**Comment by conorsch** [comment]
Closing as completed.

**Comment by conorsch** [comment]
Let's try this again, but this time using public testnets, not local nets. This is recently made possible by the dep changes in Osmosis testnet.

**Comment by aubrika** [comment]
This has been demonstrated, per @avahowell
