### ISSUE TITLE
Remove initialization code from `App::init_chain`

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3117]
Captured from https://github.com/penumbra-zone/penumbra/pull/3086

@hdevalence: I think ideally we shouldn't have the `App` do any initialization at all, and only have it call into specific components' `init_chain` methods. In order to do that, we'd need to have a clear assignment of responsibility of functionality per component, which we don't currently have (but should).

For instance, why is the epoch being written directly by the App, if the epoch handling is intertwined with the SCT? Why are the FMD parameters set by the App rather than by the shielded pool? etc.

**Comment by erwanor** [comment]
This could be tackled immediately before #3617, since those component checks are implemented using the chain helpers.
