### ISSUE TITLE
Reverse dependency relationship between `penumbra-ibc` and `penumbra-shielded-pool`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3128]
Following the design work in #3127, we should implement it, reversing the dependency relationship between the IBC crate and the shielded pool. The ICS20 app handler should move into the shielded pool crate, where it can do Penumbra-specific stuff, and we can have the `penumbra-ibc` crate be independent of Penumbra-specific details.

**Comment by conorsch** [comment]
There's some design work to do on this yet, but it's a great starting point for cross-org collab. Assigning @avahowell, given how she's been driving much of the IBC implementation work to date.
