### ISSUE TITLE
Add substore support to `penumbra-storage`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3129]
The IBC protocol requires that IBC data is recorded at specific merkle tree paths, so that all counterparties can have a standardized way to verify each others' messages. To provide domain separation, IBC implementations are allowed to specify a prefix that separates their IBC data from the rest of the state hashed upwards to their light-client-verifiable state root. 

The way this is accomplished, however, poses complications.  Rather than being just a prefix on the _keys_, the prefix is a complete sub-tree. IBC data is expected to be in a separate subtree ("substore"), whose root hash is recorded as a leaf of a higher-level state tree. Inclusion proofs are lists of multiple individual proofs, chaining verification up to the global root. This is actually required by `ibc-go`, which will reject proof specifications without at least two proofs.

While this is natural for the IAVL tree used by the SDK, it's less natural for us, using the JMT, which provides a flat keyspace. To work around this, so far we've created a bogus, depth-1, single-node "merkle tree" that re-hashes the JMT root. But not only is this ugly, it creates complications:

* Our app hash is no longer the JMT root, but some derived data. So we have to have code to manage this and layer Penumbra-specific notions of app hashing onto the JMT root. This also means we can't just have the k/v RPC methods in the storage crate (cf #3091) because they return ICS23 proofs. This means that none of those RPC implementations are directly reusable by Astria.

* We don't have domain separation between IBC data and other Penumbra data. If some future IBC protocol added new data at conflicting paths, we'd have an unresolvable problem. While we could add a custom domain separation to all of _our_ data, this is quite ugly.

One idea to resolve this problem is to add transparent substore support to `penumbra-storage`. Roughly speaking, this would be a way to "mount" JMT subtrees at specific, fixed prefixes of the tree:

- instead of `Storage::load` doing implicit init, we'd have explicit init
- initialization would specify a list of "substore prefixes". these would only be configurable on init and never afterwards, and they'd be stored in rocksdb itself, so `load()` can be used without reciting substore configuration.
- the `StateRead`/`StateWrite` interfaces are unaffected, and the storage continues to present one namespace, just as before. nothing changes about any caching layers.
- in the base layer of the stack, reads are compared against the substore prefix list. if they match, the prefix is removed and the suffix is routed to the substore instead of to the default store.
- writes are also intercepted, if new keys match the prefix, the suffix gets routed to the substore.
- substore writes happen first, so that the updated substore roots can be inserted as writes to the main store.
- `get_with_proof` now returns a list of proofs, either length 1 or 2
- range queries are not allowed to cross substore boundaries.

**Comment by conorsch** [comment]
Leaving in In Progress for now; we're optimistic that #3131 will land for 63.

**Comment by erwanor** [comment]
After adding support to substores, we will need to integrate it into our ibc implementation and adjust our proof api. To complete this ticket, we have to:

- [ ] #3131 (wip)
- [ ] ibc: use prefixed store to store ibc data
- [ ] ics23: make `get_with_proof` return a list of proofs
- [ ] storage: make NV range queries work with substores

**Comment by hdevalence** [comment]
@erwanor I'm going to split out that checklist into #3125 , to better record status there.

**Comment by hdevalence** [comment]
Re-scoping this to the content of #3131 and treating the follow-up tasks as separate items; closing.
