### ISSUE TITLE
Summonerd: Implement Bidding Mechanism

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3141]
With the functionality merged in https://github.com/penumbra-zone/penumbra/pull/3098, we now have the ingredients to implement a bidding mechanism for slot selection in the summoner coordinator, based on receiving funds to the coordinator.

**Comment by hdevalence** [comment]
For implementing the bidding mechanism, we’ll want to import the view server as a library. It would be useful to use the opportunity to discover if it has any ergonomics issues.

For instance one possible snag is configuration for the view server. What grpc endpoints does it talk to? What FVK does it use? I think this is currently done in pclientd, but it might be better if the config struct was defined in the view server crate and pulled in by the pclientd config, so it can also be pulled in by the coordinator config. In this way we can factor the configuration data across the dependency stack, and compose it together as we assemble dependencies.
