### ISSUE TITLE
Support gas price-based fees in extension

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3164]
In #3084 we added multidimensional fees based on resource pricing, and implemented support for it in `pcli` but did not integrate it into the extension. This isn't an issue on the testnets since we've set all prices to `0` for now, but we will need to support estimating and including fees based on tiered gas prices in the extension prior to mainnet.

**Comment by aubrika** [comment]
This is currently blocked on some disentangling work ongoing with the extension wasm code.
