### ISSUE TITLE
CI: Mac and Windows builds failed for 62

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3174]
**Describe the bug**
The `cargo-dist` workflow for building binaries for Linux, Mac, and Windows failed on Testnet 62: https://github.com/penumbra-zone/penumbra/actions/runs/6474718975/job/17580377131 Why? 

I suspect it could be related to the `tower-abci` v0.10.0 change, which added support for Unix domain sockets for binding pd, and could have thereby broken non-Linux builds. That make sense for the Windows failure, but the Mac build we'd've seen elsewhere. 

I'll take a stab at building manually on Windows, and see if we need `cfg` attributes in tower-abci. It's also worth asking: do we even want mac & windows binaries prebuilt? I think it's worth a timeboxed attempt to restore functionality, but if it gets complicated, I'll fall back to shipping Linux bins only in the interim.

**Additional context**
First recorded in https://github.com/penumbra-zone/penumbra/issues/3123#issuecomment-1756358231

**Comment by erwanor** [comment]
It's definitely support for unix sockets in `tower-abci` that is responsible for the windows build failing. The mac build only fails because it is cancelled when the Windows one fails. I don't think we will be able to restore the Windows build for this testnet because `tower-abci` has shipped a new major version that uses the latest `tendermint-rs` release, though we could backport it on a feature branch and do a point release for this testnet.

**Comment by conorsch** [comment]
> It's definitely support for unix sockets in tower-abci that is responsible for the windows build failing. The mac build only fails because it is cancelled when the Windows one fails. 

Beautiful, thanks for looking into it. 

> I don't think we will be able to restore the Windows build for this testnet

No problem at all: I'll do a pass through the tower-abci repo and see if I can't get it cross-platform-compatible again.

**Comment by hdevalence** [comment]
Missing Windows support for the moment is not a big deal, I don't think it's worth doing extra release shenanigans. We could pick it back up later as changes propagate from upstream.

**Comment by conorsch** [comment]
Filed a quick `cfg` PR for tower-abci: https://github.com/penumbra-zone/tower-abci/pull/37 We'll need to bump versions and pin the update in the penumbra repo for this issue to be resolved.

**Comment by erwanor** [comment]
We'll pick this up in the next release of tower-abci, as we integrate `tendermint-rs@0.34`. Thanks for fixing the upstream!

**Comment by conorsch** [comment]
There's in-flight work around version upgrades, and given that we've got an extra week for 63 (https://github.com/penumbra-zone/penumbra/issues/3182#issuecomment-1771397647), we may be able to land the necessary version bumps to unbreak the builds. cc @erwanor in case I'm making assumptions.

**Comment by erwanor** [comment]
Actually this landed with #3192, so we can close this!
