### ISSUE TITLE
[wasm] Wasm code related to transaction building is deprecated and requires refactoring 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/penumbra#3179]
[ViewProtocolService](url) on the extension side must support such requests related to transaction building as follows 
1. rpc
[Witness](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.Witness)
2. rpc
[WitnessAndBuild](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.WitnessAndBuild)
3. rpc
[AuthorizeAndBuild](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.AuthorizeAndBuild)
4. rpc
[Authorize](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.custody.v1alpha1#penumbra.custody.v1alpha1.CustodyProtocolService.Authorize)

At the same time as the current wasm code allows you to do Authorize, Witness, Build in [one function ](https://github.com/penumbra-zone/penumbra/blob/027faa0640a348d1c394244501062b071fa2a156/crates/wasm/src/tx.rs#L63)

It is necessary to make separate wasm functions for Authorize, Witness, Build that can be called from TS for proper implementation of the rpc requests given above

**Comment by grod220** [comment]
can we close this issue?

**Comment by Valentine1898** [comment]
Yeah, I'm closing
