### ISSUE TITLE
[wasm] View Server  tests

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/penumbra#3180]
[View Server](https://github.com/penumbra-zone/penumbra/blob/main/crates/wasm/src/view_server.rs) has quite a bit of complex functionality that requires testing

These should not be `wasm-bindgen-tests`

Possible challenges:
- we need to make a mock for `indexed DB` calls 
- we need to prepare quite a lot of data for tests (`Compact Blocks` of different content). 
- It is not clear how to validate the correctness of SCT changes 

- [ ] https://github.com/penumbra-zone/penumbra/issues/3273
- [ ] https://github.com/penumbra-zone/penumbra/issues/3274

**Comment by Valentine1898** [comment]
I encountered a few problems while testing wasm crate 
1. If we try to run the `cargo test` without 
`--target wasm32-unknown-unknown` then we will encounter the problem of 
```
cannot call wasm-bindgen imported functions on non-wasm targets
``` 
and in fact we will not be able to work with `JsValue`, call `serde_wasm_bindgen::from_value() `, `serde_wasm_bindgen::to_value()`. Also we won't be able to create `JsValue` from json (which I planned to do to create test data)
2. At the same time, if we run cargo test with `--target wasm32-unknown-unknown`, we encounter a compiler bug. 
locals exceed maximum (at offset 28040301)
[details](https://ritik-mishra.medium.com/resolving-the-wasm-pack-error-locals-exceed-maximum-ec3a9d96685b 
)

> What is happening here is that the compiled .wasm binary contains a function that has more than that 50,000 local 
 variables in it. As it turns out, the tool that parses the wasm file has a hard limit of 50,000 local variables
 
 3. We create an `IndexedDBStorage` instance when we initialize the view server. This means that we are guaranteed to get an error when running tests in an environment without `indexed-db `
I am considering two options 
- switch to dependency injection. This means that we should change the code so that we can inject `IndexedDBStorage` via constructor or setter. This will allow us to use mock for `IndexedDBStorage` in the tests 
- move the creation of `IndexedDBStorage` from `ViewServer::new()` to the place in the code where `IndexedDBStorage` is called. This will allow us to test most of the view server code, but we will miss some test cases that should lead to `IndexedDBStorage` calls

I will transform this into a tracking issue and add an issues for the problems described above. 
Also, any help would be appreciated @grod220

**Comment by grod220** [comment]
Why are we calling `cargo test` for these tests? I thought the strategy was that the test suite would compile to wasm and run them in nodejs or a headless browser (like we do with vite+playwright in the crypto package in the web repo).

**Comment by Valentine1898** [comment]
Essentially a error 
`locals exceed maximum (at offset 28040301) 
`
And it occurs when we try to run tests in nodejs or a headless browser using `wasm-pack test`

**Comment by hdevalence** [comment]
> Why are we calling `cargo test` for these tests? I thought the strategy was that the test suite would compile to wasm and run them in nodejs or a headless browser (like we do with vite+playwright in the crypto package in the web repo). 

All the tests in this repo must be runnable with cargo test and no other tooling. If we have code that needs other infrastructure to test it should not live in this repo.

**Comment by hdevalence** [comment]
Why are we still bundling the proving keys into wasm instead of doing #2712?

**Comment by grod220** [comment]
> All the tests in this repo must be runnable with cargo test and no other tooling

I'm not sure this is a good policy in general. The producer of the code should be bound in a kind of service-level-agreement that it can be consumed by first class apps (like the web repo). Right now, someone could easily break the wasm crate and it wouldn't be caught until the web code consumes the new wasm js package weeks later.

Even at minimum, we should add a CI/CD test that ensures that `wasm-pack` can even compile this code when someone makes a change to the code base.

Regardless, if we move to a dependency injection pattern with indexeddb usage, we could in theory run the tests in Rust.

**Comment by Valentine1898** [comment]
> Even at minimum, we should add a CI/CD test that ensures that wasm-pack can even compile this code when someone makes a change to the code base.
It's already in use 
https://github.com/penumbra-zone/penumbra/blob/main/.github/workflows/rust.yml#L71

**Comment by Valentine1898** [comment]
I think the best solution is to use tests 
`cargo test --target wasm32-unknown-unknown`
CI-CD can be configured for them [link](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/continuous-integration.html) 
But in order to do that, we have to overcome the bug with 
`locals exceed maximum (at offset 28040301)`

**Comment by TalDerei** [comment]
I know this is blocked, but see #3273

**Comment by Valentine1898** [comment]
Moved to web repo https://github.com/penumbra-zone/web/issues/694
