### ISSUE TITLE
ibc: check for tendermint client update problems

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3193]
See upstream issue here: https://github.com/cosmos/ibc-rs/issues/911 We should check whether our impls in the ibc component crate, and in the ibc-types crates, are affected by this problem.

**Comment by hdevalence** [comment]
@avahowell said this didn't seem to affect us, I'll wait for a comment describing why.

**Comment by avahowell** [comment]
The equivalent logic for this exists in our ibc-types-lightclients-tendermint:

https://github.com/penumbra-zone/ibc-types/blob/ca4cc5e9e936f229b346d19e248ec7088aed3dba/crates/ibc-types-lightclients-tendermint/src/header.rs#L110

we don't have this incorrect check, so we're not affected by this specific issue. However there are a few validations being performed that aren't present there. I will make a PR to ibc-types to add those.
