### ISSUE TITLE
`parallel` feature should be split into two features

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#3195]
We have a feature in many of our crates called `parallel` for fast proving and transaction building. Under the hood it is currently doing two things:
- Turning on the `parallel` feature in our Arkworks cryptography dependencies which uses Rayon to speed up slow operations, see e.g. https://docs.rs/crate/ark-ff/0.4.2/features#parallel
- Using the `TransactionPlan::build_concurrent` method instead of `TransactionPlan::build`. This spawns a number of tokio tasks equal to the number of proofs in the transaction.

The problem here is that @grod220 has pointed out we can use Rayon in wasm (via [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon)), but not Tokio. Thus, we should have two feature flags:
1. one that _only_ enables the `parallel` feature in the Arkworks crypto dependencies
2. and another that enables the use of the `build_concurrent` method. 

Both these features would be turned on by default for `pcli`, but the wasm code would only use the feature that turned on the `parallel` feature.

**Comment by hdevalence** [comment]
I'm not sure we want to do this. The `wasm-bindgen-rayon` crate is using web workers under the hood, but without the ability to control data sharing between them or manage the overhead of message passing. This is very different from the normal assumptions of Rayon (actually shared memory, no serialization overhead), so it's not clear that code that is fast using Rayon normally would be fast with web worker intermediation.

At the same time, we already have parallel transaction building done using web workers manually (building each action in parallel). For now I think we should not plan to do this, and see how far we get with the existing strategy.
