### ISSUE TITLE
Project planning improvements

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3211]
Refactor & relay changes to project management process

**Comment by conorsch** [comment]
Not sure if this is helpful, but I dusted off [ye olde wiki](https://github.com/penumbra-zone/penumbra/wiki) and slammed in URLs to the current github tracking boards (including the spiffy new web one).

**Comment by aubrika** [comment]
This was intended as a dummy issue for use as an example while arriving at a new project planning process - this has been done.
