### ISSUE TITLE
pcli build on M1 mac

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/penumbra#3219]
Following the `pcli` [installation steps ](https://guide.penumbra.zone/main/pcli/install.html), I can't get the command line client to build from source for 2020 M1 Macbook Pro (`Sonoma v14.0`). Instead, downloading the `aarch64-apple-darwin` (**v0.61.0** executable 
from [releases](https://github.com/penumbra-zone/penumbra/releases) worked. 

Additionally, include a note in the docs about the minimum required OS version for [MacOS builds](https://github.com/penumbra-zone/penumbra/blob/main/.github/workflows/release.yml#L90). Otherwise, it throws `dyld` linking errors for dylibs required in Mac OS X 12.0.

**Comment by TalDerei** [comment]
`cargo build --release --bin pcli` returns the following build error. `cargo nextest run --release` returns the same error.

<img width="1439" alt="Screenshot 2023-10-23 at 7 58 21 AM" src="https://github.com/penumbra-zone/penumbra/assets/70081547/2d5edd37-dfca-45ed-939c-455926184d25">

**Comment by TalDerei** [comment]
I tried forcing the compilation under **aarch64-apple-darwin** with `cargo build --release --target=aarch64-apple-darwin`, but it defaults to the **x86_64-apple-darwin** target, which is where these linking errors are coming from.

**Comment by erwanor** [comment]
can you run: `rustup show`, and if it's not using the right toolchain switch using:
1. `rustup toolchain install stable-aarch64-apple-darwin`
2. `rustup default stable-aarch64-apple-darwin`

**Comment by TalDerei** [comment]
The build progressed farther by switching to default toolchain to `stable-aarch64-apple-darwin` , but still failed towards the end. `rustup show` shows
```
Default host: x86_64-apple-darwin
rustup home:  /Users/margulus/.rustup

installed toolchains
--------------------
stable-aarch64-apple-darwin
stable-x86_64-apple-darwin
nightly-2022-06-20-x86_64-apple-darwin
nightly-aarch64-apple-darwin (default)
nightly-x86_64-apple-darwin
1.58-x86_64-apple-darwin
1.56.1-x86_64-apple-darwin

active toolchain
----------------
stable-aarch64-apple-darwin (default)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

I tried the nightly version (`rustup default nightly-aarch64-apple-darwin`) which shows

```
active toolchain
----------------
nightly-aarch64-apple-darwin (default)
rustc 1.75.0-nightly (1c05d50c8 2023-10-21)
```

but that didn't work either.

The error is related to **clang** 
```
error: failed to run custom build command for `librocksdb-sys v0.11.0+8.1.1`

Caused by:
  process didn't exit successfully: `/Users/margulus/Desktop/penumbra/target/release/build/librocksdb-sys-0ff091e1a9084e4f/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /Users/margulus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.65.1/lib.rs:603:31:
  Unable to find libclang: "the `libclang` shared library at /usr/local/Cellar/llvm@14/14.0.6/lib/libclang.dylib could not be opened: dlopen(/usr/local/Cellar/llvm@14/14.0.6/lib/libclang.dylib, 0x0005): tried: '/usr/local/Cellar/llvm@14/14.0.6/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/llvm@14/14.0.6/lib/libclang.dylib' (no such file), '/usr/local/Cellar/llvm@14/14.0.6/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

The clang build configuration on my machine is
```
clang version 15.0.7
Target: arm64-apple-darwin23.0.0
```

**Comment by erwanor** [comment]
for some reason, the toolchain is confused about your arch. the default host is reported to be x86, but you're clearly running on arm.

can you run: `rustup set default-host aarch64-apple-darwin`

and show me your ~/.rustup/settings.toml` and re-try.

**Comment by TalDerei** [comment]
I changed the default host 

```
Default host: aarch64-apple-darwin
rustup home:  /Users/margulus/.rustup

installed toolchains
--------------------
stable-aarch64-apple-darwin (default)
stable-x86_64-apple-darwin
nightly-2022-06-20-x86_64-apple-darwin
nightly-aarch64-apple-darwin
nightly-x86_64-apple-darwin
1.58-x86_64-apple-darwin
1.56.1-x86_64-apple-darwin

active toolchain
----------------
stable-aarch64-apple-darwin (default)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

and here's the  `~/.rustup/settings.toml`

```
default_host_triple = "aarch64-apple-darwin"
default_toolchain = "stable-aarch64-apple-darwin"
profile = "default"
version = "12"

[overrides]
```

For some reason, aarch64  seems to yield the same error. I would have thought that the x86_64-apple-darwin default host would have worked under M1's Rosetta emulation layer?

**Comment by erwanor** [comment]
right, can you run: `arch` and past back the result, as well as reinstall llvm: `arch -arm64 brew install llvm@14` and then `cargo clean && cargo build --release`

**Comment by TalDerei** [comment]
arch prints `i386`. I ran the commands above, added the reinstalled toolchain to my path and bash_profile (using the provided command), and ran `source ~/.bash_profile`. The active toolchain remained `stable-aarch64-apple-darwin (default)`, and I tried both the `aarch64-apple-darwin` and `x86_64-apple-darwin` default hosts.  Oddly, it's still issuing the same error.

**Comment by erwanor** [comment]
It is so strange that `arch` reports that you're using `x86`, but you mentioned something about Rosetta so maybe this is why!

I have two suspicions here: 1/ brew/bash was compiled for `i386` 2/ the fact that you got the same error running bindgen for rocksdb hints that you might have two different LLVM setups on your machine.

1. can you run `uname -a` and report back
2. `chsh -s /bin/bash` should switch you back to the native shell
3. run `export LLVM_CONFIG=/path/to/the/brew/dir`
4. `cargo build --release`

fingers crossed this work

**Comment by erwanor** [comment]
`brew config` will tell you if you compiled it for x86 which might explain why the dyn ld sanity checks fail when building rocksdb

**Comment by TalDerei** [comment]
I agree!

`uname -a` reports `Darwin Tals-MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 x86_64`

`chsh -s /bin/bash` reports `chsh: no changes made`

The output of `brew config` is

```
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 2 days ago
Core tap JSON: 23 Oct 22:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

after running `cargo clean && build --release`, same linking error.

**Comment by erwanor** [comment]
if setting `LLVM_CONFIG` doesn't work, maybe we can just try to completely uninstall the brew casket (`brew uninstall llvm`) and instead rely on the system's build, we can pair on this tomorrow if you're down, feel free to hit me up when you're available

**Comment by TalDerei** [comment]
That would be great! Have another obligation from 1-2:30 PST, but otherwise free. @margulus on discord

**Comment by TalDerei** [comment]
Interestingly, manually switching to the `zsh` shell and adding aliases to my bash_profile to easily switching between arm and x86 architectures didn't seem to make a difference in terms of the underlying error. In zsh, running `arch` reports `arm64`.

**Comment by TalDerei** [comment]
<img width="1439" alt="Screenshot 2023-10-24 at 2 33 58 PM" src="https://github.com/penumbra-zone/penumbra/assets/70081547/1b9644f5-6f85-4015-ab40-c197e507f943">

**Comment by TalDerei** [comment]
I finally got it to compile! The fix was setting the `LIBRARY_PATH` environment variable to properly detect `libiconv` dylib by setting `export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix)/lib:$(brew --prefix)/opt/libiconv/lib`. Interestingly, the only default_host and toolchain configuration that worked for me (under arch `i386`) was
```

Default host: x86_64-apple-darwin
rustup home:  /Users/margulus/.rustup

installed toolchains
--------------------
stable-aarch64-apple-darwin
stable-x86_64-apple-darwin (default)

active toolchain
----------------
stable-x86_64-apple-darwin (default)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

Setting their the toolchain or default host to aarch64 fails with the same linking error, and running on arch `arm64` (and changing the default host and toolchains to the aarch64 variants respectively, equally fails. It's odd, but it work for some reason.

**Comment by TalDerei** [comment]
Additionally, I've verified all the test cases pass with `cargo nextest run --release`.

**Comment by erwanor** [comment]
excellent!
