### ISSUE TITLE
Summonerd: Figure out how to reuse Aleo's phase1 output

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3226]
Regardless of how we actually want to run the two phases, having them as a starting point for phase1 provides a good amount of additional security and trust, and so reusing them would be nice.

This involves a bit of code-assisted reverse engineering / spelunking, but maybe a bit of code shimming on our end, so I feel like tracking this here is good, even if the work may not result in a PR per se.

As a concrete goal, we should be able to massage their transcript output file into our own phase1 input file. Note that we'll have to copy the thing 7 times: once for each circuit.

**Comment by redshiftzero** [comment]
Draft code to load the Aleo ceremony output and convert: https://github.com/AleoHQ/aleo-setup/compare/master...penumbra-zone:aleo-setup:master

**Comment by cronokirby** [comment]
So, after writing property tests to figure out the origins of our failure to convert the output of their phase1 to the structure our own, we realized that their phase1 actually used a different generator point for their Bls12-377 implementation:
https://github.com/AleoHQ/snarkVM/commit/21c7859a4835e9965534e5740401a96bc76661e4

The original Zexe paper didn't specify a generator, although many libraries such as GNark, Arkworks, etc. have standardized on a particular generator we use now. However, this is different than the one used by Aleo back when they ran the ceremony.

## Math you can ignore
The problem is that they have a generator `H` with an unknown relation to our generator `G`, i.e. `H = w * G` for some unknown `w`. (Presumably, we can't find this `w` either).

This means that something we expect to be of the form `x * G, x^2 * G, ...` is actually `w * x * G, w * x^2 * G, ...`, which doesn't match our expectations, and thus will fail validation as a valid phase output, and ultimately as a proving key when we try and construct one from the output.

## A theoretical way to get around this
We could get around this by modifying our implementation of proof creation and verification to use a different generator.
However, this makes interoperability with Penumbra more complicated, because all consumers of transactions have to be aware of this different verification method for proofs.

## Proposal
Running our own phase1 is a one time pain and annoyance, whereas using a different generate point than the rest of the ecosystem is an enduring pain and annoyance. Because of that, I propose that we switch gears and plan on running our own phase1.
