### ISSUE TITLE
[wasm] Implement unit testing suite

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/penumbra#3238]
Implement unit testing using the `wasm-bindgen-tests` attribute for the independent components involved in the build process including `TransactionPlan`, `Authorization`, `Witness`, and `Build`. 

Integration testing for the [View Server](https://github.com/penumbra-zone/penumbra/blob/main/crates/wasm/src/view_server.rs) comes with it's own set of complexities since it interacts with external services like IndexedDB. It's not recommended to use `wasm-bindgen-tests` here per https://github.com/penumbra-zone/penumbra/issues/3180.

**Comment by grod220** [comment]
@Valentine1898 fyi

**Comment by TalDerei** [comment]
Referenced in https://github.com/penumbra-zone/penumbra/pull/3289
