### ISSUE TITLE
Survey codebase for #[derive(Serialize)] for candidates for new protos

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#324]
Following changes in #321 , there may yet be data structures which should be represented in protos. These should be found and converted/represented accordingly following the pattern established in #321, along with any needed changes to domain types or persistent storage.

**Comment by hdevalence** [comment]
One category of data structures we could skip on a first pass are the ones used by `penumbra-wallet` and `pcli`, since these are (currently) only used internally, and not for data exchange.
