### ISSUE TITLE
ci: preview deploy failing due to address fmt change

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3247]
The preview CI deployment is failing during genesis creation: 

```
+ pd testnet --testnet-dir /penumbra-config/testnet_data generate --validators-input-file /penumbra/validators.json --external-addresses 35.192.203.35:26656,34.28.180.178:26656
2023-10-30T19:13:30.609296Z  INFO pd: Generating network config chain_id="penumbra-testnet-rhea-ca1e6887"
Error: invalid funding stream address in validators.json

Caused by:
    wrong bech32 human readable part penumbrav2t, expected penumbra

```

Related to changes in https://github.com/penumbra-zone/penumbra/pull/3243 . There are still some places we'll need to update the prefix.

**Comment by hdevalence** [comment]
Probably we could do `rg -uuu penumbrav2t` to find all remaining cases.

**Comment by conorsch** [comment]
Resolved, as shown by https://github.com/penumbra-zone/penumbra/actions/runs/6698286874
