### ISSUE TITLE
summonerd: UX feedback, part 2

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3261]
We performed another dry run of the summonerd ceremony today, and collected more feedback about user experience (UX). We should address these shortcomings prior to organizing a contribution ceremony. 

* [x] The `pcli ceremony contribute` command automatically and silently uses an ephemeral/one-time address for the user. The fact that this does so _silently_ is confusing, so we should amend the `pcli` CLI output to emit the one-time address used, printing it _after_ the contribution has been finalized.
* [x] It's hard to figure out what `summonerd` is doing, even with debug logging enabled. Let's add more info (and debug) log events to make it more obvious to an operator what it's thinking about.
* [x] Same as above, but for the "transition" step, which can take ~10m even on 16 vCPUs.
* [x] During a dry run, we observed the progress bar saying "2/1" (rather than 1/2 or 2/2), which shouldn't be possible. Fix that bug.
* [x] Consolidate the bind addresses into a single argument, referencing [this axum example](https://github.com/tokio-rs/axum/tree/276aa9e4b013de1646ea57cfcbf74e5966524f68/examples/rest-grpc-multiplex). https://github.com/penumbra-zone/penumbra/pull/3258
  
Refs #3218.

**Comment by hdevalence** [comment]
Done in #3258, we can try another test ceremony and see what happens.
