### ISSUE TITLE
Change genesis configuration to be proto-based

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#327]
Currently we specify genesis configuration using data structures defined in the `pd::genesis` module.  It's important for these to have a well-defined encoding, so it would be better to change them to be proto-based:

- [x] create a `genesis.proto` file in the proto crate and fill it in;
- [x] add serialization annotations to the `build.rs`;
- [x] change the existing types in `pd::genesis` to be domain types for those proto types.

**Comment by zbuc** [comment]
I've implemented all of this. The genesis data passed within the `InitChain` message is still JSON-encoded however. Is that correct?
