### ISSUE TITLE
Run tests for wasm crate

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/penumbra#3273]
I encountered a few problems while testing wasm crate 
1. If we try to run the `cargo test` without 
`--target wasm32-unknown-unknown` then we will encounter the problem of 
```
cannot call wasm-bindgen imported functions on non-wasm targets
``` 
and in fact we will not be able to work with `JsValue`, call `serde_wasm_bindgen::from_value() `, `serde_wasm_bindgen::to_value()`. Also we won't be able to create `JsValue` from json (which I planned to do to create test data)

2. At the same time, if we run cargo test with `--target wasm32-unknown-unknown`, we encounter a compiler bug. 
`locals exceed maximum (at offset 28040301)
`[details](https://ritik-mishra.medium.com/resolving-the-wasm-pack-error-locals-exceed-maximum-ec3a9d96685b 
)

> What is happening here is that the compiled .wasm binary contains a function that has more than that 50,000 local 
 variables in it. As it turns out, the tool that parses the wasm file has a hard limit of 50,000 local variables

**Comment by Valentine1898** [comment]
One theory is that the error 
`locals exceed maximum (at offset 28040301)` 
is related to `proving-keys` and there is hardly an easy way to fix it . 
This would explain that in the early stages of wasm crate development I successfully ran tests with `--target wasm32-unknown-unknown` (there were no proving-keys back then)

**Comment by TalDerei** [comment]
Compiling with `--release` fixes this. For instance `wasm-pack test --node -- --test test_file_name --target wasm32-unknown-unknown --release`
