### ISSUE TITLE
Summonerd sqlite schema falls down under load

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3304]
**Describe the bug**

`summonerd` stores contribution blobs inline with the contribution metadata, causing it to fall down under load.

**To Reproduce**

The service is currently down.

**Comment by conorsch** [comment]
Load times on the phase 1 contrib page (https://summoning.penumbra.zone/phase/1) has dramatically improved post-migration. Closing this as resolved.
