### ISSUE TITLE
penumbra: rethink our versioning strategy

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3307]
**Is your feature request related to a problem? Please describe.**

Our current versioning system is based on [semver](https://semver.org), and does not distinguish between application breaking changes and API breaking changes. This is fine, because each major release corresponds to a fresh testnet deployment. However, moving to persistent testnets requires us to rethink our versioning strategy since not every API breaking change is application breaking, and vice-versa. 

**Describe the solution you'd like**
We need to start tracking two levels of compatibility in parallel:
- application versioning: using the `app_version: u64` field in `abci::Info`, we can track app-breaking changes and maintain a compatibility table with crate versions. 
- crate versioning: keep using semantic versioning for crate-level changes.

**Comment by hdevalence** [comment]
I think all we need to do here is start actually using the app version field.
