### ISSUE TITLE
summoner should not time out on its own work

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3314]
**Is your feature request related to a problem? Please describe.**

I got a user report of someone who participated in the ceremony but whose contribution failed because of a timeout. Looking at the summonerd logs showed that this was in fact the case:
```
Nov 13 02:56:11 summoner summonerd[540084]: 2023-11-13T02:56:11.629277Z  INFO coordinator: summonerd::coordinator: starting ceremony round participant_count=243
Nov 13 02:56:11 summoner summonerd[540084]: 2023-11-13T02:56:11.629522Z  INFO coordinator: summonerd::coordinator: requesting contribution from participant address="penumbra1km66fy8f0jygmdwrvl6p0yu2…"
Nov 13 02:56:12 summoner summonerd[540084]: 2023-11-13T02:56:12.338709Z  INFO coordinator:contribute{address="penumbra1km66fy8f0jygmdwrvl6p0yu2…"}: summonerd::participant: sending ContributeNow message to participant
[many unrelated messages]
Nov 13 03:06:11 summoner summonerd[540084]: 2023-11-13T03:06:11.631838Z  INFO coordinator:contribute{address="penumbra1km66fy8f0jygmdwrvl6p0yu2…"}: summonerd::coordinator: STRIKE (timeout)
```

However, the user reported that their contribution had been uploaded successfully:

> on this end it seemed to linger on "coordinator is validating contribution" far longer than doing any compute or "submitting"

In particular, bandwidth logs show that the entire contribution was uploaded.

However, the timeout logic in summonerd wraps the _entire_ contribution process, rather than just the part spent waiting on the participant. So a complete contribution can be submitted and then wasted, if the verification takes too long.

**Describe the solution you'd like**

The timeout should only apply to the part where we are actually waiting on data from the participant.

Also, the tracing output should be improved:

- [ ] Add a debug event after we get the message from the participant and before we validate it (so there are timestamps in the debug logs)

**Comment by hdevalence** [comment]
Hmm. On the other hand there _isn't_ a message like `summonerd::participant: got Contribution message from participant, deserializing...`, so could the coordinator not have got the message after all?

**Comment by cronokirby** [comment]
There's definitely a UX issue where you see "submitting contribution" and then "connection closed" as you timeout, but this can also happen if you start uploading but then don't manage to finish uploading before you get timed out, and the current server logic can't really distinguish "I need to upload 5 more bytes" from "I need to upload 100 more megabytes"

**Comment by redshiftzero** [comment]
Summoning is completed
