### ISSUE TITLE
Threshold Custody: Implement broadcast transport over the command line

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3343]
The idea is that the custody backend assumes a sort of automated environment where we can broadcast messages out into the ether and somehow receive a fixed number of responses back. We need to instantiate this transport protocol with an instance that prints out textual encodings of messages, and then receives back the responses over the command line as well.

**Comment by hdevalence** [comment]
Previously we'd discussed using JSONLines, allowing the coordinator to copy paste messages into their terminal (each message being a single line).
