### ISSUE TITLE
Threshold Custody: Create a pcli command which acts as a centralized dealer

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3344]
We should have a pcli command that spits out several pre-filled in config files using a centralized dealer, for threshold custody.

I don't envision this being the main way people use this, instead people should use the decentralized key generation mode.

However, this is very useful for testing, and allows us to focus on the signing aspect first, before then implementing DKG as an orthogonal task.

**Comment by hdevalence** [comment]
Should this be a pcli init subcommand?
