### ISSUE TITLE
Track the total supply of every asset recorded on-chain

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#335]
We need to be able to track the total supply of every asset recorded on-chain in order to maintain supply transparency, and in particular, we need to track the number of each validator's delegation tokens, so that we can compute the voting power for that validator.

We already need to maintain an on-chain registry of denominations, so that we can look up the denomination corresponding to an asset ID. I think it makes sense to extend/unify that functionality with the supply tracking.  This would mean that instead of just recording the denomination string corresponding to each asset ID, we would also track the current supply of that asset.

Currently, the thin wallet API contains
```proto
rpc AssetLookup(AssetLookupRequest) returns (Asset);
```
where
```
// Requests an asset denom given an asset ID
message AssetLookupRequest {
  // The asset ID
  bytes asset_id = 1;
}

message Asset {
  bytes asset_id = 1;
  string asset_denom = 2;
}
```
are defined in `thin_wallet.proto`.

Instead, we should return both the denomination and information on the token supply.  With a view to the direction suggested in the discussion around #321, I'd suggest the following as a path to get there that lays out some groundwork for future cleanup:

#### New data modeling

- [x] Add a new `crypto.proto` protobuf that should correspond to the `penumbra-crypto` crate;
- [x] Add the following proto types to `crypto.proto`, and change the existing `penumbra-crypto` types to be domain types for those proto types:
  - [x] `message AssetId { bytes asset_id = 1; }`
  - [x] `message Denom { string denom = 1; }`
- [x] Add an `AssetInfo` message to the new `params.proto` for the `penumbra-chain` crate added in #332 that has something like:
```proto
// open to suggestions on this, seems useful to include some info
// about when the total supply value was current
message AssetInfo {
  crypto.AssetId asset_id = 1;
  crypto.Denom denom = 2;
  uint64 total_supply = 3;
  uint64 as_of_block_height = 4;
}
```
- [x] Add the corresponding domain type to `penumbra-chain`;
- [x] Change the thin wallet RPC method to `rpc AssetLookup(crypto.AssetId) returns (params.AssetInfo)`;

#### Using the data modeling

To implement that RPC method, we need to be able to construct `AssetInfo` responses, which requires knowing the total supply of each token. As written above, while the *response* includes the block height at which the data was current (so that the client doesn't need to do anything special to be able to keep track of it, and can just ignore/discard it if they don't care), the request doesn't include a block height, so it's always asking for the current token supply.  

We should decide whether this is sufficient. My instinct is that, until we know we need to track historical supply for some reason, YAGNI applies, and it's simpler to only maintain tracking of the current supply.

In that case, we can just:
- [x] change the `assets` table in the database to include a `bigint total_supply NOT NULL` column.

Currently, we only write into the assets table when the `new_assets` field of the `PendingBlock` is populated.  This approach would also work for tracking the token supply, with some slight semantic changes: instead of just looking for when we have *new* assets, we want to record whenever the supply of some asset changes.

To do that, we could change the field to `supply_updates: BTreeMap<asset::Id, (asset::Denom, u64)>`, and use it whenever the token supply changes:
- [x] on genesis, when we create the genesis allocations;
- (in the near future) on epoch boundaries, when we process delegations;
- (in the far future) when we process IBC transfers.

**Comment by plaidfinch** [comment]
@avahowell This should be closed now, because the associated PR is merged, right?

**Comment by avahowell** [comment]
yes
