### ISSUE TITLE
dex(perf): store indices in prefixed storage

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3353]
It's further afield, but one possible future use case could be to put all of the DEX indexes in a substore, so that DEX queries would operate only on DEX data. But I don't think this is currently the lowest hanging fruit for performance there.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/3131#discussion_r1394749412_

**Comment by hdevalence** [comment]
Closing as not planned since we have no concrete plans to do this.
