### ISSUE TITLE
ibc: implement host chain upgrades

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3356]
Tracked in: https://github.com/penumbra-zone/penumbra/issues/2985

When Penumbra’s client state (e.g. proof specification, chain id) changes. A special upgrade process must occur to allow penumbra clients located on counterparty chains to upgrade their view of our client+consensus state. 
Why this feature is required pre-mainnet
This feature could be added in an upgrade post-mainnet. However, it would mean that we would lose the opportunity to get a high amount of assurance from running persistent testnets, since every light client breaking testnet upgrade would result 

_What we need to implement_

- [ ] Add a flag on the governance `Upgrade` proposal that identifies the upgrade as light-client breaking
- [ ] Implement `penumbra_ibc::process_upgrade_plan` which commits an upgraded ics02 client state to a specific key in an `upgrade` substore
- [ ] When a governance upgrade gets enacted, call call `penumbra_ibc::process_upgrade_plan`
- [ ] When an upgrade height is reached, keep the full node in stasis (not making consensus progress, but serving K/V RPCs)
- [ ] Test that relayers can pick up on the client state upgrade message
- [ ] Plan that Testnet 64 is a clean reset, but thereafter, we perform upgrades.

**Comment by erwanor** [comment]
Closed in favor of #2985
