### ISSUE TITLE
Governance support for IBC actions

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3364]
_Why this feature is required pre- mainnet_

Subjecting IBC to governance is necessary for the IBC implementation on Penumbra to be suitable for handling real-world funds. N.B. this feature overlaps with the Governance and Upgrades planning projects.

_What we need to implement_

- [x] https://github.com/penumbra-zone/penumbra/issues/2173

**Comment by erwanor** [comment]
Duplicate of #2173
