### ISSUE TITLE
Exercise nonzero gas prices

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3368]
Set the hardcoded gas prices to some trivial but nonzero change.

_Why this feature is required pre-mainnet_

This ensures that we have end-to-end support for fee payments through the client stack and are assured that clients can actually handle fees without disruptive software upgrades, and that there is no consensus-critical blocker to making fee payments work. If we don’t implement this pre-mainnet then the network is subject to DOS attacks similar to the Sapling Woodchipper CVE against ZCash: https://saplingwoodchipper.github.io/ 

_What we need to implement_

- [x] Make a local devnet with non-zero fees 
  Fees can be arbitrary, as long as they are there.
- [x] Exercise basic transactions, using pcli to start.
  Currently, pcli uses the gas prices in the compactblock to set a fee, and we want to exercise that this actually works.
- [x] #4154

**Comment by aubrika** [comment]
Likely closed in error, reopening on account of spin-off issue

**Comment by TalDerei** [comment]
closing as complete
