### ISSUE TITLE
Support gas price-based fees in extension

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3370]
The extension does not currently fetch gas prices to set fees like pcli does.

_Why this feature is required pre-mainnet_

This will be necessary for the extension to implement in order to submit transactions, otherwise all fees will be 0.

_What we need to implement_

- [ ] https://github.com/penumbra-zone/penumbra/issues/3164

**Comment by jessepinho** [comment]
Do we have plans for the extension to eventually submit transactions via its UI? At the moment, that's only possible view the web app.

**Comment by aubrika** [comment]
Closed as duplicate of #3164
