### ISSUE TITLE
Determine a gas price update mechanism before auto pricing

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3371]
If we don’t do auto pricing, we need a story about how gas prices would change, if at all.

_Why this feature is required pre-mainnet_

We need a story about how we would deal with a sudden influx of spam transactions.

_What we need to implement_

Unclear

**Comment by zbuc** [comment]
We have gas costs managed as a governance parameter so this should be fine for now until we figure out an automatic pricing design
