### ISSUE TITLE
dex: implement an execution circuit breaker

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3374]
In the DEX design, we put a good amount of effort into ensuring we always make forward progress. But forward progress could be very slow. We don’t think that it will have pathological behavior – but it’s possible we could have missed something that then turns into a DoS vector. Similarly to the circuit breaker, it could be useful to have some kind of “execution breaker” that will bail out with incomplete fill after some execution limit. This means that if the DEX engine does have a DoS vector, it does not affect users of the shielded pool.

_Why this feature is required pre-mainnet_

This feature is important to have for mainnet because it guards against unknown DoS vectors in the DEX engine.

_What we need to implement_

- [ ] Some kind of tracking of how many “operations” we have done while executing the DEX functionality, in a way that we can bail out after the limit is hit.

**Comment by erwanor** [comment]
Closing in favor of #3303
