### ISSUE TITLE
Release tracking issue: Crypto

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3377]
- [x] #3378
- [x] #3380
- [x] #3381
- [x] #3382
- [x] #3330 
- [x] #2780
- [x] #3332 
- [x] #3379
- [ ] #3476 
- [ ] #3839
- [x] #1087

**Comment by redshiftzero** [comment]
#3476 and #3839 were deprioritized and removed from P-V1 so this is complete
