### ISSUE TITLE
Better method to load proving keys in wasm

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3378]
This would be in order to not have a huge wasm binary size. 

_Why this feature is required pre-mainnet_

It is not strictly necessary, but not having it currently causes problems for the web projects, and fixing it would save time and make development and user install/upgrade experience better.

_What we need to implement_

- [x] https://github.com/penumbra-zone/penumbra/issues/2712

**Comment by TalDerei** [comment]
Referenced by #3337
