### ISSUE TITLE
Audit transaction arity implications for client fingerprinting

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3379]
Penumbra transactions reveal the arity of their actions: how many spends, outputs, etc. Prior to committing to the transaction format, we should audit it to see whether there are any opportunities to close information leaks. For instance, should we place restrictions on how actions are ordered? Or should that be a client-side concern?

_Why this feature is required pre-mainnet_

We need to do this prior to stabilizing the transaction format

_What we need to implement_

Unclear; this would primarily be a design review with presumably minor changes to the transaction format or transaction building.

**Comment by TalDerei** [comment]
Tangentially related to #3435 and tracked by #3467
