### ISSUE TITLE
Plan for interactions between one-time addresses and FMD

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3381]
Unlike incoming viewing keys, detection keys are scoped to individual addresses, not wallets or accounts. So funds sent to one-time addresses won’t be automatically picked up by an FMD server. We should consider the implications of this for clients.

_Why this feature is required pre-mainnet_

If we need to make protocol changes, we would need to do so now.

_What we need to implement_

Write down some notes on how FMD interacts with one-time addresses. For instance, suppose a user never explicitly creates a one-time address. Could they miss things if they relied on detection?  Example: ICS20 withdrawals return funds to a one-time address. Should we have a list of places in the protocol where we’d expect one-time addresses to be used, and have that be marked for supplemental scanning? At this point we probably don’t want to make dramatic changes, so if there are fundamental tradeoffs then we are stuck with them, but thinking about it could prevent a missed opportunity.

**Comment by hdevalence** [comment]
After reflecting on this and walking some users through using the protocol, my conclusion is that:

1. We should not expose the term "one-time address" in user interfaces, and should only use "IBC Deposit Address"
2. We should not expose the use of one-time addresses in any other context (e.g., delete the "hide sender from recipient" toggle in the web UI).
