### ISSUE TITLE
Plan for dynamic FMD parameters

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3382]
We aren’t currently exercising setting the FMD parameters. What part of that is pre-mainnet?

_Why this feature is required pre-mainnet_

If there are any changes that can only be done prior to launch, we need to know that now. If we don’t exercise it pre-mainnet, we run the risk of the hinge “rusting shut”, where something prevents us from changing it but we don’t realize because the functionality is never exercised. Also, the detector will filter the chain history based on the detection rates, so if we set a high detection rate at launch and don’t change it, we’ll build up a permanent set of detection results that’s much bigger (e.g., maybe the first 6mo of chain history has detection results that are no better than individual scanning). 

_What we need to implement_

**Comment by redshiftzero** [comment]
Per synchronous discussion on 02/15/2024, the remaining items for FMD to be implemented prior to mainnet are #1087 and #3839
