### ISSUE TITLE
Split Spend Authority Custody

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3386]
We want a means of custodying funds which does not make a single machine a point of failure for compromising spend authority.

_Why this feature is required pre-mainnet_

We need a satisfactory solution to custody genesis funds, and having a means of custody which never created a single point of failure for the spend authority would satisfy that, and is required before we generate the addresses.

_What we need to implement_

- [ ] Custody backend for split spend. New init command that does the DKG. 
- [ ] Each person should have a unique username stored in the config file.
- [ ] As part of keygen we also generate a public-private decaf377-rdsa keypair. Such that we sign each contribution. 
- [ ] Pcli generates transaction plan. Standard commands used with the new option for the custody backend. Rework existing commands to allow the custody backend to customize the behavior. Then the tx plan is shared with other participants.
- [ ] Pcli follow
- [ ] Interactive.
- [ ] First paste in tx plan.
- [ ] User approves or rejects tx plan based on inspecting it.
- [ ] Then do rounds 1 and 2 of signing.
- [ ] Determine status of FROST impl. Audited by [NCC group](https://research.nccgroup.com/2023/10/23/public-report-zcash-frost-security-assessment/). Other review needed?
- [ ] Documentation targeted at us, investors, validators, big market makers(?).

**Comment by conorsch** [comment]
Discussed in backlog grooming meeting today. This work has been completed, across the following PRs:

* https://github.com/penumbra-zone/penumbra/pull/3383
* https://github.com/penumbra-zone/penumbra/pull/3449
* https://github.com/penumbra-zone/penumbra/pull/3462
* https://github.com/penumbra-zone/penumbra/pull/3464
