### ISSUE TITLE
Upgrade decaf377-rdsa to 0.9, and use deterministic signatures explicitly

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3388]
Right now, we're using an older version of decaf377-rdsa. Recently, we released version 0.9, which features a new method for explicit deterministic signing. This can improve many areas of the code where we previously implemented deterministic signing by manually seeding an RNG.

We should upgrade the version of this crate across the monorepo, and then look for places where we're using randomized signing with a seeded RNG, and replace those with the deterministic signing method.

**Comment by hdevalence** [comment]
I think this needs to happen as part of the transaction build split up PR, which we should land ASAP because it blocks all other transaction format changes

**Comment by cronokirby** [comment]
We could also do this as a quick PR and then rebase that one on top of it, but yeah.

**Comment by hdevalence** [comment]
I thought this was done as part of https://github.com/penumbra-zone/penumbra/pull/3289#issuecomment-1811726322 , but I'm not sure whether or not it was. @TalDerei , do you know?

**Comment by TalDerei** [comment]
> I thought this was done as part of [#3289 (comment)](https://github.com/penumbra-zone/penumbra/pull/3289#issuecomment-1811726322) , but I'm not sure whether or not it was. @TalDerei , do you know?

It wasn't. It was supposed to be, but I think the PR was closed before I had a chance to make the change.

**Comment by TalDerei** [comment]
Seems like we're still using `version = "0.7"`
