### ISSUE TITLE
Rust-analyzer breaks because of a valid circular dev dependency

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/penumbra#3389]
Resolve circular dependencies that prevents `rust-analyzer` from syntax highlighting / linting certain dependencies in packages. 

![Screenshot_2023-11-16_at_7 48 59_AM](https://github.com/penumbra-zone/penumbra/assets/70081547/1b5869e5-e1bb-4b13-ac1b-6433cfd2cb22)

**Comment by erwanor** [comment]
https://github.com/rust-lang/rust-analyzer/issues/14167
