### ISSUE TITLE
Update IBC component to use substores

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3390]
**Is your feature request related to a problem? Please describe.**

In #3131 we added support for "substores", in order to be able to get rid of our hacky AppHash construction. Now that that code is merged, we need to propagate those changes through the rest of our code and deprecate our existing `AppHash`.

- [x] https://github.com/penumbra-zone/penumbra/pull/3131
- [x] #3326
- [ ] https://github.com/penumbra-zone/penumbra/issues/3477
- [x] Add support for go-relayer https://github.com/penumbra-zone/penumbra/issues/3222
- [x] #3443

**Comment by conorsch** [comment]
>  Add support to our Hermes fork

@avahowell has started work on this, and initial spike is promising. She hopes to have a PR for Hermes compat by EOW. On "Add support for go-relayer" that'll likely slip past Monday's ship date; reminder that we have #3222 as well.

**Comment by avahowell** [comment]
Current status of this work:

- We have updated proof specs + code to generate proofs that are compatible with them
- We have manually tested relaying on the new substore proofs, between both penumbra<>penumbra chains and penumbra<>cosmos chains, in both the go relayer (using interchaintest) and Hermes (using our fork)

Remaining work is to rebuild the hermes fork on top of backend-specific configs, off of the latest informal main.

**Comment by avahowell** [comment]
I'm closing this issue since it tracks the substore integration into the ibc component, which is done. The remaining work is on the hermes relayer, tracked in #3477.
