### ISSUE TITLE
penumbra-ibc: handle evidence in `MsgUpdateClient`

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3404]
**Is your feature request related to a problem? Please describe.**
With the `0.7.0` release of `ibc-go`, misbehavior evidence handling via [`MsgSubmitMisbehavior`](https://github.com/cosmos/ibc-go/blob/68dba07c702b1944002ccdef3140f4b0a1e1e473/proto/ibc/core/client/v1/tx.proto#L103) has been deprecated. 

**Describe the solution you'd like**
Misbehavior submission happens as an in-band client update. When we detect it, we should freeze the associated client.

**Comment by conorsch** [comment]
Discussed at ibc sync today. @avahowell claims this is already implemented, but some code comments should be added to make it clear we're handling this use case.

**Comment by avahowell** [comment]
We're already freezing the client in the case of equivocation in `MsgUpdateClient`:

https://github.com/penumbra-zone/penumbra/blob/efb45653031e7f9a2ea16e93afbedd744a44b4f3/crates/core/component/ibc/src/component/msg_handler/update_client.rs#L121

https://github.com/penumbra-zone/penumbra/blob/efb45653031e7f9a2ea16e93afbedd744a44b4f3/crates/core/component/ibc/src/component/client.rs#L45

**Comment by avahowell** [comment]
Closing this for now since we already do it

**Comment by erwanor** [comment]
I agree this isn't a huge deal, but we don't actually do this. We do detect duplicate headers, and freeze clients accordingly, but we don't allow relayers to submit evidence via `MsgClientUpdate`. The reason why this isn't a huge deal is because we can just make hermes forward the equivocating headers in a regular update. However, it seems like a low hanging fruit to just peek at the client updates for a `client_message` that corresponds to misbehavior.

**Comment by erwanor** [comment]
I guess the emphasis of this ticket is on detecting and validating _evidence_, rather than detecting equivocation.
