### ISSUE TITLE
pd: test upgrading a validator node

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3483]

**Comment by conorsch** [comment]
I've run through this process several times now. It's very important to use the `--genesis-start` flag added in https://github.com/penumbra-zone/penumbra/pull/3491, as well as the re-initialized `priv_validator_state.json` added in same. With those changes, I'm able to restart a chain post-upgrade by upgrading the two (2) genesis validators.

**Comment by conorsch** [comment]
Closing as complete, as we're quite familiar with and confident about this part of the upgrade story.
