### ISSUE TITLE
Typed asset cannot be unambiguously parsed if it begins with a digit

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#349]
Suppose some token's name begins with a digit: this is not a hypothetical, because the `0x` token exists (https://0x.org), and probably others do too! For below, let's call this hypothetical token `1coin`.

Currently, our typed asset parsing code will not allow you to parse any typed amount of `1coin`, because any number of digits (including none) preceding the string `"1coin"` will be parsed as an amount consisting of that string of digits, appended with the digit `1`, with the denomination `coin`. For example: `101coin` parses as `101` units of `coin`, not `10` units of `1coin`.

A slate of possible solutions:

- Ban denoms from beginning with a digit
  + pro: simple, easy to implement, does not change how things look in `pcli` or require extra typing
  + con: tokens whose actual denom name begins with a digit will need to be named something else for the purposes of penumbra, unclear how we would maintain this (manually? via some auto-renaming scheme? but either introduces more potential for clashes, ambiguity, and user confusion)
- Allow disambiguation in the parsing phase, so that `10_1coin` is parsed as `10` units of `1coin`, and when printing denoms, disambiguation is added if necessary
  + pro: does not limit the strings usable as denoms
  + con: conditional need for disambiguation is less easy for humans to understand
  + con: edge case where there is a token called `1coin` and also another called `coin` means that if someone *forgets* to disambiguate, they could end up sending the wrong asset by mistake
- Force disambiguation in parsing and pretty-printing, so that you *must* specify the amounts in a syntactically unambiguous way always (i.e. the underscore is mandatory in `10_penumbra`, or some other non-space separator is used to similar effect)
  + pro: avoids the possibility of accidentally forgetting to disambiguate and sending the wrong asset
  + con: requires more typing for every asset, might look noisier visually
  + con: what if a denom begins with `_`, or whatever separator is chosen? 
- Force disambiguation as above, but using the space character
  + pro: very reasonable to enforce that denoms can't begin with _the space character_ (this should not be done!)
  + con: command line parsing gets a little more complex to implement
  + con: it's easier to copy/paste untyped amounts, rather than by default copy/pasting typed amounts

**Comment by hdevalence** [comment]
I don't think this will be a problem for us, since we can simply choose not to create any native denominations that start with a digit -- other assets, like the `0x` token, would be IBC-bridged assets, which then have an IBC prefix on them.
