### ISSUE TITLE
Port all existing `event.rs` files to use proto events.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3504]
Following the work in #3460 to define protobuf event handling, it would be good to convert the existing events:

> We should then replace all existing events defined in the Penumbra application with Protobuf-based events. These events should be defined in the Proto module corresponding to the component that emits the event. Currently, there are only 12 events currently defined (VS Code search fn in files named event.rs), so this shouldn't be a huge lift.
>
> Since any Protobuf message could in principle be encoded as an event this way, we should adopt a naming convention to distinguish messages defining events from messages defining other data. One possibility would be to name all of the event messages Event*. Using a prefix rather than a suffix means that all of the events will be grouped together when messages are sorted alphabetically.

In particular, porting over the DEX events will make them useful for trading bots (cf https://discord.com/channels/824484045370818580/1163684711667867678/1181748568135061514 )

**Comment by erwanor** [comment]
Note to self, that we should also port the staking component events to use proto-event.

**Comment by hdevalence** [comment]
Was this completed? We should ensure it's completed as part of V1 -- we can always add more events but changing events people are using will be difficult.

**Comment by erwanor** [comment]
I ported over the DEX events, but got pulled in another direction before doing the rest of the codebase. I believe that @zbuc is tracking the staking events in #3797. I'm unassigning myself for now

**Comment by zbuc** [comment]
The only place using non-protobuf event types is now the IBC code. This will require defining protobuf event types in `ibc-types`

**Comment by conorsch** [comment]
We discussed during sprint-planning today, and we're calling this complete. We specifically _don't_ want to 

> defin[e] protobuf event types in ibc-types

as we're trying to keep that library chain-agnostic, and we don't want to emit Penumbra-specific events as part of that tooling.
