### ISSUE TITLE
Comprehensive indices for advanced analytics queries

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#352]
Per discussion with @avahowell and @hdevalence, it would be good to support a mode of operation for `pd` that tracks more data than is strictly necessary to perform as a node. Specifically, historical information about the previous values of things like the validator set, token supplies, and a lot else.

Keeping these things around and indexed would cost disk space and perhaps a small amount of performance, but it would enable people to more easily build custom functionality (e.g. sophisticated trading bots) atop `pd` without having to fork the codebase and maintain these indices themselves. However, since most users of `pd` would likely not need these extra indices and not want to pay in CPU time and disk usage for them, they should be opt-in, rather than always-on.

Things to consider:

- How does this affect our database schema? (@aubrika)
- What things might we want to track?
- Is there an extensible way that we could allow people to specify more things to track than we initially think of, without modifying `pd`?
- How fine-grained should the indexing toggle be, and how should that be implemented in such a way as to minimize code complexity and performance cost?

This is a relatively long-term consideration, not high priority at the moment, because it can be built after most other functionality is developed, and indeed probably should be, so we are better informed about the total schemata we are keeping track of.

**Comment by hdevalence** [comment]
One basic question is whether we should do this by means of our own tables and indexes in `pd`, or whether we should use Tendermint's [event-indexing mechanism](https://rustdoc.penumbra.zone/main/tendermint/abci/struct.Event.html) and tell people to configure Tendermint to use Postgres as a backend.

**Comment by hdevalence** [comment]
On the Tendermint front, a basic exploration could be:

- [ ] how do we get Tendermint to use Postgres as a backend?
- [ ] how are `Event`s encoded into the database?
- [ ] what `Event`s should we start with?

**Comment by hdevalence** [comment]
@avahowell mentions that a lot of IBC relayers expect to be processing `Event`s, so having event support in our code could be tied in to IBC integration.

**Comment by hdevalence** [comment]
Our plan is to just use ABCI events for now, rather than doing something special here.
