### ISSUE TITLE
error: failed to select a version for `ibc-proto`

### ISSUE THREAD

**Issue by grafitize07** [penumbra-zone/penumbra#3521]
**Describe the bug**
Cannot release the pcli cargo, encountering this issue : error: failed to select a version for `ibc-proto`.
    ... required by package `penumbra-proto v0.64.1 (/root/penumbra/crates/proto)`
versions that meet the requirements `^0.39.0` (locked to 0.39.1) are: 0.39.1

the package `penumbra-proto` depends on `ibc-proto`, with features: `tonic` but `ibc-proto` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

**To Reproduce**

1. Clone the Penumbra repository:
git clone [https://github.com/penumbra-zone/penumbra](https://github.com/penumbra-zone/penumbra?fbclid=IwAR2Qc3OUfVddvQAawh_9SQshgy3MNBoWqOXoWSUDKZ25zaQ4yUhjBRLT2Bc)
cd penumbra
2. Build the pcli client software:
git fetch --all
git checkout v0.64.1
cargo build --release --bin pcli
3. See error

**Expected behavior**
error: failed to select a version for `ibc-proto`.

![penumbra](https://github.com/penumbra-zone/penumbra/assets/128969695/caf7e4cd-df50-4e29-9048-f16e0f796d13)

**Comment by erwanor** [comment]
I can take a look later today, but this is reminiscing of a MSRV error we saw earlier. Could you please run `rustup update` and try again, letting me know what your `rustc --version` is.

**Comment by grafitize07** [comment]
![rustc](https://github.com/penumbra-zone/penumbra/assets/128969695/6ce84858-df63-46ff-bed5-7b16f1b0c570)

**Comment by erwanor** [comment]
Yeah, run `rustup update` and try to build again and it should work. :)
