### ISSUE TITLE
Fuzz Test Circuits by checking constraint satisfication instead of constructing proofs

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3524]
Right now, we have tests that look like:

```
construct circuit
generate proof
assert!(proof.verify)
```

instead, we could simply check that the constraints of the circuit are satisfied by the witness, without actually doing the expensive part of constructing a Groth16 proof. This will speed up the test allowing us to cover more fuzz-space.

**Comment by PatStiles** [comment]
Interested in trying this out if its open for external contribution!

**Comment by redshiftzero** [comment]
we have implemented this, see #3583 for reference
