### ISSUE TITLE
Figure out how to handle genesis files with more than 65k allocations

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3545]
**Is your feature request related to a problem? Please describe.**

The maximum number of state commitments that can be added to the SCT in a single block is 4^8. The genesis allocations are added as note commitments in a single "phantom" compact block that does not correspond to any actual block (it has height 0 which is otherwise invalid).

If we had more than 65k allocations in a genesis file this would be a problem.

**Describe the solution you'd like**

- [ ] Double check the accounting above
- [ ] Figure out what, if anything to do about it (maybe: "don't have that many"?)

**Comment by conorsch** [comment]
See also #3147.
