### ISSUE TITLE
Change View RPCs to allow streaming progress indicators during build

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3549]
> there's not a way to change this with the current view service rpc, right? should we change it so that it does streaming responses, for the different stages (returning a message when built, broadcasted, confirmed, etc)?

_Originally posted by @hdevalence in https://github.com/penumbra-zone/web/issues/324#issuecomment-1872452247_

Some questions to figure out:

- How should the streaming responses be structured? What's a way to allow progress indicators but be relatively agnostic about how the server implementation supplies them?
- Should this be a second RPC, like *WithProgress, so that clients that don't care about progress don't need to consume a stream?

**Comment by grod220** [comment]
This would have to be converted to proto message format, but maybe something like this?

```rust


enum Status {
    Started,
    Completed,
}

enum BroadcastStatus {
    Started,
    Submitted(Id),
    Confirmed,
}

enum Stage {
    Plan(Status),
    Authorization(Status),
    Witness(Status),
    Build(Status),
    Broadcast(BroadcastStatus),
    Confirmed,
}

struct TxSubmitStreamRequest {
    req: TransactionPlannerRequest, // Should be the same as TxPlannerReq?
}

struct TxSubmitStreamResponse {
    stage: Stage,
}
```

I don't know if this extensible in the protobuf sense though 🤔 

Maybe this is even more generic

```rust
struct Stage {
    name: String,
    progress: u8,
    total: u8
}

struct TxSubmitStreamRequest {
    req: TransactionPlannerRequest,
}

struct TxSubmitStreamResponse {
    stage: Stage,
}
```

**Comment by hdevalence** [comment]
The planning shouldn't be included, it's instant anyways. Similarly for the "witness" step. We should only care (if at all) about building and submitting the transaction.

For building the transaction, the status message should have a float for a progress value between 0 and 1, which the server can set arbitrarily. The message sequence should look like `repeated [status update] => complete` (the server can send as many status updates as it wants and then completes).

For broadcasting the transaction, we only care about two stages, "submitted" and "confirmed".

Do we want to support one-shot methods at all? Should we just change the existing methods to return streaming responses? We already make pretty heavy use of streaming methods, so maybe it's not unreasonable to ask clients to do "consume this stream until it completes".
