### ISSUE TITLE
Buf CI actions aren't running

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3570]
**Describe the bug**

I noticed that the Buf CI actions aren't running. #3559 has green CI but is broken and incomplete.

**Comment by conorsch** [comment]
Something's definitely up. Looks like the buf action did _run_ on that PR: https://github.com/penumbra-zone/penumbra/actions/runs/7400002970 but it's certainly not displaying in the list of checks:

![gha-ci-no-buf](https://github.com/penumbra-zone/penumbra/assets/657862/c0068da5-3894-44a5-a085-7f6277342480)
