### ISSUE TITLE
governance: record proto events when proposal pass

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3581]
Before we ship 65, we should make sure that governance events are recorded using proto-events. 

Part of #3504.

**Comment by erwanor** [comment]
@zbuc For example, this is done in #3513. We should basically do the same thing for the governance module.

**Comment by conorsch** [comment]
Passed on discussion in planning meeting today, we've decided it's not critical to land this for Testnet 65 (#3554).
