### ISSUE TITLE
stake: refactor the staking component to use modular traits (draft)

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3615]
**Context:**

The staking component is largely implemented by a `StakingImpl` trait which has three responsibilities:

- Manage the validator state machines: both triggering and implementing state transitions;
- Implement end-epoch logic: computing delegation changes, defining the base rate for the next epoch, updating validator state/power;
- Responsible for important but miscellaneous tasks like tracking validator uptime, processing misbehavior evidence, and materializing cometbft consensus set updates. 

To achieve this, the `StakingImpl` trait ties together three other interfaces:
- State extension traits (R/W) that handle validator indices, staking component parameters, rate data, delegation changes, and penalty tracking.
- `ValidatorUpdates` R/W that queues consensus set changes.

The validator state machines are highly coupled to the extension traits, which themselves have low cohesion, making it hard to implement new features without having to inspect every method in the the fits-all extension trait to make sure that things are correct. 

**Proposal:**

```rust
/// Implements the staking [`cnidarium_component::Component`] logic.
pub struct Staking {}

pub(crate) trait StakingImpl: StateWrite {
    /// Process the end of an epoch, delegation changes, rate data calculations
    /// and produce the resulting updated validator set.
    fn end_epoch(...) -> Option<TendermintUpdate>;
}

/// An internal trait responsible for the implementation of the validator
/// state machine.
pub(crate) trait ValidatorManager: StateWrite + ValidatorIndex {
    /// Add a validator definition, defining its initial state and rate data.
    fn add_validator(&mut self, validator: Validator);
    /// Add a genesis validator definition, defining it as [`State::Active`].
    fn add_validator_genesis(&mut self, validator: Validator);
    /// Apply a state transition to a validator.
    async fn set_validator_state(&mut self, validator: IdentityKey, new_state: validator::State) -> Result<()>;
    /// Update a validator's definition, potentially causing a state transition.
    async fn update_validator(&mut self, validator: IdentityKey, definition: Validator) -> Result<()>;
    /// Update the consensus set's uptime, jailing validators that have missed too many blocks.
    async fn track_validator_uptime(&mut self, last_commit: tendermint::LastCommitInfo) -> Result<()>;
}

/// An internal trait that mediate writes to staking data.
pub(crate) trait StakingData {
    fn push_delegation(&mut self, delegation: Delegate);
    fn push_undelegation(&mut self, undelegation: Undelegate);
}

/// A public interface to staking data.
pub trait ReadStakingData: ValidatorIndexRead {
    fn delegation_changes(&self) -> Option<DelegationChanges>;
    async fn total_active_stake(&self) -> Result<Amount>;
}

/// An internal trait that handles updates to validator data.
pub(crate) trait ValidatorIndex: ValidatorIndexRead {
    fn set_validator_rate(&mut self, validator: IdentityKey, state: BondingState);
    fn set_validator_power(&mut self, validator: IdentityKey, power: u64);
    fn set_validator_uptime(&mut self, validator: IdentityKey, uptime: Uptime);
    fn set_valdiator_bonding_state(&mut self, validator: IdentityKey, state: BondingState);
    fn index_validator_consensus_key(&mut self, validator: IdentiytKey, consensus_key: PublicKey);
    fn deindex_validator_consensus_key(&mut self, validator: IdentityKey) -> Result<PublicKey>;
}

/// A public interface to the validator data.
pub trait ValidatorIndexRead: StateRead {
    fn get_validator_state(&mut self, validator: IdentityKey) -> Result<Option<validator::State>>;
    fn get_validator_rate(&mut self, validator: IdentityKey) -> Result<Option<RateData>>;
    fn get_validator_power(&mut self, validator: IdentityKey) -> Result<Option<u64>>;
    fn get_validator_uptime(&mut self, validator: IdentityKey) -> Result<Option<Uptime>>;
    fn get_validator_info(&self, validator: IdentityKey) -> Result<Option<validator::Info>>;
    fn get_unbonding_epoch_for_validator(&self, validator: IdentityKey) -> Option<u64>;
    fn get_validator_by_tendermint_address(&self, address: TendermintAddress) -> Result<Option<u64>>;
    fn get_validator_by_consensus_key(&self, key: PublicKey) -> Result<Option<u64>>;

    /// Return a stream of definitions from validators that form the consensus set.
    async fn validator_definition_stream(&self) -> Pin<Box<Stream<Item = Validator> + Send + 'static>>;
    /// Return a stream of [`IdentityKey`]s from validators that form the consensus set.
    async fn validator_identity_stream(&self) -> Pin<Box<Stream<Item = IdentityKey> + Send + 'static>

}

/// A public interface to the staking component's chain parameters.
pub trait StakingParameters {
    fn get_stake_parameters(&self) -> StakeParamaters;
    fn put_stake_parameters(&mut self, params: StakeParameters) -> Result<()>;
}

/// A public interface to the list of validators updates to be sent to CometBFT.
pub trait ReadTendermintUpdates {
    fn get_validator_updates(&self) -> Option<Vec<tendermint::Update>>;
}

pub(crate) trait WriteTendermintUpdates {
    fn put_validator_update(&mut self, u: Update) -> Result<()>;
}

```

At a high-level, what this achieve is:
- Separate staking logic and validator handling
- Split `StakingImpl` so that its purpose is strictly implementing end-epoch processing
- Create `ValidatorManager` which compose validator traits together and expose a reduced interface to validator state machines
- Create `ValidatorIndex` which mediate state accesses to validator data, in-lining basic invariants that should always be upheld
- De-async-ify getters/setters when it makes sense, and simplify their signature to be infaillible
- Re-organize the stake keys to track which domain they belong to
- Since each trait corresponds to an increasing level of capability, we can have write tests for each of them such that the assurance they offer is cumulative. 

**Alternatives:**

This is a draft issue, open for discussion, and feedback. This turned out to be a useful exercise to help me scope the future dynamic issuance implementation that the staking component is downstream of.

**Comment by conorsch** [comment]
Work is actively in progress! @erwanor is optimistic about having a PR up by EOD. Ideally we'd get @hdevalence's eyes on the changes, but we can also self-organize in the `#review-please` channel.

**Comment by conorsch** [comment]
See comment in https://github.com/penumbra-zone/penumbra/pull/3737#issuecomment-1930691844 Still more work to come until this work is complete.

**Comment by erwanor** [comment]
There are two items remaining before we close this, both are small and comfortably within reach tonight or tomorrow morning:
- [ ] staking: re-organize state keys into distinct namespaces
- [ ] staking: fix issues surfaces during state machine review

**Comment by conorsch** [comment]
Both PRs have been merged, so marking this as resolved. Thanks for all your hard work on the staking logic, @erwanor!
