### ISSUE TITLE
penumbra: review user supplier string fields in messages

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3620]
**Is your feature request related to a problem? Please describe.**
In #2066, we discovered that validator definition string fields were not length-limited. We should review governance action handlers (among others) to make sure that we check those fields.

Assigning myself to keep track of this issue, however it's a good first issue and I would be happy to have a contributor take it on and play assist.

**Comment by cronokirby** [comment]
Idea: create a SmallString<N> type which will automatically validate upon construction that the string is less than N characters. Then you just put it in the action struct, and it becomes impossible to not validate this in the resulting app logic.

**Comment by hdevalence** [comment]
I think it would be simpler and more ergonomic to put the validation in the `TryFrom` domain type conversion rather than introduce our own custom string type that would have feature parity with the stdlib's string type. Otherwise we put ourselves through worse ergonomics forever.

**Comment by zbuc** [comment]
> I think it would be simpler and more ergonomic to put the validation in the `TryFrom` domain type conversion rather than introduce our own custom string type that would have feature parity with the stdlib's string type. Otherwise we put ourselves through worse ergonomics forever.

One downside of this is duplication, for example `Validator` has three different `TryFrom` implementations:

`impl TryFrom<ValidatorToml> for Validator {`
`impl TryFrom<pb::Validator> for Validator {`
`impl TryFrom<&TestnetValidator> for Validator {`
