### ISSUE TITLE
Test failure after adding transaction progress streaming

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3621]
**Describe the bug**
In PR #3559 transaction progress streaming was added and seems to work in manual testing with `pcli`, however the PR unexpectedly introduced test failures in CI. I tried replicating them locally but was unable to.

I spent some time paring down the test suite in that PR and this is what I found:

* The failing test is the `transaction_sweep` test
* When only the `transaction_sweep` test is present in CI, the smoke tests pass, indicating an inter-test conflict
* When the `test_orders` test is reintroduced alongside the `transaction_sweep` test, the failure begins to occur

# Steps to resolve

- [ ] Diagnose and fix the specific side effect causing failure between the two tests
- [ ] Revert the test and debug logging changes made to #3559
- [ ] Merge #3559 

# Additional Context

* Failing test logs: https://pipelinesghubeus24.actions.githubusercontent.com/R2lw3E60pazr4YaDy7dN23NWI8as2DqxhqIHvScbTqcm1hgS7g/_apis/pipelines/1/runs/27225/signedlogcontent/2?urlExpires=2024-01-17T19%3A19%3A13.0627912Z&urlSigningMethod=HMACV1&urlSignature=uCKoTFDHx8nsLblf24S8PBWQIIWKwAdFih3qSzMIxDA%3D

**Comment by erwanor** [comment]
I think the url is expired

**Comment by conorsch** [comment]
Discussion udring sync: the two failing tests are `swap` and `sweep`. I've noticed when running locally that if I remove the `sweep` test entirely, then `swap` starts failing again. Odd. That's an interaction we need to explore further.

However, #3559 remaining unmerged is blocking web team progress, so I'm going to disable `sweep` for now, get 3559 to green, and then continue investigation after the core logic has landed.
