### ISSUE TITLE
pcli: processing multiple undelegation claims fails too aggressively

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3622]
**Is your feature request related to a problem? Please describe.**
When pcli tries to process multiple undelegation claims, it will abort completely if one of the undelegation tokens has not fully unbonded. This means that undelegation tokens that have reached maturity are not processed at all.

Steps to reproduce:

1. Delegate to validator 1
2. Delegate to validator 2
3. Undelegate validator 1
5. Wait an epoch
6. Undelegate validator 2
7. Try to run `undelegate-claim` 
8. Observe error

**Solution**
The undelegation claim logic in pcli could be refactored. But, a minimum fix could simply log that an error occurred and try to process the next one, or fetch the unbonding epoch duration and try to preemptively avoid processing unbonding undelegation tokens.

**Comment by hdevalence** [comment]
Seems like the minimal fix here is to just do each claim in a separate transaction.
