### ISSUE TITLE
Clean up `pd` auto-https code

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3627]
> In the ~year since this code was written, there may be better options. https://docs.rs/tokio-rustls-acme/latest/tokio_rustls_acme/ seems promising

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/3522#discussion_r1429038043_

#3522, the initial experiment for serving HTTP content on the GRPC endpoint, is blocked by the fact that we would then need to use Axum directly, but our current auto-https support only works with Tonic specifically (which seems wrong, it's "all HTTP")

**Comment by hdevalence** [comment]
We'll probably need to rebuild #3522 anyways, so if we could clean up the auto-https support to get something that works directly with Axum first, we would have an easier time rebuilding that work.

**Comment by cratelyn** [comment]
i going to self-assign this. @hdevalence and i spent some time talking today, getting me up to speed with the motivation here. once i have made some more headway on the mock consensus engine, #3588, i will pivot over to work on this.

**Comment by cratelyn** [comment]
starting work on this issue this week! i've also opened #3646 to track the original motivation (a self-hosted web interface) in #3646.
