### ISSUE TITLE
dex: inventorize useful ABCI events to index

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3645]
As part of #3504, we ported all of our event recording to use the `ProtoEvent` interface. We should run through a few indexing use cases (e.g. an explorer, a price monitoring tool, an event-based trading bot etc.) to check if the ABCI event coverage of the DEX is complete.

**Comment by conorsch** [comment]
Nice to have for 65 (#3554), but really we can ship without it, and follow up with a point release. The downside of shipping without it is that anyone who wants this functionality would need to reset their node and resync in order to have the older events indexed. We accept that as a downside if it helps us ship 65 sooner.

**Comment by zbuc** [comment]
## Explorer Events

* Position created
* Position reserves changed
* Position closed
* Position withdrawn
* Position reward claimed
* Swap
* Swap Claim
* Batch swap executed
* Arbitrage execution

## Price Monitoring Events

* Many of the above events are also useful
* Best priced position changes

## Event based trading bot

* Nothing different comes to mind for me here apart from what is already outlined

**Comment by hdevalence** [comment]
> Position reserves changed

Rather than framing this as "position reserves changed", i think it would be useful to frame it as a "position execution", since that's what causes the position reserves to change. That way we can emit events on all the micro-executions as well as for the overall batch execution.

**Comment by zbuc** [comment]
Going through the code right now and checking off completed events:

- [x] Position created
- [ ] Position executed against
- [x] Position closed
- [x] Position withdrawn
- [ ] Position reward claimed
- [x] Swap
- [x] Swap Claim
- [ ] Batch swap executed
- [ ] Arbitrage execution
- [ ] Best priced position changes

**Comment by zbuc** [comment]
Noticed this comment on `dex::event::position_close`:

```rust
    // TODO: should we have another event triggered by the position manager for when
    // the position is actually closed?
```

I'm not sure what the distinction of "actually closed" here is, but I haven't gone through the call chain yet. Leaving this comment to remind myself.
