### ISSUE TITLE
Support fee tiers in extension

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3648]

**Comment by jessepinho** [comment]
@zbuc is this issue needed? We don't currently have a UI for sending txns in the extension. Or do you mean, showing the selected fee tier in the approval popup dialog?

**Comment by zbuc** [comment]
I think this issue can be closed and we only need the one in the web repo. As long as the extension shows the fee to be paid and the web app lets you select tiers I think we are good.
