### ISSUE TITLE
Propagate changes into `poseidon377`

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/penumbra#3675]

**Comment by redshiftzero** [comment]
The status of this is that `poseidon-parameters` is now rewritten to use const generics, and compiles on the target embedded platform. There are individual todos in PR https://github.com/penumbra-zone/poseidon377/pull/53 tracking the next steps, which are to propagate those changes to `poseidon-parameters` through the remaining crates in the `poseidon377` workspace.

**Comment by redshiftzero** [comment]
done in https://github.com/penumbra-zone/poseidon377/pull/53
released in https://crates.io/crates/poseidon377/1.0.0
