### ISSUE TITLE
decaf377: propagate changes to circuit stack

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/penumbra#3676]

**Comment by aubrika** [comment]
This was moved into the current sprint outside of sprint planning - can someone account for this? @cronokirby @TalDerei

**Comment by aubrika** [comment]
That is incorrect - it has not been estimated, and was not prioritized an explicitly added during sprint planning, so it should not be being worked on without explicit admission into the current sprint iteration. Other work in the Sprint 0 milestone should take priority, unless myself and @hdevalence explicitly sign off on adding a ticket.

**Comment by aubrika** [comment]
Moved back to backlog for sprint load reasons
