### ISSUE TITLE
pd: 🐣 move entrypoint logic into `app` library

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3695]
in #3588, we are tracking work on a mock consensus engine. the benefit of this will be an improved ability to write in-memory `#[test]` functions of our `pd` daemon, rather than the smoke-tests. see #3588 for additional information about the motivation for that work.

on the flipside, we should also make some adjustments to facilitate writing tests against the `pd` server.

first, we should move the logic responsible for running a `RootCommand` from the `main.rs` binary artifact, to within the `pd` library. this follows the advice from Ch. 11 of The Rust Programming Language book:

> [**Integration Tests for Binary Crates**](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests-for-binary-crates)
>
> If our project is a binary crate that only contains a `src/main.rs` file and doesn’t have a `src/lib.rs` file, we can’t create integration tests in the tests directory and bring functions defined in the `src/main.rs` file into scope with a `use` statement. Only library crates expose functions that other crates can use; binary crates are meant to be run on their own.
>
> This is one of the reasons Rust projects that provide a binary have a straightforward `src/main.rs` file that calls logic that lives in the `src/lib.rs` file. Using that structure, integration tests can test the library crate with use to make the important functionality available. If the important functionality works, the small amount of code in the `src/main.rs` file will work as well, and that small amount of code doesn’t need to be tested.

#3672 made some initial headway on this. let's move the rest of our (a) tracing subscriber initialization, and (b) command logic, into a function somewhere in the `pd` library so that we can exercise this logic in integration tests someday.

* #3672
* #3588

**Comment by hdevalence** [comment]
Do we want to write tests of `pd`? I'm not sure that should be our goal. Our existing app-level integration tests are part of the `app` crate. What functionality should be in `pd` as a library rather than in the `app` crate?

**Comment by cratelyn** [comment]
> Do we want to write tests of `pd`? I'm not sure that should be our goal. Our existing app-level integration tests are part of the `app` crate. What functionality should be in `pd` as a library rather than in the `app` crate?

@hdevalence based on this comment and our conversation earlier today, i've renamed this issue. i believe the point stands that we want to pull much of the length `main.rs` startup into a place where we can effectively test it.

so, we'll aim to pull application logic into `app` rather than the `pd` binary.
