### ISSUE TITLE
Final, comprehensive review of existing Protobuf definitions

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3720]
**Is your feature request related to a problem? Please describe.**

Following Testnet 65, we want to not make any more breaking changes to Protobuf definitions. Additions and extensions are OK, but we want to use the Protobuf rules to have backwards compatibility.

So far, we've been working towards this by making various ad-hoc changes to the proto definitions, causing a lot of pain on the web side.

**Describe the solution you'd like**

Instead, we should do a comprehensive review and final change set, with a group of people doing a pairing session where we read through every `.proto` file and discuss together.

- [x] asset: Rename `DenomMetadata` to `Metadata`
- [x] asset: Rename `KnownDenom`/`UnknownDenom` `KnownAssetId`/..
- [x] ~~compact-block: investigate packed encoding~~ (only works for scalar types)
- [x] governance: use a oneof in `Proposal`
- [x] shielded-pool: rename `fmd_params` to `fixed_fmd_params` or ... `initial_fmd_params`
- [x] keys: rename `address_view::visible` to `address_view::decoded` + comments
- [x] custody: rename `CustodyProtocolService` to `CustodyService`
- [x] view: rename `ViewProtocolService` to `ViewService`
- [x] penumbra: remove `chain_id` field on rpc `Request*`s (See #3725)
- [x] ~~penumbra: rename proto packages to `v1beta1`~~ (EDIT(@hdevalence) - i'm not sure we should do this, maybe we wait and then jump right to `v1`)

**Comment by turbocrime** [comment]
nice to have: a 'witnessed' status to witnessAndBuild, and an 'authorized' and 'witnessed' status to authorizeAndBuild? or is it preferable to keep those statuses low-detail. i believe this would not be a breaking change

additionally i believe @jessepinho had a request about 'ics20withdrawal' being renamed somewhere, which would be a breaking change

**Comment by jessepinho** [comment]
re: `ics20Withdrawal` — see #3614

**Comment by turbocrime** [comment]
https://github.com/penumbra-zone/penumbra/issues/3734

**Comment by turbocrime** [comment]
provide unary equivalents of streaming requests that don't functionally require streaming https://github.com/penumbra-zone/penumbra/issues/3735

**Comment by turbocrime** [comment]
remove or explain authorization_data on AuthorizeAndBuild
