### ISSUE TITLE
View Service sometimes falls down and breaks chain scanning

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3732]
# View Service falls down and breaks chain scanning

In a long running client application that streams blocks from a Penumbra node, the client's ViewService can break, rendering it unable to process blocks. We've observed this in two situations:

* Galileo getting confused about off-by-one errors reported by pd when Galileo makes calls to a loadbalanced gRPC endpoint, e.g. `https://grpc.testnet.penumbra.zone`.
* The summonerd coordinator informing ceremony contributors that "bid amount 0 is too low" even though they did in fact bid a non-zero amount.

The latter scenario has been much more problematic, as a high number of people (>15k contributions at time of writing). As a quick hack to mitigate the "split" brain issues, we implemented a naive single retry in the view service worker: https://github.com/penumbra-zone/penumbra/pull/3291 That logic has since landed in main, and was included in the Testnet 64 release. It's insufficient for our needs in stabilizing the ceremony experience.

## Example error messages

Error received during ceremony contribution attempt:

> `Error: status: PermissionDenied, message: "Bid amount 0 is not large enough", details: [], metadata: MetadataMap { headers: {"alt-svc": "h3=":443"; ma=2592000", "content-type": "application/grpc", "date": "Fri, 02 Feb 2024 02:07:13 GMT", "server": "Caddy", "content-length": "0"} }`

**Comment by hdevalence** [comment]
Closed by #3730
