### ISSUE TITLE
protos(view): add status detail to `WitnessAndBuild` and `AuthorizeAndBuild`

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/penumbra#3734]
for witnessAndBuild and authorizeAndBuild, we could add either a field on `buildProgress` or an additional member of the `status` oneof, representing

1. authorization status (for AuthorizeAndBuild)
2. witness status (for both)

as these are identifiable sub-tasks of each, and it would be friendly to perhaps surface this information to the user.

it should be possible to add these fields/members later, and expect a client to ignore unknown status information.

there may be other progressive tasks that benefit from changes like this.

conceptually, i prefer additional fields on existing status, over additional oneof members.

**Comment by hdevalence** [comment]
I'm not sure if it's useful to separately report the witness status. Generating the witness data is extremely cheap, so it doesn't show up compared to proving time.
