### ISSUE TITLE
app: 🎋 missing `Sct` component hooks

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3739]
while reading through the `App` implementation, i noticed that the `Sct` component only ever has its `init_chain` and `begin_block` hooks called.

this isn't currently a bug, since its `end_block` and `end_epoch` hooks are no-ops, but could become one in the future if more logic was introduced to those trait methods.

this is an easy fix, but i'm filing this separately as an issue for reference in a tracking issue elsewhere.

**Comment by erwanor** [comment]
Related to #3712

**Comment by cratelyn** [comment]
@erwanor just to confirm, #3712 won't entail breaking changes to `cnidarium::Component`, is that right?

**Comment by erwanor** [comment]
That's right, that other ticket is about simplifying app-level handling of end-block/end-epoch. It doesn't require any change to the `Component` trait.

**Comment by cratelyn** [comment]
> That's right, that other ticket is about simplifying app-level handling of end-block/end-epoch. It doesn't require any change to the `Component` trait.

got it. thank you!

**Comment by cratelyn** [comment]
(_removed my assignment from this issue, to focus on tasks in [sprint 0](https://github.com/penumbra-zone/penumbra/milestone/31).
