### ISSUE TITLE
TCT makes use of field element internal representation in a potentially error-prone way

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3743]
https://github.com/penumbra-zone/penumbra/blob/59cdd7552dd4e50aea948328a79bc034c599fa1e/crates/crypto/tct/src/internal/hash.rs#L145

This line uses the fact that `Fq(2^256 - 1)`, using the arkworks implementation of that field, will return an "element" which is not equal to any other. Mathematically, this isn't a well defined operation considering `Fq` as a generic abstraction of that field, since that element will be equal to `Fq(2^256 - 1 mod q)` as well.

This might pose an issue when we start migrating the repo to use the latest version of `decaf377`, which contains a new backend, where a method to construct a field element from an unchecked internal representation may not be provided, or may not behave in the same way.

**Comment by cronokirby** [comment]
A very simple fix for this would be to instead pick a random element of `Fq`, and use that as a hardcoded constant here. (This constant could be defined in the decaf377 crate). The likelihood of that element ever getting produced by some other piece of code, including this, is indistinguishable from 0.

**Comment by cronokirby** [comment]
These are great points. Another great point raised by @plaidfinch in a discussion outside of Github was that this sentinel value can't be deserialized from bytes with a method that checks that the serialization of a field element is canonical. This safeguard against accidentally getting the sentinel value when parsing wouldn't be present with a random field element.

**Comment by cronokirby** [comment]
Another possibility which is beyond rust's capabilities right now would be to have an enum whose representation is [u64; 4], allowing us to have an Option<Fq> like type whose in-memory representation is the same as just Fq.

**Comment by cronokirby** [comment]
A fun point about semver is that arkworks is 0.4, so in theory we could get rug pulled, but oh well 8^)

**Comment by hdevalence** [comment]
Where did we end up on this?

**Comment by TalDerei** [comment]
> Where did we end up on this?

https://github.com/penumbra-zone/decaf377/pull/88/commits/db0124858be1554f7aee7e85286524d44fa9300b

**Comment by hdevalence** [comment]
OK, great! Wondering is this issue closed or is there still work we need to do?

**Comment by TalDerei** [comment]
> OK, great! Wondering is this issue closed or is there still work we need to do?

This issue can be closed!
