### ISSUE TITLE
ci: 😰  nightly regression breaking rustdoc build

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3750]
placeholder issue.

see #3749.

**Comment by cratelyn** [comment]
Fixed by #3749. thanks for bringing that one home @conorsch!

**Comment by conorsch** [comment]
Not resolved, docs builds still problematic. Reopening.

**Comment by conorsch** [comment]
Working docs build on main here: https://github.com/penumbra-zone/penumbra/actions/runs/7820567724 Keeping this issue open. Will check back in a week or two to drop the version pinning on the nightly toolchain.
