### ISSUE TITLE
tests: 🐣 mock consensus engine can perform an app handshake

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3754]
stub issue.

see #3588.

https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_comet_expected_behavior.md

we should implement functionality such that the mock consensus engine can bootstrap itself. it should be able to perform a handshake with the app, which will involve implementing the `info` and `init-chain` parts of ABCI.

* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#info
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#initchain

**Comment by hdevalence** [comment]
I'm not sure this is important, the mock consensus engine and the app state will never be out of sync since they'll be in the same test function.

**Comment by cratelyn** [comment]
_notes from call today:_
- we won't need `info`, at least initially

**Comment by cratelyn** [comment]
closing in favor of #3787.
