### ISSUE TITLE
tests: 🐤 mock consensus engine can perform a state sync

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3755]
stub issue.

requires #3754. see #3588.

once we can perform an app handshake, we should proceed to implement a state sync. this will involve implementing the following:

```
state-sync          = *state-sync-attempt success-sync info
state-sync-attempt  = offer-snapshot *apply-chunk
success-sync        = offer-snapshot 1*apply-chunk
```

source: https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_comet_expected_behavior.md

* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#offersnapshot
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#info
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#applysnapshotchunk

**Comment by erwanor** [comment]
We don't support state sync in the main application yet, so this is less important than supporting ordinary consensus execution (`consensus-exec` in the abci grammar)

**Comment by hdevalence** [comment]
I would go so far as to say we should not support this at all. We only need to be able to produce blocks and shouldn't plan to do more than that.

**Comment by cratelyn** [comment]
i thought "state sync" referred to the phase where the abci app must catch up with the chain. if the penumbra app doesn't do state sync, we shouldn't implement it. thanks all.
