### ISSUE TITLE
tests: 🍼 a placholder abci application for mock consensus engine development

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3756]
stub issue.

see #3588.

before we can connect the mock consensus engine up to pd itself, we should define a very _very_ simple abci app to act as a placeholder for its own tests & development.

the cometbft repository has an example key-value store, for example. for our sake, we can probably implement something even more straight-forward than that.

**Comment by hdevalence** [comment]
Is there a particular reason we don't want to start using the Penumbra `App` itself? It lives in the same repo, and it would ensure that we're designing against our actual requirements. We even already have a test that we could write a second version of using our new framework (`app/src/tests/spend.rs`).

**Comment by cratelyn** [comment]
closing out, #3788 will track porting the existing `spend.rs`test!
