### ISSUE TITLE
tests: 🔁 mock consensus engine generates blocks

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3757]
stub issue.

see #3588.

https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_comet_expected_behavior.md

in cometbft, the loop for generating blocks looks like so:

```
consensus-exec      = (inf)consensus-height
consensus-height    = *consensus-round finalize-block commit
consensus-round     = proposer / non-proposer

proposer            = *got-vote [prepare-proposal [process-proposal]] [extend]
extend              = *got-vote extend-vote *got-vote
non-proposer        = *got-vote [process-proposal] [extend]
```

* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#verifyvoteextension
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#finalizeblock
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#prepareproposal
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#processproposal
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#extendvote
* https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#commit

NB: because we are only supporting one validator to start, the voting and proposition process ~~should be simpler~~. (**edit:** or, as @hdevalence points out below, may not be needed at all)

in any case, we should implement the internals needed to generate successive blocks.

**Comment by hdevalence** [comment]
I think we should not aim to do this at all. The point of the mock engine is that it doesn't actually do consensus -- all the keys are recorded in memory -- so there are no consensus rounds to simulate. Our goal is not to simulate consensus, we are not trying to mock the Comet internals, we are trying just to drive the application state, by _not_ being Comet.

**Comment by cratelyn** [comment]
> I think we should not aim to do this at all. The point of the mock engine is that it doesn't actually do consensus -- all the keys are recorded in memory -- so there are no consensus rounds to simulate. Our goal is not to simulate consensus, we are not trying to mock the Comet internals, **we are trying just to drive the application state, by _not_ being Comet.**

i renamed this issue and tried to alter the description above. i am going to reopen this @hdevalence, because (_emphasis above mine_) i want an issue to track adding the ability to generate successive blocks.

**Comment by cratelyn** [comment]
one extra thought: a reason why i'd phrased this in terms of `consensus-exec` wasn't because i wanted us to implement consensus rounds, and voting in full, but to have that in mind as a future extension. apologies if that `NB` wasn't worded strongly enough.

i filed #3760 as a "future" issue, for thinking more about what support for multiple nodes in tests would look like. for the MVP though, it's definitely not worth doing.

**Comment by hdevalence** [comment]
Thanks for the clarification. I feel pretty strongly that we should not plan to do that, it is a massive increase in scope beyond what we need. If we want to build a network simulator in the future, we could plan it in the future, but it's a way bigger project and we should not leave open threads of work we have no plans to do.
