### ISSUE TITLE
Avoid change outputs for partial undelegations.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#377]
One effect of our unbonding design is that change outputs from undelegations cannot be distinguished from the unbonded stake, and so have to be quarantined for the entire unbonding period, so that it's possible for us to unwind a transaction in the event of slashing.

This makes partial undelegations potentially annoying, since a naive transaction construction might spend a note with X delegation tokens to undelegate Y < X of them, placing Z = X - Y as change in another output -- which would then be quarantined for the entire unbonding period. Oops.

We can avoid this at the cost of performing two transactions: when an undelegation of Y < X is requested, first create a transaction with a new output of exactly Y delegation tokens (and whatever other spends or change are required), then wait to receive that self-addressed note (via #376), then use that specific note to perform the undelegation without change.

Doing this will require adding a new `ClientState::note_to_spend_exact` method, analogous to the current `ClientState::notes_to_spend`, but rather than returning a `Result<Vec<Note>>`, it would return a single `Result<Note>`, failing if there was not a note with the exactly specified amount and denomination/assetid.

**Comment by hdevalence** [comment]
We should implement this prior to implementing note quarantining.

**Comment by plaidfinch** [comment]
Closing in favor of #1010. Using await-change, we now take a different approach, specifying the precise note commitment of the note we want to spend in the second transaction.
