### ISSUE TITLE
ics20: timeouts are faillible

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3774]
**Is your feature request related to a problem? Please describe.**
An invariant described in [shielded-pool(component): `transfer.rs:L522`](https://github.com/penumbra-zone/penumbra/blob/58f14d3fe08517a95ae9cdeddb4623e349f81927/crates/core/component/shielded-pool/src/component/transfer.rs#L522-L527) is that "timeouts should never fail".

Zellic reported that they were able to force it to return an error by causing an overflow via deposits.

STR:
1. User on chain B deposits $Q_1 = 2^{128} - 1$ coins to the host chain A.
2. The host chain mints $Q_1$ tokens.
3. The user submits a transfer back to A with either: an expired, or near-expired, timeout height.
4. The host chain decreases the supply by $-Q_1 = 0$
5. The user deposits $Q_2 >= 1$ tokens
6. The host chain mints $Q_2$ tokens.
7. The timeout handler for $-Q_1$ is triggered, the transfer is reverted.
8. The host chain attempts to mint $Q_1$ tokens, but since $Q_1 + Q_2 > 2^{128} - 1$ this checked operation fails
9. Since the top level invariant is violated, the node halts.

**Comment by erwanor** [comment]
It would be a huge milestone for us to be able to test this in a CI workflow, or an ordinary `#[test]`.

**Comment by conorsch** [comment]
We want to fix this issue immediately, but it would sure nice to add state machine tests for them. That test harness isn't ready yet, but on completion of this issue, a follow-up issue should be opened to remind us to write that test.

**Comment by cratelyn** [comment]
x-ref: #3588

**Comment by erwanor** [comment]
Changelog: @zbuc is driving and @avahowell is reviewer
