### ISSUE TITLE
Testnet 68: Deimos 3

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3784]
# Testnet Release

Testnet name: Deimos 3
Release date: 2024-02-26
Testnet release manager: @erwanor 

The Phobos release should exercise chain upgrades.

# Testnet Release Manager Checklist

Preceding Friday (sprint planning day):

- [ ] Create GitHub project column, work with team to populate the milestone with tickets targeted for the release.

Tuesday (or after release of previous testnet):

- [ ] Construct the genesis data for the release:
  - [ ] Create new testnet directory with initial genesis allocations for this testnet by running `cd testnets && ./new-testnet.sh`
    - This genesis data will be used for `testnet-preview` with a randomized version of the future testnet's chain ID.
  - [ ] Make sure that the chain _name_ is preserved: it should be `penumbra-testnet-deimos-3`.

Thursday:

- [ ] Check in with team again in a release meeting and update the GitHub milestone to ensure it represents what will make it into the testnet.
- [ ] Draft an announcement for peer review to ensure major changes included are comprehensive.

Following Monday (release day):

- [ ] Verify that `testnet-preview.penumbra.zone` is operational; it is redeployed on every push to main, and is an exact preview of what is about to be deployed.
- [ ] Add an entry to the `COMPATIBILITY.md` 
- [ ] Bump the version number and push its tag, via [cargo-release](https://crates.io/crates/cargo-release):
    - [ ] Enable direct pushes to main, temporarily, by unchecking "Do not allow bypassing the above settings" on the [branch protection page](https://github.com/penumbra-zone/penumbra/settings/branch_protection_rules/22169356).
    - [ ] Run `cargo release minor` for a new testnet, or `cargo release patch` for a bugfix. For the latter, make sure you're on a dedicated release branch.
    - [ ] Push the commit and newly generated tag, e.g. `v0.51.0`, to the remote.
    - [ ] Re-enable branch protection on main.
- [ ] Wait for the ["Release" workflow](https://github.com/penumbra-zone/penumbra/actions/workflows/release.yml) to complete: it'll take ~20m, after which the release URL will be live.
- [ ] Edit the newly created (and published) release object, then click "Generate release notes" and save it. 
- [ ] You must [manually review](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) the [`Waiting` deployment in the GitHub Actions UI](https://github.com/penumbra-zone/penumbra/actions/workflows/deploy-testnet.yml) before the deployment will begin. Monitor the GitHub action to ensure it completes after it is approved.
- [ ] Delegate to the Penumbra Labs CI validators; use amounts of ~200k `penumbra` per validator.
- [ ] Open a position to provide some initial liquidity: `pcli tx lp replicate xyk penumbra:test_usd 20000penumbra --current-price 20`
- [ ] Make the announcement to Discord! 🎉🎉🎉

**Comment by conorsch** [comment]
I've repurposed this issue to plan the new chain we intend to release on Monday, 2024-02-26: Deimos 3.

**Comment by erwanor** [comment]
Looks great, I added an entry for the `COMPATIBILITY.md`
