### ISSUE TITLE
Simplify governance proposal string handling

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3786]
The current implementation of string parsing for governance proposal data attempts to be promiscuous with input formats by mangling input data, for example:

```rust
impl FromStr for ProposalKind {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.replace(['-', '_', ' '], "").to_lowercase().as_str() {
            "signaling" => Ok(ProposalKind::Signaling),
            "emergency" => Ok(ProposalKind::Emergency),
            "parameterchange" => Ok(ProposalKind::ParameterChange),
            "communitypoolspend" => Ok(ProposalKind::CommunityPoolSpend),
            "upgrade_plan" => Ok(ProposalKind::UpgradePlan),
            _ => Err(anyhow::anyhow!("invalid proposal kind: {}", s)),
        }
    }
}
```

However this is fragile and bug-prone (there's a bug in the above example for `upgrade_plan`) and would be better replaced with a simple exact-string match, i.e. `"Signaling" => Ok(ProposalKind::Signaling)`.

There are several instances throughout the governance code that attempt this sort of fuzzy matching that should be replaced with simpler string matches.

**Comment by aubrika** [comment]
@hdevalence this should be added to the sprint - approved?
