### ISSUE TITLE
Compute genesis validator voting power from delegations in genesis

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#379]
Per https://github.com/penumbra-zone/penumbra/pull/362#discussion_r787356061, it makes things cleaner to not specify initial validator power in genesis, but rather by allocating delegation tokens to validators in the genesis allocations directly. This would eliminate the need for the `genesis::ValidatorPower` struct entirely, since this would be computed from the genesis allocations as needed.

**Comment by zbuc** [comment]
We should also make sure to update the genesis generation command to add the allocations to the output

**Comment by hdevalence** [comment]
This is done in the current code.
