### ISSUE TITLE
tests: 🧩 provide a block builder api in the mock consensus engine

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3792]
see #3588.

**Comment by hdevalence** [comment]
xref https://github.com/penumbra-zone/penumbra/issues/3816#issuecomment-1943031753

I think this might make sense to prioritize over the genesis data adjustment.

**Comment by cratelyn** [comment]
sounds good to me, i will work on this first. thank you for the heads up!

**Comment by cratelyn** [comment]
work-in-progress pr is at #3822. :hammer:
