### ISSUE TITLE
Extend ValueView to support "equivalent values"

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3795]
**Is your feature request related to a problem? Please describe.**

We would like frontend code to be able to work with "equivalent values" for assets. See discussion here: https://github.com/penumbra-zone/web/issues/446#issuecomment-1936338255

**Describe the solution you'd like**

Extend the `ValueView` protos with additional fields that can support all of the use cases in the linked comment.

A view server can then fill them in as desired. (We don't need to support this in the Rust view server, at least for the foreseeable future).

**Comment by conorsch** [comment]
Resolved by https://github.com/penumbra-zone/penumbra/pull/3800
