### ISSUE TITLE
staking: relax budget target circuit breaker

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3815]
**Context**
In #3663, we added a funding component which performs reward budget checks at the time of reward minting to validator funding streams. In particular, we have a circuit breaker enforcing that the total amount of reward distributed is less than the budgeted amount for that epoch.

At the same time, our mechanism to setup the chain base rate is forward-looking i.e. at epoch $e_{i}$ we decide of a base reward rate $r_{i+1} \coloneqq \frac {B_i} {T_i}$ where $T_i$ is the total active stake at epoch $e_i$.

**Problem**
The reward rate takes total stake as an input, however, the total stake amount can fluctuate between two epochs, sometimes dramatically so.

At a high-level, we treat the distribution as a hard limit, but it is better thought of as an estimation target. Indeed, there are cases when we will exceed that budget for legitimate reasons.

For example, zooming in, suppose that at epoch $e_{i+1}$ the total active stake increases such that $T_{i+1} > T_{i}$, this change will be recorded in reward calculations for epoch $e_{i+2}$ but the funding logic will attribute validator rewards to more total stake that the base rate had anticipated. This will result in a budget violation $k \cdot B_{i}$ by some fraction $0 \lt k \lt 1$

It would be nice to be able to do precise budget estimation, but the forward-rate calculation is an assumption baked in many places of the staking component, and indeed what will allow us to do dynamic issuance rate based on bonded stake targets.

**Solution**

We should `WARN` that the budget is exceeded, but not crash, this will allow us to keep an eye on that data.

**Comment by conorsch** [comment]
This work is largely complete, and we're considering making a point release (e.g. `v0.67.1`) to ship it. More discussion required.
