### ISSUE TITLE
staking: delegation tokens parsing is too permissive

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3827]
**Is your feature request related to a problem? Please describe.**
Zellic auditors have found that our delegation token parsing is too permissive. Indeed, since the regex does not specify `^` it will match anywhere in the denom string. This means that an IBC deposited asset that includes this denom string can then usurp voting on proposals, and possibly even more nefarious uses.

```rust
    let validator_identity =
        Regex::new("udelegation_(?P<data>penumbravalid1[a-zA-HJ-NP-Z0-9]+)")
             .expect("regex is valid")
             .captures(&base_denom.to_string())
             .ok_or_else(|| {
                 anyhow::anyhow!(
                     "base denom {} is not a delegation token",
                     base_denom.to_string()
                 )
             })?
```

**Solution**
Parsing should be stricter, both DRI and reviewer should use this as an opportunity to carefully check other load bearing regex in the codebase.

**Comment by zbuc** [comment]
I looked at the other usages of regex and didn't see any similar issues.
