### ISSUE TITLE
pd: support state tarball for joining nodes

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3841]
When chain upgrades are performed (#1804), pd state may be collapsed by a migration, such that late-joining nodes (i.e. nodes that join the network after the upgrade boundary has passed) will not be able to verify historical state. To support late-joining nodes, we must provide the capability for `pd testnet join` to accept compressed archives of historical pd state, and use them during bootstrapping.

Proposal: add new optional flag `--archive-url=<URL>` to `pd testnet join`. Doing so will allow late-joining nodes to pull down a compressed archive from a remote URL, and extract that archive as starting state for pd. 

Specifically, this requires:

* [x] Defining archive format and structure (e.g. "all files/directories should be extracted to `~/.penumbra/testnet_data/node0/pd`"). My understanding is we'll need at least 1) rocks db and 2) genesis file in all cases.
* [x] Providing hosting capability for future snapshots (ideally community validators will assist with this process, but we still need to host snapshots we create somewhere)
* [x] Write logic for `pd testnet join --archive-url <url>` - https://github.com/penumbra-zone/penumbra/pull/4055
* [ ] Write user-facing documentation for using the flag - https://github.com/penumbra-zone/penumbra/pull/4097
* [x] Write developer-facing documentation for storing and updating snapshots.

**Comment by hdevalence** [comment]
What's the advantage of doing this rather than providing a `.tar.xz` of the `pd` home directory?

**Comment by conorsch** [comment]
As I understand it, that's what the snapshot _is_: a compressed version of the rocksdb info that pd uses. It must also include a genesis file, which is not included in the pd home directory, but easy enough to overwrite when generating new configs. This ticket is essentially describing the need and the mechanism to "provide a .tar.xz of the pd home directory."

**Comment by hdevalence** [comment]
Got it, I was confused by the term "snapshot" because CometBFT has a notion of p2p snapshot exchange, which we're not currently using.

**Comment by conorsch** [comment]
Thanks, edited for clarity, `s/snapshot/archive/` throughout.

**Comment by erwanor** [comment]
Setting this to P-high since this is a requirement to perform a testnet upgrade (both for compaction and migrations) and must be assigned during sprint planning

**Comment by conorsch** [comment]
@erwanor I'll grab this one and give it a shot, trying to parallelize the work with what you've already got in flight on the upgrades front.

**Comment by conorsch** [comment]
Resolved via #4055, also #4093.

**Comment by conorsch** [comment]
>  Write user-facing documentation for using the flag.

Ah, still more to go. Working on this today.
