### ISSUE TITLE
dex: add `unfilled_input` to `SimulateTradeResponse`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3842]
**Is your feature request related to a problem? Please describe.**

See https://github.com/penumbra-zone/web/issues/566

**Describe the solution you'd like**

- [ ] Add `penumbra.core.asset.v1.Value unfilled_input = 2;` to the `SimulateTradeResponse`;
- [ ] Regenerate protos `./deployments/scripts/protobuf-codegen`;
- [ ] Edit the RPC handler to compute `unfilled_input` as `request.input - output.input` and return to the caller in the response data.

**Comment by erwanor** [comment]
This was done by @grod220 in #3917
