### ISSUE TITLE
staking: 🎏 remove `validator_definitions` method and refactor `rpc::validator_info` to use `consensus_set_stream`

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3846]
The staking component query service provides a `ValidatorInfo` RPC that returns the list of registered validators, optionally filtering `Inactive` validators.

The way this method is implemented is by using an internal `ValidatorDataRead::validator_definitions` methods which returns every single definition ever submitted to the chain. This is problematic because this list will inevitably grow quite large, turning usage of a benign-looking method into an onerous source of I/O and expensive rendering.

A better solution is to instead use `ConsensusIndexRead` and filter through validator definitions that are in the consensus set (i.e. validators that are in the active set, or eligible to be promoted into it).

On the other hand, this method is also used by validators to check that their submissions have been successfully recorded by the chain. To address this valid use case, we could create a `pcli query validator status` that `Defined` validator can use to inquire about their validator state. 

### :ballot_box_with_check: to do:
- [ ] Remove `ValidatorDataRead::validator_definitions` (the state accessor doing the prefix query, not the underlying store)
  * #4262
- [ ] Rework `penumbra_stake::component::rpc::validator_info` to use `ConsensusIndexRead ::consensus_set_stream`
  * #4262
- [ ] pcli(query): add `Status` to `ValidatorCmd`
  * #4263
  * https://github.com/penumbra-zone/penumbra/pull/4263#discussion_r1582437217

**Comment by erwanor** [comment]
We must make this change transparent to consumers of the service (web extension).

**Comment by hdevalence** [comment]
We should not aim to preserve API compatibility, we should instead just make it do the right thing, restricting to the list of validators above the minimum limit.

**Comment by cratelyn** [comment]
following up on this, after it came up in #4173:

`validator_definitions` returning a vector of every definition is useful (_and sometimes required_) for test logic, and saves test cases the need to repeatedly deal with polling an asynchronous stream to get a `&[Validator]` or `&[IdentityKey]` to make assertions upon.

i don't have strong opinions about how we present this information via RPC, but i'd hope we can preserve the friendly ergonomics in tests!

**Comment by erwanor** [comment]
We should assign this during sprint planning @cratelyn

**Comment by cratelyn** [comment]
> The staking component query service provides a `ValidatorInfo` RPC that returns the list of registered validators, optionally filtering `Inactive` validators.
> 
> On the other hand, this method is also used by validators to check that their submissions have been successfully recorded by the chain. To address this valid use case, we could create a `pcli query validator status` that `Defined` validator can use to inquire about their validator state.

@erwanor does it sound sensible to add an rpc method to ask about the status of a _single_ validator, without fetching the entire consensus set? this could let us return the validator info, including the status.

something like:

```diff
// Query operations for the staking component.
service QueryService {
+  rpc GetValidatorInfo(GetValidatorInfoRequest) returns (ValidatorInfoResponse);
  // Queries the current validator set, with filtering.
  rpc ValidatorInfo(ValidatorInfoRequest) returns (stream ValidatorInfoResponse);
  rpc ValidatorStatus(ValidatorStatusRequest) returns (ValidatorStatusResponse);
  rpc ValidatorPenalty(ValidatorPenaltyRequest) returns (ValidatorPenaltyResponse);
  rpc CurrentValidatorRate(CurrentValidatorRateRequest) returns (CurrentValidatorRateResponse);
}

+message GetValidatorInfoRequest {
+  core.keys.v1.IdentityKey identity_key = 2;
+}
```
