### ISSUE TITLE
penumbra: design more robust transaction checks

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3847]
**Is your feature request related to a problem? Please describe.**
In Penumbra, a `Transaction` is a collection of `Action`s, each with its own semantics and validity conditions, e.g., spending a note, uploading a validator definition, etc. These validity rules are encoded in the `ActionHandler` and can be decomposed into two steps:
- stateless verification: checking invariants that don't require access to the application state, e.g., checking bound conditions, verifying a signature.
- stateful verification: checking invariants that require access to the application state, e.g., public inputs to a proof, nullifier set membership, etc.

Crucially, the stateful checks are executed against a pinned snapshot of the application state. On one hand, this approach provides us with convenient data consistency guarantees. But on the other, it means that transaction stateful verification doesn't take into account the effects of its sub-actions.

This is a common vulnerability pattern that has been reported during audits of the application logic, which consists of crafting transactions that incorporate conflicting actions, e.g., double validator definition uploads

**Potential solution**
We have yet to find a solution that doesn't significantly impact full node performance, but here's a simple way to solve this: We can force a stateful check to occur before executing individual actions.his would create I/O overhead where there was none before, as we would maintain fail-fast concurrent stateful checks but add this additional redundancy. The advantages of this approach are that it's simple and robust. The downside is that it imposes a redundant cost.

**Comment by hdevalence** [comment]
I don't think this needs any redesign of the execution model. We can already handle this in execute, which is fallible for this reason — and is how IBC actions are handled.

In the case of this specific bug, there are two possible things that could have been done:

- Treat position IDs as akin to nullifiers (check all in parallel and then also check no overlaps within transactions).

- Have the "add a new position" method check that the position does not exist when writing it out.

In terms of a general solution, I think what we need is to have written justifications for each of the checks we do and why stateless/stateful/execution is the right place for them to live.

**Comment by erwanor** [comment]
Sounds good, closing this ticket in favor of #3855. There's also the case of validator definitions with conflicting consensus keys, which is why i thought we would want to always run an action stateful check before executing that action.
