### ISSUE TITLE
dex: don't close `Withdrawn` positions

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3850]
Zellic found a bug in the implementation of `PositionManager::handle_limit_order` which can cause `Withdrawn` positions to be reset to `Closed` if they match the reserve conditions. This is extremely problematic, because `position::Withdrawn` is a terminal state.

Moreover, combined with too permissive stateful checks, this bug can be escalated into an inflation bug (see #3847)

An immediate fix for this bug is to simply check that a position state is not `Withdrawn` before setting its state to `Closed`.

**Comment by hdevalence** [comment]
I agree this is extremely problematic. I'm unsure how it happens. Under what conditions can a withdrawn position be reset to closed? That seems deeply wrong, and like checking the position state is not `Withdrawn` is a too-late fix.

**Comment by erwanor** [comment]
The limit order logic will check if a position reserves and close the position if one of them is empty. In doing so, it unconditionally overwrites the position state to `Closed` before writing it back to storage. This means that `put_position(Withdrawn)` eventually resolves to `put_position(Closed)`.

At a minimum I think it's a sign we should make the state machine in `put_position` more explicit, like for example by restructuring the method around a `match position.state`, alternatively we could also rip out the limit order logic altogether and reduce surface.

**Comment by hdevalence** [comment]
What if we just don't auto close the "limit order" positions? That feature is what added this bug, it wasn't part of the original design and I don't think we thought through the implications.

But if we just don't mutate the position state while writing it, the whole problem goes away. If there's demand for the feature we could add it back later.

**Comment by hdevalence** [comment]
Closed by #3944
