### ISSUE TITLE
dex: define LP state machine

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3851]
In #3850 , we reported that Zellic had found that an attacker could craft positions such that `Withdrawn` positions could be wound back to `Closed` and described a minimal fix.

This highlight an issue with our LP handling. We should make the LP state machine more explicit, with an `update_lp(old_state, new_state)` method that enforces that we don't erroneously apply an illegal transition.

**Comment by hdevalence** [comment]
I'm wondering if we could avoid doing this entirely by cutting scope: https://github.com/penumbra-zone/penumbra/issues/3850#issuecomment-1977300433

**Comment by hdevalence** [comment]
#3944 fixes the problem, the rest is left as unplanned.
