### ISSUE TITLE
staking: validator definitions with conflicting consensus keys

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3858]
**Is your feature request related to a problem? Please describe.**
Similar to #3855, Zellic found that it is possible to craft a transaction with two actions that refer to distinct identity keys but conflicting consensus keys. This is a high-priority fix, because CometBFT will halt if presented with duplicate consensus identities.

**Comment by hdevalence** [comment]
We already have logic to prevent duplicate consensus keys. Did it not work here?

**Comment by erwanor** [comment]
@hdevalence This is another TOCTOU hazard, where it's possible to have two actions that use different identity keys (= different definitions) but colliding consensus keys.

**Comment by zbuc** [comment]
We check the consensus key isn't a duplicate in the `verify_stateful` method for the `ValidatorDefinition` action so this is a little surprising. I'll try to replicate

**Comment by hdevalence** [comment]
verify_stateful is precisely where the TOCTOU comes from — its parallelized

**Comment by hdevalence** [comment]
see eg the comments in the actionhandler impl in #3883

**Comment by hdevalence** [comment]
We will do #3960 instead.
