### ISSUE TITLE
shielded-pool: check balance commitment for dummy spends

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3873]
**Is your feature request related to a problem? Please describe.**
Similar to #3859. The bug is that the balance commitment check for dummy notes is skipped, so you can put anything you want it and then create a corresponding `Output` action that will net out to zero (on paper).

**Comment by hdevalence** [comment]
This isn't just similar to, but is exactly the same bug as that issue. Closing as duplicate.
