### ISSUE TITLE
mock-consensus: 1️⃣ report non-zero status codes as errors

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3876]
in #3866, i noticed that a non-zero status code in the response is not reported as an error in tests. see this log:

```
2024-02-23T02:55:09.755882Z  INFO penumbra_app::server::consensus: deliver_tx failed, e: binding signature failed to verify

Caused by:
Invalid signature.
at crates/core/app/src/server/consensus.rs:210
in penumbra_mock_consensus::abci::deliver_tx
in penumbra_mock_consensus::block::execute with height: 1, time: 1708656909
```

we should make sure that this results in an error when calling `BlockBuilder::execute`.

**Comment by hdevalence** [comment]
No, I think that's the correct behavior — DeliverTx is fallible. Blocks can include transactions that fail to execute (and this has to be the case, because prior to PrepareProposal there's no way for the application to control transaction inclusion).

**Comment by cratelyn** [comment]
do you think that this should include the `BlockBuilder::execute` helper though? what i'm worried about with this issue is that, as part of my work on #3866, i noticed that the spend transaction was failing silently.

i expect that in the majority of "happy path" cases, we would want to know about a transaction that failed to execute, right?

for test cases that do want to send an invalid transaction to the app, they could still rely on the [`abci`](https://github.com/penumbra-zone/penumbra/blob/main/crates/test/mock-consensus/src/abci.rs) submodule, and send the `deliver_tx` request themselves, inspecting the response to confirm that e.g. it was ruled invalid as expected.

**Comment by hdevalence** [comment]
I'm not sure — and I'm not sure we should overthink it, since if we move to current ABCI this interface all changes anyways.

One question I have is, why is it important for a test to know whether the transaction succeeded or not? Wouldn't we want to be writing assertions about the _effects_ of the transaction, rather than reliance on a self described success code? And in that case do we need this anyways?

For instance, in the spend case, wouldn't we want to write an assertion that, following the block, the nullifier is present in the state, that the MockClient detects the new output note, etc?

**Comment by cratelyn** [comment]
> [..] why is it important for a test to know whether the transaction succeeded or not? Wouldn't we want to be writing assertions about the _effects_ of the transaction, rather than reliance on a self described success code? And in that case do we need this anyways?
> 
> For instance, in the spend case, wouldn't we want to write an assertion that, following the block, the nullifier is present in the state, that the MockClient detects the new output note, etc?

my guiding principle here is that testing tools should report errors eagerly, to make testing happy paths more ergonomic. to your point, swallowing this error, while the correct choice in production to keep the application running, places the burden on test writers to write these assertions.

we _should_ write assertions about the outcome of a transaction (_it's part of the benefits you outlined [here](https://github.com/penumbra-zone/penumbra/issues/3588#issuecomment-1930965418_), but if it is a mandatory part of writing tests, it raises the burden of doing so, and lowers the ceiling of how much we ~can~ will test.

if effects have to be manually inspected though, i fear that we might run into false positives. i want to avoid an interface that leads people to believe they are providing assurance, where an error isn't being surfaced. i only discovered that the spend wasn't being performed by running tests with `--no-capture` set.

does propagating errors when `execute` is called prevent us from writing any particular tests? are invalid transactions part of the application's regular operation?
