### ISSUE TITLE
 Implement Prometheus Metrics for Rust View Server

### ISSUE THREAD

**Issue by bharatgoyal11** [penumbra-zone/penumbra#3925]
Issue:
Currently, project lacks comprehensive metrics for monitoring the performance of the Rust view server. Adding Prometheus metrics will provide valuable insights into the server's health, resource utilization, and request handling, enabling better monitoring and troubleshooting. This enhancement aligns with our goal of improving observability and reliability across project components.

Tasks:

Research: Investigate best practices for instrumenting Rust applications with Prometheus metrics.
Design: Define a set of custom metrics to track important server metrics such as request latency, error rates, and resource usage.
Implementation: Integrate Prometheus metrics instrumentation within the Rust view server codebase.
Integration: Incorporate the Prometheus server for collecting and visualizing metrics data.
Testing: Thoroughly test the Prometheus metrics integration to ensure accuracy and reliability.
Documentation: Document the Prometheus metrics setup and usage for developers and operators.

**Comment by conorsch** [comment]
Blocked by impending rewrite of the view server, to make it easier to test. Once we land that refactor, we should be in a better position in instrument behavior—and ideally we can even make assertions of those metrics in the new test suite.

**Comment by hdevalence** [comment]
We don't have an intended consumer for these metrics at the moment, so we'll close this as not planned. We should also avoid rewriting the view server.
