### ISSUE TITLE
undelegate-claim bug

### ISSUE THREAD

**Issue by isunfox** [penumbra-zone/penumbra#3926]
The epoch is 80 now,my account has balance as follows:
0 8888uunbonding_epoch_80_penumbra
0 999uunbonding_epoch_60_penumbra

I want to  undelegate-claim, It claim 8888uunbonding_epoch_80_penumbra first.
 can't claim 999uunbonding_epoch_60_penumbra

**Comment by erwanor** [comment]
Thanks for filing an issue describing the problem. This is a known limitation of the `undelegate-claim` pcli command, it doesn't let you select which unbonding tokens to undelegate first, and has a bug that can occur when processing multiple undelegations (#3622). We might get to fixing this eventually, but our client efforts are focused on our browser extension at the moment.
