### ISSUE TITLE
docs: 📙 add information about transaction model

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3951]
https://discord.com/channels/824484045370818580/883455571003576320/1214336481473200178

today we had a lively discussion about the transaction model, the different kinds of actions, and how these fit together to "balance" a transaction.

we should record some of the helpful information that finch & henry wrote down, in the protocol specification and documentation comments.

**Comment by cronokirby** [comment]
To what extent does https://github.com/penumbra-zone/penumbra/pull/3990 close this?

**Comment by cratelyn** [comment]
> To what extent does #3990 close this?

oh neat! i'll mark this as completed.
