### ISSUE TITLE
view: 🗼 `Planner::plan_with_spendable_and_votable_notes()` does not reset fee tiers

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3955]
https://github.com/penumbra-zone/penumbra/blob/98c42d8f09200ed41771c4dad91e5997bb4a0cab/crates/view/src/planner.rs#L45-L54

there is a comment on `Planner` that notes that new fields should be reset when a plan is produced. this came from aa942e699a in #3647.

we should reset that here: https://github.com/penumbra-zone/penumbra/blob/98c42d8f09200ed41771c4dad91e5997bb4a0cab/crates/view/src/planner.rs#L676-L683

**Comment by hdevalence** [comment]
We should not do this, and do #3896 instead, it's not worthwhile to fix up code we are planning to remove.
