### ISSUE TITLE
`ViewService#unbondingTokens`

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/penumbra#4006]
## Is your feature request related to a problem? Please describe.
We need a way to request unbonding tokens from the view service, broken out by claimable and unclaimable tokens, so that the web app's Staking page can show the two separately and allow the user to claim just the claimable ones.

## Describe the solution you'd like
This could be represented with a response of the following shape:

```protobuf
message UnbondingTokensResponse {
  repeated core.asset.v1.ValueView claimable = 1;
  repeated core.asset.v1.ValueView unclaimable = 2;
}
```

...where `claimable` is an array of unbonding tokens that are currently eligible for claiming, and `unclaimable` is an array of unbonding tokens that are currently ineligible for claiming.

## Describe alternatives you've considered
@erwanor and I discussed adding methods to `StakingService` instead (or in addition to this method) that could help determine which of the user's unbonding tokens are eligible for claiming and which aren't.

For example, we could create a `StakingService#isEligibleForClaiming` method. We'd pass it a `ValueView` of one of the user's unbonding tokens, and it'd return back a `bool` indicating whether that unbonding token is eligible for claiming. But that'd be a bit unergonomic for clients, since they'd have to make one request per unbonding token that the user holds.

Alternatively, we could create a `StakingService#claimableHeight` method. We'd pass it a `ValueView` of one of the user's unbonding tokens, and it'd return back a `uint64` indicating the height at which that unbonding token is eligible for claiming. This is probably even more unergonomic, though, since the client would need to get the current block height, and still make one request per unbonding token.

## Open question: how do we handle penalties?
At the moment, in the web app, [we request the penalty for a given validator at the moment that we make an undelegate claim request](https://github.com/penumbra-zone/web/blob/main/apps/minifront/src/state/staking/assemble-undelegate-claim-request.ts#L21-L32). It seems that validator penalties are cumulative across epochs — that is, the size of a penalty depends on which epoch you're claiming the unbonding token in. So, there isn't really a meaningful way to indicate what the penalty will be for an unbonding token until the moment the user decides to claim it, since the epoch can change at any time. That said, we could show what the penalty _would_ be if the user were to claim them in the current epoch.

All of that to say, should we include some info about penalty in this RPC's response? i.e., instead of the response's `claimable` array being an arrays of `ValueView`s, it could be an array of `ClaimingInfo`s:

```protobuf
message UnbondingTokensResponse {
  message ClaimingInfo {
    core.asset.v1.ValueView unbonding_token = 1;
    core.component.stake.v1.Penalty penalty = 2;
  }

  repeated ClaimingInfo claimable = 1;
  repeated core.asset.v1.ValueView unclaimable = 2;
}
```

I suspect, though, that we shouldn't include penalty info in the response. In the web app, the `ViewService` is implemented locally, which means that the current epoch that `ViewService` knows about might not even be accurate, since it might still be syncing. Instead, the approval dialog can just show the penalty, and that's enough.

**Comment by erwanor** [comment]
With #3738 unbonding tokens will be parameterized based on the height at which unbonding began, and they will be claimable:
- after an `unbonding_delay` (in # of blocks) has elapsed if the pool is bonded
- immediately if the pool is unbonded 

This means you should always be able to know _when_ the notes will be claimable. The penalty is cumulative between across epochs, but specifically between the epoch in which unbonding began and the one in which unbonding ended. In other words, it is not based on when the user submits the claim, but based on when the claim is allowed.

For the specific implementations, I think we should have a view service method and maybe a more general staking service one that expose the logic in [compute_unbonding_height](https://github.com/penumbra-zone/penumbra/blob/erwan/3738_unbonding_work_better/crates/core/component/stake/src/component/validator_handler/validator_store.rs#L150)
