### ISSUE TITLE
`PositionExecution` events do not appear in indexer

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4007]
**Describe the bug**

The DEX is supposed to emit `PositionExecution` events as it executes. However, these events don't appear in the indexer.

**To Reproduce**

On `deimos-5`, I created a liquidity position `plpid1cr5cxr7dt8qwwjx8lmgfjnxea3fmxn7kzlw46pnk4pt5c384nw6qajqzr0` that was intentionally mispriced. Its initial reserves were 232.897367penumbra, 0test_usd. Creation transaction is here: https://cuiloa.testnet.penumbra.zone/transaction/360cf15d5fedf532f1c2dfc2d3245354780ef3ba8218eb8b46a9c10ecf0dfede

In block 64883, this was submitted against and then arb'd to have reserves 700.935094560192616373test_usd

The ProtoJSON for that LPID is `{"inner":"wOmDD81ZwOdIx/7QmUzZ7FOzT9YX3V0GdqhXTET1m7Q="}`.

After closing and withdrawing, I saw
```
penumbra=# SELECT *
FROM events
WHERE events.rowid IN (
  SELECT event_id
  FROM attributes
  WHERE value = '{"inner":"wOmDD81ZwOdIx/7QmUzZ7FOzT9YX3V0GdqhXTET1m7Q="}'
);
 rowid | block_id | tx_id |                         type
-------+----------+-------+------------------------------------------------------
 17255 |     3576 |   400 | penumbra.core.component.dex.v1.EventPositionOpen
 24719 |     5322 |   528 | penumbra.core.component.dex.v1.EventPositionWithdraw
 24695 |     5316 |   527 | penumbra.core.component.dex.v1.EventPositionClose
(3 rows)
```
in the events DB. showing that there were other events but not `EventPositionExecution`. None of those seem to appear in the DB:
```
penumbra=# select * from events where type = 'penumbra.core.component.dex.v1.EventPositionExecution';
 rowid | block_id | tx_id | type
-------+----------+-------+------
(0 rows)
```
Looking for block-scoped events, we see
```
penumbra=# SELECT e.*
FROM events e
JOIN blocks b ON e.block_id = b.rowid
WHERE b.height = 64883 AND e.tx_id IS NULL;
 rowid | block_id | tx_id |                       type
-------+----------+-------+--------------------------------------------------
 17220 |     3576 |       | block
 17221 |     3576 |       | penumbra.core.component.dex.v1.EventArbExecution
 17222 |     3576 |       | penumbra.core.component.sct.v1.EventAnchor
 17223 |     3576 |       | penumbra.core.component.sct.v1.EventBlockRoot
(4 rows)
```
so while we see the `EventArbExecution` we don't see any `EventPositionExecution`.

The events are supposed to be emitted here: https://github.com/penumbra-zone/penumbra/blob/main/crates/core/component/dex/src/component/router/fill_route.rs#L410

**Expected behavior**

The emitted events should appear in the event database. Where are they being dropped?

**Additional context**

Blocks progress on the dex explorer

**Comment by hdevalence** [comment]
It would be useful to pull up logs scoped to block 64883 from a single validator to try to find out where the events are getting dropped.

**Comment by conorsch** [comment]
Voila: https://gist.github.com/conorsch/79a799270fb8d5e27c0dc57034adc950

**Comment by conorsch** [comment]
We see several ABCI events emitted in the logs, matching the db contents above:

```
❯ rg 'event\{[^\}]+\}' val-logs.txt -o --no-line-number | sort | uniq -c
      2 event{kind="penumbra.core.component.dex.v1.EventArbExecution"}
      2 event{kind="penumbra.core.component.sct.v1.EventAnchor"}
      2 event{kind="penumbra.core.component.sct.v1.EventBlockRoot"}
```

But nowhere do we see an EventPositionClose, as we'd expect. Why not?

**Comment by conorsch** [comment]
Zooming out from specifically block 64883, I do see `EventPositionClose` events:

```
2024-03-12T04:26:10.563034Z  INFO abci:DeliverTx{txid="6724c368a0c9d8f27b31aa1590f73fe834981f43b7481b2961ca90df837e582c"}:event{kind="penumbra.core.component.dex.v1.EventPositionClose"}: penumbra_app::server::consensus: k="positionId" v="{\"inner\":\"wOmDD81ZwOdIx/7QmUzZ7FOzT9YX3V0GdqhXTET1m7Q=\"}"
2024-03-12T04:26:10.565676Z  INFO abci:DeliverTx{txid="6724c368a0c9d8f27b31aa1590f73fe834981f43b7481b2961ca90df837e582c"}:event{kind="penumbra.core.component.dex.v1.EventPositionClose"}: penumbra_app::server::consensus: k="positionId" v="{\"inner\":\"wOmDD81ZwOdIx/7QmUzZ7FOzT9YX3V0GdqhXTET1m7Q=\"}"
```

So we know those events are at least sometimes emitted and ingested as we'd expect, which is encouraging.

**Comment by conorsch** [comment]
Ah, right, my mistake. Searching for `EventPositionExecution` shows zero results over the past week. Will need to tinker on a local devnet to try to coax an event out.
