### ISSUE TITLE
Make freshstart script for prod deployment

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#401]
The freshstart script is designed for local development deployment and expects a local database to exist.

We should create a production freshstart script. This would be very simple:

- [ ] Set the DATABASE_URL env var
- [ ] Run sqlx migrations, exit if any errors
- [ ] Run the testnet generate command

**Comment by redshiftzero** [comment]
seems like this exists now (https://github.com/penumbra-zone/penumbra/blob/main/scripts/docker_compose_freshstart.sh), closing

**Comment by zbuc** [comment]
@redshiftzero this task is to update or fork that script for production support, right now it expects you to be running Postgres in a docker container locally which is not how our prod testnet deployments work

**Comment by zbuc** [comment]
Basically, the script is suitable for running local testnets for development, but prod is configured slightly differently.

**Comment by redshiftzero** [comment]
ahh ok, thanks for clarifying

**Comment by hdevalence** [comment]
We might want to wait to do this until after removing Postgres from the deployment setup.

**Comment by zbuc** [comment]
This can probably just be documented in the guide, here's the block I've been using for resetting testnets:

```
docker-compose stop
rm -rf ~/scratch/testnet_build/node0/tendermint/data/
rm -rf ~/scratch/testnet_build/node0/pd/rocksdb
mkdir ~/scratch/testnet_build/node0/tendermint/data/
echo -n '{}' > ~/scratch/testnet_build/node0/tendermint/data/priv_validator_state.json
/root/.cargo/bin/cargo run --release --bin pd -- generate-testnet
chmod -R 777 ~/scratch/testnet_build
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
```

**Comment by hdevalence** [comment]
This was rolled into `pd testnet generate` a while ago.
