### ISSUE TITLE
undelegate error

### ISSUE THREAD

**Issue by isunfox** [penumbra-zone/penumbra#4014]
1.pcli view balance
 # 0      120.925mpenumbra                                                                              
 # 8      4027.45812delegation_penumbravalid14clrf3u5y63939pw5a0u9eqx8femp4m69naujg77avse3m9t2v8qe5sv4t

2.try to undelagate 
pcli tx undelegate 4027.45812delegation_valid14clrf3u5y63939pw5a0u9eqx8femp4m69naujg77avse3m9t2v8qe5sv4t --source 8

Error: cannot represent this value

pcli tx undelegate 4027delegation_valid14clrf3u5y63939pw5a0u9eqx8femp4m69naujg77avse3m9t2v8qe5sv4t --source 8      
Error: unknown asset id passet1tzzq32kygspkd6rg6ehekgrza9dtes4rrycpyzrq4peq03drcqpsqyje0w

**Comment by erwanor** [comment]
`pcli tx undelegate 4027delegation_valid14clrf3u5y63939pw5a0u9eqx8femp4m69naujg77avse3m9t2v8qe5sv4t --source 8`

should be

`pcli tx undelegate 4027delegation_penumbravalid14clrf3u5y63939pw5a0u9eqx8femp4m69naujg77avse3m9t2v8qe5sv4t --source 8`
