### ISSUE TITLE
can't unjail

### ISSUE THREAD

**Issue by isunfox** [penumbra-zone/penumbra#4015]
5002.672 0.00% 200bps Inactive Unbonded penumbravalid14clrf3u5y63939pw5a0u9eqx8femp4m69naujg77avse3m9t2v8qe5sv4t   XPool

I have unjail  10 hours ago,but it's Inactive

**Comment by cratelyn** [comment]
this sounds like a question about using a Penumbra testnet. i would recommend asking over in the Discord server, which has dedicated channels for questions about running a validator. see the [_getting involved_](https://github.com/penumbra-zone/penumbra?tab=readme-ov-file#getting-involved) section of the readme.
