### ISSUE TITLE
rate_data needs to return **most recent** rate data per given epoch

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#402]
Currently the `pub async fn rate_data(&self, epoch_index: u64) -> Result<Vec<RateData>>` function will retrieve rate data **only** for the given epoch. If no rate data for a validator exists in the given epoch, it won't be returned.

This needs to be updated to return the **most recent** rate data to the given epoch, so that currently inactive validators are represented in the response.

This can likely be accomplished by modifying the existing query to join two subqueries: one for the most recent rate data and one for the specified epoch.

**Comment by hdevalence** [comment]
Closed as stale
