### ISSUE TITLE
Update CometBFT to v0.37.5

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#4021]
We've been using cometbft v0.37.2 since Penumbra v0.62.0, in 2023-10 (11f6efe5f14ce02786836cc97a3019e1f0d02ae6). Since then there have been several patch releases that we've not evaluated. The most recent, [v0.37.5](https://github.com/cometbft/cometbft/blob/v0.37.5/CHANGELOG.md#v0375), contains changes to blocksync that may result in faster sync times for nodes. 

Let's try it out on preview, and see how it goes. If smooth, we should follow up and update the documentation to mention the minor version bump. Since these are patch releases, they should be backwards-compatible, so we don't need to require node operators to update. Still worth a mention in relevant release notes, though.

**Comment by conorsch** [comment]
> The most recent, [v0.37.5](https://github.com/cometbft/cometbft/blob/v0.37.5/CHANGELOG.md#v0375), contains changes to blocksync that may result in faster sync times for nodes.

Initial results are promising: two fresh fullnodes syncing against current testnet are at height 10k & 13k, for 0.37.2 & 0.37.5 respectively. Last time we measured this, [per docs](https://guide.penumbra.zone/main/pd/debugging.html#how-long-does-it-take-to-synchronize-with-the-network), we saw:

> A new node will sync at a rate of approximately 50,000 blocks per 24h.

Will wait for the nodes to sync to full height and update accordingly.

**Comment by conorsch** [comment]
The `v0.37.5` node took only ~6h to sync to full height of 111,000, during which period the `v0.37.2` node made it to height 72,000. The `v0.37.2` node reached 111,000 after about ~10h. Not only does that show a dramatic improvement in sync times between versions of CometBFT, it also represents much faster fullnode syncing than the previous time we documented it.

**Comment by erwanor** [comment]
Amazing!
