### ISSUE TITLE
dex: move value circuit breaker accounting to dex engine boundaries

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#4025]
Currently the DEX value circuit breaker is implemented within `put_position`, however this has two drawbacks:

1. Misuse resistance -- what if some code modified positions without calling `put_position`? I audited the codebase for any patterns like this during the initial implementation and couldn't find any, however it could appear in the future. However that seems like a "dark pattern" in general as `put_position` has various other state machine checks and handles updating indices and liquidity
2. More importantly, an implementation at the boundaries will be significantly more efficient, as not every position update requires updating and checking the value circuit breaker

Instead, there are only two places that value flows into the dex and two places value flows out:

**IN:**
* swap inputs
* opened liquidity positions

**OUT:**
* swap outputs
* withdrawn positions

If we move the value circuit breaker management to the entry points for those operations, we are guaranteed to check that dex inflows > outflows and get the same assurance with fewer CPU cycles.

**Comment by erwanor** [comment]
Just a note: this is state breaking because we want to split tracking of asset balances into individualized state keys that map asset id to an Amount. Another reason to do this soon is that we want to fix the delta_2 bug asap, and point Zellic to the actual value breaker approach that we will use.
