### ISSUE TITLE
staking: move uptime tracking to nonverifiable storage 

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4030]
**Is your feature request related to a problem? Please describe.**
Every block, we track each active validator's uptime over the past 10k blocks in an `Uptime` bitmap that we write to the JMT. Each entry is about 1.2KB, and since there are 80 active validators we have (without considering merkle amplification), this gets us at about 96KB per block.

We could limit state growth by tracking validator uptime in nonverifiable storage instead.

**Comment by hdevalence** [comment]
This is about 12GB per week: https://www.wolframalpha.com/input?i=96KB+*+%287+days+%2F+5+seconds%29

**Comment by conorsch** [comment]
Most recent estimate for node storage is that it grows by ~20GB/week, so making this change would reduce total storage needs by over half.
