### ISSUE TITLE
tests: 🖋️ mock consensus engine can test validator uptime measurements

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#4040]
stub issue, see #3588. see #3995.

currently, the consensus keys in the keyring are not used by either the test node or block builder to sign blocks. we should introduce the ability to sign blocks, in order to test e.g. the staking component.

see section 8a in #3995. we will likely need to do some requirements discovery as part of that work, which should drive the fix to this issue.

* #4061
* #4070
* #3995
* #3588
* #4099

**Comment by erwanor** [comment]
One thing to note is that the application doesn't actually verify signatures on blocks, it takes it as granted from the consensus layer (same for byzantine misbehavior evidence) so as long as mock consensus produces legible commit information (containing `VoteInfo`s) the application will be able to track the uptime accurately.

**Comment by cratelyn** [comment]
> One thing to note is that the application doesn't actually verify signatures on blocks, it takes it as granted from the consensus layer (same for byzantine misbehavior evidence) so as long as mock consensus produces legible commit information (containing `VoteInfo`s) the application will be able to track the uptime accurately.

this is very helpful to know, thank you!
