### ISSUE TITLE
Add consensus rule forcing at least 2 spends and at least 2 outputs

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#405]
The motivation for this rule:

1. If we don't require all transactions to contain at least 2 spends, an observer can differentiate between penumbra-only transactions, which can have only one spend, and other-asset transactions, which must spend some amount of penumbra as a fee, and also spend the other asset.
2. If we don't require all transactions to contain at least 2 outputs, an observer can differentiate between transactions which produced change and transactions which did not.

Implementing this change will mean:

- [x] #1005
- [ ] Alter the `pcli` transaction builder to construct dummy spends and outputs when necessary
- [ ] Add the consensus rule to the stateless transaction validation logic

Open questions:

1. Should this apply to *all* transactions, including delegation/undelegation transactions?
2. Are there other obfuscations necessary (e.g. randomizing order of spends or outputs)?

**Comment by plaidfinch** [comment]
This is connected to #994.

**Comment by redshiftzero** [comment]
After the analysis in #1503, we've decided to proceed with implementing SpendN, OutputN actions (for N=>2) which will replace Spend and Output actions. This obviates the need to ensure there are always 2 spends and 2 outputs since we get that for free with Spend2 and Output2.

**Comment by redshiftzero** [comment]
Reopening this because we decided not to proceed with #1503 for mainnet

**Comment by hdevalence** [comment]
I don't think there's a pressing need to do this.
