### ISSUE TITLE
dex: make `SimulateTrade` pull its routing parameters from the engine

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4060]
**Is your feature request related to a problem? Please describe.**
@hdevalence noted that since `RoutingParams` are constructed ad-hoc in the `simulate_trade` impl:

```rust
        let routing_params = match routing_strategy {
            Setting::Default(_) => RoutingParams::default(),
            Setting::SingleHop(_) => RoutingParams {
                max_hops: 1,
                ..RoutingParams::default()
            },
        };
...

```

There might be undetected divergence between the parameters that the engine actually uses and the ones that the trade simulation RPC use to process queries.

**Comment by hdevalence** [comment]
Closed as part of #4066
