### ISSUE TITLE
Audit balance commitments for each action and ensure the protocol spec matches

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4076]
**Is your feature request related to a problem? Please describe.**

Before mainnet, we should audit all of the balance commitments for each action, and ensure that the protocol spec matches the code.

This should close https://github.com/penumbra-zone/penumbra/issues/1553 as a side effect.

Some of this work may have already been done as part of other assurance work, in which case we can check it off early.

**Describe the solution you'd like**

- [x] All actions:
  - [x] `Spend` (correctly positive via `impl From<Value> for Balance`)
  - [x] `Output`
  - [x] `Swap`
  - [x] `SwapClaim` (fee contribution is correctly positive via impl From<Value> for Balance) - note this is a bit tricky as the swap outputs are minted yet do not contribute to the value balance
  - [x] `ValidatorDefinition`
  - [x] `Delegate`
  - [x] `Undelegate`
  - [x] `UndelegateClaim`
  - [x] `IbcRelay`
  - [x] `Ics20Withdrawal`
  - [x] `PositionOpen`
  - [x] `PositionClose`
  - [x] `PositionWithdraw`
  - [x] `PositionRewardClaim`
  - [x] `ProposalSubmit`
  - [x] `ProposalWithdraw`
  - [x] `ValidatorVote`
  - [x] `DelegatorVote`
  - [x] `ProposalDepositClaim`
  - [x] `CommunityPoolSpend`
  - [x] `CommunityPoolOutput`
  - [x] `CommunityPoolDeposit`
  - [x] `ActionDutchAuctionSchedule`
  - [x] `ActionDutchAuctionEnd`
  - [x] `ActionDutchAuctionWithdraw`
- [x] Ensure each action has a description in the spec with a description of its balance commitments and why
- [x] Review code to ensure it matches what should be correct

**Comment by redshiftzero** [comment]
after the new entries in #4165 and #4218, the specification is accurate and matches the code. I have taken another pass through each action's balance entry today to confirm this.
