### ISSUE TITLE
Track base reward rate, validator-specific rates, and voting power.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#41]
The application needs to track the base reward rate for staking, the base exchange rate, and the derived validator-specific exchange rates. The voting power for each validator is calculated from the size of their delegation pool, and should also be recorded.

It's important that the implementation treats the reward rate as a time series, not as a constant value, since eventually the reward rate should adjust to steer staking incentives.  We're not immediately ready to implement that, but if we use a constant staking rate, we might write code that assumes the staking rate is constant, and we wouldn't notice, because it would be accidentally correct.   As an alternative, we could choose the staking rate based on the leading byte of the hash of the last block in each epoch. This is economically meaningless, but it's easy to implement, and it means we're forced to build code around the idea that the staking rate is variable.

The details are in the staking section of the protocol spec, but the high-level picture is:

```
base reward rate (time series) ===> base exchange rate (time series)

base reward rate (time series)
   + validator funding streams (can change, so also time series) ===> validator-specific exchange rates (time series)

base exchange rate + validator exchange rate ===> validator voting power (time series)
```

Subtasks:

- [x] Add a notion of epochs to the source code
- [x] #271
- [x] #272
- [x] #273
- [x] #274
- [x] #275

**Comment by avahowell** [comment]
This is now complete
