### ISSUE TITLE
Design: ways to interact with the transaction builder

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#412]
Different scenarios (notes from discussion with @hdevalence):

1. **existing: `pcli` + software keys**
2. `pcli` + online signing (e.g. ledger)
3. `pcli` + offline signing (e.g. airgapped signing device or threshold signing)
4. web wallet + software keys
5. web wallet + online signing (e.g. ledger)
6. trading bot with software keys

Differences:

- (1) to (2): synchronous to asynchronous, but within the lifetime of the program
- (2) to (3): short asynchrony to long asynchrony (possibly longer than program's lifetime)
- (1) to (4): rust code no longer driving execution or owning data
- (2) to (5): same as (1) to (4) *and* (1) to (2)
- (1) to (6): custom state backend + application logic, depending on the design of ZSwap

**Comment by hdevalence** [comment]
Closing this in preference to the new wallet server design discussed at the team meeting (issue to be created)
