### ISSUE TITLE
sct(component): add a method to query anchor roots by height

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4153]
**Is your feature request related to a problem? Please describe.**
Multiple downstream implementation broke when we updated the SCT anchor state key in #3723.
The problem is that the SCT query service does not offer a way to safely query the anchors, forcing consumers to perform raw KV queries against the chain state.

We have stabilized the state key schemas so this is not as urgent, nevertheless, we should avoid this and fix this gap in the RPC APIs. 

**Describe the solution you'd like**
Add a `get_sct_anchor_by_height` method to the `SctQueryService`

**Additional context**
Both the extension and `relayertest` broke as a result of this change.

Prospective contributors: I am available to help you ship this, just holler at me here or on discord [@erwanor](https://discord.com/channels/824484045370818580/894628521429839983/1225106264074354774).

**Comment by phasewalk1** [comment]
hey I'd like to take this up. @erwanor I'll ping you on discord

**Comment by phasewalk1** [comment]
actually I'll just ask my question here: would the anchor in the response take the type `crypto.tct.v1.MerkleRoot`?

```protobuf
// proto/penumbra/core/component/sct/v1/sct.proto
message AnchorByHeightRequest {
    uint64 height = 1; 
}

message AnchorByHeightResponse {
    crypto.tct.v1.MerkleRoot anchor = 1;
}
```

**Comment by erwanor** [comment]
Fantastic, yes this looks great!

**Comment by erwanor** [comment]
For the protobuf generation: https://guide.penumbra.zone/main/dev/protobuf.html#building-protos
