### ISSUE TITLE
add a flag to `testnet-generate` to start a testnet with non-zero gas prices

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#4154]
We should add this flag and use it in the smoke tests so that we're exercising non-zero fees. Otherwise, fees can break and we won't know.

**Comment by aubrika** [comment]
This may have happened & may already be done, but we should make sure of this & also consider adding additional tests.

**Comment by conorsch** [comment]
Checked on main, and it's not done. Updated OP accordingly.

**Comment by TalDerei** [comment]
- [ ] Make a local devnet with non-zero fees Fees can be arbitrary, as long as they are there.
 Exercise basic transactions, using pcli to start.
- [ ] Currently, pcli uses the gas prices in the compactblock to set a fee, and we want to exercise that this actually works.

**Comment by conorsch** [comment]
Adding the flag to modify genesis params is one thing, but updating the test suite to accommodate for tx fees is a can of worms. Given all the regex-based balance checks in the smoke tests, it'll be a bear to massage the existing test suite to accommodate for fees. Unclear whether it's worthwhile to port that functionality immediately to the mock-consensus—even if we do that, we'll still need to inspect the balances very precisely.

**Comment by TalDerei** [comment]
@conorsch what's the current status of this? I'm currently experimenting with supporting nonzero prices in the pcli smoke tests.

**Comment by conorsch** [comment]
Oops, lost track of this. I'll throw something simple together to unblock.
