### ISSUE TITLE
Add `AssetMetadataByIds` to shielded pool query RPC

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4162]
**Is your feature request related to a problem? Please describe.**

The shielded pool component's query service has an `AssetMetadataById` RPC, which requests assets one at a time. It turns out to be useful to request multiple assets simultaneously ( https://github.com/penumbra-zone/web/issues/887 )

**Describe the solution you'd like**

To address this use case, we should:

- [x] add a new `AssetMetadataByIds` RPC next to the existing `AssetMetadataById` RPC. Its request should have a `repeated` list of asset IDs, and it should stream responses
  - In the docs for the RPC, we should comment that the server is not required or expected to return the responses in the order they were listed in the request.
- [ ] fill in an implementation that uses a `JoinSet` to pull all of the asset metadatas out of the state concurrently and stream them to the caller as they become available.

**Comment by phasewalk1** [comment]
happy to fill in the implementation for this if needed

**Comment by aubrika** [comment]
Not blocked, but we should see if https://github.com/penumbra-zone/web/issues/1189 is a viable solution to their problem as that will remove the need for this

**Comment by aubrika** [comment]
Closed as sufficiently complete - we can follow up with the proposed optimization at a later time if performance becomes an issue
