### ISSUE TITLE
transfer err

### ISSUE THREAD

**Issue by isunfox** [penumbra-zone/penumbra#4168]
transfer err：
    status: Internal, message: "Error submitting transaction: code 1, log: failed to deliver transaction: check_stateful failed: provided anchor 33b53c13c6fd82d41afbce2dea567c4e1af6ed8926e2a965b96881f06da10100 is not a valid SCT root", details: [], metadata: MetadataMap { headers: {} }

**Comment by cratelyn** [comment]
:wave: hello! without more context, this issue is probably best taken to the Discord, for further assistance. https://discord.gg/hKvkrqa3zC
