### ISSUE TITLE
Proposal: separate a new validator operator subkey from the identity key to permit rotation

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#4171]
Currently, the signing key used by a validator to authorize changes to the validator definition must be used periodically in the course of normal validator operations, but it is also extremely sensitive, because it can never be rotated and if compromised means the validator has no choice but to permanently self-destruct.

This establishes a tension between the desire for the validator's signing key to be usable and available for the operator, and for it to be secure against attackers due to its high value and cost of compromise.

This tension can be mitigated by introducing a new intermediary key, which I'll call the "validator operator key". This key would be used to authorize changes to the validator definition *except* those which rotate the validator operator key itself. The signing key corresponding to the validator's identity itself would only be required to sign validator definition's which rotate this operator subkey. Consequently, in this setup, the root cryptographic identity of the validator can be kept entirely in offline cold storage (likely in practice a large-threshold offline multisig) and never touched in ordinary operating circumstances — it would only be required to recover from a compromise of the operator subkey. Meanwhile, the operator subkey could be custodied still with a strong eye towards security, but without the need to consider total existential risk to the validator in the security model, because it would be possible to recover from a compromised operator subkey.

In terms of implementation, this is fairly straightforward:

- Add a new field to validator definitions which specifies the verification key for the operator subkey — akin to the governance subkey, this should default to the validator identity verification key in the validator definition template unless the custody setup specifies a separate key
- Add a new sub-component of custody, mirroring the implementation of the governance subkey, defaulting to the validator identity if not specified separately
- On the client side, use the operator subkey to sign validator definitions which don't rotate the operator subkey; continue to use the identity signing key to sign validator definitions which do change the operator subkey
- In the staking component, check the signature on validator definitions using the operator subkey if the new definition does not change the operator subkey, and using the identity key if it does change the operator subkey
- Update documentation to describe how to use the new subkey

Alternatively, we could choose not to do this, or to defer to an upgrade post-mainnet, since it would be a soft consensus-breaking but *not* a state-breaking change (it would permit strictly more validator definitions to be accepted by the chain).

I would be willing to PR this up if it is accepted as a desirable feature to implement.

**Comment by hdevalence** [comment]
We're in a soft code freeze for the staking component (and the rest of the code except the DEX) so we won't be doing this.

The validator's identity key is already supposed to provide this use case: it can be kept in cold storage except for changes to the validator definitions, which should be rare and infrequent.
