### ISSUE TITLE
dex: surface swap/position assets during candidate selection

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4177]
In order to decide which part of the search-space to explore, the DEX uses an extended candidate set that comprise:
- fixed assets that are "safe defaults", as well as,
- dynamic candidates, surfaced using liquidity heuristics

In #4066, @hdevalence noted that there are straightforward ways to make the routine cover more ground, by including:
- assets that form a trading pair that had swaps in the block
- assets that form a trading pair for which positions were opened in the block.

More context on dynamic candidate selection is available in the web of issues: #2750

**Comment by zbuc** [comment]
Code complete, merging pending review
