### ISSUE TITLE
[Performance Improvement] Use a Uint48 for PositionVar Indices

### ISSUE THREAD

**Issue by ValarDragon** [penumbra-zone/penumbra#4180]
This is certainly a post-launch / potentially never optimization, but didn't see a comment for this hence making an issue.

Right now merkle tree indices correspond to 48 bit indices using Uint64's, making an extra 16 variable allocations and excess binary constraints. I believe the Macro in arkworks for uint works for non powers of two (though may need more tests)

**Comment by redshiftzero** [comment]
this is a good point, however since circuits are now final, closing as unplanned
