### ISSUE TITLE
Provide easy-to-use installation script for precompiled binaries

### ISSUE THREAD

**Issue by pedrommaiaa** [penumbra-zone/penumbra#4186]
There are quite a few steps to take to install all the tools (pcli, pd, pclientd) made available by Penumbra.
It would be great to have a single script that makes it easy for users to install all the tools necessary to use the application.

**Comment by conorsch** [comment]
Hello @pedrommaiaa, thanks for your interest in the project. I do a lot of scripting myself, so I can relate to your desire to have an "on-rails" experience for downloading the Penumbra binaries. The somewhat kludgy script I use for that purpose is here: https://github.com/conorsch/dotfiles/blob/77d60f53e32428be395181c97c86b7d914b25c37/bin/executable_penumbra-fetch-release-bins I get a lot of mileage out of that script! 

However, I'm not sure that storing it in the monorepo is the right move: operators have their own preferences about how to manage their environments. Some might use containers, some nix environments, others pre-built binary downloads like you and me, still others will build directly from source—and I'm sure there are other options I'm not thinking of.

In terms of making Penumbra easy to install, we're investing a lot of effort in a GUI over in https://github.com/penumbra-zone/web. We expect this will be the primary way that folks will interact with the network in the future. Right now, the cli tools still support more functionality than the GUI, but the latter is quickly catching up. I expect we'll still have a "power-user" experience on the cli, and for those users, I'd expect that they'd script their setup to work with whatever environment they prefer.
