### ISSUE TITLE
dex: use big endian of complement in the base liquidity index 

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4189]
**Is your feature request related to a problem? Please describe.**
@zbuc and I noticed that the base liquidity heuristic for path search surface the worst asset first. This is because the key is encoded as `prefix || base_asset || BE(base_liquidity)` which transfer the numerical ordering over into a lexicographic ordering. But that's not what we want! 

**Describe the solution you'd like**
Instead of doing we should compute `BE(!base_liquidity)` i.e. get the big-endian encoding of the **complement** so that the position with the most base liquidity get surfaced first.

**Describe alternatives you've considered**
It is tempting to extend `cnidarium` to allow prefix queries to specify a custom iteration order. But I think that fixing the state-key is the better solution because: 1/ a unique iteration order means you don't have to remember which one is the correct for the particular query you are making 2/ this is an easy migration and a useful exercise for us to do.

Random idea, a tiny schema library could provide out-of-the-box encoding wrappers e.g. `DescendingOrder(Amount) -> BE(!amount)`.

**Additional context**
We should have a couple simple unit-tests that assert this works.

**Comment by hdevalence** [comment]
Along the way to this, it'd be great to have an isolated unit test that the ordering encoding is what we expect
