### ISSUE TITLE
auction: define action handlers and validation rules

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4211]
Once we have #4206, we can start filling in their validation/execution handlers:
- [x] `ActionDutchAuctionSchedule`
- [x] `ActionDutchAuctionEnd`
- [x] `ActionDutchAuctionWithdraw`

**Comment by erwanor** [comment]
For the validation rules, we should try to use `anyhow::ensure!(INVARIANT, MSG_INVARIANT_CONTEXT)` as much as possible, so that we can formulate validation rules positively (like they would be in a natural language spec) e.g.

```rust
// Spec: The sequence number must be zero.
ensure!(seq == 0, "opened auction nft MUST have sequence set to zero (got {bad_seq})");
```

**Comment by TalDerei** [comment]
can this issue be closed?

**Comment by erwanor** [comment]
Not yet, we have to finish the component impl and then #4228
