### ISSUE TITLE
view: add auction support to planner / planner rpc

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4241]

**Comment by TalDerei** [comment]
there's an on-going planner refactor in https://github.com/penumbra-zone/penumbra/issues/4081 that will need to fold these changes. I think this issue should scope adding the relevant planner functions, and handle the specific planner logic separately once the blocking PR is merged? cc @erwanor

**Comment by TalDerei** [comment]
can this be closed? or is there anything else this issue is intended to capture
