### ISSUE TITLE
pcli: support for auction interactions

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4242]
We should add support for, the work can be divided in two phases:

Phase 1: add CLI scaffolding for:
- [x] `pcli tx auction dutch schedule`
- [x] `pcli tx auction dutch end`
- [x] `pcli tx auction dutch withdraw`

Phase 2:  fill in the specific implementations:
- [x] `pcli tx auction dutch schedule`
- [x] `pcli tx auction dutch end`
- [x] `pcli tx auction dutch withdraw`

The item to prioritize is `tx auction dutch schedule`, so that we can work towards viewing capabilities.

**Comment by TalDerei** [comment]
pcli implementations are currently only stubbed with planner-related boilerplate.

**Comment by TalDerei** [comment]
phase 1 is tracked by https://github.com/penumbra-zone/penumbra/pull/4249. phase 2 will be completed in a separate PR.
