### ISSUE TITLE
pcli: query an auction state by id

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4243]
First, we need to create scaffolding for the command:
- [ ] `pcli q auction id AUCTION_ID`

Then, we fill in the implementation to make a gRPC query and render its response:
- [ ] `pcli q auction id AUCTION_ID`

**Comment by TalDerei** [comment]
will remain blocked until view server support (tracked by https://github.com/penumbra-zone/penumbra/issues/4251) is complete.
