### ISSUE TITLE
pcli: query a user's auction ids

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4244]
Minimal support to exercise interaction with the view service

Scaffolding:
- [ ] `pcli v auction list [--include-inactive]`

Concrete implementation (RPC call to view service and rendering):
- [ ] `pcli v auction list [--include-inactive]`

**Comment by TalDerei** [comment]
will remain blocked until view server support (tracked by https://github.com/penumbra-zone/penumbra/issues/4251) is complete.
