### ISSUE TITLE
`pcli` install instructions suggest `unxz`, which is not available by default on MacOS

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4256]
**Is your feature request related to a problem? Please describe.**

The `pcli` install instructions suggest using `unxz` to extract the xz archive, but this command is not included by default on MacOS. I never noticed because I already had it installed.

**Describe the solution you'd like**

Figure out an alternative extraction method or archive format.  I don't think that the compression choice will make a huge difference, since most of our data is (cryptographically) random and uncompressible.

**Comment by conorsch** [comment]
I'm surprised by this, given that it's a cargo-dist default for both macos and linux. Looks like it's customizable, though, so let's switch to `.tar.gz` for both mac and linux: https://opensource.axo.dev/cargo-dist/book/artifacts/archives.html
