### ISSUE TITLE
pcli threshold dkg ux: if you hit enter unnecessarily, process is aborted

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#4260]
**Is your feature request related to a problem? Please describe.**
When testing the threshold DKG in pcli, one reported frustration was the process aborting due to an errant hit of enter, leading to the DKG needing to be restarted from scratch. 

**Describe the solution you'd like**
Perhaps a "Are you sure you want to abort the setup?" prompt could help avoid this happening inadvertently.

**Comment by hdevalence** [comment]
This could be solved via #4335

**Comment by hdevalence** [comment]
Closed by #4352
