### ISSUE TITLE
pcli threshold dkg ux: guiding text hard to read

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#4261]
**Is your feature request related to a problem? Please describe.**
 When testing the threshold DKG in pcli, a user reported the guiding text being hard to distinguish from the messages to be shared with the other participants. 

**Describe the solution you'd like**
Colorize the guiding text, or separate the guiding text from the messages with `====` or similar

**Comment by conorsch** [comment]
Resolved via https://github.com/penumbra-zone/penumbra/pull/4352
