### ISSUE TITLE
Implement `ValidatorDefinition` transactions in `pcli`

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#431]
With #375 landing soon, we will have support in `pd` for handling new `ValidatorDefinition` transactions within a block, however there is no support for creating them in `pcli`.

There's no reason this work can't take place in parallel. We also already have protobuf implementations of `ValidatorDefinition` so the work should be pretty straightforward:

- [ ] Create pcli command and arguments for validator definitions (there's a stub command already)
- [ ] Have the pcli command generate the transaction containing the `ValidatorDefinition` and submit
- [ ] Implement command to grab `ValidatorDefinition` for an existing Validator (for updates)

It's not clear what the exact interface will be, the `ValidatorDefinition` is kind of complex because of all the funding stream data. Maybe entirely with flags or require a JSON file?

**Comment by hdevalence** [comment]
This is done already
