### ISSUE TITLE
clearly specify UM asset id in `app_parameters`

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/penumbra#4311]
this has caused some concern in web, as there is no clear source of truth for the staking token asset id:
  - currently in web, since transitioning web to use asset registry, we query the registry by chain id
  - currently in core, it seems to be hard-coded to generate locally
  - formerly in web, before the registry, we defined a literal constant at compile-time (this caused failures)
  - possibly in web, it could be generated as it is in core, with some mild work in wasm to expose this

querying our asset registry makes a network request to github. an additional network query to a third party seems inappropriate to simply identify what i understand is a chain constant known by the node at the time we acquire the parameters and chain id.

after reading https://github.com/penumbra-zone/penumbra/issues/2310 it seems like generating locally might be the wrong approach. but, this is a special case, so maybe that's appropriate.

adding the staking token asset id at the top level of app parameters, or perhaps a full set of metadata, makes sense to me. currently the bare asset id is technically available as the first entry in `fixed_candidates` vec of `dex_parameters` but that seems coincidental/underspecified.

**Comment by hdevalence** [comment]
Isn't the Prax asset registry supposed to be bundled into the wallet?

**Comment by turbocrime** [comment]
i did think that was the initial intention, but it seems designed to query.

**Comment by hdevalence** [comment]
I think we should design the system so that the frontend can freely query Prax for info and have Prax respond with local data

**Comment by hdevalence** [comment]
The asset ID for the UM token is (protojson) `{"inner":"KeqcLzNx9qSH5+lcJHBB9KNW+YPrBk5dKzvPMiypahA="}` or `passet1984fctenw8m2fpl8a9wzguzp7j34d7vravryuhft808nyt9fdggqxmanqm`
