### ISSUE TITLE
planner: allow prepaid fees to be collected in outputs

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/penumbra#4313]
There's parity between the wasm planner and the core planner, but there are some additional design considerations that have been discussed, and will be noted here for future reference. 

Currently, we release the surplus prepaid swap-claim fee directly into the transaction fee, making the transaction unnecessarily more expensive than it needs to be. We may consider releasing the excess value as a change output note. 

Additionally, there's been discussion of allowing for a specific change address to be specified, and change notes to be paid in any asset denomination. This would be a [UX boost](https://discord.com/channels/824484045370818580/883455571003576320/1233994930620334150) because the current design is more [restrictive](https://discord.com/channels/824484045370818580/883455571003576320/1233957899156586546) because you need `UM` to do anything on the network.

**Comment by hdevalence** [comment]
These are all done except for #4322
