### ISSUE TITLE
Swap alt fee tokens into the native token prior to fee burn

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4328]
As described in #4320, the initial implementation of multi-asset fee support burns the alt fee tokens. This is incorrect, since the chain should only be minting/burning native assets. The correct behavior is that the fees paid in alt fee tokens should be converted to the native token.  However, since the DEX is batched, we need some plumbing to collect fee amounts, include them in batch swaps, and then handle the resulting fee payments. This overlaps with work we'd thought about (but haven't done, and deferred) as part of #3666 and we should think about them at the same time.

**Comment by zbuc** [comment]
> However, since the DEX is batched, we need some plumbing to collect fee amounts, include them in batch swaps, and then handle the resulting fee payments.

Should we add an additional fee multiplier to fees paid in the non-native asset to account for the additional work of swapping?

**Comment by hdevalence** [comment]
I don't think so, since that cost isn't really attributable to a psecific transaction. 

I'm also not sure it's necessary. In this V0 design, there's no connection between the different prices, all of which are fixed -- so the values of the different fee tokens could float around and cause pricing disparities. To address this, I think that the fixed fees for alternative gas tokens should be significantly higher (10x). This way, users can come into the chain and use it, but they're incentivized to use the native fee token which will protect their privacy.

**Comment by hdevalence** [comment]
The issue here is primarily that we don't currently have any plumbing set up to move the values of the fees around and then swap them, and doing that will require some design work. Maybe we don't get to doing this pre-mainnet.

**Comment by aubrika** [comment]
Sounds like we need to discuss & clarify which part of this ticket is in scope for V1 - @hdevalence when you say "maybe we don't get to doing this pre-mainnet", do you mean this ticket generally? Will burning the alt fee tokens cause issues for users?

**Comment by TalDerei** [comment]
what does it mean if this ticket is tagged as `v1  and removed from the current sprint, specifically in the context of the upcoming code freeze?
