### ISSUE TITLE
Move `ActionList` from `view` crate into `transaction` crate

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4332]
**Is your feature request related to a problem? Please describe.**

The `ActionList` introduced in #4319 represents an in-progress list of actions that will be turned into a `TransactionPlan`, and provides helper methods for balancing the value of those actions, making it the core of a planner implementation. It should be shared between both planners.

**Describe the solution you'd like**

Remove the current `view/src/planner/action_list.rs`, redistributing its contents:
- the `prioritize_and_filter_spendable_notes` function should move up into the parent module of the `view` crate
- everything else should move into `transaction/src/action_list.rs` and be exposed as an `action_list` submodule of the `transaction` crate

Then update the existing code to match the changed imports.

**Additional context**

This allows the web code to use the same `ActionList`.

**Comment by hdevalence** [comment]
@TalDerei the call to canonicalize the action ordering would naturally fit at the end of the `ActionList::into_plan` method

**Comment by TalDerei** [comment]
> @TalDerei the call to canonicalize the action ordering would naturally fit at the end of the `ActionList::into_plan` method xref #3467

agreed, I added it right after the `ActionList::into_plan` in that PR, but I'll move it into the method.

**Comment by hdevalence** [comment]
Sounds great. If we do this part, the next time the web repo updates its rust deps, we'll be able to commonize the fee handling behavior between the two planner implementations.

**Comment by TalDerei** [comment]
@hdevalence this needs to be prioritized to fix swap-claim bug identified in https://github.com/penumbra-zone/web/issues/1054. Then we can propagate the changes in https://github.com/penumbra-zone/web/issues/876.

**Comment by hdevalence** [comment]
sounds great, want to take it on?
