### ISSUE TITLE
upgrades: 🚘 migrations should be idempotent

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#4365]
**Is your feature request related to a problem? Please describe.**

it would be nice if migrations were idempotent, to help make operator's lives easier while performing chain upgrades.

**Describe the solution you'd like**

it would be nice if we could examine a version number _(q: which?)_, and only apply a migration if the version number was below some threshold, and returning early if not, rather than writing migrations in such a way as to be idempotent.

**Comment by conorsch** [comment]
> we could examine a version number (q: which?)

Ahoy: https://github.com/penumbra-zone/penumbra/blob/v0.73.2/crates/core/app/src/lib.rs#L24 We also reference this value in the repo's `COMPATIBILITY.md`, but not yet in local state, which would be supremely useful for migrations.

**Comment by cratelyn** [comment]
is #4373 is a duplicate of this, @erwanor?

**Comment by erwanor** [comment]
I don't think it's a duplicate? This is about adding migration-scoped check against specific protocol versions, the other ticket is about changing the halt signaling mechanism and adding a broad "is chain halted" check to `pd migrate`.

**Comment by cratelyn** [comment]
agreed, i marked it as resolved because i was able to figure that out. thank you!

**Comment by hdevalence** [comment]
I think that #4373 would close this, since the migrate command would bail out if the halt-bit is unset, thus making all migrations idempotent at the top-level.

**Comment by cronokirby** [comment]
Closed in #4373.

**Comment by conorsch** [comment]
Our migrations are not currently idempotent; see reports in #4432. At the very least, we should be exercising _rerunning_ a migration and confirming no error in automated testing #4323 to verify it doesn't error.

**Comment by hdevalence** [comment]
I don’t see any evidence in that thread that there is an idenpotency issue.
