### ISSUE TITLE
auctions: 🔎 circle back on #4362 review comments

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#4366]
**Is your feature request related to a problem? Please describe.**

to help get the v`0.74.0` release out the door promptly, we merged #4362 optimistically.

**Describe the solution you'd like**

we should circle back on the "gradual" dutch auction support in `pcli` and address these [review comments](https://github.com/penumbra-zone/penumbra/pull/4362#pullrequestreview-2048243489).

**Comment by cratelyn** [comment]
see #4302.

**Comment by erwanor** [comment]
This is really low priority
