### ISSUE TITLE
chore: 🌠 upgrade to cometbft v0.37.6.

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#4369]
> ...there is a new version of CometBFT: 0.37.6. this is not yet represented in the flake, but perhaps should be updated to change it (it improves p2p performance, i think @erwanor told me).

_Originally posted by @plaidfinch in https://github.com/penumbra-zone/penumbra/pull/4358#discussion_r1596036140_

we should, at some point, upgrade to cometBFT v0.37.6.

**Comment by dynst** [comment]
The p2p performance improvement is https://github.com/cometbft/cometbft/pull/2841

The [changelog](https://github.com/cometbft/cometbft/blob/v0.37.6/CHANGELOG.md) also says v0.37.6 bumped the compiler to Go 1.21, because Go 1.20, in use by v0.37.5, is now EOL.

**Comment by conorsch** [comment]
Handled in #4720, which upgraded to CometBFT 0.37.9.
