### ISSUE TITLE
Release Testnet 75, deimos-8, via chain reset

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#4374]
# Testnet Release

Testnet name: Testnet 75, `penumbra-testnet-deimos-8`, via chain reset
Release date: 2024-05-10
Testnet release manager: @conorsch

# Testnet Release Manager Checklist

We intend to ship a reset, to recover from the mismanaged upgrade to 74. See #4325 and  #4373 for details.

Pre-release:

- [x] Fetch funding streams from previously active validators
- [x] Prepare release PR that makes the following changes:
  * bump chain id from `penumbra-testnet-deimos-7` -> `penumbra-testnet-deimos-8` 
  * reset `TOTAL_HALT_COUNT` to `0` - https://github.com/penumbra-zone/penumbra/pull/4376
  * increment `APP_VERSION` from `3` to `4` - https://github.com/penumbra-zone/penumbra/pull/4375
  * bump crate versions `v0.74.0` -> `0.75.0`

On release day:

- [x] Draft an announcement for peer review to ensure major changes included are comprehensive.
- [x] Enable testnet deploy workflow, so that chain is reset
- [x] Bump the version number and push its tag, via [cargo-release](https://crates.io/crates/cargo-release).
    - [x] Run `cargo release minor` for a new testnet, or `cargo release patch` for a bugfix. For the latter, make sure you're on a dedicated release branch.
    - [x] Push the commit and newly generated tag, e.g. `v0.51.0`, to the remote.
- [x] Wait for the ["Release" workflow](https://github.com/penumbra-zone/penumbra/actions/workflows/release.yml) to complete: it'll take ~60m, most of which is the Windows builds.
- [x] You must [manually review](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) the waiting deployment
- [x] Delegate to the Penumbra Labs CI validators; use amounts of ~200k `penumbra` per validator.
- [x] Open a position to provide some initial liquidity: `pcli tx lp replicate xyk penumbra:test_usd 20000penumbra --current-price 20`
- [x] Edit the newly created (and published) release object, then click "Generate release notes." Cut and paste the generated text from the bottom to the top of the post, then save it.
- [x] Close faucet (chain halt will make it inoperative anyway)
- [x] Update Galileo deployment, [following docs](https://github.com/penumbra-zone/galileo).
- [x] Make the announcement to Discord! 🎉🎉🎉

Post-release cleanup tasks

- [x] Send funds to funding streams for prior chain's validators, to help them get active again
- [x] Ensure faucet is open
- [x] Perform Hermes maintenance to get relayer running again
- [ ] Update GH templates for:
  - [ ] release planning (this template was heavily revised and can be reused)
  - [ ] PR templates to ask for test plans

**Comment by conorsch** [comment]
Confirmed IBC outbound (Penumbra -> Osmosis) on Testnet 75:

* penumbra tx https://cuiloa.testnet.penumbra.zone/transaction/81a160055e7a13d6dc0b6aff7faacbb450d4fd0c9cce0b75ff3484a2768161b8
* osmosis tx https://www.mintscan.io/osmosis-testnet/tx/B314A5B3A59AB51C7FD5F3995D7477CDD16F26631D28398B8096F8D9EEC505A2?height=7450796

However, given the problems documented in https://github.com/penumbra-zone/penumbra/issues/4310, I expect that channel will close soon.

**Comment by conorsch** [comment]
Confirmed IBC inbound (Osmosis -> Penumbra) on Testnet 75: 

* osmosis tx https://www.mintscan.io/osmosis-testnet/tx/08168FAF3366F9A78D9245038F9783CD6DBA7D1324FBA56BA639D18F94CBE73B?height=7452166

**Comment by hdevalence** [comment]
This is done, correct?
