### ISSUE TITLE
Implement missing IBC APIs for Skip

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#4391]
From Skip:

> I took a look at which grpc endpoints are working that Skip API depends on, and most of the IBC ones seem to work. I found three that we depend on that would be benefitial if we could have them implemented.

```
cosmos.bank.v1beta1.Query/TotalSupply
https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/proto/cosmos/bank/v1beta1/query.proto#L57

ibc.applications.transfer.v1.Query/DenomTraces
https://github.com/cosmos/ibc-go/blob/main/proto/ibc/applications/transfer/v1/query.proto#L16

ibc.core.client.v1.Query/ClientStatus
https://github.com/cosmos/ibc-go/blob/main/proto/ibc/core/client/v1/query.proto#L47
```

**Comment by zbuc** [comment]
@hdevalence Implementing the IBC APIs seems straightforward but `cosmos.bank.v1beta1.Query/TotalSupply` seems a little trickier as it's part of a larger CosmosSDK-specific RPC interface. Do we think it would be suitable to build a _similar_ query within the existing `shielded_pool` API, or do we need to implement this specific call?

**Comment by aubrika** [comment]
> @hdevalence Implementing the IBC APIs seems straightforward but `cosmos.bank.v1beta1.Query/TotalSupply` seems a little trickier as it's part of a larger CosmosSDK-specific RPC interface. Do we think it would be suitable to build a _similar_ query within the existing `shielded_pool` API, or do we need to implement this specific call?

We should implement this specific call, but we may not include everything expected on other chains - this is for compatibility and may be idiosyncratic.

**Comment by conorsch** [comment]
WIP PR here: https://github.com/penumbra-zone/penumbra/pull/4404

**Comment by hdevalence** [comment]
This needs to implement the specified RPC: https://github.com/penumbra-zone/penumbra/pull/4404#issuecomment-2126400319

Now that we merged a new RPC that we don't want we have to either deprecate it or do a breaking proto change.

**Comment by hdevalence** [comment]
We need to immediately delete the following messages newly added to the Penumbra protobufs, before they are picked up and used:
```
rpc TotalSupply
TotalSupplyResponse
TotalSupplyRequest
```

The point of the issue was to implement the expected RPC, not to make up our own incompatible one.

**Comment by conorsch** [comment]
We have a follow-up PR intended to close this out: https://github.com/penumbra-zone/penumbra/pull/4444

**Comment by conorsch** [comment]
Resolved via https://github.com/penumbra-zone/penumbra/pull/4444
