### ISSUE TITLE
Unexpected HTTP response codes for unimplemented GRPC methods

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4392]
**Describe the bug**

Skip reported unexpected HTTP response codes for unimplemented GRPC methods:

> Another thing I noticed I think has to do with the problem I was running into with grpcurl. Instead of returning "Unimplemented" GRPC error for unimplemented queries, I get back an unknown error type
> 
> 2024/05/15 15:05:12 rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); malformed header: missing HTTP content-type
exit status 1
> 
> Skip API uses the unimplemented error type to detect feature support in certain cases. We may need to handle this other error type specially since it seems like we are getting it instead of unimplemented.

They also reported that `grpcurl` didn't work, potentially because of problems with reflection.

This was against `https://grpc.testnet.penumbra.zone`; it's possible the custom load balancer setup there interferes with HTTP headers, we've had that issue in the past, but this seems more likely to be a problem in `pd` itself.

---

### :link: related work
* https://github.com/hyperium/tonic/pull/1701
* https://github.com/penumbra-zone/tonic/pull/1
* https://github.com/penumbra-zone/tonic/pull/2

**Comment by hdevalence** [comment]
Link to gist with pd logs: https://gist.github.com/hdevalence/3cc8c9cef56463dc08cf4e303f316ba4

```
$ grpcurl -plaintext -vv localhost:8080 list
Failed to list services: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); malformed header: missing HTTP content-type
```

**Comment by conorsch** [comment]
> They also reported that grpcurl didn't work

Using `grpcurl` with a known-good query works fine:

```
❯ grpcurl grpc.testnet.penumbra.zone:443 penumbra.core.app.v1.QueryService.AppParameters  | jq .appParameters.chainId
"penumbra-testnet-deimos-8"
```

> potentially because of problems with reflection.

Reflection is also supported, shown here via `grpcurl`:

```
❯ grpcurl grpc.testnet.penumbra.zone:443 list
grpc.reflection.v1alpha.ServerReflection
penumbra.cnidarium.v1.QueryService
penumbra.core.app.v1.QueryService
penumbra.core.component.auction.v1.QueryService
penumbra.core.component.community_pool.v1.QueryService
penumbra.core.component.compact_block.v1.QueryService
penumbra.core.component.dex.v1.QueryService
penumbra.core.component.dex.v1.SimulationService
penumbra.core.component.fee.v1.QueryService
penumbra.core.component.governance.v1.QueryService
penumbra.core.component.sct.v1.QueryService
penumbra.core.component.shielded_pool.v1.QueryService
penumbra.core.component.stake.v1.QueryService
penumbra.custody.v1.CustodyService
penumbra.tools.summoning.v1.CeremonyCoordinatorService
penumbra.util.tendermint_proxy.v1.TendermintProxyService
penumbra.view.v1.ViewService
```

> Skip reported unexpected HTTP response codes for unimplemented GRPC methods:

That makes sense, as a side-effect of our merging multiple routers in the pd endpoint, so that we can provide a node status page in addition to the gRPC services. I'm not sure what the best compromise is for this situation.

**Comment by conorsch** [comment]
Ah, looks like I had an outdated `grpcurl`: I was using `1.8.7`, and the results above were posted from that version. After upgrading my local version to `1.9.1`, I can reproduce problems:

```
❯ grpcurl --version
grpcurl v1.9.1

❯ grpcurl -vv grpc.testnet.penumbra.zone:443 list
Failed to list services: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); malformed header: missing HTTP content-type
```

**Comment by conorsch** [comment]
Looks like newer versions of grpcurl, the server reflection API moved from `v1alpha` to `v1`, as shown here: https://github.com/fullstorydev/grpcurl/pull/407/files We get gRPC server reflection support via the `tonic-reflection` crate, which is still using the `v1alpha` namespace: https://github.com/hyperium/tonic/issues/1685 Can we do anything about that without an upstream patch and version bump? Let's find out.

**Comment by hdevalence** [comment]
Let's do an upstream patch and version bump, that seems like the best solution

**Comment by cratelyn** [comment]
i am opening an upstream patch now!

**Comment by cratelyn** [comment]
i've opened hyperium/tonic/pull/1701. @conorsch and i confirmed fixes this issue by running `pd` locally and sending a `list` request from a new version of `grpcurl`.

once that lands, we will need to either upgrade our `tonic` dependency to a new release that includes that patch _(**NB:** this will involve upgrading from 0.10 to 0.11)_, or we will need to backport that to the 0.10 release _(that would involve a temporary fork of `tonic-*`)_. the former option is ideal, but will involve a bit of finagling to get `ibc-types`, `ibc-proto`, and our `tonic` dependencies all in agreement with one another.
