### ISSUE TITLE
governance: ibc freeze proposal types not exposed in pcli

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#4397]
**Is your feature request related to a problem? Please describe.**
We have governance proposal types for freezing and unfreezing IBC clients:

* [FreezeIbcClient](https://github.com/penumbra-zone/penumbra/blob/v0.75.0/proto/penumbra/penumbra/core/component/governance/v1/governance.proto#L314)
* [UnfreezeIbcClient](https://github.com/penumbra-zone/penumbra/blob/v0.75.0/proto/penumbra/penumbra/core/component/governance/v1/governance.proto#L321)

However, these proposals are not available via `pcli`:

```
❯ pcli tx proposal template
pcli-transaction-proposal-template
Make a template file for a new proposal

USAGE:
    pcli transaction proposal template [OPTIONS] <SUBCOMMAND>

OPTIONS:
        --file <FILE>    The file to output the template to
    -h, --help           Print help information

SUBCOMMANDS:
    community-pool-spend    Generate a template for a Community Pool spend proposal
    emergency               Generate a template for an emergency proposal
    help                    Print this message or the help of the given subcommand(s)
    parameter-change        Generate a template for a parameter change proposal
    signaling               Generate a template for a signaling proposal
    upgrade-plan            Generate a template for an upgrade proposal,
```

**Describe the solution you'd like**

I should be able to run `pcli tx proposal template freeze-ibc-client` and `pcli tx proposal template unfreeze-ibc-client` to generate governance proposals for those actions.

**Describe alternatives you've considered**
We could simply not do this. Given the security-critical nature of this functionality, however, I believe we should implement this for v1.

**Additional context**
N/A

**Comment by hdevalence** [comment]
This is not important to do, nothing prevents submission of such a proposal and we should not add additional scope at this time.
