### ISSUE TITLE
Error in delegating from web

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#4437]
**Describe the bug**
A user in Discord [reported experiencing an issue](https://discord.com/channels/824484045370818580/1082420866438156418/1242880146046713907) repeatedly when attempting to perform a delegation. The error message they received is:

```
Error: [unknown] Tendermint error 1: failed to deliver transaction: executing transaction: given
198000000 unbonded stake, expected
197722849 delegation tokens but description
produces 197791845
```

The user reports experiencing this over a one hour period, against multiple validators:

> I tried first at anatolian team, later Penumbra labs 1 . Both gave error.

When they use the same delegation amount, the values reported in the error message remain the same.

**To Reproduce**
1. Unclear

**Screenshots**
![Ekran_Resmi_2024-05-22_19 36 29](https://github.com/penumbra-zone/penumbra/assets/570040/44028827-6200-444c-9774-7a2bd1d00599)

![Ekran_Resmi_2024-05-22_20 22 57](https://github.com/penumbra-zone/penumbra/assets/570040/56f175e6-11b0-42e1-ad78-9258cef2762a)

![Ekran_Resmi_2024-05-22_20 30 45](https://github.com/penumbra-zone/penumbra/assets/570040/d1a0e57f-dc19-4abe-8363-3a64256ee3a4)
![Ekran_Resmi_2024-05-22_20 30 20](https://github.com/penumbra-zone/penumbra/assets/570040/7a3132e7-5017-4ea7-a925-38684ef4c78a)

**Comment by aubrika** [comment]
Flagging @grod220 - is there an associated issue on the web side? Seems worth parallel investigation

**Comment by TalDerei** [comment]
<img width="1728" alt="Screenshot 2024-05-22 at 10 42 07 AM" src="https://github.com/penumbra-zone/penumbra/assets/70081547/2a20f914-d9ac-4da4-99a7-f54efdedc1c2">

I cannot replicate this on current main, and this was tested before [v8.0](https://github.com/penumbra-zone/web/pull/1116) was released. I'll investigate the context.

**Comment by TalDerei** [comment]
> Flagging @grod220 - is there an associated issue on the web side? Seems worth parallel investigation

there isn't currently an issue on the web side about this.

**Comment by zbuc** [comment]
I also cannot replicate, I was able to delegate 1um to the Penumbra Labs 2 validator: https://app.testnet.penumbra.zone/#/tx/12f85129322f516e830a8928069605171113808378e9e0394f695c7fd299e046

**Comment by aubrika** [comment]
Closed as non-issue, user seems to have needed to refresh their cache
