### ISSUE TITLE
Track delegation pool size and check before transitioning validator into Active state

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#445]
Currently the implementation of validator state transitions has an open TODO:

```rust
// If an Inactive or Unbonding validator is in the top `validator_limit` based
// on voting power and the delegation pool has a nonzero balance,
// then the validator should be moved to the Active state.
```

Only the voting power check is being performed right now.

`pd` will need to be modified to track the validator's current delegation pool size. This should probably be implemented as a new field on `ValidatorStatus` and a corresponding column in the `validators` table. The value will need to be updated whenever delegation changes occur, and checked during the transition to `Active`.

@avahowell says this is how we can check the delegation token supply (is that the same as the delegation pool size?):

```rust
            let mut delegation_token_supply = reader
                .asset_lookup(identity_key.delegation_token().id())
                .await?
                .map(|info| info.total_supply)
                .unwrap_or(0)
```

**Comment by hdevalence** [comment]
Done already

**Comment by zbuc** [comment]
I misspoke, this actually isn't done yet, but I'm not clear if it _needs_ to be done -- is it possible for a validator to be in the top N validators with a 0-size delegation pool? Since voting power is based on delegations, I'd think "no"? Am I missing anything @hdevalence @avahowell ?

**Comment by zbuc** [comment]
After thinking a bit more, I think this _does_ need to be implemented, for the case where there are `< N` validators, and some of them have 0 voting power.

**Comment by zbuc** [comment]
Implemented this in https://github.com/penumbra-zone/penumbra/pull/561

Since the voting power is determined by the delegation pool, any validator with non-zero power is guaranteed to have delegations (and vice versa).

```rust
pub fn voting_power(&self, total_delegation_tokens: u64, base_rate_data: &BaseRateData) -> u64 {
        ((total_delegation_tokens as u128 * self.validator_exchange_rate as u128)
            / base_rate_data.base_exchange_rate as u128)
            .try_into()
            .unwrap()
    }
```
