### ISSUE TITLE
ViewService/Balances Response Streams Terminate with an Error

### ISSUE THREAD

**Issue by philipjames44** [penumbra-zone/penumbra#4452]
**Describe the bug**
ViewService/Balances queries returns some balances, but ultimately terminates in an error

**To Reproduce**
1. Populate an account with any test funds (e.g. send an account address to the faucet)
2. Query your pclientd for your balances
`grpcurl -plaintext -d '{"account_filter": {"account": 0}}'     0.0.0.0:8081 penumbra.view.v1.ViewService/Balances`

**Expected behavior**
Expect to receive a stream of asset balances with no errors. Instead receive a response with balances, that ultimately terminates with an error:
```
{
  "accountAddress": {
    "decoded": {
      "address": {
        "inner": "OpclSjPHsDcHwJpEEjLjb9hx1y0LdfOc83PIM6+sn610agzeNqRlmgBRB7tU7iqScK9Q/qLSZO2k6aqQ94GrS9LgfqM38scVcZU73E3AeNw="
      },
      "index": {
        
      },
      "walletId": {
        "inner": "lQstTUISYEHq/gho6/5PPyUpROynVkDqbTfZ6qdJugY="
      }
    }
  },
  "balanceView": {
    "knownAssetId": {
      "amount": {
        "lo": "25000000"
      },
      "metadata": {
        "denomUnits": [
          {
            "denom": "gm",
            "exponent": 6
          },
          {
            "denom": "mgm",
            "exponent": 3
          },
          {
            "denom": "ugm"
          }
        ],
        "base": "ugm",
        "display": "gm",
        "penumbraAssetId": {
          "inner": "HW2Eq3UZVSBttoUwUi/MUtE7rr2UU7/UH500byp7OAc="
        }
      }
    }
  }
}
ERROR:
  Code: Unavailable
  Message: error getting balances: asset ID passet1p94j5d2rafz4stelfj3fqqrz8gvc0e8vgtjhevj38k637wgxkvqskts8x3 does not match denom Unknown
  ```

**Screenshots**
N/A

**Additional context**
Confirmed as an issue on both releases 0.75.0 & 0.75.1 on 2 separate & independent machines with unique accounts.

**Comment by hdevalence** [comment]
>   Message: error getting balances: asset ID passet1p94j5d2rafz4stelfj3fqqrz8gvc0e8vgtjhevj38k637wgxkvqskts8x3 does not match denom Unknown

This seems bad. I think this error occurs when parsing a `Metadata` that specifies both (1) an asset ID and (2) a denom but the asset ID provided is not the hash of the provided denom. The denom "Unknown" is extremely suspicious, our denoms are all lower case. Could something be populating the view database with corrupted metadata?

Please keep the original view service database, but does the problem reoccur when re-syncing from scratch (it sounds like you already tried this, but can you confirm?)

**Comment by hdevalence** [comment]
```
rg Unknown

crates/view/src/storage.rs
1152:        let denom = "Unknown".to_string();
```
🤔

**Comment by hdevalence** [comment]
Looks like the bug has been there for a year, and we're just triggering it now (cc @aubrika): https://github.com/penumbra-zone/penumbra/blame/main/crates/view/src/storage.rs#L1151

We definitely don't want to make up an invalid denom when we see an unknown asset ID, but without context I'm not sure what the right behavior is.

**Comment by philipjames44** [comment]
> Please keep the original view service database, but does the problem reoccur when re-syncing from scratch (it sounds like you already tried this, but can you confirm?)

Yes that's correct. I have a copy of the view db saved as well.

**Comment by hdevalence** [comment]
@philipjames44 can you try using pcli/pclientd in #4453 ?

**Comment by hdevalence** [comment]
(That commit should be cherry-pickable onto basically any branch, if needed)

**Comment by philipjames44** [comment]
Can do, building now.

**Comment by hdevalence** [comment]
It may be that running that code causes other errors, if there are parts of the view server that erroneously assume that asset metadata is always available, which is not the case by design. For instance, LPNFTs or auction NFTs are not recorded in an on-chain registry, so if someone transfers an LPNFT to another wallet, the counterparty won't be able to understand the asset ID without getting extra information. (This information could be compiled by an off-chain indexer, but we didn't include it in a full node in order to not bloat the chain state)

**Comment by philipjames44** [comment]
Off of the try-fix-4452 branch, after running `cargo build --release` && `pcli view reset` I am still getting the same error

**Comment by hdevalence** [comment]
Hmm, I can't reproduce, even when using your FVK:
```
~/c/p/penumbra3 (try-fix-4452|✔) $ cargo run --release --bin pclientd -- --home /tmp/phil init --view REDACTED
    Finished release [optimized] target(s) in 0.30s
     Running `target/release/pclientd --home /tmp/phil init --view REDACTED`
Initializing configuration at: "/private/tmp/phil"
~/c/p/penumbra3 (try-fix-4452|✔) $ cargo run --release --bin pclientd -- --home /tmp/phil start
    Finished release [optimized] target(s) in 0.30s
     Running `target/release/pclientd --home /tmp/phil start`
2024-05-24T00:40:31.121250Z  INFO pclientd: starting pclientd opt.home="/tmp/phil" config.bind_addr=127.0.0.1:8081 config.grpc_url=https://grpc.testnet.penumbra.zone/
2024-05-24T00:40:31.568792Z  INFO penumbra_view::worker: starting client sync
(no errors)
```
```
/tmp $ grpcurl -plaintext -d '{"account_filter": {"account": 0}}'     0.0.0.0:8081 penumbra.view.v1.ViewService/Balances
... (no errors)
```

**Comment by philipjames44** [comment]
Miscomms on my end, no errors off of that build.
