### ISSUE TITLE
Ensure fullnodes in testnet deployment do not use debug logging

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4455]
**Is your feature request related to a problem? Please describe.**

We should be able to collect information about fullnode performance. We can't get this information in the presence of debug logging, because this adds an enormous amount of additional work in hot loops.

**Describe the solution you'd like**

Keep debug level logging for _validators_ , but not for the fullnodes that serve RPC.

**Comment by conorsch** [comment]
Confirmed that this is already the case, with no changes required. Validators use `RUST_LOG=info,pd=debug,penumbra=debug`, and fullnodes have no RUST_LOG override, so they log at info by default. First added in #3244.
