### ISSUE TITLE
Cherry-pick #4454 to main

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4456]
> this sounds good to me. can i ask that upon merging, you file an issue to track this, so following up on that does not fall through the cracks?

_Originally posted by @cratelyn in https://github.com/penumbra-zone/penumbra/issues/4454#issuecomment-2128509847_

**Comment by conorsch** [comment]
Resolved via https://github.com/penumbra-zone/penumbra/pull/4466
