### ISSUE TITLE
pcli BUG

### ISSUE THREAD

**Issue by isunfox** [penumbra-zone/penumbra#4486]
my local penumbra service port is 46657 ,it's not 26657

/root/.local/share/pcli/config.toml 
grpc_url = "http://127.0.0.1:8080"

pcli view balance from grpc_url http://127.0.0.1:8080
error as follows:
but my local service port is 26657 
use grpc_url = "http://127.0.0.1:8080" is ok
![image](https://github.com/penumbra-zone/penumbra/assets/30688978/8a84e6f5-c8ed-445a-8e82-e983e8116326)

**Comment by erwanor** [comment]
You can specify a custom port for the cometbft pd proxy, `pd start --help` lists all options, i think you'll want to specify `--comebtft-addr` or as an env var `PENUMBRA_PD_COMETBFT_PROXY_URL=http://127.0.0.1:46657`

**Comment by isunfox** [comment]
thx
