### ISSUE TITLE
Tracing output about DEX arb is suggestive of a bug

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4513]
**Describe the bug**

```
2024-05-31T07:14:54.747390Z  INFO abci:EndBlock{height=223048}:end_block{height=223048}:dex: penumbra_dex::component::dex: arbitrage successful! surplus=Value { amount: 0, asset_id: passet1984fctenw8m2fpl8a9wzguzp7j34d7vravryuhft808nyt9fdggqxmanqm }
```
This was not a successful arbitrage, and should not be reported as such. But more to the point, we should be sure that we're not committing any state changes as a result of it (i.e., the fix is not to skip the tracing message, but to ensure that we're discarding 0-valued arb).

**Comment by erwanor** [comment]
I recently changed it to this message, my reasoning was that no errors were returned, the logic ran successfully even if no surplus was found, but I can see how that's a bit awkward. The debug log would surface that the arb is discarded

I am certain that we discard the zero arb, but maybe @zbuc could independently confirm

**Comment by hdevalence** [comment]
Ah OK sounds good. In that case my preference would be to skip the message only.
