### ISSUE TITLE
Add a timestamp endpoint to SCT QueryService

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/penumbra#4522]
**Is your feature request related to a problem? Please describe.**

The SCT service stores timestamps for each block height, but this information is not accessible to clients. Users would like to know things like transaction times, which could be identified by block timestamp. Graph axes such as candlestick graphs could be labelled with timestamps.

**Describe the solution you'd like**

Add a timestamp endpoint to the SCT QueryService that allows querying the timestamp of a specific block height

**Describe alternatives you've considered**

Include block height timestamps in other queries that mention block heights, such as the CandlestickData query, or a CompactBlock query

**Comment by turbocrime** [comment]
i think a lower resolution such as epoch timestamp would also be fine, for tx logs or graph purposes

**Comment by aubrika** [comment]
Is this blocking on the web side @turbocrime ? If it is a nice to have we won't have bandwidth proximally

**Comment by turbocrime** [comment]
closed by #4523
