### ISSUE TITLE
penumbra.util.tendermint_proxy.v1.TendermintProxyService.GetBlocksByHeight seems broken

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/penumbra#4543]
**Describe the bug**

GetBlocksByHeight fails to respond for any attempted height

**To Reproduce**
1. Go to https://grpcui.testnet.penumbra.zone/
2. Use Service name penumbra.util.tendermint_proxy.v1.TendermintProxyService
3. Use Method name GetBlockByHeight
4. Input a valid height
5. Invoke

**Expected behavior**

Block data is returned

**Screenshots**

<img width="1026" alt="Screenshot_2024-06-04_at_10 27 26" src="https://github.com/penumbra-zone/penumbra/assets/134443988/29550335-3ae5-4dd7-bf14-31b1737c727e">

**Comment by zbuc** [comment]
I'm trying to write a test script for it locally but having some trouble.

I can call it with grpcurl at least, but the golang protobuf library isn't playing nicely with the way cometbft encoded timestamps:

```
grpcurl -d '{ "height": 326710 }' grpc.testnet.penumbra.zone:443 penumbra.util.tendermint_proxy.v1.TendermintProxyService.GetBlockByHeight
Failed to format response message 1: ns out of range [0, 1000000000)
```

and I can't find a command line flag to tell `grpcurl` to print the raw response

I then tried writing a test script in Rust, and was able to call against localhost, but not the testnet endpoint:

```
let mut tm_client = TendermintProxyServiceClient::connect("http://localhost:8080").await?;
let r = tonic::Request::new(GetBlockByHeightRequest { height: 326_710 });
let res = tm_client.get_block_by_height(r).await?.into_inner();
```

^^ that works

```
let mut tm_client = TendermintProxyServiceClient::connect("https://grpc.testnet.penumbra.zone:443").await?;
let r = tonic::Request::new(GetBlockByHeightRequest { height: 326_710 });
let res = tm_client.get_block_by_height(r).await?.into_inner();
```

^^ that doesn't:

```
Error: Status { code: Internal, message: "protocol error: received message with invalid compression flag: 52 (valid flags are 0 and 1) while receiving response with status: 404 Not Found", metadata: MetadataMap { headers: {"content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff", "content-length": "19", "date": "Tue, 04 Jun 2024 17:54:11 GMT"} }, source: None }
```

I have no idea why it would get a 404 on grpc.testnet.penumbra.zone but not localhost, especially considering that I was able to `grpcurl` the endpoint.

**Comment by zbuc** [comment]
The underlying issue with using `grpcui` to call is the same golang parsing issue. If you use the Chrome network inspector and check the response you'll find:

```
  "responses": [
    {
      "message": "ns out of range [0, 1000000000)",
      "isError": true
    }
  ],
```

**Comment by zbuc** [comment]
Figured it out, that was Tonic feature flags.

I'm able to call the API from rust code now and get a response so I don't think the API is actually **broken** however there is an issue in that historical data is unavailable post-upgrade. I know @conorsch has been looking at things in that domain, maybe there's a fix?

**Comment by turbocrime** [comment]
<img width="352" alt="Screenshot_2024-06-04_at_11 44 15" src="https://github.com/penumbra-zone/penumbra/assets/134443988/a0b20af0-add3-4fec-87f1-efa4213b3e1a">

nanos from the endpoint appear to be negative, which is against spec

https://github.com/protocolbuffers/protobuf/blob/bf7ac9f2f11e15c1a8f4b41428a75ad1c039a8fe/src/google/protobuf/timestamp.proto#L133-L144

````proto
message Timestamp {
  // Represents seconds of UTC time since Unix epoch
  // 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
  // 9999-12-31T23:59:59Z inclusive.
  int64 seconds = 1;


  // Non-negative fractions of a second at nanosecond resolution. Negative
  // second values with fractions must still have non-negative nanos values
  // that count forward in time. Must be from 0 to 999,999,999
  // inclusive.
  int32 nanos = 2;
}
````

**Comment by turbocrime** [comment]
notably, timestamp with negative nanos are unable to re-transmit to the client through our web communication channel

<img width="1026" alt="Screenshot_2024-06-04_at_11 21 26" src="https://github.com/penumbra-zone/penumbra/assets/134443988/549068d6-1752-43b5-83ad-49007e517f9e">

**Comment by zbuc** [comment]
Using an `int32` to hold a value that's supposed to be positive is chaotic

**Comment by turbocrime** [comment]
https://github.com/tendermint/tendermint/blob/35581cf54ec436b8c37fabb43fdaa3f48339a170/spec/consensus/signing.md#timestamp

>Timestamp validation is subtle and there are currently no bounds placed on the timestamp included in a proposal or vote. It is expected that validators will honestly report their local clock time.

**Comment by zbuc** [comment]
Closing as this isn't actually "broken" (well besides the nanos thing) and we need to build our own RPC endpoint
