### ISSUE TITLE
ibc: Missing check in ClientState::new

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#4548]
**Describe the bug**
The ClientState::new function in ibc-types shares most of its checks with ibc-go's ClientState.Validate but omits the check that chain_id is nonempty, and none of ChainId's From/FromStr trait implementations contain this check. This will result in penumbra-ibc nodes accepting chain IDs that ibc-go nodes will reject (though when referring to the chain ID "", it will reserialize it as "-0", which ibc-go will accept).

The ibc-go library [checks](https://github.com/cosmos/ibc-go/blob/3fbd2dfb5e42dc1cc2c8bb7bb0ff654f13874760/modules/light-clients/07-tendermint/client_state.go#L112-L114) that the chain ID is nonempty.

**Expected behavior**

This likely does not have any security impact, but it is a deviation from the specification and can potentially lead to an issue in the future.

**Comment by erwanor** [comment]
This specific addition was done in https://github.com/penumbra-zone/ibc-types/pull/88
