### ISSUE TITLE
`type_url` -> `type` in IBC protobuf encodings

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#4563]
**Describe the bug**

Skip reported difficulty loading an IBC relay transaction: https://app.testnet.penumbra.zone/#/tx/b7747ee674e8a9976fbc4b829c7eb1a69addb973db5f1c52658285e7012874f5

The error reported was `ConnectError: [unknown] cannot decode message google.protobuf.Any from JSON: "@type" is empty`.

@turbocrime said that typically other views fed to the web service via protojson have a `type` field rather than a `type_url` field. We have custom code handling IBC type serialization that uses `type_url` instead: https://github.com/penumbra-zone/penumbra/blob/main/crates/core/component/ibc/src/ibc_action.rs#L215

This PR seems related and is when the `type_url` field was introduced: https://github.com/penumbra-zone/penumbra/pull/3422

**Comment by turbocrime** [comment]
`{ type_url, value }` is a valid structure for a protobuf `Any`

it's strange that bufbuild refuses to deserialize this

**Comment by turbocrime** [comment]
https://github.com/protocolbuffers/protobuf/blob/a1e78a52e610db390f30897bb635146f8e801aaa/src/google/protobuf/any.proto#L128-L162

**Comment by turbocrime** [comment]
it seems like protojson is supposed to prefer the `@type` annotation with an unpacked structure, whereas the original protobuf wire type is a literal type_url and value pair. so json serialization is being improperly applied somehow

**Comment by zbuc** [comment]
The `IbcRelay` proto message is a little different from most of the other views in that it contains an `Any` field that we populate with the type_url/value pair, rather than relying on serde to serialize via `pbjson`: https://github.com/penumbra-zone/penumbra/blob/main/proto/penumbra/penumbra/core/component/ibc/v1/ibc.proto#L10 it's possible that we are doing something subtly wrong

**Comment by turbocrime** [comment]
afaik this is the first time we're shipping `Any` accross the `serde_wasm_bindgen` boundary, so i expect it's in the wasm bindgen serializer which has some custom configuration. we could perhaps serialize it to binary to sidestep the issue

**Comment by turbocrime** [comment]
https://github.com/penumbra-zone/web/blob/20bb7acc5c9d50eb53157c10aaca7f4a5167bfaf/packages/wasm/crate/src/tx.rs#L176-L387

**Comment by zbuc** [comment]
Closing this as it was fixed in the wasm serialization logic in https://github.com/penumbra-zone/web/pull/1255
