### ISSUE TITLE
list validators in pcli returns no validators

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#458]
# Steps to reproduce

1. Start `pd` with at least one validator in the genesis file
2. `cargo run --bin pcli -- -n 127.0.0.1 stake list-validators`

# Expected behavior

Single validator appears in the output table

# Actual behavior

```
Voting Power  Commission  Validator Info
```

# Comments

Not sure if error in pcli, pd, or if this is only partially implemented

**Comment by avahowell** [comment]
I think this is due to #462
