### ISSUE TITLE
pcli cannot query dex "all-positions"

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#4584]
**Describe the bug**
Running `pcli query dex all-positions` results in a panic.

**To Reproduce**
1. Use `pcli` version `v0.77.2`
2. Run `pcli query dex all-positions` 
3. Observe error:

```
❯ pcli query dex all-positions
Scanning blocks from last sync height 484118 to latest height 484118
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
thread 'main' panicked at crates/bin/pcli/src/command/utils.rs:36:63:
assets are known: overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
Current positions on chain should be viewable by pcli.

**Additional context**
This bug is replicable on current main (3ab4889be97ed39a7d6acfdb533fa58b897771b9) as well. Didn't seem to matter which wallet is used, given that it's a query cmd.

**Comment by conorsch** [comment]
Possibly related to #4452 / #4453?

**Comment by zbuc** [comment]
Related to https://github.com/penumbra-zone/penumbra/pull/4583 ?

**Comment by zbuc** [comment]
@conorsch I'm unable to replicate on main against the testnet deployment, are you still able to?

**Comment by conorsch** [comment]
Also cannot replicate!
