### ISSUE TITLE
rustls 0.20 is unmaintained

### ISSUE THREAD

**Issue by dynst** [penumbra-zone/penumbra#4591]
The upstream [Security Policy](https://github.com/rustls/rustls/blob/main/SECURITY.md) for rustls says 0.20.x isn't receiving any updates. The only user of rustls 0.20 is `penumbra-auto-https` (running `cargo tree --inverse` shows everything else depends, directly or indirectly, on 0.21.x).

**Comment by conorsch** [comment]
Closed by https://github.com/penumbra-zone/penumbra/pull/4592. Confirmed on preview that i can use latest-main pcli against the grpc endpoint and the status page is still working well too.
