### ISSUE TITLE
restarting node with quarantined notes results in foreign key error

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#461]
**Describe the bug**
`pd` restarting with quarantined notes results in FK error

**To Reproduce**
I don't have a clean reproducer here (was doing exploratory testing), but I was basically doing the following:

1. Start `pd` from clean state
2. Delegate and then undelegate
3. Immediately stop `pd`
4. Restart `pd`

**Expected behavior**

`pd` restarts and resumes

**Actual behavior**

```
Mar 01 14:51:42.497  INFO abci{addr=127.0.0.1:56305}:abci:Commit: sqlx::query: INSERT INTO quarantined_notes ( …; rows: 0, elapsed: 3.202ms

INSERT INTO
  quarantined_notes (
    note_commitment,
    ephemeral_key,
    encrypted_note,
    transaction_id,
    unbonding_height,
    validator_identity_key
  )
VALUES
  ($1, $2, $3, $4, $5, $6)

thread 'tokio-runtime-worker' panicked at 'commit must succeed: error returned from database: insert or update on table "quarantined_notes" violates foreign key constraint "quarantined_notes_validator_identity_key_fkey"

Caused by:
    insert or update on table "quarantined_notes" violates foreign key constraint "quarantined_notes_validator_identity_key_fkey"', /Users/redshiftzero/Documents/penumbra/pd/src/consensus/worker.rs:89:26
```

**Additional context**
I think this is a low priority bug but nevertheless filing for awareness

**Comment by hdevalence** [comment]
This might be fixed, or it will disappear in #488
