### ISSUE TITLE
Many active dydx addresses are missing from the distribution

### ISSUE THREAD

**Issue by Vovochka84** [penumbra-zone/penumbra#4628]
# Analysis of Missing dydx Addresses in Penumbra Distribution

Hi, I have checked the Penumbra airdrop distribution and found that some dydx addresses are missing.

## Methodology

I used the Numia BigQuery database, which contains all the data from the dydx chain, and filtered out all the addresses that were maker or taker (used the dydx perps) at least once before `2024-04-01`.

```sql
WITH filtered_data AS (
    SELECT taker AS address
    FROM `numia-data.dydx_mainnet.dydx_match`
    WHERE block_timestamp < '2024-04-01 00:00:00'
    UNION DISTINCT
    SELECT maker AS address
    FROM `numia-data.dydx_mainnet.dydx_match`
    WHERE block_timestamp < '2024-04-01 00:00:00'
)
SELECT DISTINCT address
FROM filtered_data
ORDER BY address;
```

Then I converted all the addresses to Cosmos format using bech32 and compared them with the Penumbra distribution 160k address list.

Files Attached

	•	dydx_users_before010424.txt - Result of the query from Numia database
	•	dydx_users_converted.txt - Same addresses but in Cosmos format
	•	not_found.txt - The addresses that are missing
[dydx_users_before010424.txt](https://github.com/user-attachments/files/15872687/dydx_users_before010424.txt)
[dydx_users_converted.txt](https://github.com/user-attachments/files/15872696/dydx_users_converted.txt)
[not_found.txt](https://github.com/user-attachments/files/15872732/not_found.txt)

**Comment by erwanor** [comment]
Hi, sorry but this is out of scope for this repository. You should reach out to the people/communities involved directly.
