### ISSUE TITLE
pd: pick a smaller value for `mempool.max_tx_bytes`

### ISSUE THREAD

**Issue by dynst** [penumbra-zone/penumbra#4629]
In the cometbft config template, maximum individual transaction size ([`max_tx_bytes`](https://github.com/penumbra-zone/penumbra/blob/1a19087c2f006d4672ac8b7dd7cb17f78fad65b4/testnets/cometbft_config_template.toml#L307C1-L309C23)) should probably be smaller than the maximum block size (the consensus parameter) that just got lowered in #4597. What's a reasonable value?

**Comment by erwanor** [comment]
We need empirical data to set a judicious default in the template, so we can revisit later, but a safe upper bound should be ~30KB. This gives ample room for a user to open a collection of replicating LPs and roll block-scoped orders.
