### ISSUE TITLE
pd(template): adjust evidence `max_bytes`

### ISSUE THREAD

**Issue by dynst** [penumbra-zone/penumbra#4635]
A block is comprised of 3 things: validator commitments, misbehavior evidence, and transactions.

#4597 set the maximum total block size `max_bytes` to 1MiB, but now it's exactly equal to misbehavior evidence `max_bytes`.

https://docs.rs/tendermint/0.34.1/tendermint/evidence/struct.Params.html#structfield.max_bytes

> This sets the maximum size of total evidence in bytes that can be committed in a single block, and should fall comfortably under the max block bytes. The default is 1048576 or 1MB.

Should the evidence limit be decreased or the block size limit be increased?

**Comment by conorsch** [comment]
Resolved by #4637.
