### ISSUE TITLE
Add IBC Packets to Penumbra transactions

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#464]
We need a way for relayers to add IBC messages to the Penumbra chain state, so they can be processed by Penumbra's IBC component. This mechanism should allow essentially arbitrary data packets, to be processed by the IBC component.

Our transactions are proto-based, and IBC is also proto-oriented, so this probably looks like having an additional transaction action, say `IBCPacket`, that contains a single IBC message; relayers can create transactions with arbitrarily many `IBCPackets` (subject to usual concerns about gas). 

Questions:

- [x] How do we represent the contents of an `IBCPacket`? Do we have plain bytes, or do we import the IBC protos and refer to those types in the Penumbra protos, or do we use some kind of proto "any type" / dynamic downcasting / etc?
- [x] How do IBC messages work with `CheckTx` vs `DeliverTx`? Presumably there's validity checking before block inclusion, but how do we actually implement this?  Do we need the mempool to have a copy of the IBC state machine to do "trial execution" of IBC messages?

**Comment by avahowell** [comment]
this is completed with #477: we now have the IBCAction type that encapsulates IBC packets
