### ISSUE TITLE
Basic IBC chain parameters

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#466]
We should add additional chain parameters that control how IBC works.  In the future, these could be dynamically controlled by governance, but should be statically set for now.

A basic set would be:

- is IBC enabled at all, i.e., can the chain create connections to other chains?
- are inbound IBC transfers enabled?
- are outbound IBC transfers enabled?

Some add-ons that could be useful when testing would be:

- what is the cap on balance of payments into the chain?

**Comment by avahowell** [comment]
This is done as of #469, modulo the cap on balance of payments into the chain
