### ISSUE TITLE
Support storing signed messages from cli

### ISSUE THREAD

**Issue by zmanian** [penumbra-zone/penumbra#4660]
In current flows with pcli, if the broadcasting the TX fails for any number of common networking issues then the user must sign again from scratch.

This is particularly frustrating when using threshold custody because then you must repeat the interactive steps.

The Cosmos SDK cli has `--offline` which assembles the signed message and 'tx broadcast' commands the enable creating a signed message and then later broadcasting it.

This would be helpful flow to have in pcli

**Comment by aubrika** [comment]
Having experienced this myself, I agree this is a significant usability problem - thanks for writing up an issue, we will prioritize this.

**Comment by cronokirby** [comment]
I think this would be good to add; one inherent limitation is that the TX might become stale for various reasons in the meantime, e.g. if chain params change. Nonetheless, because this can still work, this is a good idea.
