### ISSUE TITLE
ICS-20 Fungible Token Transfer Support

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#467]
We need to implement a variant of [ICS-20](https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer) that shields tokens as they're transferred into Penumbra.

There are two alternative mechanisms for doing this:

1. Specify a Penumbra address directly as the destination address.  The IBC component of the Penumbra chain sees this destination address, and then deterministically generates a (public) blinding factor for a note with the correct value and denomination controlled by the specified destination address, and then includes that (public) note in the chain state.
2. The sender creates a (private) note, and submits an encryption of the note, the note commitment, and a zkproof of correctness, all bundled up and encoded in the destination address field of the transfer as a "one-time deposit address".  The IBC component of the Penumbra chain verifies the proof and checks consistency with the claimed transfer amount, then includes the (private) note in the chain state.

The difference is that in (1), observers learn the address the funds were transferred to, while in (2), the addresses are not revealed.  This provides better privacy, but at a fairly steep cost to usability/interoperability, since sending funds into Penumbra requires an implementation of our proof system.

On the other hand, while (1) reveals the link between the transparent counterparty chain address and the destination shielded address on Penumbra, there's no further information leak, and any *use* of the transferred funds *within Penumbra* can't be linked to the address or the transfer.

Because of the usability cost, I think it would be better to start with (1) as a pragmatic choice.

Further components to implement:

- [x] #976
- [x] #977
- [x] #980
- [x] #978
- [x] #979
- [x] #982
- [x] #985
- [x] #981
- [x] #2534
- [x] #2284

**Comment by avahowell** [comment]
This is all implemented now, with the exception of any additional circuit breakers we want to add (in addition to the ones in the ICS-20 spec), and handlers for packet timeouts.

**Comment by conorsch** [comment]
Almost there! We still need to tackle https://github.com/penumbra-zone/penumbra/issues/981, and we just added mention of https://github.com/penumbra-zone/penumbra/issues/2284, since that's required for us to close this tracking issue out confidently.

**Comment by hdevalence** [comment]
@avahowell Can we close this out? It looks like #981 may already be done?
