### ISSUE TITLE
pindexer: dex: implement `/api/blockTimestamps` related events and tables

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4737]
We want to augment pindexer to support indexing for https://github.com/penumbra-zone/dex-explorer/blob/2b70ae60529284309f8748f6ca6a154a2bab82a9/src/pages/api/blockTimestamps/%5B...params%5D.js, adding in any events where necessary.

**Comment by vacekj** [comment]
Closing as previously completed - verified the data is already there
