### ISSUE TITLE
pindexer: dex: implement `/api/blocks` related tables and events

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4738]
We want to augment pindexer to support indexing for https://github.com/penumbra-zone/dex-explorer/blob/2b70ae60529284309f8748f6ca6a154a2bab82a9/src/pages/api/blocks/%5B...params%5D.js, adding in any events where necessary.

**Comment by vacekj** [comment]
Verified that this only gets the height and timestmap of the blocks - therefore already completed.
