### ISSUE TITLE
 pindexer: dex: implement `/api/block` related events and tables

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4740]
We should get to parity with:
https://github.com/penumbra-zone/dex-explorer/blob/2b70ae60529284309f8748f6ca6a154a2bab82a9/src/pages/api/lp/block/%5B...params%5D.js

**Comment by vacekj** [comment]
this will be fixed by #4771

**Comment by vacekj** [comment]
closed by #4771
