### ISSUE TITLE
 pindexer: dex: implement `/api/shieldedPool` related events and tables

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4742]
We should get to parity with:
https://github.com/penumbra-zone/dex-explorer/tree/2b70ae60529284309f8748f6ca6a154a2bab82a9/src/pages/api/shieldedPool

**Comment by vacekj** [comment]
The responsibility of denoms is now correctly shifted to frontends and consumers, and is no longer a responsibilty of the backend / indexer.
