### ISSUE TITLE
CI: run testnet for X blocks

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#475]
We've had a few `pd`-crashing bugs in `main` at:
1. `InitChain`
2. the `Commit` phase at the end of a block
3. During the transition between epochs

Right now we don't catch these in CI or test (related: #230).

We could have a CI job that spins up the testnet, runs for X blocks (or X * (10 seconds) time) ideally up through the first epoch boundary. If `pd` crashes, the job would fail. This would also provide a clear indication to developers as to the state of the `main` branch.

**Comment by hdevalence** [comment]
Another thing that would be useful to do (although it could be in a later chunk of work than this one) would be to also have a sequence of `pcli` invocations with some expected results.  That way we could also check that someone can send + receive funds, etc.
