### ISSUE TITLE
Can't see balance

### ISSUE THREAD

**Issue by sruPL** [penumbra-zone/penumbra#4778]
Can't get to see my balance or anything, blocks show as synced and green dot but getting this error everywhere:

TypeError: Wr[Symbol.iterator] is not a functionTypeError: Wr[Symbol.iterator] is not a function

I set the RPC and frontend as everyone adviced. Tried to search in google (no results), clear cache, reinstall wallet, etc. nothing worked.

**Comment by aubrika** [comment]
Sorry to hear you are having issues! Support requests like this should be made in the Discord, so that the moderation team there can determine if this is a bug: https://discord.gg/DQ92aHbH 

(cc: @grod220)
