### ISSUE TITLE
Discovering the position id of a new LP position created with pcli is high friction

### ISSUE THREAD

**Issue by zmanian** [penumbra-zone/penumbra#4792]
When creating an lp position with `pcli tx lp order buy`, you get a transaction_hex back but a more typical workflow would be to either monitor the position with `pcli query dex position` or with the dex explorer. 

To do that step, you need your position id. My current workflow is to call `pcli view balance` and look all my open position_nfts to find the one that was created.

**Describe the solution you'd like**

It would be useful to either have a position specific view that would basically show richer information about all open positions and/or it would be useful to have the `pcli tx lp order buy/sell` commands return a position_id.

**Comment by hdevalence** [comment]
One very low effort improvement is that the command should print out the position ID before submitting the TX

**Comment by cronokirby** [comment]
Resolved in https://github.com/penumbra-zone/penumbra/pull/4798, for now
