### ISSUE TITLE
PD migrate should check the expected version of state before migrating

### ISSUE THREAD

**Issue by zmanian** [penumbra-zone/penumbra#4793]
During a migration, pd migrate should avoid being run against the wrong version of state by checking the version of the state is expected before performing a migration.

this would help prevent operator error.

**Comment by conorsch** [comment]
This is a great idea. I've posted a proposal for how this might week [over on the forum](https://forum.penumbra.zone/t/pre-uip-version-aware-migrations-for-chain-upgrades/120) to gather additional feedback.
