### ISSUE TITLE
penumbra-ibc library accesses penumbra specific rocksdb path

### ISSUE THREAD

**Issue by jbowen93** [penumbra-zone/penumbra#4812]
**Describe the bug**

Astria uses the `penumbra-ibc` library.

When we attempt to do an IBC withdrawal we make a call to [`send_packet_check()`](https://github.com/astriaorg/astria/blob/main/crates/astria-sequencer/src/ibc/ics20_withdrawal.rs#L135) which calls  [`get_current_block_timestamp()`](https://github.com/penumbra-zone/penumbra/blob/d6422bf9aac6e953a9bd3db578bd6d90d71a59f1/crates/core/component/ibc/src/component/packet.rs#L137C39-L137C66)

```rust
async fn get_current_block_timestamp(&self) -> Result<tendermint::Time> {
        let timestamp_string: String = self
            .get_proto(state_key::block_manager::current_block_timestamp())
            .await?
            .ok_or_else(|| anyhow!("Missing current_block_timestamp"))?;

        Ok(tendermint::Time::from_str(&timestamp_string)
            .context("current_block_timestamp was an invalid RFC3339 time string")?)
    }
```
The call to `.get_proto(state_key::block_manager::current_block_timestamp())` makes a read from `sct/block_manager/block_timestamp` which causes an error in Astria as that db path doesn't exist. 

```rust
pub fn current_block_timestamp() -> &'static str {
        "sct/block_manager/block_timestamp"
}
```

**To Reproduce**

To reproduce the bug require setting up an Astria network, establishing a connection to another IBC chain, and attempting to perform a withdrawal from Astria to the other chain. The withdrawal fails.

1. **TODO**

**Expected behavior**
We would expect the ability to inject the Astria specific path for where timestamps are stored in our state tree.

**Additional context**

Astria Monorepo import ([link](https://github.com/astriaorg/astria/blob/c5364e801a193b799e71390f51c54b76a934c999/Cargo.toml#L80))
```
penumbra-ibc = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.78.0", default-features = false }
```

Astria host interface ([link](https://github.com/astriaorg/astria/blob/main/crates/astria-sequencer/src/ibc/host_interface.rs))
```
async fn get_block_timestamp<S: StateRead>(state: S) -> anyhow::Result<tendermint::Time> {
        state.get_block_timestamp().await
}
```

Astria workaround PR: https://github.com/astriaorg/astria/pull/1364/files

cc: @joroshiba @steezeburger

**Comment by hdevalence** [comment]
I believe there's already a way for the caller to thread in host-specific paths, and this part of the code just erroneously isn't using it.
