### ISSUE TITLE
pcli: migrate balance function

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#4831]
We should change pcli to have a new tx subcommand, `pcli tx migrate`, which takes the _destination FVK_ as a parameter and then constructs a transaction that:

- [x] has the memo field “migrate from `penumbrafullviewingkey1…` to `penumbrafullviewingkey1…`”
- [x] spends every single note from every account
- [ ] replicates the balances per account in the wallet of the provided destination FVK (minus any transaction fees)
- [x] pays the fees for this transaction from the lowest-numbered account with sufficient funds
- [x] include help text in clap explaining that this is for migrating custody mechanisms

**Comment by cronokirby** [comment]
Not quite done yet because we're not replicating the account structure

**Comment by conorsch** [comment]
> replicates the balances per account in the wallet of the provided destination FVK (minus any transaction fees)

Ah, I didn't notice this was in the spec: thought the changes in #4842 were sufficient to close.
