### ISSUE TITLE
Change `pd` base image to use latest stable Rust

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#484]
We should update the `pd` base image to use the latest stable Rust, to match the CI GH actions:

> I see that this was resolved with @avahowell's latest push, but the smoke test GH action and the rust CI GH actions are both using `actions-rs/toolchain@v1` with the stable [toolchain](https://github.com/actions-rs/toolchain#inputs). However, it looks like the `rustc` version issue reported in the [failed smoke test build](https://github.com/penumbra-zone/penumbra/runs/5505524664?check_suite_focus=true) was due to the version of rustc specified (1.56.x) in the [base image](https://github.com/penumbra-zone/penumbra/blob/main/Dockerfile#L1) used for `pd`, so if we see a similar error we could bump up the base image version.

_Originally posted by @redshiftzero in https://github.com/penumbra-zone/penumbra/issues/483#issuecomment-1065350862_

**Comment by redshiftzero** [comment]
Addressed in #593
