### ISSUE TITLE
Noble-Penumbra auto-deposit prototyping

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#4857]
Noble Express is shipping signerless autoforwarding soon, and we can potentially capitalize on this functionality to enable signerless autoforwarding to Penumbra.

The existing forwarding docs are here: 

https://docs.noble.xyz/modules/forwarding

And the described functionality will be extended to accept `nobled tx forwarding register-account-signerlessly` , which option is already live on their testnet.

The current forwarding protos are found here: https://github.com/noble-assets/forwarding/blob/v1.x/proto/noble/forwarding/v1/tx.proto (these will change with their 0.50 release in November)

On our side, we will at the very least need to set up IBC channels for testing, and we should do that first to see if it works for us out of the box - if we need additional changes, we can track them here as we discover them.

**Comment by hdevalence** [comment]
https://github.com/noble-assets/forwarding/blob/v1.x/x/forwarding/client/cli/tx.go#L53 looks like the Go impl of the command

I think we'll need to:

- figure out how to import the Noble protos into `pcli`
- figure out how to construct a Noble tx inside `pcli`
- figure out what the state machine for the registration is

**Comment by zbuc** [comment]
#4865 introduces a simple working prototype of registering the Noble forwarding address associated with a specific Penumbra address.

Follow-up work should be figuring out the desired end-user interaction and steps needed to integrate with the web front-end.

From @hdevalence:

> i think we want to make it so that when the user views an address (in prax or pcli) it will kick off a background task that polls a noble RPC until a balance is detected and then registers the address
