### ISSUE TITLE
pindexer: don't put empty reserves on dex_lp_update close events

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4867]
Right now, when a position is closed, the reserves appearing in that update are empty, because the update doesn't touch the reserves.

When populating the database it would be 10x more convenient as a consumer if the reserves field were always present, so that you don't have to manually look at the previous row to figure out what the unchanged reserves are.

We should, on a close event, look up the current reserves and put that in the table, thus making those two columns of `dex_lp_update` non null.

This makes life in the dex explorer easier.

**Comment by aubrika** [comment]
Closed as superseded by #4883
