### ISSUE TITLE
Index candlestick events in pindexer

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4869]
Post https://github.com/penumbra-zone/penumbra/issues/4868, we should format the candlestick events into the dex component of pindexer to make generating charts for the dex explorer easy.

We should look into and measure to see if on the fly windowing functions are sufficient to provide windows of 1m, 1h, 1d, etc. or if we instead need to memoize these at the pindexer level.

**Comment by conorsch** [comment]
As with all event additions, once the change is merged, we'll need to backport to the `0.79.x` release series, to support [reindexing workflows](https://github.com/penumbra-zone/reindexer).
