### ISSUE TITLE
app crate doesn't keep component code behind feature flag

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4885]
**Describe the bug**
Other components keep the state machine part of the code behind a feature flag. The app crate doesn't. This means that any downstream consumer of the rust view server has to pull in and build the entire full node state machine and rocksdb.

**Comment by cronokirby** [comment]
Something this made me think of: what if moved the StateRead / StateWrite traits to another crate ; this would allow a lot of components to just depend on the traits, and not even pull in cnidarium itself

**Comment by hdevalence** [comment]
That could work, but I'm also not sure we'd need to do it, since AFAICT there's not a need to model state access in client code, right?

**Comment by conorsch** [comment]
While working on this, @cronokirby discovered https://github.com/rust-lang/cargo/issues/8157, which describes how feature selection can vary in cargo workspaces. For example:

1. `cargo build --release --bin pcli` will first build all workspace packages, selecting features as required to satisfy all bin targets, then selectively build only for pcli
2. `cargo build --release --package pcli` will build only the minimal set of features required by pcli

We've previously been using only the former, but we should probably prefer the latter in most places.
