### ISSUE TITLE
build: add overflow-checks to governance code

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#4888]
Based on one of the security audits in 2024Q3, we want to add overflow checks to the `penumbra-governance` crate. We can do this via a minimal diff to the workspace `Cargo.toml` file:

```diff
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -85,6 +85,12 @@ x86_64-unknown-linux-gnu = "buildjet-32vcpu-ubuntu-2204"
 [profile.dist]
 inherits = "release"

+[profile.dev.package.penumbra-governance]
+overflow-checks = true
+
+[profile.release.package.penumbra-governance]
+overflow-checks = true
+
 # config for 'cargo release'
 [workspace.metadata.release]
 # Instruct cargo-release to increment versions for all packages in the workspace in lockstep.
```

This change was originally submitted as a PR in #4860, but due to its consensus-breaking nature, we opted not to merge it into the `v0.80.x` release series. When planning the next protocol upgrade, we should revisit this patch, and include it then, with appropriate documentation.

**Comment by aubrika** [comment]
Kicking this out of this sprint to potentially include in a future upgrade

**Comment by hdevalence** [comment]
I don't think we should plan to do this, ever -- the consensus-critical logic shouldn't be determined by build flags. Instead, if there is critical logic, it should use checked operations.

**Comment by redshiftzero** [comment]
OK we can use checked operations instead of doing the crate-wide `overflow-checks`. Closing this one
