### ISSUE TITLE
Add `TransactionView::summary()` method

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4939]
**Is your feature request related to a problem? Please describe.**

There are many applications where it would be useful to display a summary of a transaction's effects on the balances of various accounts, both pre- and post-confirmation:

- **Pre-confirmation**: in an approval dialog, for showing an exact preview of the effects of a transaction
- **Post-confirmation**: in a frontend, for showing a summary of what a transaction did

This logic should be implemented once, in the Rust code, so that it can be standardized across the Penumbra ecosystem.

**Describe the solution you'd like**

- [x] The `Balance` struct improperly has a derived Serde representation. This is a bug and a violation of our serialization policy. Verify that this was never used. Define a Protobuf message for the `Balance` struct and use that as the serialization format.

- [x] Define a new Protobuf message and corresponding domain type, `penumbra.core.transaction.v1.TransactionSummary`, something like (sketch):
```protobuf
message TransactionSummary {
    message Effects {
        core.keys.v1.AddressView address = 1;
        core.asset.v1.Balance balance = 2;
    }
    repeated Effects effects = 1;
}
```

- [x] Define a new method `TransactionView::summary(&self) -> TransactionSummary` that produces a `TransactionSummary`, iterating through each visible action and collecting the effects of the transaction. This should preserve the info available in the `AddressView`s about the meaning of the addresses.

**Comment by erwanor** [comment]
This was done for `Output/Spend/Swap/SwapClaim` views in #4943. Adding the LP ones might enable some cool use cases, but afaict this is complete.
