### ISSUE TITLE
Feature Request: Countdown for Unbonding Delegations & Wallet Timeout Feature

### ISSUE THREAD

**Issue by kriptohaize** [penumbra-zone/penumbra#4958]
I would like to request the addition of two new features for the Prax wallet:

1. Countdown for Unbonding Delegations

- Purpose: To improve delegation management and user experience, it would be helpful to have a countdown feature that displays:

- Start date of the unbonding process.
- Estimated finish date or time remaining until completion.
- Reference: For example, the unbonding countdown of 14 days
![Screenshot 2024-12-13 105902](https://github.com/user-attachments/assets/3dec9fe9-c3fe-4b88-a99f-272206ddb1b6)
 at [app.osmosis.zone](https://app.osmosis.zone) offers a similar feature that tracks unbonding delegations. Having this in Prax will allow users to monitor their unbonding more effectively.

2. Wallet Timeout Feature

- Purpose: Enhance wallet security by automatically logging out or locking the wallet after a defined period of inactivity.

- Implementation Suggestion: Allow users to configure the timeout period (e.g., X minutes or X hours of inactivity) to align with their security needs.
- Benefits: This feature would provide an additional layer of security for users, especially those working in shared or public environments.

Use Cases:

- Delegators can track their unbonding timeline directly within the wallet, reducing confusion about when funds will be available.
- Users who forget to manually log out will have their session automatically secured after a period of inactivity.

Additional Notes:

- If this feature already exists or is under consideration, please let me know where I can track its progress.
- I am open to testing or providing feedback during development if required.
- Thank you for considering these suggestions!

**Comment by erwanor** [comment]
Thanks, this is interesting! Can you open this feature request in https://github.com/prax-wallet/prax 🙏 ?
