### ISSUE TITLE
Implement IBC Query Methods

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#497]
In order for IBC relayers to function, there are a variety of `Query` methods that must be implemented. Penumbra should implement a GRPC endpoint that implements the QueryProvider functionality here:

https://github.com/cosmos/relayer/blob/main/relayer/provider/provider.go#L103

Note that some of these functions, such as `QueryBalanceWithAddress` and `QueryBalance`, may not map perfectly to our state model.

**Comment by hdevalence** [comment]
Since our IBC logic is written as a `Component`, this is connected with the task of adding JMT-based query support in #554.

**Comment by hdevalence** [comment]
We should check whether the `QueryProvider` has a proto specification of corresponding gRPC methods, since then we could use tonic to derive a Rust trait for us to implement.  Otherwise, we'd probably want to write one (?)

**Comment by avahowell** [comment]
This is done as of #803
