### ISSUE TITLE
Implementation of IBC Light Client tracking logic

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#506]
The core building block of IBC is light clients. Now that we have a basic skeleton for our IBC component and IBC messages in Penumbra transactions (#504), we should add support for handling light client messages.

- [x] Implement IBC CreateClient
- [x] #634
- [x] #635
- [x] #636

**Comment by conorsch** [comment]
Moving out of "In progress" because it technically hasn't started yet.

**Comment by avahowell** [comment]
This is complete now :)
