### ISSUE TITLE
Track Tendermint evidence & slashings

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#512]
Right now when evidence comes in from Tendermint ABCI, we simply perform the slashing.

This process could be expanded to record the evidence alongside the associated punishment somewhere within the JMT.

We may not actually want/need this, so we should have a team conversation when this ticket is picked up.

**Comment by hdevalence** [comment]
I don't think we need to do this, because Tendermint tracks evidence already.
