### ISSUE TITLE
Better `Debug` implementation for encrypted memo data

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#532]
**Is your feature request related to a problem? Please describe.**

Currently, we get tracing output containing things like:
```
CompactOutput { note_commitment: note::Commitment(77ed613d09a42dd8dd1cb508a5f5d4ebe728a211ff869fa0e1fd5903c542ee10), ephemeral_key: decaf377_ka::Public(3e29b9e589024fc072de2ab1fa0ee61b23eee1bedf2878d1749a0760df8ac106), encrypted_note: [194, 204, 62, 161, 158, 60, 54, 139, 59, 241, 95, 120, 214, 141, 102, 92, 29, 197, 234, 146, 5, 131, 115, 200, 222, 141, 194, 76, 209, 233, 99, 58, 59, 117, 142, 40, 185, 57, 185, 240, 229, 253, 188, 94, 19, 4, 249, 254, 93, 109, 147, 15, 193, 235, 57, 104, 213, 160, 180, 243, 177, 50, 111, 73, 37, 25, 8, 252, 71, 53, 235, 191, 107, 31, 146, 38, 30, 176, 234, 107, 46, 9, 219, 125, 13, 127, 110, 75, 204, 120, 148, 152, 89, 220, 118, 72, 229, 65, 39, 66, 167, 222, 194, 198, 133, 59, 40, 242, 240, 178, 151, 190, 82, 234, 122, 152, 236, 138, 255, 32, 168, 88, 226, 152, 197, 21, 134, 186, 196, 53, 167, 148] }
```
The `encrypted_note` rendering here is very long and also useless, because it's just a bunch of numbers.

**Describe the solution you'd like**

We should format the `encrypted_note` with Base64, so that it's shorter and easier to skip over, by changing the `Debug` impl for `CompactOutput` to base64-encode the data.  This might require replacing the derived impl with a manual one, using [`debug_struct`](https://doc.rust-lang.org/stable/std/fmt/struct.Formatter.html#method.debug_struct); there are probably existing examples in the source code that could be found with `rg debug_struct`.

**Describe alternatives you've considered**

We could not format the encrypted note at all, but this means that the `Debug` output doesn't actually show the contents of the `CompactOutput`, which is bad.

We could use something other than Base64, like hex encoding, but Base64 is shorter, giving more compact string output for the common case where we don't care about the opaque contents.

**Comment by plaidfinch** [comment]
What if the `Debug` implementation tried to interpret the memo as a UTF-8 string, and fell back to Base64 in the case that it is not interpretable as UTF-8? This would support reading memos in the common case where the memo is UTF-8.

**Comment by hdevalence** [comment]
This is done already
