### ISSUE TITLE
adding new validators can stall consensus

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#558]
**Describe the bug**
When testing the Orthosie testnet, we discovered that creating new validators stalled the network. Currently it's unclear why this is happening. 

**To Reproduce**
1. Start a single validator testnet
2. Create a new validator using pcli

**Behavior**
A new row is added to the validators table, initially in the inactive state. This occurs without issue. 
However, Tendermint then stalls:
```
tendermint-node0    | 2022-04-05T17:31:22Z ERROR failed to apply block err="commit failed for application: error changing validator set: applying the validator changes would result in empty set" height=53325 module=consensus
```

**Comment by zbuc** [comment]
This might go away with the new Staking design, so will retest after the Postgres stuff is completely removed

**Comment by hdevalence** [comment]
Moving this out of the Herse milestone.

Currently we don't actually write back the validator states to Tendermint from the `Staking` component, so this won't affect the Herse testnet.  We should check whether the problem recurs before Philophrosyne.
