### ISSUE TITLE
Restructure `/crypto/` section in protocol spec

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#56]
The current structure of the protocol spec has one big Cryptography section, with a separate Primitives subsection.

I think this ends up being a bit unwieldy, since there's a lot of content in the Primitives section that gets hidden.

It would be better to divide the content based on whether or not it's Penumbra-specific, and create two sections, Cryptographic Primitives (containing all content that could be useful independently) and Protocol (containing how those legos are assembled into Penumbra).

**Comment by hdevalence** [comment]
@redshiftzero since this involves moving stuff around, we should coordinate on a window where it won't clobber any outstanding PRs.

**Comment by redshiftzero** [comment]
:+1: I'll get my work thus far towards #24 up for review today and then once that's merged we can move things around if that works
