### ISSUE TITLE
Choose a minimum denomination of the staking token

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#57]
This is the analogue of satoshi for BTC, wei for ETH, uATOM for ATOM, etc.

BTC: 1e-8 BTC
ETH: 1e-18 ETH
ATOM: 1e-6 ATOM

Choosing 1e-6 fits with the rest of the Cosmos ecosystem and is probably good enough. 1e-18 seems really excessive.

**Comment by redshiftzero** [comment]
This was done in #283, the minimum denomination is 1e-6
