### ISSUE TITLE
pcli --version / -V flag not working

### ISSUE THREAD

**Issue by pygmygoats** [penumbra-zone/penumbra#575]
**Describe the bug**
per #574  pcli is not titled correctly. In addition, the pcli --version and -V flags do not appear to be working, so it may be difficult to tell what version of the testnet one is on especially if one is updating from a previous testnet install. 

**To Reproduce**
1. cargo run --quiet --release --bin pcli --version
2. OR cargo run --quiet --release --bin pcli -V 
3. See "error: Found argument '-V' which wasn't expected, or isn't valid in this context"

**Expected behavior**
Print the tagged testnet version. 
`006-orthosie` 

**Screenshots**
<img width="589" alt="Screen Shot 2022-04-07 at 7 01 26 PM" src="https://user-images.githubusercontent.com/103226075/162338124-84d45504-1b04-41ca-addf-33166fa5d989.png">

**Comment by hdevalence** [comment]
I think part of this may be a Cargo behavior; running any binary with Cargo requires using `--` to separate arguments for the binary from arguments for cargo.  I'm not sure there's much we can do about that, but I agree it's really unintuitive.
