### ISSUE TITLE
Integrate TCT into client sync

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#590]
**Is your feature request related to a problem? Please describe.**

As described in #491, the new TCT design allows clients to skip processing of whole ranges of state updates they know they're not interested in.   The initial integration in #589 won't make use of these features, because they require some changes to the client protocol and sync / scanning logic.

Because this adds complexity to the client code, we shouldn't start it until after #587.

**Describe the solution you'd like**

- [x] Extend the client protocol's proto messages to include block and epoch root hashes
- [x] Refactor the client logic so that scanning is performed as a separate step from updating the TCT, and allow clients to insert block and/or epoch roots for periods where they had no new notes.  (TODO: expand this scoping when we get closer to implementation).

**Comment by plaidfinch** [comment]
This is partially implemented at the block level now, and remaining work to accelerate sync is tracked by #842.
