### ISSUE TITLE
Delegating to non-genesis validator causes `pcli stake show` to crash

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#619]
**Describe the bug**
If a validator is created post-genesis and you delegate to it, `pcli stake show` will begin crashing because it does not know about the delegation token type.

**To Reproduce**
1. Start a local testnet
2. Upload a new validator definition
3. Stake to the new validator
4. `pcli stake show`

```console
thread 'main' panicked at 'all asset IDs should have denominations stored locally', wallet/src/state.rs:618:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think the best way to handle this is during the chain sync.

**Comment by hdevalence** [comment]
Along the way to testing this, I noticed some awkwardness with the process of defining and uploading validators: #648
