### ISSUE TITLE
TCT Hashing Written Specification

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#658]
Before proceeding with changes outlined in #657, there should be a written specification of the TCT's hashing behavior.

In particular, this specification does not need to involve itself with any of three important properties of the real implementation: its _sparsity_ (it stores only the minimum structure needed to produce authentication paths to commitments marked `Witness::Keep`), its _incrementalism_ (it takes amortized constant time to insert a new commitment into an existing tree), and its _laziness_ (it only computes hashes on demand).

Instead, the specification should describe two functions:

1. a mapping from a sequence (an eternity) of sequences (epochs) of sequences (blocks) of commitments (`Fq` elements), to a dense three-tiered quad-tree structure, without mention of how to compute internal hashes for the tree's nodes, and
2. a mapping from any node within the tree (including leaf nodes) to its hash (an element of `Fq` also), defined inductively on the structure of the tree.

This specification should be added as a section to the mdbook for the penumbra spec.

**Comment by hdevalence** [comment]
The TCT already had design outline in #491, which got dropped along the way.  Rather than discarding it and starting over, we should use the already-existing problem motivation and scope in that issue.

**Comment by hdevalence** [comment]
Closed off of the priority list, the code is pretty well-documented.
