### ISSUE TITLE
Installation docs fixes

### ISSUE THREAD

**Issue by kobigurk** [penumbra-zone/penumbra#659]
1. `pd` requires `clang` to be installed to compile `librocksdb-sys`, missing from linux instructions in https://guide.penumbra.zone/main/pcli/install.html.

2. weird latexing going on here:
![image](https://user-images.githubusercontent.com/3520024/164296077-40a4acda-f8d6-4828-b8ff-aede65a5b493.png)

3. missing $ sign in 
![image](https://user-images.githubusercontent.com/3520024/164297084-e615046b-5314-49b2-96fa-be47c66b6166.png)

4. Also in 
![image](https://user-images.githubusercontent.com/3520024/164297191-dd6cbda7-92f0-46bf-bc03-cf41247c0286.png)

**Comment by hdevalence** [comment]
I wonder whether the weird LaTeX behavior is related to the missing $ signs?

**Comment by zbuc** [comment]
@hdevalence I fixed the same issue on some of the other documentation pages but missed this -- `katex` is parsing any `$` as a LaTeX special character and adding the `span` tags. The fix is that literal `$` characters in documentation always need to be escaped: `\$`

**Comment by hdevalence** [comment]
Hmm, even in code blocks ? That seems pretty suboptimal

**Comment by zbuc** [comment]
Yep. I tested locally and if I didn't have `mdbook-katex` installed, literal `$` within a code block worked fine, but as soon as I installed `mdbook-katex` it'd need to be escaped.
