### ISSUE TITLE
New TCT executable spec matching English spec

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#668]
Before revising the TCT implementation per #657, we should update the TCT spec to reflect this design. It's worth taking this opportunity to make the spec more readable and self-evidently correct, so a rewrite based on the original design rather than a straight-up revision is a suggested strategy.

**Comment by hdevalence** [comment]
The "TCT spec" referenced in this issue *is* part of the implementation, though, it's designed to test that specific implementation, and isn't useful outside of that context. So we should not do this in advance of making a plan about how to move forward with the TCT work.

**Comment by hdevalence** [comment]
Closed off the priority list
