### ISSUE TITLE
Unit tests for boundary conditions of full tiers in TCT

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#680]
The current random testing of the TCT is unlikely to explore the cases when a block, epoch, or eternity is full. We should write unit tests to ensure that these boundary conditions are handled correctly.

**Comment by hdevalence** [comment]
We should wait to do this until we have a plan on whether and how we want to integrate the existing TCT code, or go for an alternate path forward in the near term.
