### ISSUE TITLE
Update testnet deploy instructions to use Docker image for all operations

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#699]
https://github.com/penumbra-zone/penumbra/wiki/Deployment-checklist#deployment-steps-for-the-existing-node

Currently we have to compile `pd` on the host (just to run generate-testnet) as well as have a Docker container present. We could use host directory volume mounts to make this better.

**Comment by hdevalence** [comment]
Closing as obsoleted by the new Strangelove docker setup.
