### ISSUE TITLE
Set up cron job to schedule the snapshot of the addresses posted in the discord

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#700]
Scheduling this for the Friday before a Monday deployment will expedite the testnet deployment process

**Comment by plaidfinch** [comment]
A suggestion made was to make a galileo command that specifically outputs an allocations.csv format, so you don't have to do the shell glue yourself outside galileo.

**Comment by zbuc** [comment]
Might also be nice to have it take in the allocations.csv and perform deduplication as well (we have some duplicate allocations in there right now)

**Comment by hdevalence** [comment]
We've done OK with manually scraping from time to time, and I think we don't want to invest too much effort into the bot relative to other work.
