### ISSUE TITLE
Prevent validator upload from occurring until tendermint is caught up

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#707]
People are getting slashed unexpectedly because you can have your validator enter the Active state without tendermint having caught up.

Since we are already coupling the pcli code to validator behavior (signing the validator definition with the key from pcli), it might be a reasonable assumption that pcli would be run somewhere that it can establish an RPC connection to tendermint. (Not clear if this is true for custodied/offline private key use cases but I think so)

We could prevent the validator definition upload from proceeding until the tendermint RPC says it's caught up:

`curl -s http://0.0.0.0:26657/status | jq .result.sync_info.catching_up`

Ideally pcli would take a command line argument specifying the tendermint RPC address, using local host by default. We could either poll and wait or error out of the transaction if tendermint reports that it's not caught up.

**Comment by hdevalence** [comment]
Since validator definitions are uploaded rarely, I think the simpler behavior of erroring out of broadcasting is better.

> it might be a reasonable assumption that pcli would be run somewhere that it can establish an RPC connection to tendermint. (Not clear if this is true for custodied/offline private key use cases but I think so)

For the moment I think this is fine to assume; at some later point we could build tooling for offline signing, or wait for a validator who actually cares about that to implement it.

**Comment by zbuc** [comment]
We have "disabled" status now which makes this unnecessary, however we should document this
