### ISSUE TITLE
commit proving and verification keys for dev/testnet purposes

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#711]
For our zk proofs we'll need to generate and store in the repo the proving and verification keys for Groth16 proofs~some universal parameters to use with KZG10 commitments~. We'll do this in two phases:

1. dev and testnets: adding parameters for dev/testnet purposes (this ticket),
2. before mainnet: performing a decentralized setup (or reusing/extending an existing setup) (ticket #712),

These are parameters that `pd` (verifier) and `pcli` (prover) will both need access to, so the `penumbra-crypto` crate is a good home for them. 

~For generation, `jf_plonk::proof_system::structs::UniversalSrs` is the relevant struct: this is a wrapper around `ark_poly_commit::kzg10::UniversalParams`. We'll generate an SRS size of 100000 points or so for supporting future functionality.~

**Comment by redshiftzero** [comment]
Sizes of the keys as of commit 0db4a2be63ff444aa5e481cf82e6eb22e6653500:

Output proof:
- Proving key size: 3025344 bytes ≈ 3 MB
- Verification key size: 632 bytes

Spend proof:
- Proving key: 7466016 bytes ≈ 7.4 MB
- Verification key: 680 bytes

**Comment by redshiftzero** [comment]
Documenting for posterity some of the notes from out of band discussions on this in December between me, @conorsch and @hdevalence:

## Options

### Bake into build
* ~10 MB increase in binary size for pcli, will increase as we add more proofs
* pd: not a concern, verifying keys are tiny
* pd/pcli binaries are currently 47MB
* Container images are ~100MB (`podman inspect ghcr.io/penumbra-zone/penumbra | jq '.[0].Size'  -r | xargs numfmt --to=iec` = “109M”)

### Object storage
* Dump in s3 bucket, make sure URLs are versioned (so they’re available indefinitely)
* Free caching
* No servers
* Centralized
* Leaks network privacy (bad)

### Store in ipfs
* Auth’d automatically (keyed by hash)
* Not centralized, others could mirror
* Requires lots of tooling changes
* Doesn’t simplify build story
* Still leaks network privacy data

For now we're proceeding with the first option, to bake into the build, see #1885 for more details on that.

**Comment by conorsch** [comment]
Still hashing some CI issues on the first pass, but we're hoping to merge the initial set of parameters for 041-adtraste (#1877). :crossed_fingers:
