### ISSUE TITLE
Remove `Component::new` from the `Component` trait

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#726]
**Is your feature request related to a problem? Please describe.**

Currently, we write the note commitment tree *data*, not just the note commitment tree *root*, into the Merklized storage.  This means that the internal representation of the note commitment tree is consensus critical, which is not what we want.  To fix this, we'll need to add a "sidecar" method to the storage that the shielded pool component can use to read and write the note commitment tree data.  But that requires that the shielded pool component needs to get and set data other than by the shared `State`, and this isn't possible, because the `Component` trait's `new` method means that a `Component` can only be constructed from the data in the `State`

**Describe the solution you'd like**

Remove the `Component::new` method from the trait, and move the implementations to be ordinary methods on the types implementing `Component`.

**Comment by plaidfinch** [comment]
This is already done in the TCT integration already merged.
