### ISSUE TITLE
Add method to `wallet_next::Storage` to ingest a `ScanResult` and `NoteCommitmentTree`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#751]
The `Storage` interface added in #613 only has individual read methods, not write methods. We don't want to have individual write methods, since we should only update the database state in two cases: 

1. when we initialize it with a new FVK;
2. when we scan a new block.

To do (2), in this issue, we should have a `record_block` method on `Storage`:
```
pub async fn record_block(&self, scan_result: ScanResult, nct: &mut NoteCommitmentTree) -> anyhow::Result<Self>
```
This would:

- [ ] Insert all of the new `NoteRecord`s into the `notes` table, destructuring the inner `Note` and serializing the fields as follows:
  - [ ] the `height_created` as the current `height`;
  - [ ] the `height_spent` as `None`;
  - [ ] the `note_commitment` as a `[u8; 32]` with `to_bytes`;
  - [ ] the `diversifier` as its inner `[u8; 11]`;
  - [ ] the `amount` as an integer;
  - [ ] the `asset_id` as a `[u8; 32]` with `to_bytes`;
  - [ ] the `transmission_key` as its inner `[u8; 32]`;
  - [ ] the `blinding_factor` as a `[u8; 32]` with `to_bytes`;
  - [ ] the `diversifier_index` as its inner `[u8; 11]`;
  - [ ] the `nullifier` as a `[u8; 32]` with `to_bytes`;
- [ ] **Detect spends**, by using the set of nullifiers in the `ScanResult` to update any rows of the table with matching nullifiers to have `height_spent` set to `Some(height)`.
- [ ] Construct the list of note commitments that were marked as spent in the previous step, and forget them from the NCT (this is why it's `&mut`); 
- [ ] Serialize the current NCT state to bytes with `bincode::serialize(nct)`, and update the (single) row of the `note_commitment_tree` table with the encoding.

This should all be done transactionally, since we're using SQLite as the synchronization mechanism between the worker task and the wallet service.

**Comment by aubrika** [comment]
What's the intended method for "forgetting" notes in the NCT, currently?
