### ISSUE TITLE
Implement basic grafana/prometheus monitoring

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#769]
It would aid in debugging and generally be cool if we were able to graph some of our data. We already have Prometheus and Grafana in the stack and accessible in the browser, we just need to start using them.

Initial graphs:
- [ ] Validator power by epoch
- [ ] Active validators by epoch
- [ ] Transactions by block

**Comment by hdevalence** [comment]
One code structure point to consider is how we want to have metrics in different components / crates. I think a useful pattern might be for each of the component crates to expose a register_all_metrics function in the crate root, similar to the one that already exists in pd. Then pd could call the metrics registration function for each crate it uses.

**Comment by hdevalence** [comment]
Another thing to consider is that Tendermint itself also has prometheus support. Perhaps a quick win would be to find some existing Grafana dashboards for Tendermint nodes, and pull them into the repo so they could be installed on the Grafana instance we create on deployment.

**Comment by hdevalence** [comment]
There's a tie-in with #621, in that it'd be convenient to have one place in the repo for all of the deployment-related configs (like grafana dashboards).

**Comment by hdevalence** [comment]
Adding to the next milestone, since we have some graphs, and we should make sure that they're persisted across deployments.

**Comment by hdevalence** [comment]
This is pretty much working now!
