### ISSUE TITLE
Spurious test failure in IBC code

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#797]
**Describe the bug**

The CI run for #796 failed because of an apparently spurious test failure:
```
 test component::client::tests::test_create_and_update_light_client ... FAILED

failures:

---- component::client::tests::test_create_and_update_light_client stdout ----
thread 'component::client::tests::test_create_and_update_light_client' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid argument: /tmp/.tmpqgt1D9/ibc-testing.db/CURRENT: does not exist (create_if_missing is false)', ibc/src/component/client.rs:607:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    component::client::tests::test_create_and_update_light_client
```

**Comment by hdevalence** [comment]
I think the test in question is using tmpdirs to make a testing `Storage` instance. This is a side note, but along the way to fixing it, I think it'd be useful to move that code into the `storage` crate as a `Storage::ephemeral_test_instance()` method that returns `(Self, Handle)`, where `Handle` is the RAII guard you get from the crate that makes temporary directories and cleans up the directory on drop.

**Comment by avahowell** [comment]
Closing this, this was due to a bug in the storage impl
