### ISSUE TITLE
Enable anonymous authentication for Grafana

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#798]
We don't have any sensitive data in Grafana, and it'd be helpful to have a public-facing dashboard that we could link to.  This would let people see the testnet activity, and help us collaboratively debug issues with our extended network (who might not be part of our GH org).  

Grafana docs: https://grafana.com/docs/grafana/latest/auth/grafana/#anonymous-authentication

**Comment by zbuc** [comment]
Done
