### ISSUE TITLE
Tendermint P2P issues

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#800]
This is a tracking issue for recording information about the issues we've been having with Tendermint's P2P layer. Each of our recent testnets have had issues keeping peers connected with each other.

Most recently, the Kore testnet had a bunch of network-related issues (and is now halted, for reasons that are ultimately downstream of those issues).

After launching the testnet, things appeared to work fine.  Block production proceeded normally. Then at some point, all of the non-`testnet.penumbra.zone` validators were unable to maintain connections and stay in sync.  The chain continued on with `testnet.penumbra.zone` having a >2/3 majority stake, until discord members delegated sufficient stake to their validators that it no longer had a supermajority of voting power and the ability to produce blocks independently of other nodes.  At that point, the chain halted, because the network conditions didn't allow it to talk to other validators.

<img width="1387" alt="Screen Shot 2022-05-11 at 5 59 04 PM" src="https://user-images.githubusercontent.com/44879/167971080-f71b5cca-024b-42d8-822a-fa6f1fb8be12.png">

The ABCI methods appeared to be working normally:

<img width="1442" alt="Screen Shot 2022-05-11 at 5 59 59 PM" src="https://user-images.githubusercontent.com/44879/167971173-0b895349-ac93-4e9b-b474-b381e104e8ff.png">

Tendermint would report connected peers, although those peers weren't able to stay in consensus:

<img width="1443" alt="Screen Shot 2022-05-11 at 6 01 54 PM" src="https://user-images.githubusercontent.com/44879/167971370-2f545f9c-23aa-419d-8e75-de0d7a0a8c9b.png">

One thing that's odd is that *after* the chain halted, the inbound network traffic did a step-up to 5MB/s:

<img width="1444" alt="Screen Shot 2022-05-11 at 6 02 45 PM" src="https://user-images.githubusercontent.com/44879/167971444-40c9e3e6-d986-46f7-920e-f58efdcadca8.png">

**Comment by hdevalence** [comment]
We should #798 so that we can link these dashboards.

**Comment by hdevalence** [comment]
@avahowell noticed that our instructions had people set `testnet.penumbra.zone` as a `persistent-peers`, meaning that they would always try to connect to it, rather than as an entry in `bootstrap-peers`, and wondered whether it was getting overwhelmed and hitting connection limits.  We increased the connection limits but this didn't seem to help much.  It seems surprising that even a few dozen connections would be too many.

She also noticed a surprising discrepancy with the `net_info` endpoint:
> also is http://testnet.penumbra.zone:26657/net_info showing everything? hard to believe there is only one peer
> maybe it's only outbound peers

**Comment by hdevalence** [comment]
I tried setting the testnet validator to use the legacy P2P stack, but got a bunch of errors connecting my own node to it.  The testnet validator felt that my node (not using the legacy stack) was sending PEX requests too often and getting disconnected.

**Comment by hdevalence** [comment]
@zmanian pointed to a potential issue with commit timeouts:

> Hey based on this 
https://twitter.com/penumbrazone/status/1524226482414915584?s=21&t=siLSE6F0UtO_i9AViZX4Ag
>
> The penumbra labs validator and all the other validators need to increase the commit timeout in the config.toml for tendermint
> because penumbra labs has  > 2f+1 of voting power
> their votes are always enough to finalize a block
> commit timeout sets your validator wait additional time for more votes to come in

Our validator on `testnet.penumbra.zone` is set to `5s` timeouts, but the default (used by other validators) is `1s`.

> you should double check
> this behavior looks like what would happen with 1s timeout commits

**Comment by avahowell** [comment]
>One thing that's odd is that after the chain halted, the inbound network traffic did a step-up to 5MB/s:

note: 5 MB/s is the default max bandwidth throttle for tendermint, set by `send-rate`.

**Comment by zmanian** [comment]
Can you post the config.toml you are using with your Tendermint?

**Comment by hdevalence** [comment]
Here's the `config.toml` from the testnet node: https://gist.github.com/hdevalence/e052cd754bb7045f34e718de0fa5579d

This is generated from this template file: https://github.com/penumbra-zone/penumbra/blob/main/testnets/tm_config_template.toml

**Comment by hdevalence** [comment]
In the end this turned out to be related to Tendermint 0.35, which is now EOL'd for this reason.
