### ISSUE TITLE
Extract state keys from component views

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#802]
**Is your feature request related to a problem? Please describe.**

Currently, we isolate all of the keys used to query the state into the implementations of the `View` traits.  This is good because it isolates all of the keys into one place (the read and write methods of the view traits), but it's still difficult to see a comprehensive list of all of the keys we use to store data in the state.

**Describe the solution you'd like**

Each component crate should have a (public) `crate::state_key` module.  This module should contain a bunch of bare functions, all of which return a `KeyHash`, and which take whatever arguments they need to produce the key, for instance:

```rust
fn token_supply(asset_id: &asset::Id) -> KeyHash {
    format!("shielded_pool/assets/{}/token_supply", asset_id).into()
}

fn known_assets() -> KeyHash { 
    "shielded_pool/known_assets".into()
}
```

Then the rest of the component crate can access these keys as `state_key::token_supply(asset_id)`, `state_key::known_assets()`, etc:
```rust
async fn token_supply(&self, asset_id: &asset::Id) -> Result<Option<u64>> {
    self.get_proto(state_key::token_supply(asset_id)).await
}
```

This is a totally mechanical refactoring, so it should be easy, if a bit tedious (`rg format!` would be helpful to catch any stray keys), but the upshot is that at the end, we'll have one file in each component that has a comprehensive list of keys we use to query the state.

**Comment by borngraced** [comment]
Interested...can assign please

**Comment by hdevalence** [comment]
> Interested...can assign please

@borngraced sure! I assigned you just now. One thing though is that this might end up on our critical path, so it'd be preferable if you could make a draft PR as soon as you start working on it, rather than when you're finished.  That way, if we discover that some later tasks need this in a time-critical way, and that we need to pick it up and carry it over the finish line to avoid blocking work, we'll be able to use the work you did.

**Comment by borngraced** [comment]
Ok sure will do that..👍
