### ISSUE TITLE
General-purpose state query RPC

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#803]
**Is your feature request related to a problem? Please describe.**

Currently, we only expose a limited subset of the public chain state through dedicated RPC methods.  However, it'd be useful to be able to query arbitrary parts of the chain state by key hash, especially following #802, when those keys are externally visible.

**Describe the solution you'd like**

Add new messages and RPC to the specific client protocol:
```proto
service SpecificQuery {
  rpc KeyValue(KeyValueRequest) returns (KeyValueResponse);
}

message KeyValueRequest {
  // The expected chain id (empty string if no expectation).
  string chain_id = 1;
  bytes key_hash = 2;
  // later: we can add a proof boolean that requests an auth proof
}

message KeyValueResponse {
  bytes value = 1;
  // later: we can add a merkle proof field that contains an auth proof
}
```

Then implement the backend handling for this query, which would just pull bytes out of the state and into the proto response.

**Comment by hdevalence** [comment]
@avahowell would something like this work for IBC, once we added proofs?

**Comment by avahowell** [comment]
Yes, I think so
