### ISSUE TITLE
Budget notes per block

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#830]
When adding notes to the TCT, we now have a hard limit on the number of output notes that can be included in a single block: 4^8. Once the TCT is integrated as a consensus-critical part of the chain, this will cause a chain halt if violated.

We should reject transactions in `check_tx_stateful` if they would cause the block to go "overbudget" on outputs. Additionally, we should restrict the number of funding streams per validator to a hardcoded limit, say, 64, to prevent a DoS attack where someone could upload 10,000,000 funding streams for their validator and cause the chain to reject all other transactions. We should also probably place funding stream outputs _first_ in a block, so that they are always definitely included, then add other transactions as possible.

Once we integrate ABCI++ it will be possible to control the inclusion of transactions in a block more precisely, and we should use this capability to allow transactions to linger to the next block in the mempool. In the current solution above, high-contention blocks may end up in a situation where the block proposer could add too many transactions, then some of them would be rejected for bringing the block overbudget, and they would need to be re-submitted.

**Comment by hdevalence** [comment]
We may not need to do this at all, depending on our block sizes.  Each output has a proof (~200bytes minimum), plus a note payload (~200 bytes), plus an encrypted memo (~600 bytes), giving about 1KB of data.  This isn't including any spends or other actions. 

If blocks are capped at, say, 1MB, then they won't contain more than ~1000 outputs each, well below the maximum.

**Comment by plaidfinch** [comment]
Doesn't this mean then that we will still have to budget, but for a different kind of quota? I imagine this is something we can only do effectively with ABCI++?

**Comment by hdevalence** [comment]
Yes, we need ABCI++ for this.

**Comment by erwanor** [comment]
This came up in discussions about adding a mint queue, reminder to myself to link this issue when it gets specified.

**Comment by hdevalence** [comment]
That issue was #3545 ; we can leave it unplanned for now. Other than the genesis case, the reasoning I posted above still applies.
