### ISSUE TITLE
Design notes on accelerated construction for TCT client sync

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#842]
There are four sub-tasks that could be performed under this header:

- [x] block-level serial acceleration using roots (implemented in https://github.com/penumbra-zone/penumbra/pull/921)
- [ ] epoch-level serial acceleration using roots
- [ ] parallel trial decryption (probably not worthwhile, it's trivial compared to poseidon hashing)
- [ ] parallel tree construction (either at block level, epoch level, or both)

**Comment by hdevalence** [comment]
Since this is just a performance optimization, we should wait to implement it until the chain is feature-complete, at which point we'll just have the view service to implement it in.

**Comment by plaidfinch** [comment]
Capturing some design/implementation notes here so they can be retrieved later. This may not make perfect sense to anyone, the intention is to capture the thoughts while they're here and can be paged in later.

### Trial decryption in parallel

Trial decryption can be parallelized by making a stream transformer:

```rust
struct DecryptedBlock {
    commitments: Vec<(tct::Witness, Commitment>,
    notes: Vec<Note>, // successfully decrypted
    // ... rest of structure unchanged
}

fn trial_decrypt(compact_block: CompactBlock) -> DecryptedBlock {
    // iterate through encrypted notes, trying to decrypt them,
    // and marking their commitments as `Keep` if successful
}

fn trial_decrypt_stream(
    compact_blocks: impl Stream<Item = CompactBlock>,
) -> impl Stream<Item = DecryptedBlock> {
    // ...
}
```

One possible implementation of `trial_decrypt_stream`: we `tokio::spawn_blocking` a number of worker tasks (probably equal to number of CPUs). Each task has a clone of a `mpsc::Sender<oneshot::Sender<(CompactBlock, oneshot::Sender<DecryptedBlock>)>>` "request queue". Tasks loop by sending a `oneshot::Sender` over this channel and waiting on the corresponding `oneshot::Receiver`, which will hand them back a `(CompactBlock, oneshot::Sender<DecryptedBlock>)`. They can then use `trial_decrypt` to get the `DecryptedBlock`, and send it back through the `oneshot::Sender<DecryptedBlock>`. Meanwhile, in `trial_decrypt_stream`, we loop over the stream items in `compact_blocks`: each is sent over the first-received `oneshot::Sender<(CompactBlock, oneshot::Sender<DecryptedBlock>)>` along with a `oneshot::Sender` generated to receive the result of the work. The corresponding `oneshot::Receiver<DecryptedBlock>`s are pushed into a `FuturesOrdered`, which is polled to yield resultant `DecryptedBlock`s as the output of the main function. In other words, the main function spawns the works, then loops over selecting between yielding completed results from the `FuturesOrdered` and dispatching new work as it comes in from the input stream. This select loop should happen in the context of a `stream!` macro, to make it easy to use `yield` syntax. Because worker tasks are `spawn_blocking`, they are not in an async context and therefore should use `blocking_send` on the "request queue". This design means that worker tasks indicate when they are ready for the next unit of work, exerting backpressure on the input stream. In order to ensure that backpressure propagates from the output stream to the input stream, the select should be `biased` towards yielding output, so that when the output stream lags, no more input items are consumed.

### Tree construction in parallel

In order to build the TCT, the consumer of the stream of `DecryptedBlock`s needs to read all the blocks until an epoch boundary (or end of stream), then make a decision about how to construct that epoch. For each such chunk, these are the possibilities:

1. These blocks are the trailing end of an epoch that was unfinished in the tree when the scan started: we should build the blocks in parallel, and insert them into the tree.
2. These blocks are the leading end of an epoch that is unfinished as of the end of the stream: we should build the blocks in parallel, and insert them into the tree.
3. These blocks constitute a full epoch from start to finish:
  (a) If none of the blocks contain any decrypted notes: we should insert the epoch root into the tree.
  (b) If at least one of the blocks contains decrypted notes: we should build the blocks in parallel, and insert them into a new epoch, then insert that epoch into the tree.
  
In the above, "constructing a block" should only be done from its constituent commitments if the block contained at least one decrypted note; otherwise, it should be constructed directly from the block root hash.
  
Case (3) dominates for longer scanning periods since it's the "meat of the sandwich". When epochs need to be constructed, their construction can be parallelized, just like the construction of blocks. This avoids a bottleneck where the blocks of an epoch are all constructed in parallel, but then that epoch needs to be constructed sequentially, before any further blocks can be constructed.

A similar pattern as in trial decryption can be used to parallelize epoch/block construction:

```rust
fn epochs_stream(
    decrypted_blocks: impl Stream<Item = DecryptedBlock>,
) -> (
    // leading blocks that finish the current epoch:
    impl Stream<Item = tct::builder::block::Finalized>,
    // complete epochs:
    impl Stream<Item = tct::builder::epoch::Finalized>,
    // trailing blocks that don't yet finish the last epoch:
    impl Stream<Item = tct::builder::block::Finalized>,
) {
    // ...   
}
```

The three outputs are meant to be consumed sequentially, because they will be generated sequentially. Alternatively, it would also be fine to have the output be a single `impl Stream<Item = Either<tct::builder::block::Finalized, tct::builder::epoch::Finalized>>`, which chains these three together.

The consumer of this stream then needs to insert each block or epoch sequentially into the tree. In the future, when the TCT can be incrementally serialized, this too should be a stream transformer, which outputs chunks of TCT state to be asynchronously (atomically) persisted. Insertion of entire epochs/blocks into the tree may require computing hashes, so it should be done in a dedicated compute thread made using `spawn_blocking`. When this thread finishes with the stream, its last action should be to compute the root of the tree, so that this doesn't accidentally get done on some arbitrary other task later.

In general, care should be taken to compute root hashes of finalized blocks and epochs _within the threads that construct them_, which avoids accidentally making this computation occur in the (more sequential) receiving thread. Root hashes should only be computed explicitly on finalized blocks/epochs.

This design is intended to dynamically balance the utilization of computational resources between different phases of scanning, using backpressure to determine which pieces of the computation receive more parallelization.

**Comment by hdevalence** [comment]
One thing to note about these ideas is that they're aiming to optimize the case where there is a lot of transaction activity (and hence, scanning to do, note commitments to insert).  But at the moment, this isn't the problem we have -- instead, we should first try to optimize the case where we're scanning many empty blocks.

**Comment by hdevalence** [comment]
Edited the title to "design notes" and closing as completed, since there are a lot of good ideas here, but we don't have any immediate plans to implement them in client software -- and the client software we'll want to implement them may change and evolve prior to our starting that optimization work, so it makes sense to save the context here but not preserve it as a work-item.
