### ISSUE TITLE
Assertion failure in `penumbra_tct::Tree::witness`

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#858]
**Describe the bug**

This line panics in debug-mode (sometimes?):
https://github.com/penumbra-zone/penumbra/blob/a12be7fe2d632c4d085109422bcac0d81304f507/tct/src/tree.rs#L215

This means that the index of positions of commitments is not correct; that is, the commitment represented by that leaf is not the same as the one being asked for.

**To Reproduce**

This was initially encountered in Galileo, because it was run in debug mode instead of release mode, which flipped on this assertion. I haven't had time yet to find a minimal reproducing example but I expect it's quite small.

**Expected behavior**

This assertion should never fail because the sidecar index in the `Tree` should always be correct.

**Comment by redshiftzero** [comment]
This is happening reproducibly locally in debug mode, it's possible it wasn't noticed earlier due to folks running in release mode

**Comment by plaidfinch** [comment]
The issue was caused by the `fast_hash` feature of the `penumbra_tct` crate, which was enabled across the workspace because it was enabled in only one crate (this was not the intended behavior). Because galileo is not in the penumbra workspace, it used the _correct_ hash function, which mismatched the fast (incorrect) hash function being used by mistake in `pcli`, leading to this assertion failure.
