### ISSUE TITLE
Failure to verify proof leaf hash leads to incorrect output proofs being accepted

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#859]
**Describe the bug**

When updating to use the TCT, these lines:

https://github.com/penumbra-zone/penumbra/blob/41879a8cc5ac8683f49c20bf0f0b04a3b31c26f6/crypto/src/proofs/transparent.rs#L95-L123

were replaced with these lines:

https://github.com/penumbra-zone/penumbra/blob/0b2ba0231333b91fc79266c2509e8f05402033f9/crypto/src/proofs/transparent.rs#L92-L95

Although `penumbra_tct::Proof::verify` encapsulates a lot of the previous logic, it does not check that the `Hash` contained as the leaf of the `Proof` is the same as `Hash::of` the commitment we are trying to prove the inclusion of. This means that _any_ inclusion proof will pass this check, not just one for the commitment in question.

This was discovered because of https://github.com/penumbra-zone/penumbra/issues/858: the sensibility check implemented in this assertion when _producing_ the proof is the same check that must be made for soundness when _verifying_ the proof; when the assertion was not flipped on (because it's turned off in release mode), the absence of any error meant that we had to be missing a verification step.

**Steps to fix**

Check that `self.note_commitment_proof.commitment() == self.note_commitment`, **or** (more appealingly) reduce the duplication and do not have a separate `note_commitment` field in the structure.

**Comment by hdevalence** [comment]
This seems relatively easy to fix and good to prioritize.
