### ISSUE TITLE
Document that validators must manually enable their validators

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#861]
Some confusion on the Discord occurred where people didn't realize that they needed to manually set the "enabled" flag to `true` in the generated validator template. We should document this better, perhaps even noting it in the output of the template generation command?

**Comment by D-Elektra** [comment]
Just add there a sentence - Switch enabled flag...

**Comment by plaidfinch** [comment]
@zbuc the existing documentation actually looks pretty good to me, tbh. thanks for pointing it out :)

**Comment by pygmygoats** [comment]
Added a line to the docs https://github.com/penumbra-zone/penumbra/commit/aac0924b117cbe1da772bd5f0f528101d2cc3799
