### ISSUE TITLE
Extract `App` into a `penumbra-app` crate

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#927]
**Is your feature request related to a problem? Please describe.**

Currently, `pcli` depends on `pd`, so that `pcli` can use the `pd::App` and run `App::check_tx_stateless()` before submission.  But it's not ideal for `pcli` to depend on all of `pd`.

**Describe the solution you'd like**

Split the `App` out into a separate `penumbra-app` crate that both `pd` and `pcli` can depend on.

**Comment by hdevalence** [comment]
@plaidfinch what's the current status of this relative to the refactoring that happened?

**Comment by plaidfinch** [comment]
This is completed in a modified manner: the `App` component now lives in the `component` crate.
