### ISSUE TITLE
Profile the cost of a sync run (excluding genesis)

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#929]
**Is your feature request related to a problem? Please describe.**

We have various ideas of how to optimize the sync process, but not a solid idea of exactly where we're paying costs.

**Describe the solution you'd like**

Do a profiler run with a [profiling tool](https://nnethercote.github.io/perf-book/profiling.html) on a sync run from **block 1** up to the chain tip.

It's important to skip compact block 0, which is derived from the genesis state, since it will mess up the measurements. Probably the easiest way to do this would be to insert an explicit panic on block height 1, then copy out the sqlite database as a snapshot, then remove the panic, and make runs from 1 using the snapshot.

**Comment by redshiftzero** [comment]
After the pcli sync performance improvements we released in testnet 21, we've decided to hold off on further pcli sync profiling and optimization at this time.
