### ISSUE TITLE
Baseline benchmarks for TCT

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#931]
It would be good to see a benchmark that establishes how quickly we can insert a new commitment, block, and epoch into the tree, and how quickly we can compute the root hash given that the frontier was not previously evaluated.

**Comment by hdevalence** [comment]
Closing this out as not-planned, not because we shouldn't do it eventually, but because we've largely addressed the problems we had when we originally made the TCT by improving the Poseidon implementation.
