### ISSUE TITLE
pcli error on first sync 

### ISSUE THREAD

**Issue by pygmygoats** [penumbra-zone/penumbra#932]
**Describe the bug**
During the first sync of pcli,  the sync overshoots the expected block "denominator" and doesn't return the requested command, instead continuing the sync 
https://discord.com/channels/824484045370818580/962034051991097424/981258758535659520 

Kiling the sync and then re-running whatever command, correctly returns expected output. 

**To Reproduce**
1. Install pcli
2. Run a command that requires a sync for the first time e.g. `pcli balance`
3. See sync error (sync doesn't finalize)
4. Kill sync (control C)
5. Re-run `pcli balance`

**Expected behavior**
No hanging sync :) return expected output right when sync completes

**Screenshots**
<img width="588" alt="Screen Shot 2022-05-31 at 4 56 44 PM" src="https://user-images.githubusercontent.com/103226075/171290941-23d452dd-c965-4f8b-92aa-a4eb02748de6.png">

**Additional context**
N/A

**Comment by redshiftzero** [comment]
when the sync occurs, sometimes we are not hitting the condition that `sync_height == latest_known_block_height` [here](https://github.com/penumbra-zone/penumbra/blob/main/view/src/service.rs#L298), so the break is not executed, e.g. in the below debug output where we don't ever get a `sync_height` of 16846 reported:

```
[view/src/service.rs:291] sync_height = 16843
[view/src/service.rs:291] latest_known_block_height = 16846
[view/src/worker.rs:143] height = 16845
[view/src/worker.rs:143] height = 16846
[view/src/service.rs:291] sync_height = 16845
[view/src/service.rs:291] latest_known_block_height = 16846
[view/src/worker.rs:143] height = 16847
[view/src/worker.rs:143] height = 16848
[view/src/service.rs:291] sync_height = 16847
```
