### ISSUE TITLE
Revive `tx sweep` logic and port it to the view service

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#937]
**Is your feature request related to a problem? Please describe.**

I didn't port over the `tx sweep` logic when doing the `pcli-next` refactor, but we can run into problems without it, since we have very short epoch durations on our testnets, and this causes a lot of small reward notes. 

**Describe the solution you'd like**

Uncomment the `tx sweep` code and port it to the view/custody service architecture.

**Comment by redshiftzero** [comment]
This was completed
