### ISSUE TITLE
Use `AwaitChange` to wait for transaction confirmation in `pcli`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#938]
**Is your feature request related to a problem? Please describe.**

Currently, `pcli` doesn't wait for transactions to be confirmed after sending them. This can cause problems when `pcli` is used twice in quick succession, because it might accidentally try to spend the same notes twice.

**Describe the solution you'd like**

We can use the change notification system in #935 to avoid this problem.  If we know we should detect an output of a transaction when it is committed (because we sent it to ourselves), we can use it to wait for transaction confirmation.

Transaction submission happens via
```rust
pub async fn submit_transaction(&self, transaction: &Transaction) -> Result<(), anyhow::Error>
```
Changing this to
```rust
pub async fn submit_transaction(&self, transaction: &Transaction, await_change: Option<note::Commitment>) -> Result<(), anyhow::Error>
```
would allow us to wait for confirmation, by making a view service `AwaitChange` RPC call after we submit the transaction and waiting for it to complete (or time out and error, say 30 seconds later).

We have to pass the `note::Commitment` separately from the `Transaction`, because at this point, the transaction has been created, and it doesn't reveal anything about which outputs are ours.

We only need to specify one change note per submission, even if there are multiple self-addressed outputs, since as soon as we detect one, we will have detected them all.

**Describe alternatives you've considered**

Tendermint provides an RPC that waits for confirmation.  However, it also says not to use it in production, and to use the websocket event notification system instead.  That system is now being deprecated in favor of a polling-based API, which isn't what we want here -- we want to be notified as soon as the transaction is seen.

Waiting on something from the view service is better than waiting on something from Tendermint anyways, since that way, we know that once we're notified, the data will be in our view, which we don't get from Tendermint -- we might be notified before the view service has a chance to scan, and then we'd get confused about why it's not there.

**Comment by plaidfinch** [comment]
In order to use this, builder methods for transactions will need to return the note commitment corresponding to the change note emitted. However, what if there is no change note? Should we generate a zero-value change output? I think this might make sense. It also goes halfway to implementing #405, at least in the client-side... thoughts on this @hdevalence?
