### ISSUE TITLE
`pd generate-testnet` succeeds even when the directory is nonempty

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#940]
**Is your feature request related to a problem? Please describe.**

The `pd generate-testnet` command succeeds even when the directory it writes into is nonempty/existing.

This makes it easy to get messed up with duplicate or stale state.

**Describe the solution you'd like**

We should either error out, or delete the directory.  Deleting the directory automatically seems dangerous.  Perhaps if we print the directory path that's nonempty in the error message, it's easy for someone to copy-paste it into an `rm -rf` invocation, and that'd be good enough.

**Additional context**

If we did this and #939, I think we'd cut down on the amount of bad-state issues among testnet participants considerably.

**Comment by conorsch** [comment]
Discussed in sprint planning today, and we agree this problem no longer exists.
