### ISSUE TITLE
Proto / Transaction support for ICS20 messages

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#977]
To parse and interpret ICS20 messages, we'll need to add support for the relevant protos.

There are two basic options here:

1. Extend the set of allowed inner values for an `IBCAction` to include ICS20 messages;
2. Add a new transaction action that would hold IBC application messages (ICS20, interchain accounts, etc).

(1) seems easier, and fits with the existing code structure.  It also fits with the modeling we have now, where the IBC action is an opaque blob of data that's posted to the chain.

**Comment by avahowell** [comment]
We don't need to extend IBCAction to support transfer data, since we already have the requisite IBC packet types (IBCAction encapsulates MsgRecvPacket which contains an opaque bytes array that contains the FungibleTokenPacketData).
