### ISSUE TITLE
Mint notes for inbound IBC transfers

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#979]
To handle inbound IBC transfers, we want to cause corresponding notes to be minted.

We already have a mechanism for this, in the form of the "commission amounts": https://github.com/penumbra-zone/penumbra/blob/main/component/src/shielded_pool/component.rs#L573-L583

This should be renamed to something more general, and used by the ICS20 component to mint new notes.

- [x] #1351
- [x] Actually do IBC transfer

**Comment by conorsch** [comment]
Currently blocked, pending progress on #465.

**Comment by conorsch** [comment]
Needs https://github.com/penumbra-zone/penumbra/pull/2315 & https://github.com/penumbra-zone/penumbra/pull/2301; after those land, this ticket should be blocked.

**Comment by conorsch** [comment]
Committing to shipping in Testnet 51!

**Comment by avahowell** [comment]
Done in #2392
