### ISSUE TITLE
Implement ICS20 balance-of-payments or other circuit-breaker functionality.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#981]
We can add more complex functionality later, but to start, we should just have *a* part of the code that does basic accounting and circuit-breaking:

- [x] Record the net amount of each token transferred between each counterparty chain (this may be partially accounted for by the generic supply tracking functionality in the shielded pool -- we already track the supply of all of the bearer tokens, so we just need to record how many tokens we've sent out to each counterparty chain);
- [x] For assets originating from Penumbra, never accept the return of more tokens than were transferred out.
- [x] For assets not originating from Penumbra, never transfer out more tokens than were transferred in.  (Our counterparties should be checking this anyways, since if we were Byzantine we could lie to them).

**Comment by conorsch** [comment]
@avahowell suspects this work may be complete already. @avahowell can you comment with more details, and close if warranted?

**Comment by conorsch** [comment]
Discussed in IBC sync today. Good news: 2/3 of these are already done! Leaving this issue open to track the remaining item.

**Comment by erwanor** [comment]
This was done in #3294
