### ISSUE TITLE
Extend View functionality to support tracking quarantine status of notes

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#993]
**Is your feature request related to a problem? Please describe.**
Currently view service does not track quarantine status and we need to do that

**Describe the solution you'd like**
View service/client should support `include_quarantined` for notes queries

**Additional context**
We will need to extend the NoteRecord to include more information from the CompactBlock relevant to quarantined status and update the local note storage entries appropriately on each commit to storage. The `NotesRequest` proto will need updated with `include_quarantined`. `pcli` will need to display quarantined values as a separate line item in `balance`, with a subcommand to break down the quarantined total (which could be added later outside of this scope, but could include estimates on when these notes will be available)

**Comment by hdevalence** [comment]
Subsumed by #1009
