### ISSUE TITLE
Randomize note selection for spending

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#994]
**Is your feature request related to a problem? Please describe.**
Selecting notes to spend in a transaction leaks some information about what notes you have in your wallet. While (a) this information leakage is seems to only be comprehensible by a very powerful (network?) adversary who can tie your transactions to your identity, and (b) it's very slight, given that actual amounts are encrypted, we should still strive to minimize it. The least amount of information we can reveal is if we select notes truly randomly, up to the threshold required for the spend. Currently, this is _almost_ the case already, but coincidentally: the primary key for the notes table on the view service is the commitment, which means that iterating over notes yields them in a pseudorandom order, since commitments are effectively random. However, this is (a) not codified or enforced, and it would be easy for future developers to change it accidentally, and (b) it is a fixed pseudorandom ordering, rather than a new one for each transaction.

**Describe the solution you'd like**
The `notes` query for the view service should return a fresh random note ordering each time it is queried. This can be accomplished by plucking a note at random out of the table by index, and iterating until enough value is gathered (avoiding duplicates). Because the database is local, the overhead of many queries vs. a single one seems negligible.

**Describe alternatives you've considered**
We could just do nothing. Note that this does not have to happen pre-launch.

**Comment by plaidfinch** [comment]
This is connected to #405.

**Comment by hdevalence** [comment]
If we want to do this, rather than doing multiple queries, could we do an `ORDER BY random()` or something in the sql query?

**Comment by aubrika** [comment]
> If we want to do this, rather than doing multiple queries, could we do an `ORDER BY random()` or something in the sql query?

We discussed this, but `iterating until enough value is gathered (avoiding duplicates)` imposes some constraints that make it so we can't just say `LIMIT 100` or whatever, since we care about a total aggregate value rather than just a total number of notes returned.

**Comment by hdevalence** [comment]
> > If we want to do this, rather than doing multiple queries, could we do an `ORDER BY random()` or something in the sql query?
> 
> 
> 
> We discussed this, but `iterating until enough value is gathered (avoiding duplicates)` imposes some constraints that make it so we can't just say `LIMIT 100` or whatever, since we care about a total aggregate value rather than just a total number of notes returned.

I don't think I follow, can't we just query for all the (unspent) notes in random order, without a limit clause, and then loop over the records as we do now?

I think it's unlikely that the *unspent* note set will ever get so big that this is meaningfully inefficient. If so we can fix it then.

**Comment by plaidfinch** [comment]
> If so we can fix it then.

I agree. A fix then would be as simple as using the streaming query API and looping async over the stream of returned results (provided that SQLite doesn't do a bunch of up-front work to generate the random permutation before returning the first result).

**Comment by hdevalence** [comment]
I think it's simpler not to do this -- we ensure privacy by not linking spends and outputs, and the benefit seems pretty theoretical.
